const COLLOCATIONS=[
  {phrase:"make a decision",tr:"karar vermek",warn:"❌ 'do a decision' değil — make kullanılır"},
  {phrase:"do homework",tr:"ödev yapmak",warn:"❌ 'make homework' değil — do kullanılır"},
  {phrase:"make a mistake",tr:"hata yapmak",warn:"❌ 'do a mistake' değil — make kullanılır"},
  {phrase:"take a break",tr:"ara vermek, mola vermek"},
  {phrase:"pay attention",tr:"dikkat etmek",warn:"❌ 'give attention' değil — pay kullanılır"},
  {phrase:"make progress",tr:"ilerleme kaydetmek",warn:"❌ 'do progress' değil — make kullanılır"},
  {phrase:"do exercise",tr:"egzersiz yapmak",warn:"❌ 'make exercise' değil — do kullanılır"},
  {phrase:"take a photo",tr:"fotoğraf çekmek",warn:"❌ 'make a photo' değil — take kullanılır"},
  {phrase:"make an effort",tr:"çaba göstermek"},
  {phrase:"have a meeting",tr:"toplantı yapmak"},
  {phrase:"catch a cold",tr:"soğuk algınlığı kapma"},
  {phrase:"make a difference",tr:"fark yaratmak"},
  {phrase:"do research",tr:"araştırma yapmak",warn:"❌ 'make research' değil — do kullanılır"},
  {phrase:"take responsibility",tr:"sorumluluk almak"},
  {phrase:"make a complaint",tr:"şikayette bulunmak"},
  {phrase:"do the dishes",tr:"bulaşık yıkamak"},
  {phrase:"make a reservation",tr:"rezervasyon yaptırmak"},
  {phrase:"take action",tr:"harekete geçmek"},
  {phrase:"make a profit",tr:"kâr etmek"},
  {phrase:"do damage",tr:"zarar vermek",warn:"❌ 'make damage' değil — do kullanılır"},
  {phrase:"take a risk",tr:"risk almak"},
  {phrase:"make friends",tr:"arkadaş edinmek"},
  {phrase:"do business",tr:"iş yapmak"},
  {phrase:"take notes",tr:"not almak"},
  {phrase:"make a speech",tr:"konuşma yapmak"},
  {phrase:"do the laundry",tr:"çamaşır yıkamak"},
  {phrase:"take turns",tr:"sırayla yapmak"},
  {phrase:"make sense",tr:"mantıklı olmak, anlamlı olmak"},
  {phrase:"do harm",tr:"zarar vermek",warn:"❌ 'make harm' değil — do kullanılır"},
  {phrase:"take advantage of",tr:"yararlanmak, fırsattan istifade etmek"},
  {phrase:"make a living",tr:"geçimini sağlamak"},
  {phrase:"do a favor",tr:"iyilik yapmak"},
  {phrase:"take care of",tr:"ilgilenmek, bakmak"},
  {phrase:"make an appointment",tr:"randevu almak"},
  {phrase:"do good",tr:"iyilik yapmak, faydalı olmak"},
  {phrase:"take part in",tr:"katılmak, iştirak etmek"},
  {phrase:"make a point",tr:"önemli bir şey vurgulamak"},
  {phrase:"do well",tr:"iyi gitmek, başarılı olmak"},
  {phrase:"take place",tr:"gerçekleşmek"},
  {phrase:"make a choice",tr:"seçim yapmak"},
  {phrase:"do nothing",tr:"hiçbir şey yapmamak"},
  {phrase:"take medicine",tr:"ilaç almak",warn:"❌ 'drink medicine' değil — take kullanılır"},
  {phrase:"make a noise",tr:"gürültü çıkarmak"},
  {phrase:"do one's best",tr:"elinden gelenin en iyisini yapmak"},
  {phrase:"take a step",tr:"adım atmak"},
  {phrase:"make an excuse",tr:"bahane üretmek"},
  {phrase:"do justice to",tr:"hakkını vermek"},
  {phrase:"take effect",tr:"yürürlüğe girmek, etkisini göstermek"},
  {phrase:"make a move",tr:"harekete geçmek"},
  {phrase:"do wonders",tr:"harikalar yaratmak"}
];
