const CONVERSATIONS=[
  // ──────────────── EASY ────────────────
  {id:"conv_cafe",c:"social",emoji:"☕",title:"Kafe Siparişi",level:"easy",turns:[
    {bot:["Welcome to Sunrise Café! What can I get for you today?","Hi there! Ready to order?","Good morning! What would you like?"],tr:["Sunrise Café'ye hoş geldiniz! Bugün ne alırdınız?","Merhaba! Sipariş vermeye hazır mısınız?","Günaydın! Ne almak isterdiniz?"]},
    {userHint:"Büyük boy cappuccino ve çikolatalı kek isteyin",keywords:["large","cappuccino","chocolate","cake","please"],expected:"I'd like a large cappuccino and a slice of chocolate cake, please."},
    {bot:["Sure! Is that to have here or to take away?","Great choice! Eat in or take away?","Coming right up! For here or to go?"],tr:["Tabii! Burada mı içeceksiniz, yoksa götürecek misiniz?","Harika seçim! İçeride mi, dışarıya götürülecek mi?","Hemen hazırlayalım! Burada mı yoksa götürülecek mi?"]},
    {userHint:"Burada içeceğinizi söyleyin ve fiyatı sorun",keywords:["here","how much","cost","price"],expected:"To have here, please. How much is that?"},
    {bot:["That comes to £6.50. Cash or card?","That'll be £6.50. How would you like to pay?","Six fifty, please. Cash or card?"],tr:["Toplam 6,50 £. Nakit mi kart mı?","Toplam 6,50 £. Nasıl ödemek istersiniz?","Altı elli lütfen. Nakit mi kart mı?"]},
    {userHint:"Kartla ödeyeceğinizi söyleyin",keywords:["card","pay","by card"],expected:"I'll pay by card, please."}
  ]},
  {id:"conv_directions",c:"travel",emoji:"🗺️",title:"Yol Tarifi",level:"easy",turns:[
    {bot:["Hello! You look a bit lost — can I help?","Hi! Are you looking for somewhere?","Excuse me, can I help you find something?"],tr:["Merhaba! Biraz kaybolmuş gibi görünüyorsunuz — yardımcı olabilir miyim?","Selam! Bir yer mi arıyorsunuz?","Affedersiniz, bir şey aramanıza yardımcı olabilir miyim?"]},
    {userHint:"Şehir müzesinin nerede olduğunu sorun",keywords:["city museum","where","get to","directions"],expected:"Yes, please. Can you tell me how to get to the city museum?"},
    {bot:["Of course! Go straight ahead and turn left at the traffic lights.","Sure! Walk along this road and turn left at the lights.","No problem! Take this road and turn left at the junction."],tr:["Tabii! Düz gidin ve trafik ışıklarında sola dönün.","Elbette! Bu yolda devam edin ve ışıklarda sola dönün.","Sorun değil! Bu yolda gidin ve kavşakta sola dönün."]},
    {userHint:"Yürüyerek ne kadar süreceğini sorun",keywords:["how long","walk","minutes","far"],expected:"Thank you. How long does it take to walk there?"},
    {bot:["About ten minutes on foot.","It's around ten minutes walking.","Not long at all — just ten minutes or so."],tr:["Yürüyerek yaklaşık on dakika.","Yürüyüşle on dakika kadar.","Çok uzun değil — on dakika falan."]},
    {userHint:"Teşekkür edin",keywords:["thank","thanks","helpful","appreciate"],expected:"That's great, thank you so much!"}
  ]},
  {id:"conv_return",c:"social",emoji:"🛍️",title:"Mağazada İade",level:"easy",turns:[
    {bot:["Hello, how can I help you today?","Good morning! What can I do for you?","Hi there! What brings you in?"],tr:["Merhaba, bugün size nasıl yardımcı olabilirim?","Günaydın! Nasıl yardımcı olabilirim?","Merhaba! Ne yapabilirim sizin için?"]},
    {userHint:"Geçen hafta aldığınız gömleği iade etmek istediğinizi söyleyin",keywords:["return","shirt","bought","last week","receipt"],expected:"I'd like to return this shirt I bought last week. I have the receipt."},
    {bot:["Of course. What seems to be the problem with it?","No problem. What's the reason for the return?","Sure. Is there an issue with the item?"],tr:["Tabii ki. Sorun nedir?","Sorun değil. İade sebebiniz nedir?","Elbette. Üründe bir sorun mu var?"]},
    {userHint:"Yanlış beden olduğunu söyleyin",keywords:["wrong size","too small","size","exchange"],expected:"It's the wrong size — it's too small for me."},
    {bot:["No problem. Would you like to exchange it or get a refund?","We can swap it for the right size or give you a full refund.","Do you want to exchange it or would you prefer your money back?"],tr:["Sorun değil. Değişim mi yapmak istersiniz yoksa para iadesi mi?","Doğru bedenle değiştirebilir ya da tam iade yapabiliriz.","Değişim mi yoksa para iadesi mi tercih edersiniz?"]},
    {userHint:"Doğru beden için değiştirmek istediğinizi söyleyin",keywords:["exchange","medium","size","please"],expected:"I'd like to exchange it for a medium size, please."}
  ]},
  {id:"conv_airport",c:"travel",emoji:"✈️",title:"Havalimanı Check-in",level:"easy",turns:[
    {bot:["Good morning. May I have your passport and booking reference, please?","Hello! Passport and booking confirmation, please.","Welcome. Could I see your travel documents?"],tr:["Günaydın. Pasaportunuzu ve rezervasyon kodunuzu alabilir miyim?","Merhaba! Pasaport ve rezervasyon belgesi lütfen.","Hoş geldiniz. Seyahat belgelerinizi görebilir miyim?"]},
    {userHint:"Pasaportunuzu verin ve pencere kenarı koltuk isteyin",keywords:["here","passport","window seat","prefer"],expected:"Here's my passport. Could I have a window seat if possible?"},
    {bot:["Of course! Seat 12A is available — that's a window seat. How many bags are you checking in?","You're in luck — 12A is free! How many bags to check?","Window seat 12A is available. How many bags today?"],tr:["Tabii! 12A koltuğu müsait — bu bir pencere kenarı. Kaç bagaj vereceksiniz?","Şansınız var — 12A boş! Kaç valiz vereceksiniz?","12A pencere kenarı müsait. Bugün kaç bagaj var?"]},
    {userHint:"Bir valiz vereceğinizi ve el bagajınızın olduğunu söyleyin",keywords:["one suitcase","check","hand luggage","cabin bag"],expected:"I have one suitcase to check in and one hand luggage."},
    {bot:["Your bag is 18kg — within the limit. Here's your boarding pass. Gate 14, boarding at 09:30.","18 kilos, all fine! Boarding pass for you. Please go to gate 14, boarding at half nine.","18kg, that's fine. Your boarding pass is ready — gate 14, boarding 09:30."],tr:["Valiziniz 18 kg — limit dahilinde. Biniş kartınız hazır. 14 numaralı kapı, biniş 09:30.","18 kilo, tamam! Biniş kartınız. 14. kapıya gidin, biniş saat 09:30.","18 kg, sorun değil. Biniş kartınız hazır — kapı 14, biniş 09:30."]},
    {userHint:"Teşekkür edin ve 14. kapının nerede olduğunu sorun",keywords:["thank","where","gate","terminal","find"],expected:"Thank you! Could you tell me where gate 14 is?"}
  ]},
  {id:"conv_hotel",c:"travel",emoji:"🏨",title:"Otel Check-in",level:"easy",turns:[
    {bot:["Good evening! Welcome. Do you have a reservation?","Hello, welcome to the hotel! Are you checking in?","Good evening! How can I help you?"],tr:["İyi akşamlar! Hoş geldiniz. Rezervasyonunuz var mı?","Merhaba, otele hoş geldiniz! Check-in mi yapacaksınız?","İyi akşamlar! Nasıl yardımcı olabilirim?"]},
    {userHint:"Adınıza rezervasyon yaptırdığınızı söyleyin",keywords:["reservation","booking","name","yes"],expected:"Yes, I have a reservation. It should be under my name."},
    {bot:["Of course. Could I have your full name, please?","What name is the booking under?","And the name on the reservation?"],tr:["Tabii ki. Tam adınızı alabilir miyim?","Rezervasyon kimin adına?","Rezervasyondaki isim nedir?"]},
    {userHint:"Adınızı söyleyin ve iki gecelik çift kişilik oda olduğunu belirtin",keywords:["name","two nights","double room","nights"],expected:"It's [name]. It should be a double room for two nights."},
    {bot:["Perfect, I have it here. Could I see your passport for a moment?","Found it! May I briefly see your passport?","Here we are. I just need your passport for check-in."],tr:["Mükemmel, kayıtlarımızda var. Pasaportunuzu bir an için görebilir miyim?","Buldum! Pasaportunuzu kısaca görebilir miyim?","İşte burada. Check-in için pasaportunuza ihtiyacım var."]},
    {userHint:"Pasaportunuzu verin ve erken check-in mümkün mü diye sorun",keywords:["here","passport","early check-in","possible","ready"],expected:"Here it is. Is early check-in possible, by any chance?"}
  ]},
  // ──────────────── MEDIUM ────────────────
  {id:"conv_doctor",c:"medical",emoji:"🩺",title:"Doktor Muayenesi",level:"medium",turns:[
    {bot:["Good morning. Please take a seat. What seems to be the problem?","Hello! Come in. What brings you in today?","Good morning. What's been troubling you?"],tr:["Günaydın. Lütfen oturun. Sorun nedir?","Merhaba! Buyurun. Bugün sizi getiren nedir?","Günaydın. Sizi rahatsız eden ne?"]},
    {userHint:"Üç gündür boğaz ağrısı ve ateşiniz olduğunu söyleyin",keywords:["sore throat","fever","three days","temperature","pain"],expected:"I've had a sore throat and a fever for about three days now."},
    {bot:["I see. Let me take your temperature... 38.5 — slightly elevated. Are you taking any medication?","38.5 — a bit high. Have you taken anything for it?","That's a slight fever. Are you on any medicine currently?"],tr:["Anlıyorum. Ateşinizi ölçeyim... 38.5 — biraz yüksek. Herhangi bir ilaç kullanıyor musunuz?","38.5 — biraz yüksek. Bir şey aldınız mı?","Hafif ateş var. Şu an herhangi bir ilaç kullanıyor musunuz?"]},
    {userHint:"Parasetamol aldığınızı ama işe yaramadığını söyleyin",keywords:["paracetamol","taking","not helping","still","temperature"],expected:"I've been taking paracetamol, but it's not really helping."},
    {bot:["I'll prescribe antibiotics. One tablet twice a day with food. Come back in five days if there's no improvement.","I'm putting you on a course of antibiotics — twice daily with meals. Return in five days if needed.","Antibiotics should clear this up. Twice a day with food, five-day course. Come back if it persists."],tr:["Antibiyotik yazıyorum. Günde iki kez yemekle birlikte bir tablet. Beş gün içinde iyileşme olmazsa gelin.","Antibiyotik kürü başlatıyorum — günde iki kez yemekle. Gerekirse beş gün sonra gelin.","Antibiyotik sorunu çözecektir. Günde iki kez yemekle, beş günlük kür. İyileşmezse gelin."]},
    {userHint:"Teşekkür edin ve yan etkiler olup olmadığını sorun",keywords:["thank","side effects","anything","worry","know"],expected:"Thank you, doctor. Are there any side effects I should be aware of?"}
  ]},
  {id:"conv_flat",c:"social",emoji:"🏡",title:"Kiralık Ev Görüşmesi",level:"medium",turns:[
    {bot:["Hi! You must be here about the flat. Come in and have a look around!","Hello! Glad you could make it. Shall we start with a tour?","Good afternoon! You're here about the two-bedroom flat, right? Let me show you around."],tr:["Merhaba! Daire için geldiniz, değil mi? Buyurun, bir bakın!","Selam! Geldiğinize sevindim. Turu başlatalım mı?","İyi öğleden sonralar! İki odalı daire için geldiniz, değil mi? Gezdireyim."]},
    {userHint:"Evet olduğunuzu onaylayın ve ilanı online gördüğünüzü söyleyin",keywords:["yes","online","listing","saw","interested"],expected:"Yes, that's right. I saw the listing online and I'm very interested."},
    {bot:["Great! It's two bedrooms, fully furnished, £1,200 per month. Bills are not included.","It's a two-bed, furnished flat. Rent is £1,200 monthly — bills extra.","Two bedrooms, fully furnished. £1,200 a month, not including utilities."],tr:["Harika! İki yatak odalı, tam eşyalı, aylık 1.200 £. Faturalar dahil değil.","İki odalı, eşyalı daire. Kira aylık 1.200 £ — faturalar ayrı.","İki yatak odalı, tam eşyalı. Aylık 1.200 £, faturalar hariç."]},
    {userHint:"Yakınlarda park olup olmadığını ve evcil hayvan politikasını sorun",keywords:["park","near","pets","allowed","policy"],expected:"Is there a park nearby? Also, are pets allowed in the flat?"},
    {bot:["There's a park five minutes away. Pets are allowed — small ones — with a small additional deposit.","Yes, there's a lovely park nearby! Small pets are fine, though we ask for a small extra deposit.","The park is a short walk away. We do allow pets with an additional deposit."],tr:["Beş dakika yürüme mesafesinde bir park var. Evcil hayvanlara izin var — küçük olanlara — ek depozito ile.","Evet, yakında güzel bir park var! Küçük evcil hayvanlara izin veriyoruz, ek depozito ile.","Park kısa yürüme mesafesinde. Ek depozito ile evcil hayvana izin veriyoruz."]},
    {userHint:"Ne zaman taşınılabileceğini sorun ve beğendiğinizi belirtin",keywords:["when","move in","available","love","wonderful"],expected:"The flat is wonderful. When would it be available to move in?"}
  ]},
  {id:"conv_university",c:"business",emoji:"🎓",title:"Üniversite Kayıt Görüşmesi",level:"medium",turns:[
    {bot:["Hello! I'm the admissions officer. I see you've applied for Business Management — is that right?","Welcome! Let's go through your Business Management application together.","Good morning! You're applying for our Business Management programme. Let's get started."],tr:["Merhaba! Kayıt görevlisiyim. İşletme Yönetimi için başvurduğunuzu görüyorum — doğru mu?","Hoş geldiniz! İşletme Yönetimi başvurunuzu birlikte inceleyelim.","Günaydın! İşletme Yönetimi programımıza başvuruyorsunuz. Başlayalım."]},
    {userHint:"Evet olduğunu onaylayın ve heyecanlı olduğunuzu belirtin",keywords:["yes","correct","excited","looking forward","application"],expected:"Yes, that's correct. I'm very excited about this opportunity."},
    {bot:["Wonderful. Your academic record looks strong. Why did you choose Business Management specifically?","Your grades are solid. What drew you to Business Management?","Your application is impressive. Why this programme in particular?"],tr:["Harika. Akademik kaydınız güçlü görünüyor. Neden özellikle İşletme Yönetimi?","Notlarınız sağlam. Sizi İşletme Yönetimi'ne çeken ne oldu?","Başvurunuz etkileyici. Özellikle bu programı neden seçtiniz?"]},
    {userHint:"İşletmeye olan ilginizden ve analitik becerilerinizden bahsedin",keywords:["passionate","business","analytical","skills","career","interest"],expected:"I'm passionate about business and I believe my analytical skills make it a great fit for my career goals."},
    {bot:["Great answer. The programme includes a work placement in year two. Do you have any relevant work experience?","Excellent! We have a placement year in the programme. Any work experience so far?","Fantastic. Our course has a work placement component. Do you have any experience to mention?"],tr:["Harika cevap. Program ikinci yılda staj içeriyor. İlgili iş deneyiminiz var mı?","Mükemmel! Programda staj yılı var. Şimdiye kadar iş deneyiminiz oldu mu?","Fantastik. Kursumuzun staj bileşeni var. Bahsedebileceğiniz bir deneyim var mı?"]},
    {userHint:"Part-time çalıştığınızı ve deneyimin değerli olduğunu söyleyin",keywords:["part-time","work","experience","valuable","learned"],expected:"I've been working part-time in a local business, which has been really valuable experience."}
  ]},
  {id:"conv_lost",c:"emergency",emoji:"🎒",title:"Kayıp Eşya Bildirimi",level:"medium",turns:[
    {bot:["Lost property office, can I help you?","Hello, you've reached the lost property office. How can I assist?","Lost and found — how can I help?"],tr:["Kayıp eşya ofisi, nasıl yardımcı olabilirim?","Merhaba, kayıp eşya ofisine ulaştınız. Nasıl yardımcı olabilirim?","Kayıp eşya — nasıl yardımcı olabilirim?"]},
    {userHint:"Trende çantanızı unuttuğunuzu ve içinde önemli şeyler olduğunu söyleyin",keywords:["bag","left","train","important","forgot"],expected:"I left my bag on the train earlier today. It has some important things inside."},
    {bot:["I'm sorry to hear that. Can you describe the bag and tell me which line?","Oh no! What does it look like, and which line were you on?","Let's try to find it. Can you describe the bag and the route you took?"],tr:["Çok üzgünüm. Çantayı tarif edebilir misiniz ve hangi hattaydınız?","Vay be! Nasıl bir şey ve hangi hattaydınız?","Bulmaya çalışalım. Çantayı tarif edebilir ve rotanızı söyleyebilir misiniz?"]},
    {userHint:"Siyah sırt çantası olduğunu ve Victoria hattında bıraktığınızı söyleyin",keywords:["black","backpack","Victoria line","afternoon","around"],expected:"It's a black backpack. I left it on the Victoria line around 3 PM this afternoon."},
    {bot:["We do have a black backpack handed in this afternoon. Can you tell me what's inside to confirm it's yours?","Actually, a black backpack was handed in! Can you confirm the contents?","There's a black backpack here. What are the contents so we can verify it's yours?"],tr:["Bu öğleden sonra teslim edilmiş bir siyah sırt çantamız var. İçindekiler neler?","Aslında, bir siyah sırt çantası teslim edildi! İçindekiler neler?","Burada siyah bir sırt çantası var. Sizin olduğunu doğrulamak için içindekiler neler?"]},
    {userHint:"Laptop, cüzdan ve mavi defterin içinde olduğunu söyleyin",keywords:["laptop","wallet","notebook","blue","inside"],expected:"There's a laptop, a wallet, and a blue notebook inside."}
  ]},
  {id:"conv_visa",c:"travel",emoji:"🛂",title:"Vize Mülakatı",level:"medium",turns:[
    {bot:["Good morning. Please state your full name and the purpose of your visit.","Hello. Could you tell me your name and why you wish to visit the UK?","Good morning. Please introduce yourself and explain the reason for your application."],tr:["Günaydın. Lütfen tam adınızı ve ziyaret amacınızı belirtin.","Merhaba. Adınızı ve neden İngiltere'yi ziyaret etmek istediğinizi söyler misiniz?","Günaydın. Lütfen kendinizi tanıtın ve başvuru nedeninizi açıklayın."]},
    {userHint:"Adınızı söyleyin ve iş konferansı için gittiğinizi belirtin",keywords:["name","business","conference","attend","company","representing"],expected:"My name is [name]. I'm attending a three-day business conference representing my company."},
    {bot:["How long do you intend to stay, and where will you be staying?","And the duration of your stay? Do you have accommodation arranged?","What is the planned length of your visit, and do you have a place to stay?"],tr:["Ne kadar kalmayı düşünüyorsunuz ve nerede kalacaksınız?","Kalış süreniz? Konaklama ayarladınız mı?","Ziyaretinizin planlanan süresi nedir ve kalacak yeriniz var mı?"]},
    {userHint:"5 gün kalacağınızı ve otel rezervasyonunuz olduğunu söyleyin",keywords:["five days","hotel","booked","accommodation","central"],expected:"I plan to stay for five days. I have a hotel booked in central London."},
    {bot:["What guarantees your return? Employment, family, financial commitments?","Do you have ties to your home country — work, family, property?","How can you demonstrate your intention to return home after your visit?"],tr:["Dönüşünüzü ne garanti ediyor? İş, aile, mali yükümlülükler?","Ülkenizle bağlantılarınız var mı — iş, aile, mülk?","Ziyaret sonrası eve dönme niyetinizi nasıl kanıtlayabilirsiniz?"]},
    {userHint:"Sabit işiniz ve ailenizin orada olduğunu söyleyin",keywords:["employed","job","family","home","return","ties"],expected:"I'm employed full-time and my family is at home. I have every reason to return."}
  ]},
  // ──────────────── HARD ────────────────
  {id:"scen_v3_1",c:"business",emoji:"💼",title:"Yatırımcı Sunumu (Pitch)",level:"hard",turns:[
    {bot:["Welcome. We've reviewed your pitch deck. What is your primary competitive advantage?","Glad to have you here. Your deck looks promising — what makes you stand out most?","Thanks for coming. We have some concerns. What exactly is your competitive edge?"],tr:["Hoş geldiniz. Sunum dosyanızı inceledik. Temel rekabet avantajınız nedir?","Sizi burada görmek güzel. Sunumunuz umut verici — sizi en çok öne çıkaran nedir?","Geldiğiniz için teşekkürler ama bazı endişelerimiz var. Rekabet avantajınız nedir?"]},
    {userHint:"Yapay zeka tabanlı algoritmanızdan ve pazar payınızdan bahsedin",keywords:["unique","ai","algorithm","market","share","advantage"],expected:"Our unique AI algorithm and rapidly growing market share are our biggest advantages."},
    {bot:["Interesting. How do you plan to scale internationally within the next year?","That sounds solid. Do you have a clear strategy for international expansion?","I see — scaling globally is difficult. How do you intend to handle international growth?"],tr:["İlginç. Önümüzdeki yıl içinde bunu uluslararası düzeyde nasıl ölçeklendirmeyi planlıyorsunuz?","Kulağa sağlam geliyor. Uluslararası ölçeklendirme için net bir stratejiniz var mı?","Anlıyorum ama küresel ölçeklendirme zordur. Uluslararası büyümeyi nasıl yönetmeyi düşünüyorsunuz?"]},
    {userHint:"Yerel ortaklıklar kuracağınızı ve dijital pazarlamaya odaklanacağınızı söyleyin",keywords:["local","partnerships","digital","marketing","global","focus"],expected:"We plan to establish local partnerships and focus heavily on digital marketing for global growth."}
  ]},
  {id:"conv_salary",c:"business",emoji:"💰",title:"Maaş Pazarlığı",level:"hard",turns:[
    {bot:["Hello. I understand you wanted to discuss your compensation. What's on your mind?","Hi, glad you brought this up. Talk me through your thinking on salary.","Good to meet. You've requested a salary discussion — let's hear your case."],tr:["Merhaba. Ücret konusunu görüşmek istediğinizi anlıyorum. Ne düşünüyorsunuz?","Selam, bunu gündeme getirdiğinize sevindim. Maaş konusundaki düşüncelerinizi anlatın.","Tanışmak güzel. Maaş görüşmesi talep ettiniz — argümanlarınızı dinleyelim."]},
    {userHint:"Performansınızı ve piyasa araştırmanızı sunun, belirli bir artış talep edin",keywords:["performance","market","research","increase","raise","deserve"],expected:"Based on my performance this year and market research, I'd like to discuss a 15% salary increase."},
    {bot:["That's a significant ask. Walk me through the market data you've looked at.","15% is bold. What market research supports that figure?","Interesting. Can you back that number up with data?"],tr:["Bu ciddi bir talep. Baktığınız piyasa verilerini anlatın.","15% cesur bir talep. Bu rakamı hangi piyasa araştırması destekliyor?","İlginç. Bu rakamı verilerle destekleyebilir misiniz?"]},
    {userHint:"Sektör verilerini ve katkılarınızı açıklayın",keywords:["industry","data","contribution","revenue","results","evidence"],expected:"Industry benchmarks show my role averages 12–18% higher. I also drove a 22% revenue increase last quarter."},
    {bot:["Those are strong numbers. I can approve 10% immediately, with a review in six months for the remainder. Does that work?","That's compelling. I can offer 10% now with a structured review for the rest in Q3. What do you think?","Solid case. I'm able to offer 10% now and commit to revisiting the full amount in six months."],tr:["Bunlar güçlü rakamlar. Şimdi 10% onaylayabilirim ve altı ay içinde geri kalanı için değerlendirme yaparız. Uygun mudur?","İkna edici. Şimdi 10% teklif edebilir, geri kalanı için Q3'te yapılandırılmış bir değerlendirme yaparım. Ne düşünürsünüz?","Sağlam argüman. Şimdi 10% teklif edebilir, tam tutara altı ay içinde tekrar bakacağımı taahhüt edebilirim."]},
    {userHint:"Teklife yanıt verin ve yapılandırılmış gözden geçirmeyi netleştirin",keywords:["appreciate","accept","confirm","review","timeline","written"],expected:"I appreciate that. I'd accept on the condition that the six-month review is confirmed in writing."}
  ]},
  {id:"conv_interview",c:"business",emoji:"🤝",title:"İş Görüşmesi",level:"hard",turns:[
    {bot:["Good morning. Please take a seat. Tell me a little about yourself and your professional background.","Welcome. Could you briefly introduce yourself and outline your experience?","Good morning. Let's start with a brief introduction — who are you and what's your background?"],tr:["Günaydın. Lütfen oturun. Kendinizden ve profesyonel geçmişinizden biraz bahsedin.","Hoş geldiniz. Kendinizi kısaca tanıtabilir ve deneyiminizi özetleyebilir misiniz?","Günaydın. Kısa bir tanıtımla başlayalım — kim olduğunuzu ve geçmişinizi anlatın."]},
    {userHint:"Deneyiminizi, güçlü yönlerinizi ve neden bu pozisyona başvurduğunuzu anlatın",keywords:["experience","passionate","role","skills","contribute","background"],expected:"I have five years of experience in marketing and I'm passionate about growth strategy. I applied because this role perfectly matches my skills."},
    {bot:["Interesting. Can you describe a challenging professional situation and how you resolved it?","Tell me about a time you dealt with a difficult challenge at work and what you learned.","What's the most significant professional challenge you've overcome?"],tr:["İlginç. Zorlu bir profesyonel durumu ve onu nasıl çözdüğünüzü anlatabilir misiniz?","İşte yaşadığınız zor bir durumu ve öğrendiklerinizi anlatın.","Aştığınız en önemli profesyonel zorluk neydi?"]},
    {userHint:"Zor bir projeden, çözümünüzden ve sonucundan bahsedin",keywords:["challenge","team","deadline","solution","result","learned"],expected:"We faced a major deadline crisis on a product launch. I restructured the team's workflow and we delivered two days early."},
    {bot:["Impressive. Where do you see yourself professionally in five years?","And looking ahead — what are your five-year career goals?","Great answer. What's your vision for the next five years in this field?"],tr:["Etkileyici. Kendinizi beş yıl sonra profesyonel açıdan nerede görüyorsunuz?","İleriye bakarak — beş yıllık kariyer hedefleriniz neler?","Harika cevap. Bu alanda önümüzdeki beş yıl için vizyonunuz nedir?"]},
    {userHint:"Liderlik rolü hedeflediğinizi ve uzun vadeli büyümek istediğinizi belirtin",keywords:["leadership","senior","grow","long-term","develop","vision"],expected:"I aim to develop into a senior leadership role and grow with the company long-term."}
  ]},
  {id:"conv_performance",c:"business",emoji:"📊",title:"Performans Değerlendirmesi",level:"hard",turns:[
    {bot:["Thanks for coming in. Overall it's been a strong quarter — what highlights would you like to mention first?","Let's begin the review. It's been productive. What achievements are you most proud of?","Before I share feedback, what do you feel went particularly well this quarter?"],tr:["Geldiğiniz için teşekkürler. Genel olarak güçlü bir çeyrek oldu — önce öne çıkarmak istediğiniz noktalar var mı?","Değerlendirmeye başlayalım. Verimli geçti. En çok neyle gurur duyuyorsunuz?","Geri bildirim vermeden önce — bu çeyrekte özellikle neyin iyi gittiğini düşünüyorsunuz?"]},
    {userHint:"Projeyi zamanında bitirdiğinizden ve müşteri memnuniyetini artırdığınızdan bahsedin",keywords:["delivered","on time","client satisfaction","improved","exceeded","target"],expected:"I delivered the Henderson project on time and client satisfaction scores improved by 18% this quarter."},
    {bot:["Excellent results. One development area: cross-team communication could be stronger. Your thoughts?","Great work. On development — interdepartmental communication has come up in feedback. How do you see it?","Strong outcomes. One point to develop: wider team communication. What's your perspective?"],tr:["Mükemmel sonuçlar. Bir gelişim alanı: çapraz takım iletişimi güçlendirilebilir. Düşünceleriniz?","Harika iş. Gelişim açısından — departmanlar arası iletişim geri bildirimde öne çıktı. Siz nasıl görüyorsunuz?","Güçlü sonuçlar. Geliştirme noktası: daha geniş ekip iletişimi. Bakış açınız nedir?"]},
    {userHint:"Kabul edin ve nasıl geliştireceğinize dair planınızı açıklayın",keywords:["acknowledge","improve","plan","weekly","meetings","aware","briefings"],expected:"I acknowledge that. I plan to introduce weekly cross-team briefings to improve communication going forward."},
    {bot:["Proactive thinking. We're also considering you for team lead next quarter. Are you ready for that?","Good initiative. There's also news: we'd like to put you forward for team lead from Q2. How do you feel?","Sounds constructive. On a positive note, you're being considered for team lead. Does that interest you?"],tr:["Proaktif düşünce. Ayrıca sizi gelecek çeyrekte takım liderliği için düşünüyoruz. Hazır mısınız?","İyi inisiyatif. Ayrıca bir haber: sizi Q2'den itibaren takım liderliğine önermeyi düşünüyoruz. Nasıl hissediyorsunuz?","Yapıcı geliyor. Olumlu bir not olarak, takım liderliği için düşünülüyorsunuz. İlginizi çekiyor mu?"]},
    {userHint:"Heyecanlı olduğunuzu ve hazır olduğunuzu söyleyin, rolün kapsamını sorun",keywords:["excited","ready","responsibility","grateful","understand","involves"],expected:"I'm genuinely excited and feel ready for that responsibility. Could you walk me through what the role involves?"}
  ]},
  {id:"conv_panel",c:"business",emoji:"🎤",title:"Konferans Paneli",level:"hard",turns:[
    {bot:["Welcome to the panel. First question: how will artificial intelligence reshape the workplace over the next decade?","Let's begin. What's your view on AI's impact on employment and professional environments?","Our opening question: what role do you see AI playing in reshaping work over the next ten years?"],tr:["Panele hoş geldiniz. İlk soru: yapay zeka önümüzdeki on yılda iş dünyasını nasıl yeniden şekillendirecek?","Başlayalım. Yapay zekanın istihdam ve profesyonel ortamlar üzerindeki etkisine bakış açınız nedir?","Açılış sorusu: önümüzdeki on yılda yapay zekanın çalışma hayatını şekillendirmede nasıl bir rol oynayacağını düşünüyorsunuz?"]},
    {userHint:"AI'nın işleri ortadan kaldırmak yerine dönüştüreceğini ve yeni rollerin ortaya çıkacağını savunun",keywords:["transform","replace","new roles","adapt","augment","human"],expected:"AI will primarily transform roles rather than eliminate them. New positions will emerge that require humans to adapt and collaborate with AI systems."},
    {bot:["A measured view. Are organisations moving fast enough to prepare their workforces for this transition?","Interesting. Do you feel companies are adequately preparing employees for AI-driven change?","Thoughtful. Are businesses keeping pace in terms of workforce preparation for this shift?"],tr:["Ölçülü bir görüş. Kuruluşlar iş güçlerini bu geçiş için yeterince hızlı hazırlıyor mu?","İlginç. Şirketlerin yapay zeka odaklı değişim için çalışanları yeterince hazırladığını düşünüyor musunuz?","Düşünceli. İşletmeler bu değişim için iş gücü hazırlığı açısından yeterince hızlı mı?"]},
    {userHint:"Çoğu şirketin yavaş olduğunu ama öncü şirketlerin iyi örnekler sergilediğini belirtin",keywords:["most","behind","however","leading","companies","reskilling","examples"],expected:"Most organisations are lagging behind, though leading companies are investing heavily in reskilling — and those examples should be studied and replicated."},
    {bot:["Final question: what single piece of advice would you give to someone entering the workforce today?","To close — what's the most important quality for professionals navigating this period of change?","Last question: what's your advice for a young professional beginning their career right now?"],tr:["Son soru: bugün iş gücüne giren birine vereceğiniz tek tavsiye nedir?","Kapanış — bu değişim döneminde profesyoneller için en önemli özellik nedir?","Son soru: kariyerine şu an başlayan genç bir profesyonele tavsiyeniz nedir?"]},
    {userHint:"Adaptasyon ve sürekli öğrenme yeteneğinin teknik becerilerden daha önemli olduğunu söyleyin",keywords:["adaptability","continuous learning","mindset","skills","durable","advantage"],expected:"Cultivate adaptability above all else. Technical skills become outdated quickly, but the ability to learn continuously is a durable competitive advantage."}
  ]}
];
