'use strict';
/* ============================================================
   English Rhapsody — UI Language Strings  v2.0
   Supported: TR (Turkish) · EN (English) · ES (Spanish)
   ============================================================ */

const LANG_UI = {

  // ── TURKISH ────────────────────────────────────────────────
  tr: {
    // Navigation
    nav_home:    'Merkez',
    nav_learn:   'Sinestezi',
    nav_reading: 'Okuma',
    nav_speak:   'Konuşma',

    // Home Dashboard
    home_subtitle:       'İngilizce öğrenimine devam et',
    greeting_morning:    '🌅 Günaydın!',
    greeting_afternoon:  '☀️ İyi öğlenler!',
    greeting_evening:    '🌙 İyi akşamlar!',
    stat_words:          'Kelime Öğrenildi',
    stat_streak:         'Gün Serisi',
    stat_accuracy:       'Başarı Oranı',
    xp_remain:           'XP kaldı',
    daily_goal:          '🎯 Günlük Hedef',
    daily_done:          '✅ Günlük hedef tamamlandı!',
    weekly_activity:     'Son 7 Gün',
    wod_label:           '⭐ Günün Kelimesi',
    wod_listen:          '🔊 Dinle',
    best_score:          'En iyi',
    try_today:           'Bugün dene →',
    completed_pct:       'tamamlandı',
    no_history:          'Henüz deneme yok',

    // Home Activity Cards
    lab_learn_title: 'Sinestezi Lab',
    lab_learn_desc:  'Yapay zeka destekli aralıklı tekrar ile kelimeleri kalıcı öğren.',
    lab_speak_title: 'Konuşma Lab',
    lab_speak_desc:  'Mikrofona konuş, AI telaffuzunu kelime kelime analiz etsin.',
    lab_read_title:  'Okuma Atölyesi',
    lab_read_desc:   'Hikayeler içinde bağlam kurarak kelime öğren ve anlamayı derinleştir.',

    // Reading Workshop
    reading_title:     '📖 Okuma Atölyesi',
    reading_subtitle:  'Gerçek metinlerle bağlamı hisset, kelimeleri yaşa.',
    reading_mode_read: '📚 Okuma',
    reading_mode_quiz: '🧩 Egzersiz',
    reading_listen:    '🎧 Sesli Dinle',
    reading_stop:      '🛑 Durdur',
    reading_prev:      '← Önceki',
    reading_next:      'Sonraki →',
    reading_shuffle:   '🔀 Karıştır',
    level_easy:        '🌱 Kolay',
    level_mid:         '📚 Orta',
    level_adv:         '🔥 İleri',
    no_content:        'İçerik bulunamadı.',
    quiz_no_blank:     'Önce bir boşluk seçin (___).',

    // Sinestezi / Practice Module
    synth_title:         'SİNESTEZİ',
    synth_subtitle:      'Nöral Öğrenme Matrisi — Çok Modlu İmmersyon',
    synth_rule1:         'YAZMA: Her harf kendi renginde parlar — gerçek sinestezi deneyimi.',
    synth_rule2:         'BAĞLAM: Kelimeleri cümle içindeki boşluklara yerleştirerek öğren.',
    synth_rule3:         'Hız bonusu: Ne kadar hızlı o kadar +XP. Kombo: 5× = 2×, 10× = 3× XP.',
    synth_mode_label:    'Mod Seçimi',
    synth_mode_context:  'BAĞLAM',
    synth_mode_context_desc: 'Cümle tamamlama',
    synth_mode_speed:    'ZAMANA KARŞI',
    synth_mode_speed_desc: 'Hızlı ol, 30 XP!',
    synth_mode_choice:   'SEÇME',
    synth_session_label: 'Oturum Uzunluğu',
    synth_start_btn:     'BAĞLANTIYI KUR',
    synth_pause_sub:     'Hazır olunca devam et',
    synth_resume_btn:    '▶ DEVAM ET',
    synth_menu_btn:      'Ana Menüye Dön',
    synth_hint_label:    'ipucu kullanıldı',
    synth_listen_btn:    '🔊 Dinle',
    synth_skip_btn:      'Bilmiyorum ⏭',
    synth_finish_title:  'BAĞLANTI TAMAMLANDI',
    synth_xp_earned:     'XP Kazanıldı',
    synth_perfect:       'Mükemmel',
    synth_accuracy:      'Doğruluk',
    synth_avg_time:      'Ort. Süre',
    synth_fastest:       'En Hızlı',
    synth_home_btn:      'Ana Menü',
    synth_mode_ind_speed:   '⚡ ZAMANA KARŞI',
    synth_mode_ind_context: '🧩 BAĞLAM',
    synth_mode_ind_choice:  '🔘 SEÇME',
    synth_grade_great:   '🏆 Mükemmel!',
    synth_grade_good:    '💪 İyi iş!',
    synth_grade_ok:      '📚 Pratik yap!',
    synth_grade_retry:   '🔄 Devam et!',
    synth_choice_label:  '🔘 Seçme',
    synth_speed_bonus:   '⚡ Hız XP',
    synth_timeout:       'Süre doldu!',
    synth_too_slow:      '⚡ Çok yavaş!',
    hint_first_letter:   'İpucu: İlk harf',
    hint_wrong3:         '⚠️ 3 Hata! Doğru cevap gösteriliyor...',

    // Speaking Module
    speak_title:         '🎙️ Konuşma Lab',
    speak_subtitle:      'AI destekli konuşma koçunuz — 4 güçlü mod',
    speak_mode_pronounce:'🎯 Telaffuz',
    speak_mode_ai:       '🤖 AI Sohbet',
    speak_diff_easy:     '🌱 Başlangıç',
    speak_diff_mid:      '📚 Orta',
    speak_diff_adv:      '🔥 İleri',
    speak_shadow:        'Gölge Modu',
    speak_shuffle:       'Karıştır',
    speak_listen:        'Dinle',
    speak_slow:          'Yavaş',
    speak_record:        'Konuş',
    speak_playback:      'Seni Dinle',
    speak_retry:         'Tekrar',
    speak_stop:          'Durdur',
    speak_keyboard_hint: '⌨️ Boşluk — Kaydet / Durdur',
    speak_session_panel: '📊 Oturum',
    speak_history_panel: '📋 Son Denemeler',
    speak_best:          'En İyi',
    speak_no_history:    'Henüz deneme yok',
    speak_listening:     '🎙️ Dinliyorum... Konuşmaya başla',
    speak_no_support:    "Tarayıcın ses tanıma API'sini desteklemiyor.",
    speak_click_listen:  'Dinlemek için tıkla',
    speak_improve_ipa:   '🎯 Telaffuzunu Geliştir:',
    fb_perfect:          '🏆 Mükemmel! Anadili gibi!',
    fb_great:            '🎉 Harika! Çok iyi gidiyorsun.',
    fb_good:             '💪 İyi iş! Biraz daha pratik yap.',
    fb_retry:            '🔄 Tekrar dene — daha net söyle.',

    // Conversation Module
    convo_title:         'Senaryo Seç',
    convo_subtitle:      'Gerçek hayat durumlarında İngilizce konuş',
    convo_turns:         'konuşma turu',
    convo_example:       'Örnek:',
    convo_finish_title:  'Sohbet Tamamlandı!',
    convo_xp:            'XP kazandın!',
    convo_new:           'Yeni Senaryo Seç',
    convo_skipped:       '(atlandı)',
    convo_diff_easy:     '🌱 Kolay',
    convo_diff_mid:      '📚 Orta',
    convo_diff_adv:      '🔥 İleri',

    // Popup / Word Def
    popup_example:       'Örnek Cümle',
    popup_synonyms:      'Eş Anlamlılar',
    popup_collocations:  'Sık Kullanılan Kalıplar',
    popup_add:           '➕ Listeye Ekle',
    popup_no_entry:      'Bu kelime şu an veritabanında yok',
    popup_grammar_word:  '/bağlam kelimesi/',
    popup_grammar_note:  'Bu temel bir dil bilgisi kelimesidir ve listeye eklenemez.',
    popup_audio_only:    '🔊 Sesi Dinle',

    // Word Type Labels
    type_word:         'Kelime',
    type_phrasal:      'Phrasal Verb',
    type_idiom:        'Deyim',
    type_grammar:      'Gramer Kalıbı',
    type_verb_pattern: 'Eylem Kalıbı',
    type_noun_phrase:  'İsim Tamlaması',

    // Quiz / Cloze
    quiz_correct:   '✓ Doğru!',
    quiz_wrong:     '✗ Yanlış',

    // Toasts
    toast_word_added:    'Kelime öğrenilecekler listesine eklendi! 📚',
    toast_word_exists:   'Bu kelime zaten listende!',
    toast_level_up:      'Seviye atladın!',
    toast_words_goal:    'kelimeye ulaştın!',
    toast_accent_us:     '🗣️ Aksan: Amerikan İngilizcesi',
    toast_accent_gb:     '🗣️ Aksan: İngiliz İngilizcesi',
    toast_shadow_on:     'Gölge Modu Açık',
    toast_shadow_off:    'Gölge Modu Kapalı',
    toast_shuffle_on:    'Karışık Mod Açık',
    toast_shuffle_off:   'Karışık Mod Kapalı',
    toast_lang_tr:       '🇹🇷 Türkçe seçildi',
    toast_lang_en:       '🇬🇧 English selected',
    toast_lang_es:       '🇪🇸 Español seleccionado',

    // Onboarding
    ob_title:      'English Rhapsody\'ye Hoş Geldin!',
    ob_subtitle:   'Birkaç soruda seviyeni belirleyelim ve sana özel bir öğrenme deneyimi oluşturalım.',
    ob_start:      'Başla →',
    ob_q1:         'İngilizce seviyeni nasıl tanımlarsın?',
    ob_q1_sub:     'Sana uygun içeriği hazırlayalım',
    ob_q1_a0:      'Hiç bilmiyorum',
    ob_q1_a0_sub:  'A1 · Sıfırdan',
    ob_q1_a5:      'İleri düzeydeyim',
    ob_q1_a5_sub:  'C1+',
    ob_q2_sub:     'Doğru seçeneği tıkla',
    ob_q3_sub:     'Doğru seçeneği seç',
    ob_finish:     'Hadi Başlayalım!',
    ob_level_set:  '✅ Seviye belirlendi! Öğrenmeye başla.',
    ob_bonus:      'Başlangıç bonusu:',
    ob_rank_begin: 'Başlangıç 🌱',
    ob_rank_adv:   'İleri Seviye 🏆',

    // Ranks
    rank_0: 'Çırak', rank_1: 'Kalfa', rank_2: 'Usta',
    rank_3: 'Şef',   rank_4: 'Üstat', rank_5: 'İlah',

    // Daily tip
    tip_label: '💡 Dil İpucu',

    // Misc
    xp_label:    'XP',
    streak_label:'🔥 Seri',
    loading:     'Yükleniyor…',
    close_btn:   '✕',
    back:        'Geri',
    skip:        '⏭ Geç',

    // Achievement
    achievement_unlocked: 'Başarım Kilidi Açıldı!',

    // Days (short, Mon=0)
    days_short: ['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'],

    // Onboarding extras
    ob_q1_title:   'Seviyeni Belirle',
    ob_q1_a1:      'Biraz biliyorum',
    ob_q1_a1_sub:  'A2 · Temel',
    ob_q1_a3:      'Orta seviyeyim',
    ob_q1_a3_sub:  'B1/B2',
    ob_q2_title:   '"Galaxy" ne demek?',
    ob_q2_a0:      '☀️ Güneş',
    ob_q2_a1:      '🌀 Galaksi',
    ob_q2_a2:      '⭐ Yıldız',
    ob_q2_a3:      '🪐 Gezegen',
    ob_q3_title:   '"I\'m looking forward to ___ you."',
    ob_finish_title: 'Seviyeni Belirledik!',
    ob_rank_mid:   'Orta Seviye 📚',

    // Synesthesia extras
    synth_write_mode:  '⌨️ YAZMA',
    synth_missed_title:'📝 Tekrar Edilecekler',
    synth_replay_btn:  'TEKRAR OYNA',
    synth_total_label: 'Toplam',

    // Speaking extras
    speak_rec_speak:     'Konuş',
    speak_rec_stop:      'Durdur',
    speak_mic_error:     'Mikrofon izni gerekli.',
    speak_word_chip:     'Dinle ve Tekrar Et',

    // Conversation extras
    convo_avg_score:     'Ortalama Skor',
    convo_scenarios_back:'← Senaryolar',
    convo_speak_label:   'Konuş',
    convo_stop_label:    'Durdur',

    // Word popup extras
    word_added_btn: '✅ Eklendi',
  },

  // ── ENGLISH ────────────────────────────────────────────────
  en: {
    nav_home:    'Home',
    nav_learn:   'Practice',
    nav_reading: 'Reading',
    nav_speak:   'Speaking',

    home_subtitle:       'Continue your English learning journey',
    greeting_morning:    '🌅 Good morning!',
    greeting_afternoon:  '☀️ Good afternoon!',
    greeting_evening:    '🌙 Good evening!',
    stat_words:          'Words Learned',
    stat_streak:         'Day Streak',
    stat_accuracy:       'Accuracy',
    xp_remain:           'XP remaining',
    daily_goal:          '🎯 Daily Goal',
    daily_done:          '✅ Daily goal completed!',
    weekly_activity:     'Last 7 Days',
    wod_label:           '⭐ Word of the Day',
    wod_listen:          '🔊 Listen',
    best_score:          'Best',
    try_today:           'Try today →',
    completed_pct:       'completed',
    no_history:          'No attempts yet',

    lab_learn_title: 'Synesthesia Lab',
    lab_learn_desc:  'Learn words permanently with AI-powered spaced repetition.',
    lab_speak_title: 'Speaking Lab',
    lab_speak_desc:  'Speak into the microphone — AI analyses your pronunciation word by word.',
    lab_read_title:  'Reading Workshop',
    lab_read_desc:   'Build context through stories and deepen your understanding.',

    reading_title:     '📖 Reading Workshop',
    reading_subtitle:  'Feel the context through real texts, live the words.',
    reading_mode_read: '📚 Read',
    reading_mode_quiz: '🧩 Exercise',
    reading_listen:    '🎧 Listen',
    reading_stop:      '🛑 Stop',
    reading_prev:      '← Previous',
    reading_next:      'Next →',
    reading_shuffle:   '🔀 Shuffle',
    level_easy:        '🌱 Easy',
    level_mid:         '📚 Medium',
    level_adv:         '🔥 Advanced',
    no_content:        'No content found.',
    quiz_no_blank:     'Please select a blank (_____) first.',

    synth_title:         'SYNESTHESIA',
    synth_subtitle:      'Neural Learning Matrix — Multi-Modal Immersion',
    synth_rule1:         'TYPING: Each letter glows in its own colour — a true synesthesia experience.',
    synth_rule2:         'CONTEXT: Learn words by filling in blanks inside real sentences.',
    synth_rule3:         'Speed bonus: The faster you type, the more +XP. Combo: 5× = 2×, 10× = 3× XP.',
    synth_mode_label:    'Mode',
    synth_mode_context:  'CONTEXT',
    synth_mode_context_desc: 'Sentence completion',
    synth_mode_speed:    'TIME ATTACK',
    synth_mode_speed_desc: 'Be fast, earn 30 XP!',
    synth_mode_choice:   'CHOICE',
    synth_session_label: 'Session Length',
    synth_start_btn:     'START SESSION',
    synth_pause_sub:     'Ready when you are',
    synth_resume_btn:    '▶ CONTINUE',
    synth_menu_btn:      'Main Menu',
    synth_hint_label:    'hints used',
    synth_listen_btn:    '🔊 Listen',
    synth_skip_btn:      "Don't know ⏭",
    synth_finish_title:  'SESSION COMPLETE',
    synth_xp_earned:     'XP Earned',
    synth_perfect:       'Perfect',
    synth_accuracy:      'Accuracy',
    synth_avg_time:      'Avg. Time',
    synth_fastest:       'Fastest',
    synth_home_btn:      'Home',
    synth_mode_ind_speed:   '⚡ TIME ATTACK',
    synth_mode_ind_context: '🧩 CONTEXT',
    synth_mode_ind_choice:  '🔘 CHOICE',
    synth_grade_great:   '🏆 Outstanding!',
    synth_grade_good:    '💪 Great job!',
    synth_grade_ok:      '📚 Keep practising!',
    synth_grade_retry:   '🔄 Keep going!',
    synth_choice_label:  '🔘 Choice',
    synth_speed_bonus:   '⚡ Speed XP',
    synth_timeout:       'Time up!',
    synth_too_slow:      '⚡ Too slow!',
    hint_first_letter:   'Hint: First letter',
    hint_wrong3:         '⚠️ 3 mistakes! Showing answer...',

    speak_title:         '🎙️ Speaking Lab',
    speak_subtitle:      'Your AI-powered speaking coach — 4 powerful modes',
    speak_mode_pronounce:'🎯 Pronunciation',
    speak_mode_ai:       '🤖 AI Chat',
    speak_diff_easy:     '🌱 Beginner',
    speak_diff_mid:      '📚 Intermediate',
    speak_diff_adv:      '🔥 Advanced',
    speak_shadow:        'Shadow Mode',
    speak_shuffle:       'Shuffle',
    speak_listen:        'Listen',
    speak_slow:          'Slow',
    speak_record:        'Speak',
    speak_playback:      'Playback',
    speak_retry:         'Retry',
    speak_stop:          'Stop',
    speak_keyboard_hint: '⌨️ Space — Record / Stop',
    speak_session_panel: '📊 Session',
    speak_history_panel: '📋 Recent Attempts',
    speak_best:          'Best',
    speak_no_history:    'No attempts yet',
    speak_listening:     '🎙️ Listening... Start speaking',
    speak_no_support:    "Your browser doesn't support speech recognition.",
    speak_click_listen:  'Click to listen',
    speak_improve_ipa:   '🎯 Improve Your Pronunciation:',
    fb_perfect:          '🏆 Outstanding! Native-level!',
    fb_great:            '🎉 Excellent! You\'re doing great.',
    fb_good:             '💪 Good job! A little more practice.',
    fb_retry:            '🔄 Try again — speak more clearly.',

    convo_title:         'Choose a Scenario',
    convo_subtitle:      'Speak English in real-life situations',
    convo_turns:         'turns',
    convo_example:       'Example:',
    convo_finish_title:  'Conversation Complete!',
    convo_xp:            'XP earned!',
    convo_new:           'New Scenario',
    convo_skipped:       '(skipped)',
    convo_diff_easy:     '🌱 Easy',
    convo_diff_mid:      '📚 Medium',
    convo_diff_adv:      '🔥 Advanced',

    popup_example:       'Example',
    popup_synonyms:      'Synonyms',
    popup_collocations:  'Common Collocations',
    popup_add:           '➕ Add to List',
    popup_no_entry:      'This word is not in the database yet',
    popup_grammar_word:  '/grammar word/',
    popup_grammar_note:  'This is a functional word and cannot be added to the list.',
    popup_audio_only:    '🔊 Listen',

    type_word:         'Word',
    type_phrasal:      'Phrasal Verb',
    type_idiom:        'Idiom',
    type_grammar:      'Grammar Pattern',
    type_verb_pattern: 'Verb Pattern',
    type_noun_phrase:  'Noun Phrase',

    quiz_correct: '✓ Correct!',
    quiz_wrong:   '✗ Wrong',

    toast_word_added:  'Word added to your learning list! 📚',
    toast_word_exists: 'This word is already in your list!',
    toast_level_up:    'Level up!',
    toast_words_goal:  'words reached!',
    toast_accent_us:   '🗣️ Accent: American English',
    toast_accent_gb:   '🗣️ Accent: British English',
    toast_shadow_on:   'Shadow Mode On',
    toast_shadow_off:  'Shadow Mode Off',
    toast_shuffle_on:  'Shuffle Mode On',
    toast_shuffle_off: 'Shuffle Mode Off',
    toast_lang_tr:     '🇹🇷 Türkçe seçildi',
    toast_lang_en:     '🇬🇧 English selected',
    toast_lang_es:     '🇪🇸 Español seleccionado',

    ob_title:      'Welcome to English Rhapsody!',
    ob_subtitle:   'Answer a few questions so we can set your level and create a personalised learning experience.',
    ob_start:      'Get Started →',
    ob_q1:         'How would you describe your English level?',
    ob_q1_sub:     'We\'ll prepare content that suits you',
    ob_q1_a0:      'Complete beginner',
    ob_q1_a0_sub:  'A1 · Starting from scratch',
    ob_q1_a5:      'Advanced speaker',
    ob_q1_a5_sub:  'C1+',
    ob_q2_sub:     'Click the correct option',
    ob_q3_sub:     'Select the right option',
    ob_finish:     "Let's Begin!",
    ob_level_set:  '✅ Level set! Start learning.',
    ob_bonus:      'Starter bonus:',
    ob_rank_begin: 'Beginner 🌱',
    ob_rank_adv:   'Advanced 🏆',

    rank_0:'Apprentice', rank_1:'Journeyman', rank_2:'Expert',
    rank_3:'Master',     rank_4:'Virtuoso',   rank_5:'Legend',

    tip_label: '💡 Language Tip',

    xp_label:     'XP',
    streak_label: '🔥 Streak',
    loading:      'Loading…',
    close_btn:    '✕',
    back:         'Back',
    skip:         '⏭ Skip',

    // Achievement
    achievement_unlocked: 'Achievement Unlocked!',

    // Days (short, Mon=0)
    days_short: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],

    // Onboarding extras
    ob_q1_title:   'Set Your Level',
    ob_q1_a1:      'I know a little',
    ob_q1_a1_sub:  'A2 · Basic',
    ob_q1_a3:      "I'm at intermediate level",
    ob_q1_a3_sub:  'B1/B2',
    ob_q2_title:   'What does "Galaxy" mean?',
    ob_q2_a0:      '☀️ Sun',
    ob_q2_a1:      '🌀 Galaxy',
    ob_q2_a2:      '⭐ Star',
    ob_q2_a3:      '🪐 Planet',
    ob_q3_title:   '"I\'m looking forward to ___ you."',
    ob_finish_title: "We've Set Your Level!",
    ob_rank_mid:   'Intermediate Level 📚',

    // Synesthesia extras
    synth_write_mode:  '⌨️ TYPING',
    synth_missed_title:'📝 To Review',
    synth_replay_btn:  'PLAY AGAIN',
    synth_total_label: 'Total',

    // Speaking extras
    speak_rec_speak:     'Speak',
    speak_rec_stop:      'Stop',
    speak_mic_error:     'Microphone permission required.',
    speak_word_chip:     'Listen and Repeat',

    // Conversation extras
    convo_avg_score:     'Average Score',
    convo_scenarios_back:'← Scenarios',
    convo_speak_label:   'Speak',
    convo_stop_label:    'Stop',

    // Word popup extras
    word_added_btn: '✅ Added',
  },

  // ── SPANISH ────────────────────────────────────────────────
  es: {
    nav_home:    'Inicio',
    nav_learn:   'Práctica',
    nav_reading: 'Lectura',
    nav_speak:   'Hablar',

    home_subtitle:       'Continúa tu aprendizaje de inglés',
    greeting_morning:    '🌅 ¡Buenos días!',
    greeting_afternoon:  '☀️ ¡Buenas tardes!',
    greeting_evening:    '🌙 ¡Buenas noches!',
    stat_words:          'Palabras Aprendidas',
    stat_streak:         'Racha de Días',
    stat_accuracy:       'Precisión',
    xp_remain:           'XP restantes',
    daily_goal:          '🎯 Meta Diaria',
    daily_done:          '✅ ¡Meta diaria completada!',
    weekly_activity:     'Últimos 7 Días',
    wod_label:           '⭐ Palabra del Día',
    wod_listen:          '🔊 Escuchar',
    best_score:          'Mejor',
    try_today:           'Intenta hoy →',
    completed_pct:       'completado',
    no_history:          'Aún sin intentos',

    lab_learn_title: 'Lab Sinestesia',
    lab_learn_desc:  'Aprende palabras de forma permanente con repetición espaciada por IA.',
    lab_speak_title: 'Lab de Habla',
    lab_speak_desc:  'Habla al micrófono — la IA analiza tu pronunciación palabra por palabra.',
    lab_read_title:  'Taller de Lectura',
    lab_read_desc:   'Construye contexto a través de historias y profundiza tu comprensión.',

    reading_title:     '📖 Taller de Lectura',
    reading_subtitle:  'Siente el contexto con textos reales, vive las palabras.',
    reading_mode_read: '📚 Leer',
    reading_mode_quiz: '🧩 Ejercicio',
    reading_listen:    '🎧 Escuchar',
    reading_stop:      '🛑 Detener',
    reading_prev:      '← Anterior',
    reading_next:      'Siguiente →',
    reading_shuffle:   '🔀 Mezclar',
    level_easy:        '🌱 Fácil',
    level_mid:         '📚 Medio',
    level_adv:         '🔥 Avanzado',
    no_content:        'No se encontró contenido.',
    quiz_no_blank:     'Primero selecciona un espacio (___).',

    synth_title:         'SINESTESIA',
    synth_subtitle:      'Matriz de Aprendizaje Neural — Inmersión Multimodal',
    synth_rule1:         'ESCRITURA: Cada letra brilla en su color — experiencia sinestésica real.',
    synth_rule2:         'CONTEXTO: Aprende palabras completando espacios en oraciones reales.',
    synth_rule3:         'Bonus de velocidad: Cuanto más rápido, más +XP. Combo: 5× = 2×, 10× = 3× XP.',
    synth_mode_label:    'Modo',
    synth_mode_context:  'CONTEXTO',
    synth_mode_context_desc: 'Completar oraciones',
    synth_mode_speed:    'CONTRARRELOJ',
    synth_mode_speed_desc: '¡Sé rápido, gana 30 XP!',
    synth_mode_choice:   'ELECCIÓN',
    synth_session_label: 'Duración de la Sesión',
    synth_start_btn:     'INICIAR SESIÓN',
    synth_pause_sub:     'Cuando estés listo, continúa',
    synth_resume_btn:    '▶ CONTINUAR',
    synth_menu_btn:      'Menú Principal',
    synth_hint_label:    'pistas usadas',
    synth_listen_btn:    '🔊 Escuchar',
    synth_skip_btn:      'No sé ⏭',
    synth_finish_title:  'SESIÓN COMPLETA',
    synth_xp_earned:     'XP Ganados',
    synth_perfect:       'Perfecto',
    synth_accuracy:      'Precisión',
    synth_avg_time:      'T. Prom.',
    synth_fastest:       'Más Rápido',
    synth_home_btn:      'Inicio',
    synth_mode_ind_speed:   '⚡ CONTRARRELOJ',
    synth_mode_ind_context: '🧩 CONTEXTO',
    synth_mode_ind_choice:  '🔘 ELECCIÓN',
    synth_grade_great:   '🏆 ¡Sobresaliente!',
    synth_grade_good:    '💪 ¡Buen trabajo!',
    synth_grade_ok:      '📚 ¡Sigue practicando!',
    synth_grade_retry:   '🔄 ¡Continúa!',
    synth_choice_label:  '🔘 Elección',
    synth_speed_bonus:   '⚡ XP Velocidad',
    synth_timeout:       '¡Tiempo agotado!',
    synth_too_slow:      '⚡ ¡Demasiado lento!',
    hint_first_letter:   'Pista: Primera letra',
    hint_wrong3:         '⚠️ ¡3 errores! Mostrando respuesta...',

    speak_title:         '🎙️ Lab de Habla',
    speak_subtitle:      'Tu entrenador de conversación con IA — 4 modos potentes',
    speak_mode_pronounce:'🎯 Pronunciación',
    speak_mode_ai:       '🤖 Chat IA',
    speak_diff_easy:     '🌱 Principiante',
    speak_diff_mid:      '📚 Intermedio',
    speak_diff_adv:      '🔥 Avanzado',
    speak_shadow:        'Modo Sombra',
    speak_shuffle:       'Mezclar',
    speak_listen:        'Escuchar',
    speak_slow:          'Lento',
    speak_record:        'Hablar',
    speak_playback:      'Reproducir',
    speak_retry:         'Reintentar',
    speak_stop:          'Detener',
    speak_keyboard_hint: '⌨️ Espacio — Grabar / Detener',
    speak_session_panel: '📊 Sesión',
    speak_history_panel: '📋 Intentos Recientes',
    speak_best:          'Mejor',
    speak_no_history:    'Aún sin intentos',
    speak_listening:     '🎙️ Escuchando... Empieza a hablar',
    speak_no_support:    'Tu navegador no soporta reconocimiento de voz.',
    speak_click_listen:  'Clic para escuchar',
    speak_improve_ipa:   '🎯 Mejora tu Pronunciación:',
    fb_perfect:          '🏆 ¡Sobresaliente! ¡Nivel nativo!',
    fb_great:            '🎉 ¡Excelente! Lo estás haciendo muy bien.',
    fb_good:             '💪 ¡Buen trabajo! Practica un poco más.',
    fb_retry:            '🔄 Inténtalo de nuevo — habla más claro.',

    convo_title:         'Elige un Escenario',
    convo_subtitle:      'Habla inglés en situaciones de la vida real',
    convo_turns:         'turnos',
    convo_example:       'Ejemplo:',
    convo_finish_title:  '¡Conversación Completada!',
    convo_xp:            '¡XP ganados!',
    convo_new:           'Nuevo Escenario',
    convo_skipped:       '(omitido)',
    convo_diff_easy:     '🌱 Fácil',
    convo_diff_mid:      '📚 Medio',
    convo_diff_adv:      '🔥 Avanzado',

    popup_example:       'Ejemplo',
    popup_synonyms:      'Sinónimos',
    popup_collocations:  'Expresiones Comunes',
    popup_add:           '➕ Añadir a la Lista',
    popup_no_entry:      'Esta palabra aún no está en la base de datos',
    popup_grammar_word:  '/palabra gramatical/',
    popup_grammar_note:  'Esta es una palabra funcional y no se puede añadir a la lista.',
    popup_audio_only:    '🔊 Escuchar',

    type_word:         'Palabra',
    type_phrasal:      'Verbo Frasal',
    type_idiom:        'Modismo',
    type_grammar:      'Patrón Gramatical',
    type_verb_pattern: 'Patrón Verbal',
    type_noun_phrase:  'Expresión Nominal',

    quiz_correct: '✓ ¡Correcto!',
    quiz_wrong:   '✗ Incorrecto',

    toast_word_added:  '¡Palabra añadida a tu lista de aprendizaje! 📚',
    toast_word_exists: '¡Esta palabra ya está en tu lista!',
    toast_level_up:    '¡Subiste de nivel!',
    toast_words_goal:  '¡palabras alcanzadas!',
    toast_accent_us:   '🗣️ Acento: Inglés Americano',
    toast_accent_gb:   '🗣️ Acento: Inglés Británico',
    toast_shadow_on:   'Modo Sombra activado',
    toast_shadow_off:  'Modo Sombra desactivado',
    toast_shuffle_on:  'Modo Aleatorio activado',
    toast_shuffle_off: 'Modo Aleatorio desactivado',
    toast_lang_tr:     '🇹🇷 Türkçe seçildi',
    toast_lang_en:     '🇬🇧 English selected',
    toast_lang_es:     '🇪🇸 Español seleccionado',

    ob_title:      '¡Bienvenido a English Rhapsody!',
    ob_subtitle:   'Responde unas preguntas para establecer tu nivel y crear una experiencia personalizada.',
    ob_start:      'Empezar →',
    ob_q1:         '¿Cómo describirías tu nivel de inglés?',
    ob_q1_sub:     'Prepararemos contenido adecuado para ti',
    ob_q1_a0:      'Soy principiante total',
    ob_q1_a0_sub:  'A1 · Desde cero',
    ob_q1_a5:      'Soy hablante avanzado',
    ob_q1_a5_sub:  'C1+',
    ob_q2_sub:     'Haz clic en la opción correcta',
    ob_q3_sub:     'Selecciona la opción correcta',
    ob_finish:     '¡Comencemos!',
    ob_level_set:  '✅ ¡Nivel establecido! Empieza a aprender.',
    ob_bonus:      'Bonificación inicial:',
    ob_rank_begin: 'Principiante 🌱',
    ob_rank_adv:   'Avanzado 🏆',

    rank_0:'Aprendiz',  rank_1:'Oficial',   rank_2:'Experto',
    rank_3:'Maestro',   rank_4:'Virtuoso',  rank_5:'Leyenda',

    tip_label: '💡 Consejo de Idioma',

    xp_label:     'XP',
    streak_label: '🔥 Racha',
    loading:      'Cargando…',
    close_btn:    '✕',
    back:         'Atrás',
    skip:         '⏭ Omitir',

    // Achievement
    achievement_unlocked: '¡Logro desbloqueado!',

    // Days (short, Mon=0)
    days_short: ['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'],

    // Onboarding extras
    ob_q1_title:   'Establece tu nivel',
    ob_q1_a1:      'Sé un poco',
    ob_q1_a1_sub:  'A2 · Básico',
    ob_q1_a3:      'Nivel intermedio',
    ob_q1_a3_sub:  'B1/B2',
    ob_q2_title:   '¿Qué significa "Galaxy"?',
    ob_q2_a0:      '☀️ Sol',
    ob_q2_a1:      '🌀 Galaxia',
    ob_q2_a2:      '⭐ Estrella',
    ob_q2_a3:      '🪐 Planeta',
    ob_q3_title:   '"I\'m looking forward to ___ you."',
    ob_finish_title: '¡Hemos establecido tu nivel!',
    ob_rank_mid:   'Nivel Intermedio 📚',

    // Synesthesia extras
    synth_write_mode:  '⌨️ ESCRITURA',
    synth_missed_title:'📝 Para Repasar',
    synth_replay_btn:  'JUGAR DE NUEVO',
    synth_total_label: 'Total',

    // Speaking extras
    speak_rec_speak:     'Hablar',
    speak_rec_stop:      'Detener',
    speak_mic_error:     'Permiso de micrófono requerido.',
    speak_word_chip:     'Escuchar y Repetir',

    // Conversation extras
    convo_avg_score:     'Puntuación Promedio',
    convo_scenarios_back:'← Escenarios',
    convo_speak_label:   'Hablar',
    convo_stop_label:    'Detener',

    // Word popup extras
    word_added_btn: '✅ Añadido',
  },
};

// ── Helpers ────────────────────────────────────────────────────
function getTypeName(rawType, lang) {
  const map = {
    'Kelime':         { tr:'Kelime',         en:'Word',             es:'Palabra'           },
    'Phrasal Verb':   { tr:'Phrasal Verb',   en:'Phrasal Verb',     es:'Verbo Frasal'      },
    'Deyim':          { tr:'Deyim',          en:'Idiom',            es:'Modismo'           },
    'Gramer Kalıbı':  { tr:'Gramer Kalıbı',  en:'Grammar Pattern',  es:'Patrón Gramatical' },
    'Eylem Kalıbı':   { tr:'Eylem Kalıbı',   en:'Verb Pattern',     es:'Patrón Verbal'     },
    'İsim Tamlaması': { tr:'İsim Tamlaması', en:'Noun Phrase',      es:'Expresión Nominal' },
  };
  const entry = map[rawType];
  if (!entry) return rawType;
  return entry[lang] || entry.tr;
}

// Basic function-word translations per language
const BASIC_DICT = {
  tr: {
    the:'belirli nesne (açıklayıcı)', a:'bir', an:'bir', and:'ve', or:'veya',
    but:'fakat, ama', is:'dır/dir (olmak)', am:'ım/im (olmak)',
    are:'lar/ler (olmak)', was:'idi (geçmiş)', were:'idiler',
    in:'içinde', on:'üzerinde', at:'de/da', to:'e/a', with:'ile', from:'den/dan',
    i:'ben', you:'sen/siz', he:'o (erkek)', she:'o (kadın)',
    it:'o (cansız)', we:'biz', they:'onlar',
    my:'benim', your:'senin', his:'onun (erkek)', her:'onun (kadın)',
    its:'onun (cansız)', our:'bizim', their:'onların',
    me:'beni/bana', him:'onu/ona', us:'bizi/bize', them:'onları/onlara',
    this:'bu', that:'şu/o', these:'bunlar', those:'şunlar/onlar',
    for:'için', of:'ın/in', as:'olarak', by:'tarafından/yanında',
    can:'ebilmek', will:'ecek/acak', would:'erdi/ardı',
    should:'meli/malı', must:'malı/meli (zorunluluk)',
    not:'değil/olumsuzluk', no:'hayır', yes:'evet', very:'çok', so:'öylece/çok',
    have:'sahip olmak', has:'sahip olmak', had:'sahip oldu',
    do:'yapmak', does:'yapmak', did:'yaptı',
    said:'dedi/söyledi', says:'der/söyler', say:'demek/söylemek',
  },
  en: {
    the:'definite article (specifies a noun)', a:'indefinite article', an:'indefinite article (before vowel)',
    and:'connects words or clauses', or:'indicates a choice', but:'shows contrast',
    is:'3rd person singular of "be"', am:'1st person singular of "be"',
    are:'plural/you form of "be"', was:'past singular of "be"', were:'past plural of "be"',
    in:'inside; within', on:'on top of; about', at:'at a place or time',
    to:'towards; infinitive marker', with:'together with', from:'point of origin',
    i:'first person singular pronoun', you:'second person pronoun',
    he:'third person singular male', she:'third person singular female',
    it:'third person singular neuter', we:'first person plural', they:'third person plural',
    my:'belonging to me', your:'belonging to you', his:'belonging to him',
    her:'belonging to her', its:'belonging to it', our:'belonging to us', their:'belonging to them',
    me:'object form of I', him:'object form of he', us:'object form of we', them:'object form of they',
    this:'near demonstrative', that:'far demonstrative',
    these:'near demonstrative plural', those:'far demonstrative plural',
    for:'purpose or duration', of:'possession or relation',
    as:'in the role of; to the same degree', by:'near; through the action of',
    can:'ability or possibility', will:'future intention', would:'conditional',
    should:'advice or expectation', must:'necessity or strong inference',
    not:'negation', no:'refusal or absence', yes:'affirmation',
    very:'intensifier', so:'therefore; to such a degree',
    have:'possession; perfect auxiliary', has:'3rd person of have',
    had:'past of have', do:'perform; auxiliary verb', does:'3rd person of do',
    did:'past of do', said:'past of say', says:'3rd person of say', say:'to speak words',
  },
  es: {
    the:'artículo determinado', a:'artículo indeterminado', an:'artículo indeterminado (ante vocal)',
    and:'y (conjunción)', or:'o (conjunción)', but:'pero (conjunción)',
    is:'es / está (3ª persona)', am:'soy / estoy (1ª persona)',
    are:'son / están (plural)', was:'era / estaba (pasado singular)', were:'eran / estaban',
    in:'en; dentro de', on:'sobre; encima de', at:'en; a',
    to:'a; hacia; para', with:'con', from:'de; desde',
    i:'yo', you:'tú; usted', he:'él', she:'ella',
    it:'ello (neutro)', we:'nosotros', they:'ellos; ellas',
    my:'mi; mis', your:'tu; tus', his:'su; sus (él)',
    her:'su; sus (ella)', its:'su; sus (neutro)', our:'nuestro; nuestra', their:'su; sus (ellos)',
    me:'me; mí', him:'lo; le; a él', us:'nos; nosotros', them:'los; les; a ellos',
    this:'este; esta; esto', that:'ese; aquel; eso',
    these:'estos; estas', those:'esos; aquellos',
    for:'para; por', of:'de (posesión)', as:'como; en calidad de', by:'por; junto a',
    can:'poder (capacidad)', will:'futuro / voluntad', would:'condicional',
    should:'debería', must:'debe; hay que',
    not:'no (negación)', no:'no; ningún', yes:'sí', very:'muy', so:'entonces; tan',
    have:'tener; haber (auxiliar)', has:'tiene; ha (3ª persona)', had:'tenía; había',
    do:'hacer (verbo auxiliar)', does:'hace (3ª persona)', did:'hizo; hizo (pasado)',
    said:'dijo (pasado de say)', says:'dice (3ª persona)', say:'decir',
  },
};
