'use strict';
/* ============================================================
   English Rhapsody — Word & Phrase Translations
   WORD_ES  : WORDS id → Spanish translation
   PHRASE_ES: PHRASE_DICT key → Spanish translation
   PHRASE_EN: PHRASE_DICT key → English definition
   ============================================================ */

// ── Spanish translations for WORDS array ──────────────────────
const WORD_ES = {
  // A1 – Core
  apple:'manzana', book:'libro', car:'coche, auto', door:'puerta',
  family:'familia', house:'casa', key:'llave', money:'dinero',
  name:'nombre', phone:'teléfono', school:'escuela, colegio',
  table:'mesa', welcome:'bienvenido; dar la bienvenida',
  water:'agua', window:'ventana', day:'día', night:'noche',
  morning:'mañana', friend:'amigo, amiga', room:'habitación, cuarto',
  city:'ciudad', child:'niño; hijo', man:'hombre', woman:'mujer',
  year:'año', life:'vida',

  // Animals
  dog:'perro', cat:'gato', fish:'pez; pescado', bird:'pájaro, ave',
  horse:'caballo', cow:'vaca', rabbit:'conejo', lion:'león',
  elephant:'elefante', butterfly:'mariposa',

  // Nature
  sun:'sol', tree:'árbol', rain:'lluvia; llover', flower:'flor',
  mountain:'montaña', cloud:'nube', sea:'mar', sky:'cielo',
  river:'río', wind:'viento',

  // Food & Drink
  bread:'pan', milk:'leche', egg:'huevo', meat:'carne', fruit:'fruta',
  rice:'arroz', sugar:'azúcar', salt:'sal', coffee:'café', tea:'té',
  juice:'zumo, jugo', cake:'pastel, tarta', soup:'sopa',
  cheese:'queso', butter:'mantequilla',

  // Colours & Adjectives
  red:'rojo', blue:'azul', green:'verde', white:'blanco', black:'negro',
  big:'grande', small:'pequeño', new:'nuevo', old:'viejo, antiguo',
  hot:'caliente; caluroso', cold:'frío', fast:'rápido', slow:'lento',
  good:'bueno', bad:'malo',

  // Common Verbs
  eat:'comer', drink:'beber; bebida', sleep:'dormir; sueño',
  run:'correr', walk:'caminar; paseo', read:'leer', write:'escribir',
  play:'jugar; tocar', work:'trabajar; trabajo', help:'ayudar; ayuda',
  buy:'comprar', open:'abrir; abierto', close:'cerrar; cercano',
  give:'dar', take:'tomar, coger',

  // Emotions
  happy:'feliz, alegre', sad:'triste', angry:'enfadado, enojado',
  tired:'cansado', hungry:'hambriento; con hambre',
  afraid:'asustado; con miedo', excited:'emocionado, ilusionado',
  bored:'aburrido', surprised:'sorprendido', proud:'orgulloso',

  // Home
  bathroom:'baño, cuarto de baño', bedroom:'dormitorio',
  kitchen:'cocina', garden:'jardín',

  // More Adjectives
  clean:'limpio; limpiar', dirty:'sucio', heavy:'pesado',
  light:'ligero; luz; claro', loud:'ruidoso', quiet:'tranquilo, silencioso',
  expensive:'caro, costoso', cheap:'barato', difficult:'difícil',
  easy:'fácil', correct:'correcto', wrong:'incorrecto, equivocado',
  same:'mismo, igual', different:'diferente, distinto', free:'libre; gratis',

  // Travel
  travel:'viajar; viaje', ticket:'billete, boleto', passport:'pasaporte',
  luggage:'equipaje', hotel:'hotel', flight:'vuelo',
  destination:'destino', map:'mapa', tour:'excursión, gira',
  vacation:'vacaciones', trip:'viaje', guide:'guía',
  customs:'aduana', reservation:'reserva',

  // Work & Business
  job:'trabajo, empleo', company:'empresa, compañía',
  meeting:'reunión; encuentro', email:'correo electrónico',
  report:'informe; reportar', project:'proyecto',
  deadline:'fecha límite, plazo', salary:'salario, sueldo',
  manager:'gerente, director', team:'equipo', customer:'cliente',
  product:'producto',

  // Health
  doctor:'médico, doctor', nurse:'enfermero, enfermera',
  medicine:'medicamento; medicina', hospital:'hospital',
  sick:'enfermo', pain:'dolor', fever:'fiebre', cough:'tos; toser',
  headache:'dolor de cabeza', exercise:'ejercicio; ejercitarse',
  diet:'dieta; régimen',

  // Technology
  computer:'ordenador, computadora', internet:'internet',
  message:'mensaje', camera:'cámara', battery:'batería',
  screen:'pantalla', password:'contraseña', app:'aplicación',
  website:'sitio web, página web', software:'software, programa',
  hardware:'hardware, componentes', network:'red',
  database:'base de datos', digital:'digital', download:'descargar',
  upload:'cargar, subir', device:'dispositivo', robot:'robot',
  artificial:'artificial', wireless:'inalámbrico', update:'actualizar',

  // Education
  university:'universidad', student:'estudiante',
  teacher:'profesor, maestro', lesson:'lección, clase',
  homework:'tarea, deberes', exam:'examen',
  grade:'nota, calificación', language:'idioma, lengua',
  practice:'practicar; práctica', question:'pregunta',
  answer:'respuesta; responder', mistake:'error, equivocación',
  learn:'aprender',

  // Family & Social
  neighbor:'vecino', parent:'padre/madre; padres',
  husband:'esposo, marido', wife:'esposa, mujer',
  brother:'hermano', sister:'hermana', cousin:'primo, prima',
  weekend:'fin de semana', holiday:'vacaciones; día festivo',
  birthday:'cumpleaños', wedding:'boda', party:'fiesta', gift:'regalo',

  // Sports & Arts
  sport:'deporte', swimming:'natación; nadar', music:'música',
  dance:'bailar; baile', sing:'cantar', draw:'dibujar; empate',
  cook:'cocinar; cocinero', film:'película, filme', game:'juego',
  story:'historia, cuento', newspaper:'periódico, diario',

  // Environment & Nature
  weather:'tiempo, clima', street:'calle', bank:'banco',
  market:'mercado', restaurant:'restaurante', airport:'aeropuerto',
  library:'biblioteca', science:'ciencia', research:'investigación',
  experiment:'experimento', discovery:'descubrimiento', theory:'teoría',
  evidence:'evidencia, prueba', laboratory:'laboratorio',
  energy:'energía', gravity:'gravedad', biology:'biología',
  chemistry:'química', physics:'física', evolution:'evolución',
  temperature:'temperatura', environment:'medio ambiente; entorno',
  pollution:'contaminación', climate:'clima', forest:'bosque, selva',
  ocean:'océano', species:'especie', wildlife:'fauna silvestre',
  recycle:'reciclar', renewable:'renovable', carbon:'carbono',
  ecosystem:'ecosistema', drought:'sequía', flood:'inundación',
  earthquake:'terremoto',

  // Economics & Business (advanced)
  economy:'economía', investment:'inversión', profit:'beneficio, ganancia',
  industry:'industria', competition:'competencia, competición',
  strategy:'estrategia', marketing:'marketing, mercadotecnia',
  negotiation:'negociación', budget:'presupuesto', finance:'finanzas',
  trade:'comercio; comerciar', contract:'contrato',
  revenue:'ingresos, recaudación',

  // Medical (advanced)
  treatment:'tratamiento', surgery:'cirugía, operación',
  therapy:'terapia', diagnosis:'diagnóstico', symptom:'síntoma',
  vaccine:'vacuna', nutrition:'nutrición', vitamin:'vitamina',
  protein:'proteína', prevention:'prevención', allergy:'alergia',

  // Society & Culture
  community:'comunidad', culture:'cultura', tradition:'tradición',
  religion:'religión', government:'gobierno', democracy:'democracia',
  freedom:'libertad', equality:'igualdad', justice:'justicia',
  leadership:'liderazgo', responsibility:'responsabilidad',
  citizen:'ciudadano', poverty:'pobreza', volunteer:'voluntario',
  charity:'caridad; organización benéfica',

  // Communication
  conversation:'conversación', discuss:'discutir, debatir',
  debate:'debate; debatir', persuade:'persuadir, convencer',
  describe:'describir', explain:'explicar',
  presentation:'presentación', interview:'entrevista; entrevistar',

  // Arts & Literature
  painting:'pintura, cuadro', sculpture:'escultura',
  literature:'literatura', theater:'teatro', instrument:'instrumento',
  audience:'público, audiencia', creativity:'creatividad',

  // Soft Skills & Emotions (advanced)
  confidence:'confianza, seguridad', courage:'valentía, coraje',
  patience:'paciencia', wisdom:'sabiduría', motivation:'motivación',
  inspiration:'inspiración', frustration:'frustración',
  anxiety:'ansiedad', compassion:'compasión', gratitude:'gratitud',
  respect:'respeto; respetar', honesty:'honestidad, honradez',
  ambition:'ambición', determination:'determinación',
  empathy:'empatía', stress:'estrés', focus:'enfoque; concentrarse',

  // False friends & tricky A2/B1
  actual:'real, verdadero (¡falso amigo!)',
  eventually:'finalmente, con el tiempo',
  sensible:'sensato, prudente', sensitive:'sensible, delicado',
  sympathetic:'comprensivo, compasivo',

  // Academic Vocabulary (B2/C1)
  analysis:'análisis', hypothesis:'hipótesis',
  methodology:'metodología', conclusion:'conclusión',
  perspective:'perspectiva', concept:'concepto',
  principle:'principio', framework:'marco, estructura',
  interpretation:'interpretación', evaluation:'evaluación',
  abstract:'abstracto; resumen', objective:'objetivo; imparcial',
  subjective:'subjetivo', empirical:'empírico',
  theoretical:'teórico', significant:'significativo, importante',
  relevant:'relevante, pertinente', context:'contexto',
  implication:'implicación', correlation:'correlación',

  // Business (B2/C1)
  entrepreneur:'emprendedor', innovation:'innovación',
  disruption:'disrupción, interrupción', efficiency:'eficiencia',
  productivity:'productividad', sustainability:'sostenibilidad',
  corporate:'corporativo, empresarial', strategic:'estratégico',
  stakeholder:'parte interesada', optimize:'optimizar',
  agile:'ágil', scalable:'escalable', merger:'fusión',
  acquisition:'adquisición', compliance:'cumplimiento',
  governance:'gobernanza, gobierno',

  // Psychology & Social Science
  psychology:'psicología', behavior:'comportamiento, conducta',
  cognitive:'cognitivo', subconscious:'subconsciente',
  perception:'percepción', personality:'personalidad',
  resilience:'resiliencia, resistencia', bias:'sesgo, prejuicio',
  trauma:'trauma', mindset:'mentalidad', habit:'hábito, costumbre',

  // Philosophy
  philosophy:'filosofía', ethics:'ética',
  moral:'moral, ético; moraleja', consciousness:'conciencia',
  existence:'existencia', identity:'identidad',

  // Politics & Law
  constitution:'constitución', legislation:'legislación',
  parliament:'parlamento', election:'elección',
  policy:'política (de gobierno)', reform:'reforma; reformar',
  treaty:'tratado', diplomacy:'diplomacia',
  sovereignty:'soberanía', corruption:'corrupción',
  protest:'protesta; protestar',

  // Literary Terms
  narrative:'narrativa, relato', metaphor:'metáfora',
  symbolism:'simbolismo', irony:'ironía', genre:'género (literario)',
  theme:'tema', protagonist:'protagonista', conflict:'conflicto',
  imagery:'imágenes, imaginería', poetry:'poesía',
  plot:'trama, argumento', dialogue:'diálogo',

  // Social Issues
  urbanization:'urbanización', migration:'migración',
  globalization:'globalización', inequality:'desigualdad',
  diversity:'diversidad', stereotype:'estereotipo',
  discrimination:'discriminación', tolerance:'tolerancia',
  heritage:'patrimonio, herencia', refugee:'refugiado',
  ideology:'ideología',

  // Economics (C1/C2)
  capitalism:'capitalismo', inflation:'inflación',
  recession:'recesión', welfare:'bienestar; asistencia social',
  monopoly:'monopolio', deficit:'déficit', dividend:'dividendo',
  subsidy:'subvención, subsidio', tariff:'arancel, tarifa',

  // Philosophy (C1/C2)
  epistemology:'epistemología', ontology:'ontología',
  paradigm:'paradigma', dialectics:'dialéctica',
  discourse:'discurso; discurso académico',
  hermeneutics:'hermenéutica', semantics:'semántica',
  pragmatics:'pragmática', semiotics:'semiótica',
  postmodernism:'posmodernismo', structuralism:'estructuralismo',
  deconstruction:'deconstrucción', relativism:'relativismo',
  determinism:'determinismo', empiricism:'empirismo',
  rationalism:'racionalismo', aesthetics:'estética',
  transcendence:'trascendencia', hegemony:'hegemonía',
  autonomy:'autonomía', entrepreneurship:'emprendimiento',
  synergy:'sinergia', pragmatic:'pragmático, práctico',
  iterative:'iterativo', holistic:'holístico, integral',
  transparency:'transparencia',
  accountability:'responsabilidad, rendición de cuentas',
  litigation:'litigio', arbitration:'arbitraje',
  restructuring:'reestructuración',

  // Science (C1/C2)
  quantum:'cuántico; quantum', relativity:'relatividad',
  photosynthesis:'fotosíntesis', mitochondria:'mitocondria',
  thermodynamics:'termodinámica', chromosome:'cromosoma',
  metabolism:'metabolismo', catalyst:'catalizador',
  entropy:'entropía', equilibrium:'equilibrio', nucleus:'núcleo',
  mutation:'mutación', genome:'genoma', neuroscience:'neurociencia',
  algorithm:'algoritmo', cybersecurity:'ciberseguridad',
  neuroplasticity:'neuroplasticidad', metacognition:'metacognición',
  self_efficacy:'autoeficacia', conformity:'conformidad',
  introspection:'introspección', narcissism:'narcisismo',
  intuition:'intuición', postmodern:'posmoderno',
  avant_garde:'vanguardia', contemporary:'contemporáneo',
  iconography:'iconografía', juxtaposition:'yuxtaposición',
  indigenous:'indígena', artifact:'artefacto',
  rhetoric:'retórica', propaganda:'propaganda',
  genocide:'genocidio', imperialism:'imperialismo',
  colonialism:'colonialismo', secularism:'secularismo, laicismo',
  philanthropy:'filantropía', consortium:'consorcio',
  arbitrage:'arbitraje', depreciation:'depreciación',
  cryptocurrency:'criptomoneda', blockchain:'cadena de bloques',
  automation:'automatización', biometric:'biométrico',
  geopolitics:'geopolítica', oligarchy:'oligarquía',
  solipsism:'solipsismo', circumlocution:'circunloquio',
  malapropism:'malapropismo', pleonasm:'pleonasmo',
  synecdoche:'sinécdoque', metonymy:'metonimia',
  hyperbole:'hipérbole', litotes:'litotes',
  euphemism:'eufemismo', verisimilitude:'verosimilitud',
  intertextuality:'intertextualidad', palimpsest:'palimpsesto',
  catharsis:'catarsis', anagnorisis:'anagnórisis',
  hamartia:'hamartía', hubris:'hibris, arrogancia',
  pathos:'patetismo, pathos', aporia:'aporía',
  bioluminescence:'bioluminiscencia', photovoltaic:'fotovoltaico',
  epigenetics:'epigenética', proteomics:'proteómica',
  neurogenesis:'neurogénesis', crystallography:'cristalografía',
  nanotechnology:'nanotecnología', teleological:'teleológico',
  eschatological:'escatológico', dialectical:'dialéctico',
  ontological:'ontológico', ekphrasis:'écfrasis',
  apophasis:'apofasis', peripatetic:'peripatético',
  prolix:'prolijo', laconic:'lacónico',
  sycophancy:'adulación, servilismo', perfidious:'pérfido, traicionero',
  ephemeral:'efímero', propitious:'propicio',
  loquacious:'locuaz', perspicacious:'perspicaz',

  // Story-specific words
  first:'primero', nervous:'nervioso', dress:'vestido; vestirse',
  bus:'autobús', office:'oficina', boss:'jefe', pocket:'bolsillo',
  balloon:'globo', vegetable:'verdura, vegetal', fresh:'fresco',
  shower:'ducha; ducharse', breakfast:'desayuno',
  orange:'naranja; anaranjado', healthy:'sano, saludable',
  menu:'menú, carta', pasta:'pasta', salad:'ensalada', park:'parque',
  kite:'cometa, papalote', skill:'habilidad, destreza',
  cancelled:'cancelado', accommodation:'alojamiento, hospedaje',
  business:'negocio, empresa', disease:'enfermedad',
  apartment:'apartamento, piso', account:'cuenta',
  authority:'autoridad', medication:'medicamento; medicación',
  invitation:'invitación', intelligence:'inteligencia',
  ethical:'ético', society:'sociedad', emissions:'emisiones',
  implications:'implicaciones', authenticity:'autenticidad',
  negotiations:'negociaciones', breakthrough:'avance, descubrimiento',
  unemployment:'desempleo, paro', algorithms:'algoritmos',

  // Irregular verb forms
  v_wore:'llevaba puesto', v_took:'tomó, cogió', v_found:'encontró',
  v_sang:'cantó', v_felt:'sintió', v_made:'hizo', v_told:'dijo, contó',
  v_went:'fue', v_ate:'comió', v_drank:'bebió', v_woke:'despertó',
  v_smiled:'sonrió', v_baked:'horneó', v_said:'dijo',

  // B2/C1 Advanced vocabulary
  exhilarating:'emocionante, estimulante', meticulous:'meticuloso',
  adversity:'adversidad', ambiguous:'ambiguo', collaborate:'colaborar',
  consensus:'consenso', detrimental:'perjudicial, dañino',
  exacerbate:'exacerbar, agravar', imperative:'imperativo; esencial',
  obsolete:'obsoleto', pervasive:'omnipresente, generalizado',
  resilient:'resiliente, resistente', vibrant:'vibrante, animado',
  unprecedented:'sin precedentes', eloquent:'elocuente',
  foster:'fomentar; acoger', scrutiny:'escrutinio, examen',
  transition:'transición', abundance:'abundancia',
  paradox:'paradoja', mitigate:'mitigar, reducir',
  innovative:'innovador', diligent:'diligente, trabajador',

  // Phrases in WORDS
  p_welcome_to:'bienvenido a',
  p_thank_you:'gracias',
  p_good_morning:'buenos días',
  p_a_lot_of:'mucho, muchos, una gran cantidad',
  p_each_other:'el uno al otro, mutuamente',

  // Extra coverage
  building:'edificio', friendly:'amable, simpático', kind:'amable; tipo',
  exciting:'emocionante', fridge:'nevera, refrigerador', late:'tarde; tardío',
  balloons:'globos', flowers:'flores', song:'canción', presents:'regalos',
  toy:'juguete', shoes:'zapatos', trees:'árboles', birds:'pájaros',
  place:'lugar, sitio', books:'libros', home:'hogar; casa',
  television:'televisión', snow:'nieve; nevar', vegetables:'verduras',
  understand:'entender, comprender', worried:'preocupado', metal:'metal',
  princess:'princesa', surprise:'sorpresa; sorprender',
  butterflies:'mariposas', relax:'relajarse', warm:'cálido, tibio',
  sleepy:'soñoliento', cloudy:'nublado', skills:'habilidades',
  stay:'quedarse', museum:'museo', delicious:'delicioso',
  tools:'herramientas', patient:'paciente', health:'salud',
  active:'activo', dishes:'platos', international:'internacional',
  differences:'diferencias', success:'éxito', temperatures:'temperaturas',
  peaceful:'tranquilo, pacífico', challenging:'desafiante',
  achievement:'logro', communication:'comunicación',
  position:'posición; puesto', growth:'crecimiento',
  challenge:'desafío; desafiar', responsible:'responsable',
  remote:'remoto, a distancia', advantages:'ventajas',
  challenges:'desafíos', succeed:'tener éxito, triunfar',
  standard:'estándar, nivel', function:'función; funcionar',
  recover:'recuperarse', exchange:'intercambiar; intercambio',
  traditions:'tradiciones', model:'modelo', opportunity:'oportunidad',
  impression:'impresión', optimistic:'optimista', voucher:'vale, cupón',
  productive:'productivo', flexibility:'flexibilidad',
  commuting:'desplazarse al trabajo', industries:'industrias',
  diseases:'enfermedades', concern:'preocupación; concernir',
  regulations:'regulaciones', profits:'beneficios', resources:'recursos',
  exploration:'exploración', legal:'legal', aspect:'aspecto',
  alternatives:'alternativas', selection:'selección',
  address:'dirección; dirigirse a', footprint:'huella',
  isolation:'aislamiento', hybrid:'híbrido', 'well-being':'bienestar',
  perspectives:'perspectivas', discrepancies:'discrepancias',
  unintended:'no intencionado', algorithmic:'algorítmico',
  inequalities:'desigualdades', intervention:'intervención',
  biodiversity:'biodiversidad', ecosystems:'ecosistemas',
  humanity:'humanidad', acceleration:'aceleración',
  geopolitical:'geopolítico', breakthroughs:'avances, descubrimientos',
  extraction:'extracción', contamination:'contaminación',
  frontier:'frontera', tensions:'tensiones', overwhelmed:'abrumado',
  perceived:'percibido', phenomenon:'fenómeno',
  dissatisfaction:'insatisfacción', inhibit:'inhibir',
  minimalist:'minimalista', burden:'carga, peso',
  reimagining:'reimaginar', infrastructure:'infraestructura',
  architectural:'arquitectónico', integrate:'integrar',
  transit:'tránsito', ecological:'ecológico',
  conundrums:'enigmas, dilemas', paralysis:'parálisis',
  necessitates:'hace necesario, requiere',
  monopoly_c1:'desinversión', sovereignty_c1:'jurisdicción',
};

// ── Spanish translations for PHRASE_DICT ─────────────────────
const PHRASE_ES = {
  // Phrasal Verbs
  'give up':        'rendirse, abandonar',
  'look up':        'buscar (en un diccionario); admirar',
  'look for':       'buscar',
  'look after':     'cuidar',
  'look forward to':'tener ganas de, esperar con ilusión',
  'take off':       'despegar; quitarse',
  'take on':        'asumir, encargarse de',
  'take part in':   'participar en',
  'put off':        'aplazar, posponer',
  'put up with':    'soportar, aguantar',
  'carry on':       'continuar, seguir',
  'catch up':       'ponerse al día; alcanzar',
  'end up':         'terminar, acabar',
  'find out':       'descubrir, averiguar',
  'get on with':    'llevarse bien con; seguir con',
  'get over':       'superar, recuperarse de',
  'go on':          'continuar, seguir',
  'go through':     'pasar por; revisar',
  'keep up with':   'mantener el ritmo con',
  'make up':        'inventar; maquillarse; compensar',
  'pick up':        'recoger; aprender (habilidad)',
  'point out':      'señalar, indicar',
  'run out of':     'quedarse sin',
  'set up':         'establecer, montar',
  'show up':        'aparecer, presentarse',
  'slow down':      'desacelerar, reducir la velocidad',
  'stand for':      'significar; representar',
  'take care of':   'cuidar de',
  'turn out':       'resultar, salir',
  'woke up':        'despertó',
  'paid off':       'valió la pena, dio resultado',
  'led to':         'llevó a, condujo a',
  'come up with':   'idear, encontrar (una idea)',
  'break down':     'averiarse; desglosar; venirse abajo',
  'break up':       'romper (una relación); separarse',
  'bring up':       'criar; mencionar (un tema)',
  'build up':       'acumular; desarrollar',
  'call off':       'cancelar',
  'calm down':      'calmarse, tranquilizarse',
  'cut down on':    'reducir, recortar',
  'deal with':      'tratar con, ocuparse de',
  'drop off':       'dejar (a alguien); quedarse dormido',
  'figure out':     'descifrar, entender',
  'fill in':        'rellenar, completar',
  'focus on':       'centrarse en',
  'get rid of':     'deshacerse de',
  'give in':        'ceder, rendirse',
  'go ahead':       'adelante; proceder',
  'hang out':       'pasar el tiempo, quedar',
  'hold on':        'esperar; aferrarse',
  'look into':      'investigar, indagar',
  'make out':       'distinguir; arreglárselas',
  'move on':        'seguir adelante',
  'open up':        'abrirse; abrir',
  'put together':   'montar, juntar',
  'run into':       'encontrarse con (alguien)',
  'settle down':    'establecerse; calmarse',
  'sort out':       'resolver, arreglar',
  'speak up':       'hablar más alto; expresarse',
  'stand out':      'destacar, sobresalir',
  'take over':      'tomar el control; hacerse cargo',
  'think over':     'pensar bien, reflexionar',
  'try out':        'probar, experimentar',
  'turn up':        'aparecer; subir el volumen',
  'use up':         'agotar, consumir todo',
  'work out':       'hacer ejercicio; resolver; salir bien',

  // Idioms
  'a piece of cake':              'pan comido (algo muy fácil)',
  'break the ice':                'romper el hielo',
  'bite the bullet':              'aguantar el dolor; enfrentarse a algo difícil',
  'hit the nail on the head':     'dar en el clavo',
  'burn the midnight oil':        'quemarse las cejas (trabajar de noche)',
  'cost an arm and a leg':        'costar un ojo de la cara',
  'once in a blue moon':          'muy de vez en cuando',
  'kill two birds with one stone':'matar dos pájaros de un tiro',
  'every cloud has a silver lining':'no hay mal que por bien no venga',
  'bite off more than you can chew':'abarcar más de lo que puedes',
  'easier said than done':        'del dicho al hecho hay un gran trecho',
  'get a taste of your own medicine':'que te traten como tú tratas a otros',
  'hit the books':                'ponerse a estudiar',
  'let the cat out of the bag':   'revelar el secreto sin querer',
  'miss the boat':                'perder la oportunidad',
  'on thin ice':                  'en terreno peligroso',
  'sit on the fence':             'no tomar partido',
  'spill the beans':              'irse de la lengua',
  'the ball is in your court':    'la pelota está en tu tejado',
  'under the weather':            'encontrarse mal (de salud)',
  'beat around the bush':         'andarse por las ramas',
  'cut to the chase':             'ir al grano',
  'read between the lines':       'leer entre líneas',
  'throw in the towel':           'tirar la toalla',
  'when pigs fly':                'cuando las ranas críen pelo',

  // Grammar Patterns & Expressions
  'in order to':          'con el fin de, para',
  'be able to':           'poder, ser capaz de',
  'used to':              'solía, acostumbraba a',
  'be supposed to':       'se supone que debe',
  'as well as':           'así como, además de',
  'in spite of':          'a pesar de',
  'due to':               'debido a',
  'in terms of':          'en términos de',
  'on the other hand':    'por otro lado',
  'for instance':         'por ejemplo',
  'as a result':          'como resultado',
  'in addition':          'además',
  'nevertheless':         'sin embargo, no obstante',
  'on the contrary':      'por el contrario',
  'in conclusion':        'en conclusión',
  'to sum up':            'en resumen',
  'for example':          'por ejemplo',
  'at the moment':        'en este momento',
  'of course':            'por supuesto, claro',
  'as soon as':           'tan pronto como',
  'by the way':           'por cierto, a propósito',
  'in fact':              'de hecho',
  'at least':             'al menos, por lo menos',
  'so far':               'hasta ahora',
  'as long as':           'siempre que, mientras',
  'in case':              'en caso de que',
  'rather than':          'en lugar de, más que',
  'as if':                'como si',
  'even though':          'aunque, a pesar de que',
  'provided that':        'siempre que, con tal de que',
  'regardless of':        'independientemente de',

  // Noun Phrases
  'climate change':          'cambio climático',
  'artificial intelligence': 'inteligencia artificial',
  'social media':            'redes sociales',
  'mental health':           'salud mental',
  'human rights':            'derechos humanos',
  'carbon footprint':        'huella de carbono',
  'free time':               'tiempo libre',
  'middle class':            'clase media',
  'sea level':               'nivel del mar',
  'public transport':        'transporte público',
  'job market':              'mercado laboral',
  'life expectancy':         'esperanza de vida',
  'quality of life':         'calidad de vida',
  'communication skills':    'habilidades comunicativas',
  'life skills':             'habilidades para la vida',
  'standard of living':      'nivel de vida',
  'global warming':          'calentamiento global',
  'economic growth':         'crecimiento económico',
  'role model':              'modelo a seguir',
  'turning point':           'punto de inflexión',

  // Common Vocabulary (Kelime entries)
  'ability':          'habilidad, capacidad',
  'absence':          'ausencia',
  'absolute':         'absoluto',
  'access':           'acceso; acceder',
  'accurate':         'preciso, exacto',
  'achieve':          'lograr, alcanzar',
  'acknowledge':      'reconocer, admitir',
  'acquire':          'adquirir',
  'action':           'acción',
  'activity':         'actividad',
  'adapt':            'adaptar; adaptarse',
  'adequate':         'adecuado, suficiente',
  'admire':           'admirar',
  'advance':          'avanzar; avance',
  'adventure':        'aventura',
  'advocate':         'abogar; defensor',
  'affordable':       'asequible, accesible',
  'age':              'edad; envejecer',
  'aim':              'objetivo; apuntar',
  'allow':            'permitir, dejar',
  'ancient':          'antiguo',
  'anxiety':          'ansiedad',
  'appear':           'aparecer',
  'apply':            'aplicar; solicitar',
  'approach':         'enfoque; acercarse',
  'argue':            'argumentar; discutir',
  'aspect':           'aspecto',
  'associate':        'asociar; relacionar',
  'atmosphere':       'atmósfera; ambiente',
  'attempt':          'intentar; intento',
  'attention':        'atención',
  'attract':          'atraer',
  'autumn':           'otoño',
  'available':        'disponible',
  'bake':             'hornear',
  'baker':            'panadero',
  'bakery':           'panadería',
  'barely':           'apenas',
  'basic':            'básico',
  'behaviour':        'comportamiento, conducta',
  'belief':           'creencia, fe',
  'beneath':          'debajo de',
  'bicycle':          'bicicleta',
  'biological':       'biológico',
  'birth':            'nacimiento',
  'brain':            'cerebro',
  'break':            'romper; descanso',
  'capable':          'capaz',
  'capacity':         'capacidad',
  'career':           'carrera profesional',
  'century':          'siglo',
  'challenge':        'desafío; desafiar',
  'choice':           'elección, opción',
  'claim':            'afirmar; reclamar',
  'collective':       'colectivo, conjunto',
  'complex':          'complejo',
  'confidence':       'confianza, seguridad',
  'conscious':        'consciente',
  'consumer':         'consumidor',
  'control':          'controlar; control',
  'cooperation':      'cooperación',
  'core':             'núcleo; fundamental',
  'creative':         'creativo',
  'crowd':            'multitud',
  'cultural':         'cultural',
  'daily':            'diario; a diario',
  'data':             'datos',
  'decade':           'década',
  'decision':         'decisión',
  'design':           'diseñar; diseño',
  'develop':          'desarrollar',
  'digital':          'digital',
  'diverse':          'diverso',
  'dream':            'sueño; soñar',
  'drive':            'conducir; impulso',
  'economic':         'económico',
  'education':        'educación',
  'electricity':      'electricidad',
  'emotion':          'emoción',
  'employ':           'emplear, contratar',
  'engage':           'involucrar; comprometerse',
  'ensure':           'asegurar, garantizar',
  'essential':        'esencial, fundamental',
  'evidence':         'evidencia, prueba',
  'experience':       'experiencia; experimentar',
  'explore':          'explorar',
  'failure':          'fracaso, fallo',
  'fashion':          'moda; manera',
  'fear':             'miedo; temer',
  'final':            'final',
  'fire':             'fuego; despedir',
  'food':             'comida, alimento',
  'freedom':          'libertad',
  'fuel':             'combustible',
  'generate':         'generar',
  'global':           'global, mundial',
  'government':       'gobierno',
  'habit':            'hábito, costumbre',
  'harvest':          'cosecha; cosechar',
  'history':          'historia',
  'honour':           'honor; honrar',
  'impact':           'impacto; impactar',
  'improve':          'mejorar',
  'include':          'incluir',
  'income':           'ingresos',
  'indicate':         'indicar',
  'insight':          'perspicacia; comprensión profunda',
  'inspire':          'inspirar',
  'intelligence':     'inteligencia',
  'invest':           'invertir',
  'isolate':          'aislar',
  'key':              'clave; llave',
  'knowledge':        'conocimiento, saber',
  'labour':           'trabajo, labor',
  'lead':             'liderar; llevar a',
  'level':            'nivel',
  'lifestyle':        'estilo de vida',
  'limit':            'límite; limitar',
  'manage':           'gestionar; lograrlo',
  'material':         'material; materiales',
  'media':            'medios de comunicación',
  'memory':           'memoria; recuerdo',
  'mental':           'mental',
  'mentor':           'mentor; orientar',
  'model':            'modelo',
  'movement':         'movimiento',
  'natural':          'natural',
  'network':          'red; relacionarse',
  'neural':           'neuronal',
  'novel':            'novela; novedoso',
  'oil':              'aceite; petróleo',
  'online':           'en línea',
  'organisation':     'organización',
  'outcome':          'resultado, consecuencia',
  'pain':             'dolor',
  'passion':          'pasión',
  'period':           'período; período menstrual',
  'physical':         'físico',
  'platform':         'plataforma',
  'political':        'político',
  'positive':         'positivo',
  'power':            'poder; energía',
  'process':          'proceso; procesar',
  'produce':          'producir; producto',
  'programme':        'programa',
  'property':         'propiedad',
  'public':           'público',
  'quality':          'calidad',
  'rapid':            'rápido',
  'rational':         'racional',
  'recipe':           'receta',
  'reduce':           'reducir',
  'region':           'región',
  'relationship':     'relación',
  'reward':           'recompensa; recompensar',
  'risk':             'riesgo; arriesgar',
  'role':             'papel, rol',
  'rural':            'rural',
  'satisfaction':     'satisfacción',
  'sense':            'sentido; sensación',
  'significant':      'significativo, importante',
  'social':           'social',
  'solution':         'solución',
  'source':           'fuente; origen',
  'specific':         'específico, concreto',
  'stage':            'etapa; escenario',
  'store':            'tienda; almacenar',
  'student':          'estudiante',
  'success':          'éxito',
  'system':           'sistema',
  'technology':       'tecnología',
  'traditional':      'tradicional',
  'unique':           'único',
  'urban':            'urbano',
  'value':            'valor; valorar',
  'vital':            'vital, esencial',
  'wellbeing':        'bienestar',
  'wonder':           'maravillar; maravilla',
  'worth':            'valor; merecer la pena',
};

// ── English definitions for PHRASE_DICT ──────────────────────
const PHRASE_EN = {
  // Phrasal Verbs
  'give up':        'to stop trying or doing something',
  'look up':        'to search for information; to respect',
  'look for':       'to search for something or someone',
  'look after':     'to take care of someone or something',
  'look forward to':'to feel excited about a future event',
  'take off':       'to leave the ground (aircraft); to remove clothing',
  'take on':        'to accept responsibility; to employ',
  'take part in':   'to participate in an activity',
  'put off':        'to delay; to postpone',
  'put up with':    'to tolerate something unpleasant',
  'carry on':       'to continue doing something',
  'catch up':       'to reach someone or something ahead of you',
  'end up':         'to finally be in a situation',
  'find out':       'to discover a fact or information',
  'get on with':    'to have a good relationship; to continue',
  'get over':       'to recover from illness or difficulty',
  'go on':          'to continue; to happen',
  'go through':     'to experience something difficult',
  'keep up with':   'to maintain the same pace or level',
  'make up':        'to invent; to reconcile; to compensate',
  'pick up':        'to collect; to learn informally',
  'point out':      'to direct attention to something',
  'run out of':     'to have no more of something',
  'set up':         'to establish or arrange something',
  'show up':        'to arrive or appear',
  'slow down':      'to reduce speed or pace',
  'stand for':      'to represent or mean',
  'take care of':   'to look after someone',
  'turn out':       'to result in a particular way',
  'come up with':   'to think of an idea or solution',
  'break down':     'to stop working; to analyse; to cry',
  'break up':       'to end a relationship; to separate',
  'bring up':       'to raise (children); to mention',
  'deal with':      'to handle a situation or problem',
  'figure out':     'to understand or solve something',
  'focus on':       'to concentrate on something',
  'move on':        'to continue forward; to forget the past',
  'work out':       'to exercise; to solve; to be successful',

  // Idioms
  'a piece of cake':              'something very easy to do',
  'break the ice':                'to do something to relieve tension',
  'bite the bullet':              'to endure a painful situation bravely',
  'hit the nail on the head':     'to be exactly right about something',
  'burn the midnight oil':        'to work or study late into the night',
  'cost an arm and a leg':        'to be extremely expensive',
  'once in a blue moon':          'very rarely',
  'kill two birds with one stone':'to accomplish two things with one action',
  'easier said than done':        'more difficult to do than to talk about',
  'under the weather':            'to feel ill or unwell',
  'beat around the bush':         'to avoid the main topic',
  'cut to the chase':             'to get to the point quickly',
  'throw in the towel':           'to admit defeat or give up',

  // Grammar & Expressions
  'in order to':       'with the purpose of; so as to',
  'be able to':        'to have the skill or possibility to do',
  'used to':           'describes a past habit or state',
  'as well as':        'in addition to',
  'in spite of':       'despite; regardless of',
  'due to':            'because of; caused by',
  'in terms of':       'with respect to; regarding',
  'on the other hand': 'from a different perspective',
  'as a result':       'consequently; therefore',
  'in addition':       'also; furthermore',
  'nevertheless':      'despite this; however',
  'in conclusion':     'to summarise; finally',
  'for example':       'as an illustration',
  'of course':         'certainly; naturally',
  'as soon as':        'immediately when',
  'by the way':        'incidentally; also',
  'in fact':           'actually; in reality',
  'so far':            'until now; up to this point',
  'even though':       'despite the fact that',

  // Vocabulary
  'ability':       'skill or power to do something',
  'achieve':       'to succeed in reaching a goal',
  'adapt':         'to change to fit new conditions',
  'advocate':      'to support a cause; a person who supports',
  'ambitious':     'having a strong desire to succeed',
  'analyse':       'to examine something carefully',
  'approach':      'a way of dealing with something; to come near',
  'aspect':        'a part or feature of something',
  'attitude':      'a way of thinking or feeling about something',
  'capacity':      'the ability or space to contain something',
  'career':        'a profession followed as a life\'s work',
  'challenge':     'a difficult task; to question or compete',
  'conscious':     'aware; awake and thinking',
  'consequence':   'a result or effect of an action',
  'consider':      'to think carefully about something',
  'contribute':    'to give a part of something',
  'crucial':       'extremely important',
  'define':        'to explain the meaning of something',
  'demonstrate':   'to show or prove clearly',
  'despite':       'without being affected by; even though',
  'determine':     'to find out; to decide',
  'diverse':       'varied; showing many differences',
  'efficient':     'achieving results with little waste',
  'eliminate':     'to remove or get rid of',
  'emerge':        'to come out or become known',
  'enable':        'to make possible; to allow',
  'enhance':       'to improve the quality of something',
  'ensure':        'to make certain something happens',
  'establish':     'to set up or create something',
  'evaluate':      'to judge the value of something',
  'evidence':      'facts that prove something',
  'expand':        'to become larger; to increase',
  'explore':       'to examine or travel through',
  'expose':        'to uncover; to make vulnerable',
  'factor':        'something that contributes to a result',
  'generate':      'to produce or create',
  'identify':      'to recognise or find',
  'impact':        'a strong effect; to affect strongly',
  'implement':     'to put into effect; to carry out',
  'improve':       'to make or become better',
  'include':       'to have as part of a whole',
  'indicate':      'to show or point to',
  'influence':     'to affect; to have an effect on',
  'insight':       'deep understanding of a complex matter',
  'involve':       'to include or take part in',
  'issue':         'an important topic or problem',
  'maintain':      'to keep in good condition',
  'major':         'important; large in scale',
  'manage':        'to be in charge; to succeed in doing',
  'obtain':        'to get or acquire',
  'occur':         'to happen or exist',
  'overcome':      'to succeed in dealing with a problem',
  'participate':   'to take part in an activity',
  'perceive':      'to become aware of; to understand',
  'potential':     'possible future ability or quality',
  'process':       'a series of actions; to handle',
  'promote':       'to support; to advertise; to raise in rank',
  'provide':       'to supply or give',
  'pursue':        'to follow; to try to achieve',
  'reaction':      'a response to an event',
  'recognise':     'to know again; to accept as valid',
  'reduce':        'to make smaller or less',
  'reflect':       'to think carefully; to show an image',
  'relevant':      'closely connected to the matter',
  'rely':          'to depend on with confidence',
  'require':       'to need something',
  'reveal':        'to make known or visible',
  'significant':   'large enough to be noticed; important',
  'similar':       'having qualities in common',
  'source':        'a place from which something comes',
  'specific':      'particular; precise',
  'strengthen':    'to make stronger',
  'suggest':       'to put forward an idea',
  'support':       'to help; evidence that confirms',
  'sustain':       'to keep going; to support',
  'tend':          'to be inclined to; to look after',
  'theory':        'a set of ideas explaining something',
  'transform':     'to change completely',
  'trend':         'a general direction of change',
  'unique':        'being the only one of its kind',
  'utilise':       'to make practical use of',
  'vary':          'to differ; to change',
  'vital':         'absolutely necessary; full of life',
};
