const SPEAK_CHALLENGES = {
  "easy": [
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator."
  ],
  "medium": [
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication."
  ],
  "hard": [
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring."
  ]
};


const STORIES = [];
