const SPEAK_CHALLENGES = {
  "easy": [
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator.",
    "Hello, how are you today?",
    "My name is Alex.",
    "I like to read books.",
    "The weather is really beautiful.",
    "Can you please help me?",
    "I would like a cup of coffee.",
    "Where is the nearest bus stop?",
    "I am very happy to meet you.",
    "This is a really nice city.",
    "What is your favorite color?",
    "I have a cat and a dog.",
    "The sun is shining bright.",
    "I want to learn English fast.",
    "Can we go to the park?",
    "See you later alligator."
  ],
  "medium": [
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication.",
    "Artificial intelligence is shaping our future.",
    "Consistency is the key to mastering a language.",
    "Technology makes our daily lives so much easier.",
    "The quick brown fox jumps over the lazy dog.",
    "I'm looking forward to working with your team.",
    "Could you please repeat that?",
    "She has been studying English for three years now.",
    "We should eat more vegetables for health.",
    "Travel broadens the mind and soul.",
    "Success comes after hard work and dedication."
  ],
  "hard": [
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring.",
    "Despite the bureaucratic obstacles, the project was completed successfully.",
    "The complex algorithm optimized the data processing speed significantly.",
    "Environmental sustainability is a global priority for the next decade.",
    "Historical artifacts provide a glimpse into ancient daily life.",
    "The entrepreneur's perseverance ultimately led to unprecedented success.",
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "The parliamentary committee thoroughly investigated the allegations.",
    "Her enthusiasm for astrophysics was truly extraordinary and inspiring."
  ]
};

const STORIES = [
  {
    "id": 1,
    "title": "A Day in the Park",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 2,
    "title": "The Job Interview",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 3,
    "title": "Space Exploration",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 4,
    "title": "A Day in the Park Part 2",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 5,
    "title": "The Job Interview Part 2",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 6,
    "title": "Space Exploration Part 2",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 7,
    "title": "A Day in the Park Part 3",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 8,
    "title": "The Job Interview Part 3",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 9,
    "title": "Space Exploration Part 3",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 10,
    "title": "A Day in the Park Part 4",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 11,
    "title": "The Job Interview Part 4",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 12,
    "title": "Space Exploration Part 4",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 13,
    "title": "A Day in the Park Part 5",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 14,
    "title": "The Job Interview Part 5",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 15,
    "title": "Space Exploration Part 5",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 16,
    "title": "A Day in the Park Part 6",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 17,
    "title": "The Job Interview Part 6",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 18,
    "title": "Space Exploration Part 6",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 19,
    "title": "A Day in the Park Part 7",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 20,
    "title": "The Job Interview Part 7",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 21,
    "title": "Space Exploration Part 7",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 22,
    "title": "A Day in the Park Part 8",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 23,
    "title": "The Job Interview Part 8",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 24,
    "title": "Space Exploration Part 8",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 25,
    "title": "A Day in the Park Part 9",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 26,
    "title": "The Job Interview Part 9",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 27,
    "title": "Space Exploration Part 9",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 28,
    "title": "A Day in the Park Part 10",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 29,
    "title": "The Job Interview Part 10",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 30,
    "title": "Space Exploration Part 10",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 31,
    "title": "A Day in the Park Part 11",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 32,
    "title": "The Job Interview Part 11",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 33,
    "title": "Space Exploration Part 11",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 34,
    "title": "A Day in the Park Part 12",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 35,
    "title": "The Job Interview Part 12",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 36,
    "title": "Space Exploration Part 12",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 37,
    "title": "A Day in the Park Part 13",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 38,
    "title": "The Job Interview Part 13",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 39,
    "title": "Space Exploration Part 13",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 40,
    "title": "A Day in the Park Part 14",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 41,
    "title": "The Job Interview Part 14",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 42,
    "title": "Space Exploration Part 14",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 43,
    "title": "A Day in the Park Part 15",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 44,
    "title": "The Job Interview Part 15",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 45,
    "title": "Space Exploration Part 15",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 46,
    "title": "A Day in the Park Part 16",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 47,
    "title": "The Job Interview Part 16",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  },
  {
    "id": 48,
    "title": "Space Exploration Part 16",
    "text": "The recent advancements in {astrophysics} have been remarkable. Scientists have discovered a new {exoplanet} in a distant galaxy. This could potentially answer questions about {extraterrestrial} life and the origins of our {universe}.",
    "options": [
      "astrophysics",
      "exoplanet",
      "extraterrestrial",
      "universe",
      "biology",
      "star",
      "human",
      "city"
    ],
    "level": "İleri"
  },
  {
    "id": 49,
    "title": "A Day in the Park Part 17",
    "text": "It was a beautiful sunny day. Alex decided to go to the {park}. He took his {dog} with him. They played {catch} for an hour. Afterwards, they sat under a large {tree} to rest.",
    "options": [
      "park",
      "dog",
      "catch",
      "tree",
      "car",
      "cat",
      "run",
      "building"
    ],
    "level": "Kolay"
  },
  {
    "id": 50,
    "title": "The Job Interview Part 17",
    "text": "Sarah was very nervous about her {interview}. she wore her best {suit} and arrived ten minutes {early}. The manager asked her about her previous {experience}. She answered confidently.",
    "options": [
      "interview",
      "suit",
      "early",
      "experience",
      "party",
      "dress",
      "late",
      "hobby"
    ],
    "level": "Orta"
  }
];
