/* translate-data2.js — TR→EN ek veri: A1 (155 yeni cümle) */
TRANSLATE_DATA.push(
// ── A1 yeni ──
{id:'a1_21',level:'A1',topic:'to be (+)',tr:'O bir öğretmen.',en:'She is a teacher.',alt:["She's a teacher.","He is a teacher.","He's a teacher."],keys:['teacher'],tip:'O → <b>He/She is</b>. İkisi de doğru.'},
{id:'a1_22',level:'A1',topic:'to be (+)',tr:'Ben İngilizim.',en:'I am English.',alt:["I'm English."],keys:['English'],tip:'uyruk: <b>I am English</b>, She is Turkish'},
{id:'a1_23',level:'A1',topic:'to be (−)',tr:'O Türk değil.',en:'He is not Turkish.',alt:["He isn't Turkish.","He's not Turkish.","She is not Turkish.","She isn't Turkish."],keys:['Turkish'],tip:'değil → <b>is not</b> / <b>isn\'t</b>'},
{id:'a1_24',level:'A1',topic:'to be (?)',tr:'Onlar mutlu mu?',en:'Are they happy?',alt:[],keys:['happy'],tip:'çoğul soru: <b>Are + they + sıfat?</b>'},
{id:'a1_25',level:'A1',topic:'to be (+)',tr:'Ben yirmi yaşındayım.',en:'I am twenty years old.',alt:["I'm twenty years old.","I'm twenty."],keys:['twenty'],tip:'yaş: <b>I am + sayı + years old</b>'},
{id:'a1_26',level:'A1',topic:'to be (−)',tr:'O çok yorgun değil.',en:'She is not very tired.',alt:["She isn't very tired.","She's not very tired.","He is not very tired."],keys:['tired'],tip:'<b>not very + sıfat</b>: çok ... değil'},
{id:'a1_27',level:'A1',topic:'to be (+)',tr:'Biz Ankaralıyız.',en:'We are from Ankara.',alt:["We're from Ankara."],keys:['Ankara'],tip:'nereli: <b>We are from + şehir</b>'},
{id:'a1_28',level:'A1',topic:'to be (?)',tr:'Onlar arkadaş mı?',en:'Are they friends?',alt:[],keys:['friends'],tip:'<b>Are they + isim?</b>'},
{id:'a1_29',level:'A1',topic:'to be (+)',tr:'Bugün hava çok sıcak.',en:'It is very hot today.',alt:["It's very hot today."],keys:['hot'],tip:'hava durumu: <b>It is + sıfat</b>'},
{id:'a1_30',level:'A1',topic:'to be (?)',tr:'O senin öğretmenin mi?',en:'Is she your teacher?',alt:['Is he your teacher?'],keys:['teacher'],tip:'tekil soru: <b>Is + özne + ...?</b>'},
{id:'a1_31',level:'A1',topic:'simple present (+)',tr:'Babam hastanede çalışıyor.',en:'My father works in a hospital.',alt:[],keys:['works','hospital'],tip:'3. tekil: <b>work → works</b>'},
{id:'a1_32',level:'A1',topic:'simple present (+)',tr:'Öğle yemeğini her gün on ikide yerim.',en:'I eat lunch at twelve every day.',alt:[],keys:['lunch'],tip:'Alışkanlık: <b>I eat + zaman + her gün</b>'},
{id:'a1_33',level:'A1',topic:'simple present (he)',tr:'Hafta sonları futbol oynarlar.',en:'They play football at weekends.',alt:[],keys:['play','football'],tip:'they: fiil yalın hali → <b>play</b>'},
{id:'a1_34',level:'A1',topic:'simple present (+)',tr:'Küçük bir kasabada yaşıyoruz.',en:'We live in a small town.',alt:[],keys:['live','town'],tip:'<b>live in + şehir/kasaba</b>'},
{id:'a1_35',level:'A1',topic:'simple present (−)',tr:'O çay içmez.',en:'She does not drink tea.',alt:["She doesn't drink tea."],keys:['drink','tea'],tip:'he/she/it olumsuz: <b>does not / doesn\'t + yalın fiil</b>'},
{id:'a1_36',level:'A1',topic:'simple present (?)',tr:'İngilizce konuşuyor musun?',en:'Do you speak English?',alt:[],keys:['speak','English'],tip:'<b>Do you + yalın fiil?</b>'},
{id:'a1_37',level:'A1',topic:'simple present (he)',tr:'Banka saat dokuzda açılıyor.',en:'The bank opens at nine.',alt:[],keys:['opens','nine'],tip:'3. tekil: <b>open → opens</b>; saat: <b>at nine</b>'},
{id:'a1_38',level:'A1',topic:'simple present (−)',tr:'Fazla televizyon izlemiyorum.',en:'I do not watch much TV.',alt:["I don't watch much TV."],keys:['watch'],tip:'<b>do not / don\'t + yalın fiil</b>'},
{id:'a1_39',level:'A1',topic:'simple present (?)',tr:'Saat kaçta uyanıyorsun?',en:'What time do you wake up?',alt:[],keys:['wake up'],tip:'<b>What time + do + özne + yalın fiil?</b>'},
{id:'a1_40',level:'A1',topic:'simple present (+)',tr:'Abim her sabah gazete okuyor.',en:'My brother reads the newspaper every morning.',alt:['My sister reads the newspaper every morning.'],keys:['reads','newspaper'],tip:'3. tekil: <b>read → reads</b>'},
{id:'a1_41',level:'A1',topic:'can (?)',tr:'Bisiklet sürebilir misin?',en:'Can you ride a bike?',alt:[],keys:['ride','bike'],tip:'yetenek sorusu: <b>Can you + yalın fiil?</b>'},
{id:'a1_42',level:'A1',topic:'can (−)',tr:'O çok iyi şarkı söyleyemiyor.',en:"She can't sing very well.",alt:["She cannot sing very well."],keys:['sing'],tip:'yapamama: <b>can\'t / cannot + yalın fiil</b>'},
{id:'a1_43',level:'A1',topic:'can (+)',tr:'Kardeşim çok iyi yemek yapabilir.',en:'My brother can cook very well.',alt:['My sister can cook very well.'],keys:['can','cook'],tip:'yetenek: <b>can + yalın fiil</b>'},
{id:'a1_44',level:'A1',topic:'can (?)',tr:'Bana yardım edebilir misin?',en:'Can you help me?',alt:[],keys:['help'],tip:'rica: <b>Can you + yalın fiil?</b>'},
{id:'a1_45',level:'A1',topic:'can (+)',tr:'Biraz Fransızca konuşabiliyorum.',en:'I can speak a little French.',alt:[],keys:['can','French'],tip:'<b>a little = biraz</b>; can + yalın fiil'},
{id:'a1_46',level:'A1',topic:'can (?)',tr:'O hızlı koşabilir mi?',en:'Can he run fast?',alt:['Can she run fast?'],keys:['run','fast'],tip:'<b>Can + özne + yalın fiil?</b>'},
{id:'a1_47',level:'A1',topic:'have/has',tr:'Yeni bir telefonum var.',en:'I have a new phone.',alt:[],keys:['have','phone'],tip:'sahiplik: <b>I have + nesne</b>'},
{id:'a1_48',level:'A1',topic:'have/has',tr:'Uzun saçları var.',en:'She has long hair.',alt:['He has long hair.'],keys:['hair'],tip:'3. tekil: <b>has + nesne</b>'},
{id:'a1_49',level:'A1',topic:'have/has (?)',tr:'Kalemin var mı?',en:'Do you have a pen?',alt:["Have you got a pen?"],keys:['pen'],tip:'<b>Do you have + nesne?</b>'},
{id:'a1_50',level:'A1',topic:'have/has',tr:'Büyük bir bahçemiz var.',en:'We have a big garden.',alt:[],keys:['garden'],tip:'<b>We have + nesne</b>'},
{id:'a1_51',level:'A1',topic:'have/has (−)',tr:'Arabasının anahtarı yok.',en:'He does not have a car key.',alt:["He doesn't have a car key."],keys:['key'],tip:'3. tekil olumsuz: <b>does not have</b>'},
{id:'a1_52',level:'A1',topic:'have/has',tr:'Başı ağrıyor.',en:'She has a headache.',alt:['He has a headache.'],keys:['headache'],tip:'ağrı: <b>have a headache / stomachache / toothache</b>'},
{id:'a1_53',level:'A1',topic:'there is/are',tr:'Masanın altında bir kedi var.',en:'There is a cat under the table.',alt:["There's a cat under the table."],keys:['cat','table'],tip:'tekil: <b>There is a + isim</b>'},
{id:'a1_54',level:'A1',topic:'there is/are',tr:'Odamda iki pencere var.',en:'There are two windows in my room.',alt:[],keys:['two','windows'],tip:'çoğul: <b>There are + sayı + isim</b>'},
{id:'a1_55',level:'A1',topic:'there is/are (?)',tr:'Yakında bir banka var mı?',en:'Is there a bank near here?',alt:[],keys:['bank'],tip:'tekil soru: <b>Is there a + isim?</b>'},
{id:'a1_56',level:'A1',topic:'there is/are (−)',tr:'Buzdolabında süt yok.',en:'There is no milk in the fridge.',alt:["There isn't any milk in the fridge."],keys:['milk','fridge'],tip:'yokluk: <b>There is no + isim</b>'},
{id:'a1_57',level:'A1',topic:'there is/are',tr:'Sınıfta çok öğrenci var.',en:'There are many students in the class.',alt:[],keys:['students','class'],tip:'<b>There are many + çoğul isim</b>'},
{id:'a1_58',level:'A1',topic:'prepositions of place',tr:'Anahtarlar masanın üstünde.',en:'The keys are on the desk.',alt:[],keys:['keys','desk'],tip:'üstünde: <b>on</b>; içinde: <b>in</b>; altında: <b>under</b>'},
{id:'a1_59',level:'A1',topic:'prepositions of place',tr:'Telefonum dizüstü bilgisayarın yanında.',en:'My phone is next to the laptop.',alt:[],keys:['next to','laptop'],tip:'yanında: <b>next to</b>'},
{id:'a1_60',level:'A1',topic:'prepositions of place',tr:'Kedi yatağın altında.',en:'The cat is under the bed.',alt:[],keys:['under','bed'],tip:'altında: <b>under</b>'},
{id:'a1_61',level:'A1',topic:'prepositions of place',tr:'Süpermarket okulun arkasında.',en:'The supermarket is behind the school.',alt:[],keys:['behind','school'],tip:'arkasında: <b>behind</b>; önünde: <b>in front of</b>'},
{id:'a1_62',level:'A1',topic:'prepositions of place',tr:'Posta kutusu bankanın yanı başında.',en:'The post box is next to the bank.',alt:['The post box is beside the bank.'],keys:['post box','bank'],tip:'yanında: <b>next to / beside</b>'},
{id:'a1_63',level:'A1',topic:'prepositions of place',tr:'Fırın kütüphanenin karşısında.',en:'The bakery is opposite the library.',alt:['The bakery is across from the library.'],keys:['opposite'],tip:'karşısında: <b>opposite / across from</b>'},
{id:'a1_64',level:'A1',topic:'prepositions of time',tr:'Toplantı saat üçte.',en:'The meeting is at three o\'clock.',alt:["The meeting is at three."],keys:['three'],tip:'saat: <b>at + saat</b>'},
{id:'a1_65',level:'A1',topic:'prepositions of time',tr:'Doğum günüm Temmuz ayında.',en:'My birthday is in July.',alt:[],keys:['July'],tip:'ay: <b>in + ay</b>. Güne: <b>on + gün</b>'},
{id:'a1_66',level:'A1',topic:'prepositions of time',tr:'Cuma günü bir sınavımız var.',en:'We have a test on Friday.',alt:[],keys:['test','Friday'],tip:'gün: <b>on + gün</b>'},
{id:'a1_67',level:'A1',topic:'prepositions of time',tr:'Genellikle gece on ikide yatarım.',en:'I usually go to bed at midnight.',alt:[],keys:['midnight'],tip:'<b>at midnight / at noon / at night</b>'},
{id:'a1_68',level:'A1',topic:'prepositions of time',tr:'1998 yılında doğdum.',en:'I was born in 1998.',alt:[],keys:['born','1998'],tip:'yıl: <b>in + yıl</b>. doğmak: <b>be born</b>'},
{id:'a1_69',level:'A1',topic:'prepositions of time',tr:'Dükkan altıda kapanıyor.',en:'The shop closes at six.',alt:[],keys:['closes','six'],tip:'saat: <b>at six</b>; 3. tekil: <b>closes</b>'},
{id:'a1_70',level:'A1',topic:'articles',tr:'Şemsiyeye ihtiyacım var.',en:'I need an umbrella.',alt:[],keys:['umbrella'],tip:'ünlü sesle başlayan kelime: <b>an umbrella, an apple, an egg</b>'},
{id:'a1_71',level:'A1',topic:'articles',tr:'Bu çok eski bir bina.',en:'This is an old building.',alt:[],keys:['old','building'],tip:'"old" ünlü sesle başlar → <b>an old</b>'},
{id:'a1_72',level:'A1',topic:'articles',tr:'Restoran solda.',en:'The restaurant is on the left.',alt:[],keys:['restaurant','left'],tip:'belli bir yer: <b>the restaurant</b>. Sola → <b>on the left</b>'},
{id:'a1_73',level:'A1',topic:'articles',tr:'O iyi bir öğretmen.',en:'He is a good teacher.',alt:['She is a good teacher.'],keys:['good','teacher'],tip:'meslek, ilk kez söz edilen: <b>a + meslek</b>'},
{id:'a1_74',level:'A1',topic:'articles',tr:'Bir portakal alabilir miyim?',en:'Can I have an orange?',alt:[],keys:['orange'],tip:'ünlü ses: <b>an orange</b>. Rica: <b>Can I have...?</b>'},
{id:'a1_75',level:'A1',topic:'imperatives (+)',tr:'Kitaplarınızı açın!',en:'Open your books!',alt:[],keys:['open','books'],tip:'emir: <b>fiil yalın hali + nesne</b>'},
{id:'a1_76',level:'A1',topic:'imperatives (−)',tr:'Ona dokunma!',en:"Don't touch that!",alt:["Do not touch that!"],keys:['touch'],tip:'olumsuz emir: <b>Don\'t + yalın fiil</b>'},
{id:'a1_77',level:'A1',topic:'imperatives (+)',tr:'Lütfen buraya gel!',en:'Come here, please!',alt:[],keys:['come','here'],tip:'rica: <b>fiil + please</b> (başta veya sonda)'},
{id:'a1_78',level:'A1',topic:'imperatives (+)',tr:'Trafik ışıklarında sola dön.',en:'Turn left at the traffic lights.',alt:[],keys:['left','traffic lights'],tip:'yön emri: <b>Turn left/right</b>'},
{id:'a1_79',level:'A1',topic:'imperatives (−)',tr:'Ödevini unutma!',en:"Don't forget your homework!",alt:["Do not forget your homework!"],keys:['forget','homework'],tip:'<b>Don\'t forget + nesne</b>'},
{id:'a1_80',level:'A1',topic:'imperatives (+)',tr:'Dikkatlice dinle!',en:'Listen carefully!',alt:[],keys:['listen'],tip:'emir + zarf: <b>Listen carefully!</b>'},
{id:'a1_81',level:'A1',topic:'possessives',tr:'Bu onun evi.',en:'This is her house.',alt:['This is his house.'],keys:['her','house'],tip:'iyelik: benim→my, senin→your, onun(k)→his/her'},
{id:'a1_82',level:'A1',topic:'possessives',tr:'Ceketini nereye koydun?',en:'Where is your jacket?',alt:[],keys:['jacket'],tip:'senin → <b>your</b>. Where is = nerede'},
{id:'a1_83',level:'A1',topic:'possessives',tr:'Onların çocukları çok kibar.',en:'Their children are very polite.',alt:[],keys:['their','children'],tip:'onların → <b>their</b>'},
{id:'a1_84',level:'A1',topic:'possessives',tr:'Onun adı Marco.',en:'His name is Marco.',alt:['Her name is Marco.'],keys:['name'],tip:'erkek için → <b>his</b>'},
{id:'a1_85',level:'A1',topic:'possessives',tr:'Okulumuz çok büyük.',en:'Our school is very big.',alt:[],keys:['our','school'],tip:'bizim → <b>our</b>'},
{id:'a1_86',level:'A1',topic:'possessives',tr:'Anahtarlarımı evde bıraktım.',en:'I left my keys at home.',alt:[],keys:['keys','home'],tip:'bırakmak: <b>leave → left</b>. evde: <b>at home</b>'},
{id:'a1_87',level:'A1',topic:'question words',tr:'O kaç yaşında?',en:'How old is she?',alt:['How old is he?'],keys:['how old'],tip:'yaş sorusu: <b>How old + is/are + özne?</b>'},
{id:'a1_88',level:'A1',topic:'question words',tr:'Neden geç kaldın?',en:'Why are you late?',alt:[],keys:['why','late'],tip:'neden: <b>Why + yardımcı + özne?</b>'},
{id:'a1_89',level:'A1',topic:'question words',tr:'Şu adam kim?',en:'Who is that man?',alt:[],keys:['who','man'],tip:'kim: <b>Who + is/are + ...?</b>'},
{id:'a1_90',level:'A1',topic:'question words',tr:'Bu kaç para?',en:'How much is this?',alt:['How much does this cost?'],keys:['how much'],tip:'fiyat: <b>How much is...?</b>'},
{id:'a1_91',level:'A1',topic:'question words',tr:'Tren saat kaçta kalkıyor?',en:'What time does the train leave?',alt:['When does the train leave?'],keys:['train','leave'],tip:'saat sorusu: <b>What time + does + özne + fiil?</b>'},
{id:'a1_92',level:'A1',topic:'question words',tr:'Hangi çanta senin?',en:'Which bag is yours?',alt:[],keys:['which','bag'],tip:'hangisi: <b>Which + isim + is/are?</b>'},
{id:'a1_93',level:'A1',topic:'adjectives (colour)',tr:'Bugün gökyüzü mavi.',en:'The sky is blue today.',alt:[],keys:['sky','blue'],tip:'renk sıfatı: <b>The sky is blue</b>'},
{id:'a1_94',level:'A1',topic:'adjectives (colour)',tr:'Kahverengi gözleri var.',en:'She has brown eyes.',alt:['He has brown eyes.'],keys:['brown','eyes'],tip:'renk + isim: <b>brown eyes</b>'},
{id:'a1_95',level:'A1',topic:'adjectives (colour)',tr:'Kırmızı bir elma istiyorum.',en:'I want a red apple.',alt:[],keys:['red','apple'],tip:'sıfat ismin önüne gelir: <b>a red apple</b>'},
{id:'a1_96',level:'A1',topic:'adjectives',tr:'O çok uzun boylu.',en:'He is very tall.',alt:['She is very tall.'],keys:['tall'],tip:'<b>very + sıfat</b>: çok uzun boylu'},
{id:'a1_97',level:'A1',topic:'adjectives',tr:'Bu kahve çok sıcak.',en:'This coffee is very hot.',alt:[],keys:['coffee','hot'],tip:'<b>very hot</b>: çok sıcak (ısı)'},
{id:'a1_98',level:'A1',topic:'adjectives',tr:'Yemek lezzetliydi.',en:'The food was delicious.',alt:[],keys:['delicious'],tip:'geçmiş: <b>was + sıfat</b>'},
{id:'a1_99',level:'A1',topic:'adjectives',tr:'Bu sorun çok ciddi.',en:'This problem is very serious.',alt:[],keys:['problem','serious'],tip:'<b>serious = ciddi</b>'},
{id:'a1_100',level:'A1',topic:'numbers',tr:'Üç kız kardeşim var.',en:'I have three sisters.',alt:[],keys:['three','sisters'],tip:'sayı + çoğul isim: <b>three sisters</b>'},
{id:'a1_101',level:'A1',topic:'numbers',tr:'İki kedimiz ve bir köpeğimiz var.',en:'We have two cats and one dog.',alt:[],keys:['two','cats'],tip:'<b>two cats</b> (çoğul), <b>one dog</b> (tekil)'},
{id:'a1_102',level:'A1',topic:'numbers',tr:'Sınıfımızda otuz öğrenci var.',en:'There are thirty students in my class.',alt:[],keys:['thirty','students'],tip:'<b>There are + sayı + çoğul isim</b>'},
{id:'a1_103',level:'A1',topic:'food',tr:'Pizza ve makarna severim.',en:'I like pizza and pasta.',alt:['I love pizza and pasta.'],keys:['pizza','pasta'],tip:'<b>like + isim</b>: severim'},
{id:'a1_104',level:'A1',topic:'food',tr:'Biraz ekmek ister misin?',en:'Do you want some bread?',alt:[],keys:['some','bread'],tip:'olumlu ifade/teklif: <b>some bread</b>'},
{id:'a1_105',level:'A1',topic:'food',tr:'Her sabah portakal suyu içiyor.',en:'She drinks orange juice every morning.',alt:['He drinks orange juice every morning.'],keys:['orange juice','morning'],tip:'3. tekil: <b>drinks</b>; her sabah: <b>every morning</b>'},
{id:'a1_106',level:'A1',topic:'food',tr:'Et yemiyorum.',en:"I don't eat meat.",alt:["I do not eat meat."],keys:['eat','meat'],tip:'olumsuz alışkanlık: <b>I don\'t + yalın fiil</b>'},
{id:'a1_107',level:'A1',topic:'food',tr:'Çikolatayı çok seviyor.',en:'He loves chocolate.',alt:['She loves chocolate.'],keys:['loves','chocolate'],tip:'3. tekil: <b>love → loves</b>'},
{id:'a1_108',level:'A1',topic:'food (?)',tr:'En sevdiğin yemek nedir?',en:'What is your favourite food?',alt:["What's your favourite food?"],keys:['favourite','food'],tip:'<b>What is your favourite + isim?</b>'},
{id:'a1_109',level:'A1',topic:'weather',tr:'Dışarısı yağmurlu.',en:'It is raining outside.',alt:["It's raining outside."],keys:['raining'],tip:'yağmur: <b>It is raining</b>. Şu an → -ing'},
{id:'a1_110',level:'A1',topic:'weather',tr:'Hava soğuk ve rüzgarlı.',en:'The weather is cold and windy.',alt:[],keys:['cold','windy'],tip:'hava + iki sıfat: <b>cold and windy</b>'},
{id:'a1_111',level:'A1',topic:'weather (?)',tr:'Kar yağıyor mu?',en:'Is it snowing?',alt:[],keys:['snowing'],tip:'kar yağmak: <b>It is snowing</b>'},
{id:'a1_112',level:'A1',topic:'weather',tr:'Güneşli günleri seviyorum.',en:'I love sunny days.',alt:['I love sunny weather.'],keys:['sunny'],tip:'güneşli: <b>sunny</b>'},
{id:'a1_113',level:'A1',topic:'feelings',tr:'Bugün çok mutluyum.',en:'I am very happy today.',alt:["I'm very happy today."],keys:['happy'],tip:'duygu: <b>I am + sıfat</b>'},
{id:'a1_114',level:'A1',topic:'feelings',tr:'Sınav için endişeleniyor.',en:'She is nervous about the exam.',alt:['He is nervous about the exam.'],keys:['nervous','exam'],tip:'endişeli: <b>nervous about + isim</b>'},
{id:'a1_115',level:'A1',topic:'feelings',tr:'Korkmuş musun?',en:'Are you scared?',alt:[],keys:['scared'],tip:'duygu sorusu: <b>Are you + sıfat?</b>'},
{id:'a1_116',level:'A1',topic:'feelings',tr:'Üzgün görünüyor.',en:'He looks sad.',alt:['She looks sad.'],keys:['sad'],tip:'görünmek: <b>look + sıfat</b>'},
{id:'a1_117',level:'A1',topic:'feelings',tr:'Seyahat için çok heyecanlıyız.',en:'We are excited about the trip.',alt:["We're excited about the trip."],keys:['excited','trip'],tip:'heyecanlı: <b>excited about + isim</b>'},
{id:'a1_118',level:'A1',topic:'family',tr:'Annem doktor.',en:'My mother is a doctor.',alt:[],keys:['mother','doctor'],tip:'meslek: <b>My mother is a + meslek</b>'},
{id:'a1_119',level:'A1',topic:'family',tr:'Daha büyük bir erkek kardeşim var.',en:'I have an older brother.',alt:[],keys:['older','brother'],tip:'yaşça büyük: <b>older brother</b>'},
{id:'a1_120',level:'A1',topic:'family',tr:'Büyükannem yetmiş yaşında.',en:'My grandmother is seventy years old.',alt:[],keys:['grandmother','seventy'],tip:'yaş: <b>seventy years old</b>'},
{id:'a1_121',level:'A1',topic:'family',tr:'Babam bir bankada çalışıyor.',en:'My father works in a bank.',alt:[],keys:['father','bank'],tip:'iş yeri: <b>work in a + yer</b>'},
{id:'a1_122',level:'A1',topic:'and / but / or',tr:'Yazı severim ama kışı sevmem.',en:"I like summer but I don't like winter.",alt:["I like summer but I don't like winter."],keys:['summer','winter'],tip:'zıtlık: <b>but</b>. Ek: <b>and</b>. Seçenek: <b>or</b>'},
{id:'a1_123',level:'A1',topic:'and / but / or',tr:'Hem yorgun hem de açım.',en:'I am tired and hungry.',alt:["I'm tired and hungry."],keys:['tired','hungry'],tip:'iki sıfatı birbirine bağlama: <b>and</b>'},
{id:'a1_124',level:'A1',topic:'and / but / or',tr:'Çay mı yoksa kahve mi istersiniz?',en:'Would you like tea or coffee?',alt:[],keys:['tea','coffee'],tip:'seçenek: <b>... or ...</b>'},
{id:'a1_125',level:'A1',topic:'because',tr:'Hasta olduğum için evdeyim.',en:'I am at home because I am sick.',alt:["I'm at home because I'm sick."],keys:['because','sick'],tip:'neden: <b>because + cümle</b>'},
{id:'a1_126',level:'A1',topic:'this / that / these / those',tr:'Bu benim telefonu değil, seninkini.',en:'This is not my phone, it is yours.',alt:["This is not my phone, it's yours."],keys:['yours'],tip:'bu→<b>this</b>, şu/o→<b>that</b>, bunlar→<b>these</b>, şunlar→<b>those</b>'},
{id:'a1_127',level:'A1',topic:'this / that / these / those',tr:'Şu elmalar çok taze.',en:'Those apples are very fresh.',alt:[],keys:['those','fresh'],tip:'uzaktaki çoğul: <b>Those + çoğul isim</b>'},
{id:'a1_128',level:'A1',topic:'this / that / these / those',tr:'Oradaki adam benim amcam.',en:'That man over there is my uncle.',alt:[],keys:['uncle'],tip:'uzaktaki tekil: <b>That man</b>'},
{id:'a1_129',level:'A1',topic:'this / that / these / those',tr:'Bu ayakkabılar çok küçük.',en:'These shoes are too small.',alt:[],keys:['shoes','small'],tip:'yakındaki çoğul: <b>These + çoğul isim</b>'},
{id:'a1_130',level:'A1',topic:'this / that / these / those (?)',tr:'Bu koltuk dolu mu?',en:'Is this seat taken?',alt:[],keys:['seat','taken'],tip:'<b>Is this seat taken?</b> = Bu yer boş mu?'},
{id:'a1_131',level:'A1',topic:'would like',tr:'Bir sandviç alabilir miyim?',en:'I would like a sandwich, please.',alt:["I'd like a sandwich, please."],keys:['sandwich'],tip:'nazik istek: <b>I would like / I\'d like + nesne</b>'},
{id:'a1_132',level:'A1',topic:'would like (?)',tr:'Biraz kahve ister misiniz?',en:'Would you like some coffee?',alt:[],keys:['coffee'],tip:'teklif: <b>Would you like + isim?</b>'},
{id:'a1_133',level:'A1',topic:'would like',tr:'İki kişilik masa istiyoruz.',en:'We would like a table for two.',alt:["We'd like a table for two."],keys:['table','two'],tip:'<b>a table for two</b>: iki kişilik masa'},
{id:'a1_134',level:'A1',topic:"let's",tr:'Parka gidelim!',en:"Let's go to the park!",alt:[],keys:["let's","park"],tip:'öneri: <b>Let\'s + yalın fiil</b>'},
{id:'a1_135',level:'A1',topic:"let's",tr:'Birlikte akşam yemeği yiyelim.',en:"Let's have dinner together.",alt:[],keys:["let's","dinner"],tip:'<b>Let\'s have dinner</b>: akşam yemeği yiyelim'},
{id:'a1_136',level:'A1',topic:'how many / how much',tr:'Evinde kaç oda var?',en:'How many rooms are there in your house?',alt:[],keys:['how many','rooms'],tip:'sayılabilir: <b>How many + çoğul isim</b>'},
{id:'a1_137',level:'A1',topic:'how many / how much',tr:'Bu ne kadar tutuyor?',en:'How much does this cost?',alt:['How much is this?'],keys:['how much'],tip:'sayılamaz/fiyat: <b>How much + does + isim + cost?</b>'},
{id:'a1_138',level:'A1',topic:'how many / how much',tr:'Ailende kaç kişi var?',en:'How many people are in your family?',alt:[],keys:['how many','family'],tip:'<b>How many + çoğul</b>'},
{id:'a1_139',level:'A1',topic:'present continuous (intro)',tr:'Şu an bir kitap okuyorum.',en:'I am reading a book at the moment.',alt:["I'm reading a book at the moment."],keys:['reading'],tip:'şu an: <b>am/is/are + fiil-ing</b>'},
{id:'a1_140',level:'A1',topic:'present continuous (intro)',tr:'Çocuklar bahçede oynuyor.',en:'The children are playing in the garden.',alt:[],keys:['playing','garden'],tip:'şu an devam eden: <b>are + playing</b>'},
{id:'a1_141',level:'A1',topic:'present continuous (intro)',tr:'Bugün çalışmıyor.',en:'She is not working today.',alt:["She isn't working today.","He is not working today."],keys:['working'],tip:'olumsuz: <b>is not + fiil-ing</b>'},
{id:'a1_142',level:'A1',topic:'present continuous (?)',tr:'Ne yapıyorsun?',en:'What are you doing?',alt:[],keys:['doing'],tip:'<b>What are you doing?</b>: ne yapıyorsun?'},
{id:'a1_143',level:'A1',topic:'simple present (+)',tr:'Hafta içi erken kalkıyorum.',en:'I get up early on weekdays.',alt:[],keys:['get up','weekdays'],tip:'alışkanlık: <b>get up early</b>. Hafta içi: <b>on weekdays</b>'},
{id:'a1_144',level:'A1',topic:'simple present (he)',tr:'Köpeğim her gün koşuyor.',en:'My dog runs every day.',alt:[],keys:['runs'],tip:'3. tekil: <b>run → runs</b>'},
{id:'a1_145',level:'A1',topic:'simple present (+)',tr:'Her yaz tatile gidiyoruz.',en:'We go on holiday every summer.',alt:[],keys:['holiday','summer'],tip:'tatile gitmek: <b>go on holiday</b>'},
{id:'a1_146',level:'A1',topic:'adjectives',tr:'O çok sabırsız bir öğrenci.',en:'He is a very impatient student.',alt:['She is a very impatient student.'],keys:['impatient'],tip:'sıfat ismin önüne gelir: <b>a very impatient student</b>'},
{id:'a1_147',level:'A1',topic:'prepositions of place',tr:'Kütüphane okulun ikinci katında.',en:'The library is on the second floor.',alt:[],keys:['second floor'],tip:'katta: <b>on the + sıra sayısı + floor</b>'},
{id:'a1_148',level:'A1',topic:'simple present (?)',tr:'En sevdiğin renk ne?',en:'What is your favourite colour?',alt:["What's your favourite colour?","What is your favorite color?"],keys:['favourite'],tip:'<b>What is your favourite + isim?</b>'},
{id:'a1_149',level:'A1',topic:'to be (+)',tr:'Hava çok bulutlu.',en:'It is very cloudy.',alt:["It's very cloudy."],keys:['cloudy'],tip:'hava: <b>It is + hava sıfatı</b>'},
{id:'a1_150',level:'A1',topic:'frequency adverbs',tr:'Her zaman zamanında geliyorum.',en:'I always arrive on time.',alt:[],keys:['always','on time'],tip:'sıklık zarfı be\'den sonra, diğer fiillerden önce: <b>always arrive</b>'},
{id:'a1_151',level:'A1',topic:'frequency adverbs',tr:'Nadiren dışarıda yemek yeriz.',en:'We rarely eat out.',alt:['We seldom eat out.'],keys:['rarely'],tip:'nadiren: <b>rarely / seldom</b>'},
{id:'a1_152',level:'A1',topic:'simple present (+)',tr:'Sabah kahvaltımda genelde yumurta yerim.',en:'I usually have eggs for breakfast.',alt:[],keys:['usually','breakfast'],tip:'genellikle: <b>usually + fiil</b>'},
{id:'a1_153',level:'A1',topic:'have/has',tr:'Kötü bir günüm var.',en:'I am having a bad day.',alt:["I'm having a bad day."],keys:['bad day'],tip:'şu anki durum: <b>I am having a bad day</b>'},
{id:'a1_154',level:'A1',topic:'to be (−)',tr:'Kapı kilitli değil.',en:'The door is not locked.',alt:["The door isn't locked."],keys:['door','locked'],tip:'değil: <b>is not / isn\'t + sıfat</b>'},
{id:'a1_155',level:'A1',topic:'simple present (+)',tr:'Çok fazla uyuyor.',en:'She sleeps a lot.',alt:['He sleeps a lot.'],keys:['sleeps'],tip:'3. tekil: <b>sleep → sleeps</b>. çok: <b>a lot</b>'}
);
