/* translate-data.js — TR→EN Cümle Çevirisi veri seti
   Her cümle: { id, level, topic, tr, en, alt[], keys[], tip }
   alt  : kabul edilen alternatif cevaplar (kısaltmalar dahil)
   keys : mutlaka bulunması gereken anahtar kelimeler
   tip  : gramer ipucu */

const TRANSLATE_DATA = [

  // ═══════════════════════════════════════ A1 ═══════
  { id:'a1_01', level:'A1', topic:'to be (+)',
    tr:'Ben bir öğrenciyim.',
    en:'I am a student.',
    alt:["I'm a student."],
    keys:['student'],
    tip:'Ben → <b>I am</b> / <b>I\'m</b>' },

  { id:'a1_02', level:'A1', topic:'to be (+)',
    tr:'O çok yorgun.',
    en:'He is very tired.',
    alt:["He's very tired.","She is very tired.","She's very tired."],
    keys:['tired'],
    tip:'O (erkek) → <b>He is</b> &nbsp;|&nbsp; O (kadın) → <b>She is</b>' },

  { id:'a1_03', level:'A1', topic:'to be (+)',
    tr:'Biz İstanbul\'dayız.',
    en:'We are in Istanbul.',
    alt:["We're in Istanbul."],
    keys:['istanbul'],
    tip:'Biz → <b>We are</b> / <b>We\'re</b>' },

  { id:'a1_04', level:'A1', topic:'to be (?)',
    tr:'Adın ne?',
    en:'What is your name?',
    alt:["What's your name?"],
    keys:['name'],
    tip:'Soru: <b>What is</b> / <b>What\'s</b>' },

  { id:'a1_05', level:'A1', topic:'to be (−)',
    tr:'O bir doktor değil, hemşire.',
    en:'She is not a doctor, she is a nurse.',
    alt:["She's not a doctor, she's a nurse.","She isn't a doctor, she's a nurse.","She isn't a doctor, she is a nurse."],
    keys:['nurse'],
    tip:'değil → <b>is not</b> / <b>isn\'t</b>' },

  { id:'a1_06', level:'A1', topic:'simple present',
    tr:'Her sabah kahvaltı yaparım.',
    en:'I have breakfast every morning.',
    alt:[],
    keys:['breakfast','morning'],
    tip:'Alışkanlık → <b>simple present</b>. "have breakfast" = kahvaltı yapmak' },

  { id:'a1_07', level:'A1', topic:'simple present he/she',
    tr:'Kardeşim her gün okula gider.',
    en:'My brother goes to school every day.',
    alt:['My sister goes to school every day.'],
    keys:['goes','school'],
    tip:'He/She → fiil + <b>-s/-es</b>: go → <b>goes</b>' },

  { id:'a1_08', level:'A1', topic:'simple present (−)',
    tr:'Kahve sevmiyorum.',
    en:'I do not like coffee.',
    alt:["I don't like coffee."],
    keys:['like','coffee'],
    tip:'I/you/we/they → <b>do not</b> / <b>don\'t</b>' },

  { id:'a1_09', level:'A1', topic:'simple present (?)',
    tr:'Nerede yaşıyorsun?',
    en:'Where do you live?',
    alt:[],
    keys:['where','live'],
    tip:'Soru: <b>Where + do + özne + fiil</b>' },

  { id:'a1_10', level:'A1', topic:'can',
    tr:'İyi yüzebilirim.',
    en:'I can swim well.',
    alt:[],
    keys:['can','swim'],
    tip:'Yetenek → <b>can + yalın fiil</b> (swim, not swims)' },

  { id:'a1_11', level:'A1', topic:'can (−)',
    tr:'Araba kullanamam.',
    en:'I cannot drive.',
    alt:["I can't drive."],
    keys:['drive'],
    tip:'yapamamak → <b>cannot</b> / <b>can\'t</b>' },

  { id:'a1_12', level:'A1', topic:'there is/are',
    tr:'Masada üç kitap var.',
    en:'There are three books on the table.',
    alt:[],
    keys:['three','books','table'],
    tip:'Çoğul → <b>There are</b>. Tekil → <b>There is</b>' },

  { id:'a1_13', level:'A1', topic:'have/has',
    tr:'İki kardeşim var.',
    en:'I have two siblings.',
    alt:['I have two brothers.','I have two sisters.'],
    keys:['have','two'],
    tip:'Ben/Sen/Biz → <b>have</b>. O → <b>has</b>' },

  { id:'a1_14', level:'A1', topic:'prepositions',
    tr:'Kitap çantanın içinde.',
    en:'The book is in the bag.',
    alt:[],
    keys:['book','bag'],
    tip:'içinde → <b>in</b>, üstünde → <b>on</b>, yanında → <b>next to</b>' },

  { id:'a1_15', level:'A1', topic:'want',
    tr:'Bir bardak su istiyorum.',
    en:'I want a glass of water.',
    alt:[],
    keys:['want','water'],
    tip:'"<b>a glass of water</b>" kalıbını ezberle!' },

  { id:'a1_16', level:'A1', topic:'possessives',
    tr:'Bu benim çantam.',
    en:'This is my bag.',
    alt:[],
    keys:['my','bag'],
    tip:'benim → <b>my</b>, senin → <b>your</b>, onun → <b>his/her</b>' },

  { id:'a1_17', level:'A1', topic:'articles',
    tr:'Dışarıda bir köpek var.',
    en:'There is a dog outside.',
    alt:[],
    keys:['dog','outside'],
    tip:'"<b>a</b>" → sessiz harften önce. "<b>an</b>" → ünlü harften önce: an apple, an umbrella' },

  { id:'a1_18', level:'A1', topic:'imperatives',
    tr:'Lütfen sessiz ol!',
    en:'Please be quiet!',
    alt:[],
    keys:['quiet'],
    tip:'Emir → fiil yalın haliyle başlar: <b>Be</b>, Go, Stop, Listen' },

  { id:'a1_19', level:'A1', topic:'plural',
    tr:'Bu çocuklar çok akıllı.',
    en:'These children are very smart.',
    alt:['These children are very clever.'],
    keys:['children'],
    tip:'child → <b>children</b> (düzensiz çoğul). these = bunlar' },

  { id:'a1_20', level:'A1', topic:'like / love',
    tr:'Müzik dinlemeyi çok seviyorum.',
    en:'I love listening to music.',
    alt:['I really like listening to music.','I love to listen to music.'],
    keys:['love','music'],
    tip:'sevmek → <b>love</b> / <b>like</b> + verb-ing veya to-infinitive' },

  // ═══════════════════════════════════════ A2 ═══════
  { id:'a2_01', level:'A2', topic:'past simple',
    tr:'Dün sinemaya gittim.',
    en:'I went to the cinema yesterday.',
    alt:[],
    keys:['went','cinema','yesterday'],
    tip:'Düzensiz geçmiş: <b>go → went</b>, come → came, see → saw' },

  { id:'a2_02', level:'A2', topic:'past simple (−)',
    tr:'Dün çalışmadım.',
    en:'I did not work yesterday.',
    alt:["I didn't work yesterday."],
    keys:['work','yesterday'],
    tip:'Geçmiş olumsuz: <b>did not / didn\'t + yalın fiil</b>' },

  { id:'a2_03', level:'A2', topic:'past simple (?)',
    tr:'Nerede doğdun?',
    en:'Where were you born?',
    alt:[],
    keys:['where','born'],
    tip:'doğmak → <b>be born</b> (pasif). Where were you born?' },

  { id:'a2_04', level:'A2', topic:'going to',
    tr:'Bu yaz İtalya\'ya gideceğiz.',
    en:'We are going to go to Italy this summer.',
    alt:["We're going to go to Italy this summer.","We're going to Italy this summer."],
    keys:['going to','italy','summer'],
    tip:'Plan/niyet → <b>be going to + yalın fiil</b>' },

  { id:'a2_05', level:'A2', topic:'will',
    tr:'Sana yardım edeceğim.',
    en:'I will help you.',
    alt:["I'll help you."],
    keys:['will','help'],
    tip:'Anlık karar / söz → <b>will + yalın fiil</b>' },

  { id:'a2_06', level:'A2', topic:'present continuous',
    tr:'Şu an kitap okuyorum.',
    en:'I am reading a book now.',
    alt:["I'm reading a book now."],
    keys:['reading','now'],
    tip:'Şu an olan iş → <b>am/is/are + verb-ing</b>' },

  { id:'a2_07', level:'A2', topic:'comparative',
    tr:'Bu kitap diğerinden daha zor.',
    en:'This book is more difficult than the other one.',
    alt:['This book is harder than the other.'],
    keys:['more','than'],
    tip:'Uzun kelimeler: <b>more + adjective</b>. Kısa: <b>adjective + -er</b>' },

  { id:'a2_08', level:'A2', topic:'superlative',
    tr:'O, sınıfın en zeki öğrencisi.',
    en:'She is the smartest student in the class.',
    alt:['He is the smartest student in the class.','She is the cleverest student in the class.'],
    keys:['class'],
    tip:'En üstün: <b>the + adj + -est</b> (kısa) / <b>the most + adj</b> (uzun)' },

  { id:'a2_09', level:'A2', topic:'must / have to',
    tr:'Her gün egzersiz yapmalısın.',
    en:'You must exercise every day.',
    alt:['You have to exercise every day.','You need to exercise every day.'],
    keys:['must','exercise'],
    tip:'zorunluluk → <b>must</b> / <b>have to</b>. Öneri → <b>should</b>' },

  { id:'a2_10', level:'A2', topic:'should',
    tr:'Daha fazla uyumalısın.',
    en:'You should sleep more.',
    alt:[],
    keys:['should','sleep'],
    tip:'tavsiye → <b>should + yalın fiil</b>' },

  { id:'a2_11', level:'A2', topic:'past simple irreg.',
    tr:'Geçen hafta yeni bir araba aldım.',
    en:'I bought a new car last week.',
    alt:[],
    keys:['bought','last week'],
    tip:'<b>buy → bought</b> (düzensiz). last week = geçen hafta' },

  { id:'a2_12', level:'A2', topic:'how many/much',
    tr:'Kaç tane kardeşin var?',
    en:'How many siblings do you have?',
    alt:['How many brothers do you have?','How many sisters do you have?'],
    keys:['how many'],
    tip:'Sayılabilir → <b>How many</b>. Sayılamaz → <b>How much</b>' },

  { id:'a2_13', level:'A2', topic:'used to',
    tr:'Eskiden her gün yüzerdim.',
    en:'I used to swim every day.',
    alt:[],
    keys:['used to','swim'],
    tip:'Geçmişteki alışkanlık → <b>used to + yalın fiil</b>' },

  { id:'a2_14', level:'A2', topic:'would like',
    tr:'Bir fincan çay alır mısın?',
    en:'Would you like a cup of tea?',
    alt:[],
    keys:['would like','tea'],
    tip:'Nazik teklif → <b>Would you like...?</b>' },

  { id:'a2_15', level:'A2', topic:'past continuous',
    tr:'Film başladığında yemek yiyordum.',
    en:'I was eating when the film started.',
    alt:[],
    keys:['was eating','started'],
    tip:'Geçmişte süregelen iş → <b>was/were + verb-ing</b>' },

  { id:'a2_16', level:'A2', topic:'frequency adverbs',
    tr:'Nadiren fast food yerim.',
    en:'I rarely eat fast food.',
    alt:['I seldom eat fast food.'],
    keys:['rarely'],
    tip:'Sıklık: always → usually → often → sometimes → <b>rarely</b> → never' },

  { id:'a2_17', level:'A2', topic:'because',
    tr:'Eve erken gittim çünkü yorgundum.',
    en:'I went home early because I was tired.',
    alt:[],
    keys:['because','tired','early'],
    tip:'Neden → <b>because</b>. Sonuç → <b>so</b>' },

  { id:'a2_18', level:'A2', topic:'some / any',
    tr:'Buzdolabında süt var mı?',
    en:'Is there any milk in the fridge?',
    alt:[],
    keys:['any','milk','fridge'],
    tip:'Soru/olumsuz → <b>any</b>. Olumlu → <b>some</b>' },

  { id:'a2_19', level:'A2', topic:'ago',
    tr:'İki yıl önce buraya taşındım.',
    en:'I moved here two years ago.',
    alt:[],
    keys:['two years ago'],
    tip:'...önce → <b>... ago</b>. Geçmiş zamanda kullanılır.' },

  { id:'a2_20', level:'A2', topic:'question tags',
    tr:'Hava bugün güzel, değil mi?',
    en:"The weather is nice today, isn't it?",
    alt:[],
    keys:["isn't it"],
    tip:'Soru eki: olumlu cümle → <b>olumsuz ek</b>. is → <b>isn\'t it</b>' },

  // ═══════════════════════════════════════ B1 ═══════
  { id:'b1_01', level:'B1', topic:'present perfect',
    tr:'Hiç Paris\'e gittin mi?',
    en:'Have you ever been to Paris?',
    alt:[],
    keys:['have','ever','paris'],
    tip:'Deneyim → <b>Have you ever + past participle?</b>' },

  { id:'b1_02', level:'B1', topic:'present perfect (for/since)',
    tr:'Üç yıldır burada yaşıyorum.',
    en:'I have lived here for three years.',
    alt:["I've lived here for three years.",'I have been living here for three years.'],
    keys:['three years'],
    tip:'Süre → <b>for</b> + süre. Başlangıç → <b>since</b> + tarih' },

  { id:'b1_03', level:'B1', topic:'1st conditional',
    tr:'Yeterince çalışırsan sınavı geçersin.',
    en:'If you study enough, you will pass the exam.',
    alt:["If you study enough, you'll pass the exam."],
    keys:['if','study','will pass'],
    tip:'1. Koşul: <b>If + present simple, will + yalın fiil</b>' },

  { id:'b1_04', level:'B1', topic:'passive (present)',
    tr:'Bu araba Almanya\'da üretiliyor.',
    en:'This car is produced in Germany.',
    alt:['This car is made in Germany.','This car is manufactured in Germany.'],
    keys:['is','germany'],
    tip:'Edilgen: <b>am/is/are + past participle</b>' },

  { id:'b1_05', level:'B1', topic:'passive (past)',
    tr:'Bu köprü 1973\'te inşa edildi.',
    en:'This bridge was built in 1973.',
    alt:[],
    keys:['was built','1973'],
    tip:'Geçmiş edilgen: <b>was/were + past participle</b>' },

  { id:'b1_06', level:'B1', topic:'relative clause (who)',
    tr:'O, bana yardım eden kadın.',
    en:'She is the woman who helped me.',
    alt:['She is the woman that helped me.'],
    keys:['who','helped'],
    tip:'Kişi için → <b>who</b> / <b>that</b>. Nesne için → <b>which</b> / <b>that</b>' },

  { id:'b1_07', level:'B1', topic:'relative clause (which)',
    tr:'Bu, dün satın aldığım kitap.',
    en:'This is the book which I bought yesterday.',
    alt:['This is the book that I bought yesterday.'],
    keys:['bought','yesterday'],
    tip:'Nesne için → <b>which</b> / <b>that</b>' },

  { id:'b1_08', level:'B1', topic:'reported speech',
    tr:'O, yorgun olduğunu söyledi.',
    en:'She said that she was tired.',
    alt:['She said she was tired.','He said that he was tired.','He said he was tired.'],
    keys:['said','was tired'],
    tip:'Dolaylı aktarım: am/is → <b>was</b>. will → <b>would</b>' },

  { id:'b1_09', level:'B1', topic:'might',
    tr:'Bu akşam geç gelebilirim.',
    en:'I might come late this evening.',
    alt:[],
    keys:['might','late'],
    tip:'ihtimal → <b>might</b> / <b>may</b> + yalın fiil' },

  { id:'b1_10', level:'B1', topic:'although',
    tr:'Hasta olmasına rağmen işe gitti.',
    en:'Although he was ill, he went to work.',
    alt:['Although she was ill, she went to work.','Even though he was ill, he went to work.'],
    keys:['although','ill','went'],
    tip:'Zıtlık → <b>although</b> / <b>even though</b> + cümle' },

  { id:'b1_11', level:'B1', topic:'wish (present)',
    tr:'Keşke daha fazla param olsa.',
    en:'I wish I had more money.',
    alt:[],
    keys:['wish','had','money'],
    tip:'Gerçekleşmeyen dilek → <b>wish + past simple</b>' },

  { id:'b1_12', level:'B1', topic:'gerund as subject',
    tr:'Düzenli egzersiz yapmak sağlıklıdır.',
    en:'Doing regular exercise is healthy.',
    alt:['Regular exercise is healthy.'],
    keys:['exercise','healthy'],
    tip:'Fiil özne olunca → <b>verb + -ing</b> (Gerund)' },

  { id:'b1_13', level:'B1', topic:'infinitive of purpose',
    tr:'Seni görmek için geldim.',
    en:'I came to see you.',
    alt:[],
    keys:['came','to see'],
    tip:'Amaç → <b>to + infinitive</b>: I came <b>to help</b>.' },

  { id:'b1_14', level:'B1', topic:'yet / already',
    tr:'Ödevimi henüz bitirmedim.',
    en:"I haven't finished my homework yet.",
    alt:["I have not finished my homework yet."],
    keys:['finished','yet'],
    tip:'<b>yet</b> → henüz (olumsuz/soru). <b>already</b> → zaten (olumlu)' },

  { id:'b1_15', level:'B1', topic:'too / enough',
    tr:'Bu kıyafet benim için çok küçük.',
    en:'This dress is too small for me.',
    alt:['This outfit is too small for me.'],
    keys:['too small'],
    tip:'Fazla → <b>too + adjective</b>. Yeterli → <b>adjective + enough</b>' },

  { id:'b1_16', level:'B1', topic:'so ... that',
    tr:'O kadar yorgundum ki uyuya kaldım.',
    en:'I was so tired that I fell asleep.',
    alt:[],
    keys:['so tired','fell asleep'],
    tip:'<b>so + adjective + that</b> → I was <b>so tired that</b>...' },

  { id:'b1_17', level:'B1', topic:'indirect question',
    tr:'Tren istasyonunun nerede olduğunu biliyor musun?',
    en:'Do you know where the train station is?',
    alt:[],
    keys:['do you know','where'],
    tip:'Dolaylı soru: Do you know <b>where + özne + fiil</b> (soru kelime sırası değişir!)' },

  { id:'b1_18', level:'B1', topic:'present perfect continuous',
    tr:'İki saattir bu kitabı okuyorum.',
    en:'I have been reading this book for two hours.',
    alt:["I've been reading this book for two hours."],
    keys:['have been reading','two hours'],
    tip:'Süregelen eylem → <b>have/has been + verb-ing</b> + for/since' },

  { id:'b1_19', level:'B1', topic:'could (past ability)',
    tr:'Çocukken çok hızlı koşabilirdim.',
    en:'I could run very fast when I was a child.',
    alt:['I was able to run very fast when I was a child.'],
    keys:['could','run'],
    tip:'Geçmişte yetenek → <b>could + yalın fiil</b>' },

  { id:'b1_20', level:'B1', topic:'need to',
    tr:'Bu hafta sonu evi temizlemem gerekiyor.',
    en:'I need to clean the house this weekend.',
    alt:['I have to clean the house this weekend.'],
    keys:['need to','clean'],
    tip:'zorunluluk → <b>need to</b> / <b>have to</b> / <b>must</b>' },

  // ═══════════════════════════════════════ B2 ═══════
  { id:'b2_01', level:'B2', topic:'2nd conditional',
    tr:'Daha fazla param olsaydı büyük bir ev alırdım.',
    en:'If I had more money, I would buy a big house.',
    alt:["If I had more money, I'd buy a big house."],
    keys:['if','had','would buy'],
    tip:'2. Koşul (varsayımsal): <b>If + past simple, would + infinitive</b>' },

  { id:'b2_02', level:'B2', topic:'3rd conditional',
    tr:'Daha sıkı çalışsaydın sınavı geçerdin.',
    en:'If you had studied harder, you would have passed the exam.',
    alt:["If you had studied harder, you'd have passed the exam."],
    keys:['had studied','would have passed'],
    tip:'3. Koşul (geçmiş pişmanlık): <b>If + past perfect, would have + past participle</b>' },

  { id:'b2_03', level:'B2', topic:'past perfect',
    tr:'Biz vardığımızda film çoktan başlamıştı.',
    en:'When we arrived, the film had already started.',
    alt:[],
    keys:['arrived','had already started'],
    tip:'Geçmişte daha önce olan → <b>past perfect (had + past participle)</b>' },

  { id:'b2_04', level:'B2', topic:'passive (present perfect)',
    tr:'Toplantı saat üçe ertelenmiş.',
    en:"The meeting has been postponed to three o'clock.",
    alt:[],
    keys:['has been postponed'],
    tip:'Present perfect passive: <b>has/have been + past participle</b>' },

  { id:'b2_05', level:'B2', topic:'causative have',
    tr:'Dün saçımı kestirdim.',
    en:'I had my hair cut yesterday.',
    alt:[],
    keys:['had my hair cut'],
    tip:'Yaptırmak → <b>have + nesne + past participle</b>: have it <b>fixed</b>, get it <b>done</b>' },

  { id:'b2_06', level:'B2', topic:'must have (speculation)',
    tr:'O anahtarları almış olmalı.',
    en:'She must have taken the keys.',
    alt:['He must have taken the keys.'],
    keys:['must have taken'],
    tip:'Geçmiş kesin ihtimal → <b>must have + past participle</b>' },

  { id:'b2_07', level:'B2', topic:'wish (past)',
    tr:'Keşke ona söyleseydin.',
    en:'I wish you had told him.',
    alt:['I wish you had told her.'],
    keys:['wish','had told'],
    tip:'Geçmiş pişmanlık → <b>wish + past perfect</b>' },

  { id:'b2_08', level:'B2', topic:'reporting verbs',
    tr:'Gelmeyi reddetti.',
    en:'He refused to come.',
    alt:['She refused to come.'],
    keys:['refused to come'],
    tip:'Reporting verbs + infinitive: <b>agree, refuse, offer, promise, decide</b>' },

  { id:'b2_09', level:'B2', topic:'despite',
    tr:'Tüm zorluklara rağmen başardı.',
    en:'Despite all the difficulties, she succeeded.',
    alt:['Despite all the difficulties, he succeeded.','In spite of all the difficulties, she succeeded.'],
    keys:['despite'],
    tip:'<b>despite / in spite of</b> + noun/gerund (sonrasında cümle olmaz!)' },

  { id:'b2_10', level:'B2', topic:'inversion (never)',
    tr:'Hayatımda bu kadar güzel bir şey hiç görmedim.',
    en:'Never in my life have I seen such a beautiful thing.',
    alt:[],
    keys:['never','have i seen'],
    tip:'Vurgu için olumsuz başlangıç: <b>Never</b> + yardımcı + özne (devrik cümle)' },

  { id:'b2_11', level:'B2', topic:'mixed conditional',
    tr:'Daha dikkatli olsaydın şimdi hastanede yatmıyordun.',
    en:"If you had been more careful, you wouldn't be in hospital now.",
    alt:["If you had been more careful, you would not be in hospital now."],
    keys:['had been',"wouldn't be"],
    tip:'Karma koşul: <b>geçmişteki neden → şimdiki sonuç</b>' },

  { id:'b2_12', level:'B2', topic:"can't have",
    tr:'Öyle bir şey söylememiş olmalı.',
    en:"She can't have said such a thing.",
    alt:["She couldn't have said such a thing.",'He can\'t have said such a thing.'],
    keys:["can't have"],
    tip:"Geçmiş imkansızlık → <b>can't have / couldn't have + past participle</b>" },

  { id:'b2_13', level:'B2', topic:'whatever / whenever',
    tr:'Ne zaman ihtiyacın olursa ara.',
    en:'Call me whenever you need.',
    alt:['Call me whenever you need to.'],
    keys:['whenever'],
    tip:'her ne zaman → <b>whenever</b>, her kim → <b>whoever</b>, ne olursa → <b>whatever</b>' },

  { id:'b2_14', level:'B2', topic:'hardly ... when',
    tr:'Eve gelir gelmez uyuya kaldım.',
    en:'Hardly had I arrived home when I fell asleep.',
    alt:["I had hardly arrived home when I fell asleep."],
    keys:['hardly','arrived'],
    tip:'Hemen ardından → <b>Hardly had + özne + pp + when...</b>' },

  { id:'b2_15', level:'B2', topic:'cleft sentence',
    tr:'Bana yardım eden tek kişi sendin.',
    en:'You were the only person who helped me.',
    alt:['It was you who helped me.'],
    keys:['only','who helped'],
    tip:'Vurgu: <b>It was ... who/that</b> veya "the only one who"' },

];
