const fs = require('fs');
const content = fs.readFileSync('js/data.js', 'utf8');

const missingWordsData = [
  {id:'maria',en:'Maria',tr:'Maria (isim)',ipa:'/məˈriː.ə/',level:'A1',cat:'İnsanlar',icon:'👩',ex:'Maria starts a new job.'},
  {id:'center',en:'center',tr:'merkez',ipa:'/ˈsen.tər/',level:'A1',cat:'Yerler',icon:'📍',ex:'The office is in the city center.'},
  {id:'prepare',en:'prepare',tr:'hazırlamak',ipa:'/prɪˈpeər/',level:'A1',cat:'Eylemler',icon:'🍳',ex:'I need to prepare breakfast.'},
  {id:'yogurt',en:'yogurt',tr:'yoğurt',ipa:'/ˈjəʊ.ɡət/',level:'A1',cat:'Yiyecek',icon:'🥣',ex:'I eat yogurt every day.'},
  {id:'miller',en:'Miller',tr:'Miller (soyisim)',ipa:'/ˈmɪl.ər/',level:'A1',cat:'İnsanlar',icon:'👨',ex:'Mr. Miller is my boss.'},
  {id:'tom',en:'Tom',tr:'Tom (isim)',ipa:'/tɒm/',level:'A1',cat:'İnsanlar',icon:'👦',ex:'Tom is looking for his key.'},
  {id:'anna',en:'Anna',tr:'Anna (isim)',ipa:'/ˈæn.ə/',level:'A1',cat:'İnsanlar',icon:'👧',ex:'Today is Anna\'s birthday.'},
  {id:'tenth',en:'tenth',tr:'onuncu',ipa:'/tenθ/',level:'A1',cat:'Sayılar',icon:'🔟',ex:'It is her tenth birthday.'},
  {id:'kitchen',en:'kitchen',tr:'mutfak',ipa:'/ˈkɪtʃ.ən/',level:'A1',cat:'Ev',icon:'🍳',ex:'Mom is in the kitchen.'},
  {id:'mary',en:'Mary',tr:'Mary (isim)',ipa:'/ˈmeə.ri/',level:'A1',cat:'İnsanlar',icon:'👩',ex:'Mary lives in a big house.'},
  {id:'ben',en:'Ben',tr:'Ben (isim)',ipa:'/ben/',level:'A1',cat:'İnsanlar',icon:'👦',ex:'Ben stayed home today.'},
  {id:'television',en:'television',tr:'televizyon',ipa:'/ˈtel.ɪ.vɪʒ.ən/',level:'A1',cat:'Ev',icon:'📺',ex:'We watched television.'},
  {id:'david',en:'David',tr:'David (isim)',ipa:'/ˈdeɪ.vɪd/',level:'A1',cat:'İnsanlar',icon:'👨',ex:'David had an interview.'},
  {id:'sophie',en:'Sophie',tr:'Sophie (isim)',ipa:'/ˈsəʊ.fi/',level:'A1',cat:'İnsanlar',icon:'👩',ex:'Sophie is at the airport.'},
  {id:'museum',en:'museum',tr:'müze',ipa:'/mjuːˈziː.əm/',level:'A2',cat:'Yerler',icon:'🏛️',ex:'We visited the museum.'},
  {id:'carlos',en:'Carlos',tr:'Carlos (isim)',ipa:'/ˈkɑː.lɒs/',level:'A1',cat:'İnsanlar',icon:'👨',ex:'Carlos started a business.'},
  {id:'kim',en:'Kim',tr:'Kim (isim)',ipa:'/kɪm/',level:'A1',cat:'İnsanlar',icon:'👩',ex:'Dr. Kim is a doctor.'},
  {id:'sarah',en:'Sarah',tr:'Sarah (isim)',ipa:'/ˈseə.rə/',level:'A1',cat:'İnsanlar',icon:'👩',ex:'Sarah moved to a new city.'},
  {id:'james',en:'James',tr:'James (isim)',ipa:'/dʒeɪmz/',level:'A1',cat:'İnsanlar',icon:'👨',ex:'James went to the doctor.'},
  {id:'maya',en:'Maya',tr:'Maya (isim)',ipa:'/ˈmaɪ.ə/',level:'A1',cat:'İnsanlar',icon:'👩',ex:'Maya won a prize.'},
  {id:'lily',en:'Lily',tr:'Lily (isim)',ipa:'/ˈlɪl.i/',level:'A1',cat:'İnsanlar',icon:'👧',ex:'Lily is a new friend.'},
  {id:'ensure',en:'ensure',tr:'emin olmak/sağlamak',ipa:'/ɪnˈʃɔːr/',level:'B2',cat:'Eylemler',icon:'✅',ex:'Ensure a good impression.'},
  {id:'researching',en:'researching',tr:'araştırma yapmak',ipa:'/rɪˈsɜː.tʃɪŋ/',level:'B2',cat:'Eylemler',icon:'🔍',ex:'Researching the company.'},
  {id:'praised',en:'praised',tr:'övüldü',ipa:'/preɪzd/',level:'B2',cat:'Eylemler',icon:'👏',ex:'He was praised for his work.'},
  {id:'foster',en:'foster',tr:'teşvik etmek/büyütmek',ipa:'/ˈfɒs.tər/',level:'B2',cat:'Eylemler',icon:'🌱',ex:'Foster a culture of transparency.'},
  {id:'reconcile',en:'reconcile',tr:'uzlaştırmak',ipa:'/ˈrek.ən.saɪl/',level:'B2',cat:'Eylemler',icon:'🤝',ex:'Reconcile differences.'},
  {id:'evolve',en:'evolve',tr:'gelişmek/evrimleşmek',ipa:'/ɪˈvɒlv/',level:'C1',cat:'Eylemler',icon:'🧬',ex:'Technology continues to evolve.'},
  {id:'grapple',en:'grapple',tr:'mücadele etmek/boğuşmak',ipa:'/ˈɡræp.əl/',level:'C1',cat:'Eylemler',icon:'🤼',ex:'Grapple with dilemmas.'},
  {id:'produce',en:'produce',tr:'üretmek',ipa:'/prəˈdjuːs/',level:'B1',cat:'Eylemler',icon:'🏭',ex:'Produce unintended consequences.'},
  {id:'threatens',en:'threatens',tr:'tehdit eder',ipa:'/ˈθret.ənz/',level:'B2',cat:'Eylemler',icon:'⚠️',ex:'Bias threatens equality.'},
  {id:'establish',en:'establish',tr:'kurmak',ipa:'/ɪˈstæb.lɪʃ/',level:'B2',cat:'Eylemler',icon:'🏢',ex:'Establish robust legislation.'},
  {id:'promote',en:'promote',tr:'teşvik etmek/tanıtmak',ipa:'/prəˈməʊt/',level:'B1',cat:'Eylemler',icon:'📈',ex:'Promote safety standards.'},
  {id:'prevent',en:'prevent',tr:'önlemek',ipa:'/prɪˈvent/',level:'B1',cat:'Eylemler',icon:'🚫',ex:'Prevent systemic adversity.'},
  {id:'rise',en:'rise',tr:'yükselmek',ipa:'/raɪz/',level:'A2',cat:'Eylemler',icon:'📈',ex:'Temperatures will rise.'},
  {id:'implementing',en:'implementing',tr:'uygulama',ipa:'/ˈɪm.plɪ.men.tɪŋ/',level:'B2',cat:'Eylemler',icon:'🛠️',ex:'Implementing new policies.'},
  {id:'prioritizes',en:'prioritizes',tr:'önceliklendirir',ipa:'/praɪˈɒr.ɪ.taɪ.zɪz/',level:'B2',cat:'Eylemler',icon:'🔝',ex:'Prioritizes sustainability.'},
  {id:'collaborate',en:'collaborate',tr:'iş birliği yapmak',ipa:'/kəˈlæb.ə.reɪt/',level:'B2',cat:'İş',icon:'🤝',ex:'Collaborate on missions.'},
  {id:'extraction',en:'extraction',tr:'çıkarma',ipa:'/ɪkˈstræk.ʃən/',level:'C1',cat:'Eylemler',icon:'⛏️',ex:'Extraction of resources.'},
  {id:'autonomous',en:'autonomous',tr:'otonom/özerk',ipa:'/ɔːˈtɒn.ə.məs/',level:'C1',cat:'Sıfatlar',icon:'🤖',ex:'Autonomous systems.'},
  {id:'unintended',en:'unintended',tr:'istenmeyen',ipa:'/ˌʌn.ɪnˈten.dɪd/',level:'C1',cat:'Sıfatlar',icon:'🤷',ex:'Unintended consequences.'},
  {id:'detrimental',en:'detrimental',tr:'zararlı',ipa:'/ˌdet.rɪˈmen.təl/',level:'C1',cat:'Sıfatlar',icon:'⚠️',ex:'Detrimental effects.'},
  {id:'pervasive',en:'pervasive',tr:'yaygın',ipa:'/pəˈveɪ.sɪv/',level:'C1',cat:'Sıfatlar',icon:'🌫️',ex:'Pervasive bias.'},
  {id:'algorithmic',en:'algorithmic',tr:'algoritmik',ipa:'/ˌæl.ɡəˈrɪð.mɪk/',level:'C1',cat:'Teknoloji',icon:'💻',ex:'Algorithmic nature.'},
  {id:'robust',en:'robust',tr:'güçlü/sağlam',ipa:'/rəʊˈbʌst/',level:'B2',cat:'Sıfatlar',icon:'💪',ex:'Robust legislation.'},
  {id:'systemic',en:'systemic',tr:'sistemsel',ipa:'/sɪˈstem.ɪk/',level:'C1',cat:'Sıfatlar',icon:'⚙️',ex:'Systemic adversity.'},
  {id:'catastrophic',en:'catastrophic',tr:'felaket düzeyinde',ipa:'/ˌkæt.əˈstrɒf.ɪk/',level:'C1',cat:'Sıfatlar',icon:'🌋',ex:'Catastrophic levels.'},
  {id:'worldwide',en:'worldwide',tr:'dünya çapında',ipa:'/ˌwɜːldˈwaɪd/',level:'B1',cat:'Sosyal',icon:'🌍',ex:'Governments worldwide.'},
  {id:'renewable',en:'renewable',tr:'yenilenebilir',ipa:'/rɪˈnjuː.ə.bəl/',level:'B2',cat:'Doğa',icon:'♻️',ex:'Renewable energy.'},
  {id:'sustainable',en:'sustainable',tr:'sürdürülebilir',ipa:'/səˌsteɪ.nəˈbɪl.ə.ti/',level:'B2',cat:'Doğa',icon:'♻️',ex:'Sustainable model.'},
  {id:'financial',en:'financial',tr:'finansal',ipa:'/faɪˈnæn.ʃəl/',level:'B1',cat:'Finans',icon:'💰',ex:'Financial profits.'},
  {id:'multilateral',en:'multilateral',tr:'çok taraflı',ipa:'/ˌmʌl.tiˈlæt.ər.əl/',level:'C1',cat:'Sosyal',icon:'🤝',ex:'Multilateral cooperation.'},
  {id:'ambitious',en:'ambitious',tr:'hırslı/iddialı',ipa:'/æmˈbɪʃ.əs/',level:'B1',cat:'Kişilik',icon:'🎯',ex:'Ambitious missions.'},
  {id:'complex',en:'complex',tr:'karmaşık',ipa:'/ˈkɒm.pleks/',level:'B1',cat:'Soyut',icon:'🌀',ex:'Complex sovereignty.'},
  {id:'lunar',en:'lunar',tr:'ay ile ilgili',ipa:'/ˈluː.nər/',level:'B2',cat:'Uzay',icon:'🌙',ex:'Lunar resources.'},
  {id:'planetary',en:'planetary',tr:'gezegen ile ilgili',ipa:'/ˈplæn.ɪ.tri/',level:'B2',cat:'Uzay',icon:'🪐',ex:'Planetary contamination.'},
  {id:'legal',en:'legal',tr:'yasal',ipa:'/ˈliː.ɡəl/',level:'B2',cat:'Hukuk',icon:'⚖️',ex:'Legal conundrums.'},
  {id:'minimalist',en:'minimalist',tr:'minimalist',ipa:'/ˈmɪn.ɪ.mə.lɪst/',level:'C1',cat:'Sıfatlar',icon:'⬜',ex:'Minimalist lifestyle.'},
  {id:'urban',en:'urban',tr:'kentsel',ipa:'/ˈɜː.bən/',level:'B2',cat:'Yerler',icon:'🏙️',ex:'Urban centers.'},
  {id:'complete',en:'complete',tr:'tam/eksiksiz',ipa:'/kəmˈpliːt/',level:'A2',cat:'Sıfatlar',icon:'💯',ex:'Complete reimagining.'},
  {id:'efficient',en:'efficient',tr:'verimli',ipa:'/ɪˈfɪʃ.ənt/',level:'B2',cat:'Sıfatlar',icon:'⚡',ex:'Efficient public transit.'},
  {id:'ecological',en:'ecological',tr:'ekolojik',ipa:'/ˌiː.kəˈlɒdʒ.ɪ.kəl/',level:'C1',cat:'Doğa',icon:'🍃',ex:'Ecological crises.'},
  {id:'ensuring',en:'ensuring',tr:'garanti etmek/sağlamak',ipa:'/ɪnˈʃɔː.rɪŋ/',level:'B2',cat:'Eylemler',icon:'✅',ex:'Ensuring fair benefits.'},
  {id:'rejected',en:'rejected',tr:'reddedildi',ipa:'/rɪˈdʒek.tɪd/',level:'B2',cat:'Eylemler',icon:'❌',ex:'The options were rejected.'},
  {id:'seeking',en:'seeking',tr:'arayışında olma',ipa:'/ˈsiː.kɪŋ/',level:'B2',cat:'Eylemler',icon:'🔍',ex:'Seeking to alleviate burden.'},
  {id:'integrate',en:'integrate',tr:'entegre etmek',ipa:'/ˈɪn.tɪ.ɡreɪt/',level:'C1',cat:'Eylemler',icon:'🧩',ex:'Integrate green spaces.'},
  {id:'address',en:'address',tr:'ele almak/çözmek',ipa:'/əˈdres/',level:'B2',cat:'Eylemler',icon:'🎯',ex:'Address the footprint.'},
  {id:'alleviate',en:'alleviate',tr:'hafifletmek',ipa:'/əˈliː.vi.eɪt/',level:'C1',cat:'Eylemler',icon:'🩹',ex:'Alleviate mental burden.'},
  {id:'vibrant',en:'vibrant',tr:'canlı/vibrant',ipa:'/ˈvaɪ.brənt/',level:'B2',cat:'Sıfatlar',icon:'🌈',ex:'Vibrant city center.'},
  {id:'productive',en:'productive',tr:'üretken',ipa:'/prəˈdʌk.tɪv/',level:'B2',cat:'Sıfatlar',icon:'🏭',ex:'Productive employees.'},
  {id:'diligent',en:'diligent',tr:'gayretli/çalışkan',ipa:'/ˈdɪl.ɪ.dʒənt/',level:'B2',cat:'Kişilik',icon:'🐝',ex:'Diligent work.'},
  {id:'tangible',en:'tangible',tr:'somut/elle tutulur',ipa:'/ˈtæn.dʒə.bəl/',level:'B2',cat:'Sıfatlar',icon:'🧱',ex:'Tangible improvement.'},
  {id:'infrastructure',en:'infrastructure',tr:'altyapı',ipa:'/ˈɪn.frəˌstrʌk.tʃər/',level:'C1',cat:'Yapı',icon:'🏗️',ex:'The country needs better infrastructure.'},
  {id:'reimagining',en:'reimagining',tr:'yeniden hayal etme',ipa:'/ˌriː.ɪˈmædʒ.ɪn.ɪŋ/',level:'C1',cat:'Zihin',icon:'💭',ex:'A complete reimagining.'},
  {id:'necessitates',en:'necessitates',tr:'gerektirir',ipa:'/nəˈses.ɪ.teɪts/',level:'C2',cat:'Eylemler',icon:'❗',ex:'This necessitates action.'},
  {id:'urbanization',en:'urbanization',tr:'şehirleşme',ipa:'/ˌɜː.bə.naɪˈzeɪ.ʃən/',level:'B2',cat:'Yerler',icon:'🏙️',ex:'Modern urbanization.'},
  {id:'beauty',en:'beauty',tr:'güzellik',ipa:'/ˈbjuː.ti/',level:'A2',cat:'Sıfatlar',icon:'✨',ex:'Natural beauty.'},
  {id:'fragile',en:'fragile',tr:'kırılgan',ipa:'/ˈfrædʒ.aɪl/',level:'B2',cat:'Sıfatlar',icon:'🏺',ex:'Fragile ecosystems.'},
  {id:'humanity',en:'humanity',tr:'insanlık',ipa:'/hjuːˈmæn.ə.ti/',level:'C1',cat:'Sosyal',icon:'🌍',ex:'Threat to all humanity.'},
  {id:'acceleration',en:'acceleration',tr:'hızlanma',ipa:'/əkˌsel.əˈreɪ.ʃən/',level:'C1',cat:'Fizik',icon:'🚀',ex:'Rapid acceleration.'},
  {id:'exploration',en:'exploration',tr:'keşif',ipa:'/ˌek.spləˈreɪ.ʃən/',level:'B2',cat:'Uzay',icon:'🔭',ex:'Space exploration.'},
  {id:'geopolitical',en:'geopolitical',tr:'jeopolitik',ipa:'/ˌdʒiː.əʊ.pəˈlɪt.ɪ.kəl/',level:'C1',cat:'Sosyal',icon:'🗺️',ex:'Geopolitical competition.'},
  {id:'breakthroughs',en:'breakthroughs',tr:'buluşlar/atılımlar',ipa:'/ˈbreɪk.θruːz/',level:'C1',cat:'Zihin',icon:'💡',ex:'Scientific breakthroughs.'},
  {id:'contamination',en:'contamination',tr:'kirlenme',ipa:'/kənˌtæm.ɪˈneɪ.ʃən/',level:'C1',cat:'Doğa',icon:'☣️',ex:'Prevent contamination.'},
  {id:'frontier',en:'frontier',tr:'sınır',ipa:'/ˈfrʌn.tɪər/',level:'C1',cat:'Yerler',icon:'🚧',ex:'The final frontier.'},
  {id:'overwhelmed',en:'overwhelmed',tr:'bunaltılmış/boğulmuş',ipa:'/ˌəʊ.vəˈwelmd/',level:'C1',cat:'Duygular',icon:'😵',ex:'Felt overwhelmed.'},
  {id:'perceived',en:'perceived',tr:'algılanan',ipa:'/pəˈsiːvd/',level:'C1',cat:'Zihin',icon:'👀',ex:'Perceived value.'},
  {id:'paralysis',en:'paralysis',tr:'felç',ipa:'/pəˈræl.ə.sɪs/',level:'C2',cat:'Sağlık',icon:'🦽',ex:'Decision paralysis.'},
  {id:'phenomenon',en:'phenomenon',tr:'olgu/fenomen',ipa:'/fəˈnɒm.ɪ.nən/',level:'C1',cat:'Doğa',icon:'✨',ex:'Strange phenomenon.'},
  {id:'dissatisfaction',en:'dissatisfaction',tr:'memnuniyetsizlik',ipa:'/ˌdɪsˌsæt.ɪsˈfæk.ʃən/',level:'C1',cat:'Duygular',icon:'😒',ex:'Customer dissatisfaction.'},
  {id:'inhibit',en:'inhibit',tr:'engellemek',ipa:'/ɪnˈhɪb.ɪt/',level:'C1',cat:'Eylemler',icon:'🚫',ex:'Inhibit our ability.'},
  {id:'burden',en:'burden',tr:'yük',ipa:'/ˈbɜː.dən/',level:'C1',cat:'Soyut',icon:'🏋️',ex:'Mental burden.'},
  {id:'scrutiny',en:'scrutiny',tr:'inceleme/denetim',ipa:'/ˈskruː.tɪ.ni/',level:'C1',cat:'Zihin',icon:'🔍',ex:'Close scrutiny.'},
  {id:'footprint',en:'footprint',tr:'ayak izi',ipa:'/ˈfʊt.prɪnt/',level:'B2',cat:'Doğa',icon:'👣',ex:'Environmental footprint.'},
  {id:'biodiversity',en:'biodiversity',tr:'biyoçeşitlilik',ipa:'/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/',level:'C1',cat:'Doğa',icon:'🐾',ex:'Preservation of biodiversity.'},
  {id:'regulations',en:'regulations',tr:'düzenlemeler/kurallar',ipa:'/ˌreɡ.jəˈleɪ.ʃənz/',level:'B2',cat:'Hukuk',icon:'📜',ex:'Strict regulations.'},
  {id:'intervention',en:'intervention',tr:'müdahale',ipa:'/ˌɪn.təˈven.ʃən/',level:'C1',cat:'Sosyal',icon:'✋',ex:'Significant intervention.'},
  {id:'consensus',en:'consensus',tr:'fikir birliği/uzlaşı',ipa:'/kənˈsen.səs/',level:'C1',cat:'Sosyal',icon:'⚖️',ex:'Reach a consensus.'},
  {id:'unprecedented',en:'unprecedented',tr:'eşi görülmemiş',ipa:'/ʌnˈpres.ɪ.den.tɪd/',level:'C1',cat:'Sıfatlar',icon:'🤯',ex:'Unprecedented rate.'},
  {id:'innovative',en:'innovative',tr:'yenilikçi',ipa:'/ˈɪn.ə.veɪ.tɪv/',level:'B2',cat:'Teknoloji',icon:'💡',ex:'Innovative projects.'},
  {id:'meticulously',en:'meticulously',tr:'titizlikle',ipa:'/məˈtɪk.jə.ləs.li/',level:'C1',cat:'Zarf',icon:'🧐',ex:'Prepared meticulously.'},
  {id:'impression',en:'impression',tr:'izlenim',ipa:'/ɪmˈpreʃ.ən/',level:'B2',cat:'Zihin',icon:'🧠',ex:'Good impression.'},
  {id:'corporate',en:'corporate',tr:'kurumsal',ipa:'/ˈkɔː.pər.ət/',level:'B2',cat:'İş',icon:'🏢',ex:'Corporate office.'},
  {id:'friendly',en:'friendly',tr:'dost canlısı',ipa:'/ˈfrend.li/',level:'A1',cat:'Kişilik',icon:'🤝',ex:'Friendly man.'},
  {id:'building',en:'building',tr:'bina',ipa:'/ˈbɪl.dɪŋ/',level:'A1',cat:'Yerler',icon:'🏢',ex:'Tall building.'},
  {id:'exciting',en:'exciting',tr:'heyecan verici',ipa:'/ɪkˈsaɪ.tɪŋ/',level:'A1',cat:'Duygular',icon:'🤩',ex:'Exciting day.'},
  {id:'healthy',en:'healthy',tr:'sağlıklı',ipa:'/ˈhel.θi/',level:'A2',cat:'Sağlık',icon:'💪',ex:'Healthy breakfast.'},
  {id:'nervous',en:'nervous',tr:'gergin',ipa:'/ˈnɜːr.vəs/',level:'A2',cat:'Duygular',icon:'😟',ex:'Maria was nervous.'},
  {id:'room',en:'room',tr:'oda',ipa:'/ruːm/',level:'A1',cat:'Yerler',icon:'🏠',ex:'Small room.'},
  {id:'fridge',en:'fridge',tr:'buzdolabı',ipa:'/frɪdʒ/',level:'A1',cat:'Ev',icon:'🧊',ex:'Inside the fridge.'},
  {id:'pocket',en:'pocket',tr:'cep',ipa:'/ˈpɒk.ɪt/',level:'A2',cat:'Giyim',icon:'👖',ex:'Jacket pocket.'},
  {id:'metal',en:'metal',tr:'metal',ipa:'/ˈmet.əl/',level:'A2',cat:'Nesneler',icon:'🔩',ex:'Something metal.'},
  {id:'birthday',en:'birthday',tr:'doğum günü',ipa:'/ˈbɜːrθ.deɪ/',level:'A1',cat:'Zaman',icon:'🎂',ex:'Tenth birthday.'},
  {id:'balloons',en:'balloons',tr:'balonlar',ipa:'/bəˈluːnz/',level:'A1',cat:'Eğlence',icon:'🎈',ex:'Colorful balloons.'},
  {id:'flowers',en:'flowers',tr:'çiçekler',ipa:'/ˈflaʊ.ərz/',level:'A1',cat:'Doğa',icon:'🌸',ex:'Beautiful flowers.'},
  {id:'kitchen',en:'kitchen',tr:'mutfak',ipa:'/ˈkɪtʃ.ən/',level:'A1',cat:'Ev',icon:'🍳',ex:'Spent morning in the kitchen.'},
  {id:'song',en:'song',tr:'şarkı',ipa:'/sɒŋ/',level:'A1',cat:'Sanat',icon:'🎵',ex:'Happy song.'},
  {id:'presents',en:'presents',tr:'hediyeler',ipa:'/ˈprez.ənts/',level:'A1',cat:'Eğlence',icon:'🎁',ex:'Received many presents.'},
  {id:'book',en:'book',tr:'kitap',ipa:'/bʊk/',level:'A1',cat:'Eğitim',icon:'📚',ex:'New book.'},
  {id:'toy',en:'toy',tr:'oyuncak',ipa:'/tɔɪ/',level:'A1',cat:'Eğlence',icon:'🧸',ex:'Cute toy.'},
  {id:'princess',en:'princess',tr:'prenses',ipa:'/ˌprɪnˈses/',level:'A2',cat:'İnsanlar',icon:'👑',ex:'Felt like a princess.'},
  {id:'surprise',en:'surprise',tr:'sürpriz',ipa:'/səˈpraɪz/',level:'A2',cat:'Duygular',icon:'😲',ex:'Thanked for the surprise.'},
  {id:'house',en:'house',tr:'ev',ipa:'/haʊs/',level:'A1',cat:'Yerler',icon:'🏠',ex:'Big house.'},
  {id:'garden',en:'garden',tr:'bahçe',ipa:'/ˈɡɑː.dən/',level:'A1',cat:'Yerler',icon:'🌳',ex:'Beautiful garden.'},
  {id:'shoes',en:'shoes',tr:'ayakkabı',ipa:'/ʃuːz/',level:'A1',cat:'Giyim',icon:'👞',ex:'Puts on her shoes.'},
  {id:'fresh',en:'fresh',tr:'taze',ipa:'/freʃ/',level:'A1',cat:'Sıfatlar',icon:'🍃',ex:'Fresh air.'},
  {id:'trees',en:'trees',tr:'ağaçlar',ipa:'/triːz/',level:'A1',cat:'Doğa',icon:'🌳',ex:'Tall green trees.'},
  {id:'door',en:'door',tr:'kapı',ipa:'/dɔːr/',level:'A1',cat:'Nesneler',icon:'🚪',ex:'Small wooden door.'},
  {id:'birds',en:'birds',tr:'kuşlar',ipa:'/bɜːrdz/',level:'A1',cat:'Hayvanlar',icon:'🐦',ex:'Birds singing.'},
  {id:'butterflies',en:'butterflies',tr:'kelebekler',ipa:'/ˈbʌt.ə.flaɪz/',level:'A2',cat:'Hayvanlar',icon:'🦋',ex:'Butterflies flying.'},
  {id:'place',en:'place',tr:'yer',ipa:'/pleɪs/',level:'A1',cat:'Yerler',icon:'📍',ex:'Favorite place.'},
  {id:'books',en:'books',tr:'kitaplar',ipa:'/bʊks/',level:'A1',cat:'Eğitim',icon:'📚',ex:'Read her books.'},
  {id:'relax',en:'relax',tr:'rahatlamak',ipa:'/rɪˈlæks/',level:'A2',cat:'Eylemler',icon:'😌',ex:'Place to relax.'},
  {id:'home',en:'home',tr:'ev',ipa:'/həʊm/',level:'A1',cat:'Yerler',icon:'🏠',ex:'Stay home.'},
  {id:'warm',en:'warm',tr:'sıcak/ılık',ipa:'/wɔːm/',level:'A2',cat:'Doğa',icon:'🌡️',ex:'Stay warm.'},
  {id:'peaceful',en:'peaceful',tr:'huzurlu',ipa:'/ˈpiːs.fəl/',level:'B1',cat:'Sıfatlar',icon:'🕊️',ex:'Felt very peaceful.'},
  {id:'film',en:'film',tr:'film',ipa:'/fɪlm/',level:'A1',cat:'Sanat',icon:'🎬',ex:'Watched a film.'},
  {id:'cat',en:'cat',tr:'kedi',ipa:'/kæt/',level:'A1',cat:'Hayvanlar',icon:'🐱',ex:'With his cat.'},
  {id:'sleepy',en:'sleepy',tr:'uykulu',ipa:'/ˈsliː.pi/',level:'A2',cat:'Duygular',icon:'🥱',ex:'Cat was very sleepy.'},
  {id:'cloudy',en:'cloudy',tr:'bulutlu',ipa:'/ˈklaʊ.di/',level:'A2',cat:'Doğa',icon:'☁️',ex:'Cloudy outside.'},
  {id:'skills',en:'skills',tr:'beceriler',ipa:'/skɪlz/',level:'A2',cat:'İş',icon:'🎯',ex:'Technical skills.'},
  {id:'confidence',en:'confidence',tr:'güven',ipa:'/ˈkɒn.fɪ.dəns/',level:'B2',cat:'Zihin',icon:'🦁',ex:'Answered with confidence.'},
  {id:'team',en:'team',tr:'ekip',ipa:'/tiːm/',level:'A2',cat:'İş',icon:'👥',ex:'Diverse team.'},
  {id:'achievement',en:'achievement',tr:'başarı',ipa:'/əˈtʃiːv.mənt/',level:'B1',cat:'İş',icon:'🏆',ex:'Sense of achievement.'},
  {id:'communication',en:'communication',tr:'iletişim',ipa:'/kəˌmjuː.nɪˈkeɪ.ʃən/',level:'B1',cat:'Sosyal',icon:'🗣️',ex:'Clear communication.'},
  {id:'position',en:'position',tr:'konum/iş pozisyonu',ipa:'/pəˈzɪʃ.ən/',level:'B1',cat:'İş',icon:'📍',ex:'Optimistic about the position.'},
  {id:'growth',en:'growth',tr:'büyüme',ipa:'/ɡrəʊθ/',level:'B1',cat:'İş',icon:'📈',ex:'Future growth.'},
  {id:'flight',en:'flight',tr:'uçuş',ipa:'/flaɪt/',level:'A2',cat:'Seyahat',icon:'✈️',ex:'Flight was cancelled.'},
  {id:'cancelled',en:'cancelled',tr:'iptal edildi',ipa:'/ˈkæn.səld/',level:'B1',cat:'Günlük',icon:'❌',ex:'Flight cancelled.'},
  {id:'snow',en:'snow',tr:'kar',ipa:'/snəʊ/',level:'A1',cat:'Doğa',icon:'❄️',ex:'Heavy snow.'},
  {id:'responsible',en:'responsible',tr:'sorumlu',ipa:'/rɪˈspɒn.sə.bəl/',level:'B1',cat:'Kişilik',icon:'🧑‍⚖️',ex:'Responsible for the delay.'},
  {id:'voucher',en:'voucher',tr:'kupon',ipa:'/ˈvaʊ.tʃər/',level:'B2',cat:'Finans',icon:'🎫',ex:'Provided her with a voucher.'},
  {id:'delicious',en:'delicious',tr:'lezzetli',ipa:'/dɪˈlɪʃ.əs/',level:'A2',cat:'Yiyecek',icon:'🤤',ex:'Delicious meal.'},
  {id:'advantages',en:'advantages',tr:'avantajlar',ipa:'/ədˈvɑːn.tɪdʒɪz/',level:'B1',cat:'Soyut',icon:'✅',ex:'Several advantages.'},
  {id:'flexibility',en:'flexibility',tr:'esneklik',ipa:'/ˌflek.səˈbɪl.ə.ti/',level:'B2',cat:'Soyut',icon:'🤸',ex:'Increased flexibility.'},
  {id:'commuting',en:'commuting',tr:'işe gidip gelme',ipa:'/kəˈmjuː.tɪŋ/',level:'B2',cat:'Eylemler',icon:'🚆',ex:'Commuting time.'},
  {id:'isolation',en:'isolation',tr:'yalnızlık',ipa:'/ˌaɪ.səlˈeɪ.ʃən/',level:'C1',cat:'Sosyal',icon:'🏝️',ex:'Social isolation.'},
  {id:'tools',en:'tools',tr:'araçlar',ipa:'/tuːlz/',level:'A2',cat:'Nesneler',icon:'🛠️',ex:'Digital tools.'},
  {id:'industries',en:'industries',tr:'endüstriler',ipa:'/ˈɪn.də.striz/',level:'B2',cat:'İş',icon:'🏭',ex:'Many industries.'},
  {id:'nutrition',en:'nutrition',tr:'beslenme',ipa:'/njuːˈtrɪʃ.ən/',level:'B2',cat:'Sağlık',icon:'🍎',ex:'Good nutrition reduces risk.'},
  {id:'diseases',en:'diseases',tr:'hastalıklar',ipa:'/dɪˈziːzɪz/',level:'B2',cat:'Sağlık',icon:'🦠',ex:'Chronic diseases.'},
  {id:'recover',en:'recover',tr:'iyileşmek',ipa:'/rɪˈkʌv.ər/',level:'B1',cat:'Eylemler',icon:'🩹',ex:'Allows the body to recover.'},
  {id:'traditions',en:'traditions',tr:'gelenekler',ipa:'/trəˈdɪʃ.ənz/',level:'B1',cat:'Kültür',icon:'🏺',ex:'Shared unique traditions.'},
  {id:'customs',en:'customs',tr:'adetler',ipa:'/ˈkʌs.təmz/',level:'B1',cat:'Kültür',icon:'🛂',ex:'Diverse customs.'},
  {id:'differences',en:'differences',tr:'farklılıklar',ipa:'/ˈdɪf.ər.ənsɪz/',level:'A2',cat:'Soyut',icon:'↔️',ex:'Despite their differences.'},
  {id:'discrepancies',en:'discrepancies',tr:'çelişkiler/farklılıklar',ipa:'/dɪˈskrep.ən.siz/',level:'C1',cat:'Zihin',icon:'⚖️',ex:'Cultural discrepancies.'},
  {id:'accountability',en:'accountability',tr:'hesap verebilirlik',ipa:'/əˌkaʊn.təˈbɪl.ə.ti/',level:'C1',cat:'Sosyal',icon:'⚖️',ex:'Accountability of systems.'},
  {id:'inequalities',en:'inequalities',tr:'eşitsizlikler',ipa:'/ˌɪn.ɪˈkwɒl.ə.tiz/',level:'C1',cat:'Sosyal',icon:'⚖️',ex:'Exacerbate inequalities.'},
  {id:'emissions',en:'emissions',tr:'emisyonlar',ipa:'/iˈmɪʃ.ənz/',level:'C1',cat:'Doğa',icon:'💨',ex:'Carbon emissions.'},
  {id:'ecosystems',en:'ecosystems',tr:'ekosistemler',ipa:'/ˈiː.kəʊˌsɪs.təmz/',level:'C1',cat:'Doğa',icon:'🌿',ex:'Planet\'s ecosystems.'},
  {id:'implications',en:'implications',tr:'sonuçlar',ipa:'/ˌɪm.plɪˈkeɪ.ʃənz/',level:'C1',cat:'Zihin',icon:'🔗',ex:'Complex implications.'},
  {id:'conundrums',en:'conundrums',tr:'bilmeceler',ipa:'/kəˈnʌn.drəmz/',level:'C2',cat:'Zihin',icon:'🧩',ex:'Ethical conundrums.'},
  {id:'tensions',en:'tensions',tr:'gerilimler',ipa:'/ˈten.ənz/',level:'C1',cat:'Sosyal',icon:'⚡',ex:'Global tensions.'}
];

let dataContent = content;
const wordsStr = missingWordsData.map(w => `  {id:'${w.id}',en:'${w.en}',tr:'${w.tr}',ipa:"${w.ipa}",level:'${w.level}',cat:'${w.cat}',icon:'${w.icon}',ex:'${w.ex.replace(/'/g, "\\'")}'},`).join('\n');

dataContent = dataContent.replace('  // ─── Missing Story Vocabulary ───────────────────────────────────────────', '  // ─── Missing Story Vocabulary ───────────────────────────────────────────\n' + wordsStr);

fs.writeFileSync('js/data.js', dataContent);
