const fs = require('fs');
const path = require('path');
const raw = fs.readFileSync(path.join(__dirname, '../js/data.js'), 'utf8');
const arrStr = raw.slice(raw.indexOf('['), raw.lastIndexOf(']') + 1);
const WORDS = eval('(' + arrStr + ')');
const existing = new Set(WORDS.map(w => w.en.toLowerCase().trim()));

const newA1 = [
  // ── More Verbs ────────────────────────────────────────────────────────────
  { en:'ask',        tr:'sormak',          ipa:'/ɑːsk/',           cat:'Fiiller',   icon:'❓', ex:'Ask the teacher if you don\'t know.' },
  { en:'answer',     tr:'cevaplamak',      ipa:'/ˈɑːnsə/',        cat:'Fiiller',   icon:'💬', ex:'Answer the question carefully.' },
  { en:'tell',       tr:'anlatmak / söylemek',ipa:'/tel/',         cat:'Fiiller',   icon:'🗣️', ex:'Tell me your name.' },
  { en:'say',        tr:'söylemek',        ipa:'/seɪ/',            cat:'Fiiller',   icon:'💬', ex:'What did she say?' },
  { en:'talk',       tr:'konuşmak',        ipa:'/tɔːk/',           cat:'Fiiller',   icon:'🗣️', ex:'Let\'s talk about the problem.' },
  { en:'describe',   tr:'tarif etmek / tanımlamak',ipa:'/dɪˈskraɪb/',cat:'Fiiller',icon:'🖊️', ex:'Describe the picture.' },
  { en:'explain',    tr:'açıklamak',       ipa:'/ɪkˈspleɪn/',     cat:'Fiiller',   icon:'💡', ex:'Can you explain the rules?' },
  { en:'repeat',     tr:'tekrarlamak',     ipa:'/rɪˈpiːt/',       cat:'Fiiller',   icon:'🔁', ex:'Please repeat the question.' },
  { en:'think',      tr:'düşünmek',        ipa:'/θɪŋk/',           cat:'Fiiller',   icon:'🤔', ex:'I think this is the right answer.' },
  { en:'know',       tr:'bilmek',          ipa:'/nəʊ/',            cat:'Fiiller',   icon:'💡', ex:'Do you know his name?' },
  { en:'learn',      tr:'öğrenmek',        ipa:'/lɜːn/',           cat:'Fiiller',   icon:'📚', ex:'She is learning to drive.' },
  { en:'teach',      tr:'öğretmek',        ipa:'/tiːtʃ/',          cat:'Fiiller',   icon:'🎓', ex:'He teaches maths at a school.' },
  { en:'study',      tr:'çalışmak / ders çalışmak',ipa:'/ˈstʌdi/',cat:'Fiiller',   icon:'📖', ex:'I need to study for the exam.' },
  { en:'practise',   tr:'pratik yapmak',   ipa:'/ˈpræktɪs/',      cat:'Fiiller',   icon:'🔄', ex:'Practise speaking every day.' },
  { en:'try',        tr:'denemek',         ipa:'/traɪ/',           cat:'Fiiller',   icon:'💪', ex:'Try your best.' },
  { en:'give',       tr:'vermek',          ipa:'/ɡɪv/',            cat:'Fiiller',   icon:'🤲', ex:'Give me the pen, please.' },
  { en:'take',       tr:'almak',           ipa:'/teɪk/',           cat:'Fiiller',   icon:'✋', ex:'Take an umbrella — it may rain.' },
  { en:'get',        tr:'almak / elde etmek',ipa:'/ɡet/',          cat:'Fiiller',   icon:'📦', ex:'I got a new phone for my birthday.' },
  { en:'put',        tr:'koymak',          ipa:'/pʊt/',            cat:'Fiiller',   icon:'📦', ex:'Put the book on the table.' },
  { en:'bring',      tr:'getirmek',        ipa:'/brɪŋ/',           cat:'Fiiller',   icon:'📦', ex:'Bring your notebook to class.' },
  { en:'send',       tr:'göndermek',       ipa:'/send/',           cat:'Fiiller',   icon:'📨', ex:'Send me a message later.' },
  { en:'receive',    tr:'almak (teslim)',   ipa:'/rɪˈsiːv/',       cat:'Fiiller',   icon:'📬', ex:'Did you receive my email?' },
  { en:'keep',       tr:'tutmak / saklamak',ipa:'/kiːp/',          cat:'Fiiller',   icon:'🔒', ex:'Keep the receipt.' },
  { en:'hold',       tr:'tutmak',          ipa:'/həʊld/',          cat:'Fiiller',   icon:'🤲', ex:'Hold the door open for me.' },
  { en:'turn',       tr:'dönmek / çevirmek',ipa:'/tɜːn/',         cat:'Fiiller',   icon:'🔄', ex:'Turn left at the traffic lights.' },
  { en:'move',       tr:'hareket etmek / taşınmak',ipa:'/muːv/',  cat:'Fiiller',   icon:'🔄', ex:'Please move your bag.' },
  { en:'use',        tr:'kullanmak',       ipa:'/juːz/',           cat:'Fiiller',   icon:'🔧', ex:'You can use my pen.' },
  { en:'need',       tr:'ihtiyaç duymak',  ipa:'/niːd/',           cat:'Fiiller',   icon:'❗', ex:'I need some help.' },
  { en:'want',       tr:'istemek',         ipa:'/wɒnt/',           cat:'Fiiller',   icon:'✋', ex:'Do you want some tea?' },
  { en:'like',       tr:'beğenmek / sevmek',ipa:'/laɪk/',         cat:'Fiiller',   icon:'👍', ex:'I like chocolate ice cream.' },
  { en:'love',       tr:'sevmek / aşık olmak',ipa:'/lʌv/',        cat:'Fiiller',   icon:'❤️', ex:'She loves her family.' },
  { en:'hate',       tr:'nefret etmek',    ipa:'/heɪt/',           cat:'Fiiller',   icon:'😠', ex:'I hate getting up early.' },
  { en:'prefer',     tr:'tercih etmek',    ipa:'/prɪˈfɜː/',       cat:'Fiiller',   icon:'✅', ex:'I prefer coffee to tea.' },
  { en:'miss',       tr:'özlemek / kaçırmak',ipa:'/mɪs/',         cat:'Fiiller',   icon:'💔', ex:'She misses her friends.' },
  { en:'hope',       tr:'ummak / umut etmek',ipa:'/həʊp/',        cat:'Fiiller',   icon:'🌟', ex:'I hope you feel better soon.' },
  { en:'think of',   tr:'aklına gelmek',   ipa:'/θɪŋk ɒv/',       cat:'Fiiller',   icon:'💭', ex:'What do you think of this idea?' },
  { en:'look at',    tr:'bakmak',          ipa:'/lʊk æt/',        cat:'Fiiller',   icon:'👀', ex:'Look at the picture carefully.' },
  { en:'listen to',  tr:'dinlemek',        ipa:'/ˈlɪsən tuː/',    cat:'Fiiller',   icon:'👂', ex:'Listen to the teacher.' },
  { en:'look for',   tr:'aramak',          ipa:'/lʊk fɔː/',       cat:'Fiiller',   icon:'🔍', ex:'I am looking for my keys.' },
  { en:'come back',  tr:'geri gelmek',     ipa:'/kʌm bæk/',       cat:'Fiiller',   icon:'↩️', ex:'Come back before ten o\'clock.' },
  { en:'go back',    tr:'geri gitmek',     ipa:'/ɡəʊ bæk/',       cat:'Fiiller',   icon:'↩️', ex:'She went back to sleep.' },
  { en:'sit down',   tr:'oturmak',         ipa:'/sɪt daʊn/',      cat:'Fiiller',   icon:'🪑', ex:'Please sit down.' },
  { en:'stand up',   tr:'ayağa kalkmak',   ipa:'/stænd ʌp/',      cat:'Fiiller',   icon:'🧍', ex:'Stand up and say your name.' },
  { en:'turn on',    tr:'açmak',           ipa:'/tɜːn ɒn/',       cat:'Fiiller',   icon:'💡', ex:'Turn on the light.' },
  { en:'turn off',   tr:'kapatmak',        ipa:'/tɜːn ɒf/',       cat:'Fiiller',   icon:'💡', ex:'Turn off the TV and go to bed.' },
  { en:'come in',    tr:'içeri girmek',    ipa:'/kʌm ɪn/',        cat:'Fiiller',   icon:'🚪', ex:'Come in — the door is open.' },
  { en:'go out',     tr:'dışarı çıkmak',   ipa:'/ɡəʊ aʊt/',       cat:'Fiiller',   icon:'🚪', ex:'We go out every Friday.' },
  { en:'look up',    tr:'bakmak (yukarı/sözlükte)',ipa:'/lʊk ʌp/',cat:'Fiiller',   icon:'🔍', ex:'Look up the word in the dictionary.' },
  { en:'write down', tr:'not almak',       ipa:'/raɪt daʊn/',     cat:'Fiiller',   icon:'✏️', ex:'Write down the new words.' },
  { en:'switch on',  tr:'açmak',           ipa:'/swɪtʃ ɒn/',      cat:'Fiiller',   icon:'🔌', ex:'Switch on the computer.' },
  { en:'switch off', tr:'kapatmak',        ipa:'/swɪtʃ ɒf/',      cat:'Fiiller',   icon:'🔌', ex:'Switch off your phone in class.' },
  // ── More Adjectives ───────────────────────────────────────────────────────
  { en:'great',      tr:'harika',          ipa:'/ɡreɪt/',          cat:'Sıfatlar',  icon:'⭐', ex:'That is a great idea.' },
  { en:'wonderful',  tr:'muhteşem',        ipa:'/ˈwʌndəfəl/',     cat:'Sıfatlar',  icon:'🌟', ex:'We had a wonderful holiday.' },
  { en:'terrible',   tr:'korkunç / berbat',ipa:'/ˈterɪbəl/',      cat:'Sıfatlar',  icon:'😱', ex:'The weather was terrible yesterday.' },
  { en:'horrible',   tr:'berbat / korkunç',ipa:'/ˈhɒrɪbəl/',      cat:'Sıfatlar',  icon:'😨', ex:'The smell was horrible.' },
  { en:'excellent',  tr:'mükemmel',        ipa:'/ˈeksələnt/',     cat:'Sıfatlar',  icon:'✨', ex:'Her English is excellent.' },
  { en:'perfect',    tr:'mükemmel',        ipa:'/ˈpɜːfɪkt/',      cat:'Sıfatlar',  icon:'💯', ex:'That is a perfect answer.' },
  { en:'favourite',  tr:'en sevilen / favori',ipa:'/ˈfeɪvərɪt/', cat:'Sıfatlar',  icon:'⭐', ex:'What is your favourite food?' },
  { en:'special',    tr:'özel',            ipa:'/ˈspeʃəl/',       cat:'Sıfatlar',  icon:'🌟', ex:'Today is a special day.' },
  { en:'important',  tr:'önemli',          ipa:'/ɪmˈpɔːtənt/',   cat:'Sıfatlar',  icon:'❗', ex:'Eating well is very important.' },
  { en:'interesting',tr:'ilginç',          ipa:'/ˈɪntrestɪŋ/',   cat:'Sıfatlar',  icon:'🤔', ex:'This is an interesting book.' },
  { en:'boring',     tr:'sıkıcı',          ipa:'/ˈbɔːrɪŋ/',       cat:'Sıfatlar',  icon:'😴', ex:'The film was really boring.' },
  { en:'funny',      tr:'komik',           ipa:'/ˈfʌni/',          cat:'Sıfatlar',  icon:'😄', ex:'He told a very funny joke.' },
  { en:'serious',    tr:'ciddi',           ipa:'/ˈsɪəriəs/',      cat:'Sıfatlar',  icon:'😐', ex:'She is very serious about her work.' },
  { en:'true',       tr:'doğru / gerçek',  ipa:'/truː/',           cat:'Sıfatlar',  icon:'✅', ex:'Is that story true?' },
  { en:'false',      tr:'yanlış / sahte',  ipa:'/fɔːls/',          cat:'Sıfatlar',  icon:'❌', ex:'That information is false.' },
  { en:'modern',     tr:'modern',          ipa:'/ˈmɒdən/',        cat:'Sıfatlar',  icon:'🏙️', ex:'They live in a modern flat.' },
  { en:'traditional',tr:'geleneksel',      ipa:'/trəˈdɪʃənəl/',  cat:'Sıfatlar',  icon:'🏛️', ex:'They cooked a traditional meal.' },
  { en:'popular',    tr:'popüler',         ipa:'/ˈpɒpjʊlə/',      cat:'Sıfatlar',  icon:'⭐', ex:'Football is the most popular sport.' },
  { en:'usual',      tr:'olağan / her zamanki',ipa:'/ˈjuːʒʊəl/',  cat:'Sıfatlar',  icon:'🔄', ex:'I had my usual breakfast.' },
  { en:'normal',     tr:'normal',          ipa:'/ˈnɔːməl/',       cat:'Sıfatlar',  icon:'😐', ex:'That is completely normal.' },
  { en:'possible',   tr:'mümkün',          ipa:'/ˈpɒsɪbəl/',      cat:'Sıfatlar',  icon:'✅', ex:'Is it possible to change the ticket?' },
  { en:'sure',       tr:'emin',            ipa:'/ʃʊə/',            cat:'Sıfatlar',  icon:'✅', ex:'Are you sure about that?' },
  { en:'afraid',     tr:'korkmuş',         ipa:'/əˈfreɪd/',       cat:'Duygular',  icon:'😱', ex:'She is afraid of the dark.' },
  { en:'worried',    tr:'endişeli',        ipa:'/ˈwʌrid/',        cat:'Duygular',  icon:'😟', ex:'He is worried about the exam.' },
  { en:'excited',    tr:'heyecanlı',       ipa:'/ɪkˈsaɪtɪd/',    cat:'Duygular',  icon:'😆', ex:'She was excited about the trip.' },
  { en:'proud',      tr:'gururlu',         ipa:'/praʊd/',          cat:'Duygular',  icon:'😊', ex:'I am proud of you.' },
  { en:'lucky',      tr:'şanslı',          ipa:'/ˈlʌki/',          cat:'Sıfatlar',  icon:'🍀', ex:'You are so lucky!' },
  // ── More Nouns ────────────────────────────────────────────────────────────
  { en:'air',        tr:'hava',            ipa:'/eə/',             cat:'Doğa',      icon:'💨', ex:'The mountain air is fresh.' },
  { en:'fire',       tr:'ateş',            ipa:'/faɪə/',           cat:'Doğa',      icon:'🔥', ex:'There is a fire in the forest.' },
  { en:'earth',      tr:'dünya / toprak',  ipa:'/ɜːθ/',            cat:'Doğa',      icon:'🌍', ex:'The Earth goes around the sun.' },
  { en:'world',      tr:'dünya',           ipa:'/wɜːld/',          cat:'Genel',     icon:'🌍', ex:'She wants to travel the world.' },
  { en:'country',    tr:'ülke',            ipa:'/ˈkʌntri/',       cat:'Coğrafya',  icon:'🌍', ex:'She lives in a beautiful country.' },
  { en:'city',       tr:'şehir',           ipa:'/ˈsɪti/',          cat:'Coğrafya',  icon:'🏙️', ex:'They live in a big city.' },
  { en:'town',       tr:'kasaba',          ipa:'/taʊn/',           cat:'Coğrafya',  icon:'🏘️', ex:'I grew up in a small town.' },
  { en:'village',    tr:'köy',             ipa:'/ˈvɪlɪdʒ/',       cat:'Coğrafya',  icon:'🏡', ex:'She lives in a quiet village.' },
  { en:'north',      tr:'kuzey',           ipa:'/nɔːθ/',           cat:'Coğrafya',  icon:'🧭', ex:'The river is north of the city.' },
  { en:'south',      tr:'güney',           ipa:'/saʊθ/',           cat:'Coğrafya',  icon:'🧭', ex:'They drove south towards the sea.' },
  { en:'east',       tr:'doğu',            ipa:'/iːst/',           cat:'Coğrafya',  icon:'🧭', ex:'The sun rises in the east.' },
  { en:'west',       tr:'batı',            ipa:'/west/',           cat:'Coğrafya',  icon:'🧭', ex:'The sun sets in the west.' },
  { en:'centre',     tr:'merkez',          ipa:'/ˈsentə/',        cat:'Coğrafya',  icon:'🎯', ex:'The museum is in the city centre.' },
  { en:'capital',    tr:'başkent',         ipa:'/ˈkæpɪtəl/',      cat:'Coğrafya',  icon:'🏛️', ex:'Paris is the capital of France.' },
  { en:'office',     tr:'ofis',            ipa:'/ˈɒfɪs/',          cat:'İş',        icon:'🏢', ex:'He works in an office.' },
  { en:'job',        tr:'iş',              ipa:'/dʒɒb/',           cat:'İş',        icon:'💼', ex:'She has a good job.' },
  { en:'work',       tr:'iş / çalışma',    ipa:'/wɜːk/',           cat:'İş',        icon:'💼', ex:'He goes to work at eight.' },
  { en:'company',    tr:'şirket',          ipa:'/ˈkʌmpəni/',      cat:'İş',        icon:'🏢', ex:'She works for a big company.' },
  { en:'shop',       tr:'dükkan',          ipa:'/ʃɒp/',            cat:'Alışveriş', icon:'🛍️', ex:'Let\'s go to the shop.' },
  { en:'store',      tr:'mağaza',          ipa:'/stɔː/',           cat:'Alışveriş', icon:'🏪', ex:'She bought shoes from the store.' },
  { en:'market',     tr:'pazar / market',  ipa:'/ˈmɑːkɪt/',       cat:'Alışveriş', icon:'🛒', ex:'We buy vegetables at the market.' },
  { en:'bag',        tr:'çanta',           ipa:'/bæɡ/',            cat:'Genel',     icon:'👜', ex:'She put the book in her bag.' },
  { en:'box',        tr:'kutu',            ipa:'/bɒks/',           cat:'Genel',     icon:'📦', ex:'The chocolates are in a box.' },
  { en:'bottle',     tr:'şişe',            ipa:'/ˈbɒtl/',          cat:'Genel',     icon:'🍶', ex:'She drank a bottle of water.' },
  { en:'cup',        tr:'fincan',          ipa:'/kʌp/',            cat:'Genel',     icon:'☕', ex:'I had a cup of tea.' },
  { en:'glass',      tr:'bardak / cam',    ipa:'/ɡlɑːs/',          cat:'Genel',     icon:'🥛', ex:'She drank a glass of orange juice.' },
  { en:'plate',      tr:'tabak',           ipa:'/pleɪt/',          cat:'Genel',     icon:'🍽️', ex:'Wash the plates after dinner.' },
  { en:'bowl',       tr:'kase / kâse',     ipa:'/bəʊl/',           cat:'Genel',     icon:'🥣', ex:'She had a bowl of cereal.' },
  { en:'ticket',     tr:'bilet',           ipa:'/ˈtɪkɪt/',        cat:'Seyahat',   icon:'🎫', ex:'Have you bought your ticket?' },
  { en:'newspaper',  tr:'gazete',          ipa:'/ˈnjuːspeɪpə/',   cat:'Medya',     icon:'📰', ex:'He reads the newspaper every morning.' },
  { en:'magazine',   tr:'dergi',           ipa:'/ˌmæɡəˈziːn/',   cat:'Medya',     icon:'📖', ex:'She reads fashion magazines.' },
  { en:'film',       tr:'film',            ipa:'/fɪlm/',           cat:'Eğlence',   icon:'🎬', ex:'Let\'s watch a film tonight.' },
  { en:'song',       tr:'şarkı',           ipa:'/sɒŋ/',            cat:'Müzik',     icon:'🎵', ex:'She sang a beautiful song.' },
  { en:'game',       tr:'oyun',            ipa:'/ɡeɪm/',           cat:'Eğlence',   icon:'🎮', ex:'He likes to play video games.' },
  { en:'sport',      tr:'spor',            ipa:'/spɔːt/',          cat:'Spor',      icon:'⚽', ex:'What sport do you play?' },
  { en:'hobby',      tr:'hobi',            ipa:'/ˈhɒbi/',          cat:'Eğlence',   icon:'🎨', ex:'What is your hobby?' },
  { en:'story',      tr:'hikaye',          ipa:'/ˈstɔːri/',        cat:'Genel',     icon:'📖', ex:'Tell me a story.' },
  { en:'joke',       tr:'şaka',            ipa:'/dʒəʊk/',          cat:'Genel',     icon:'😄', ex:'He told a funny joke.' },
  { en:'dream',      tr:'rüya',            ipa:'/driːm/',          cat:'Genel',     icon:'💤', ex:'I had a strange dream last night.' },
  { en:'money',      tr:'para',            ipa:'/ˈmʌni/',          cat:'Genel',     icon:'💰', ex:'I don\'t have enough money.' },
  { en:'coin',       tr:'bozuk para',      ipa:'/kɔɪn/',           cat:'Genel',     icon:'🪙', ex:'She put a coin in her pocket.' },
  { en:'note',       tr:'banknot / not',   ipa:'/nəʊt/',           cat:'Genel',     icon:'💵', ex:'He paid with a twenty-pound note.' },
  { en:'card',       tr:'kart',            ipa:'/kɑːd/',           cat:'Genel',     icon:'💳', ex:'She paid by credit card.' },
  { en:'post',       tr:'posta / gönderi', ipa:'/pəʊst/',          cat:'İletişim',  icon:'📮', ex:'The post arrives at nine.' },
  { en:'letter',     tr:'mektup / harf',   ipa:'/ˈletə/',          cat:'İletişim',  icon:'✉️', ex:'She wrote a letter to her friend.' },
  { en:'envelope',   tr:'zarf',            ipa:'/ˈenvələʊp/',     cat:'İletişim',  icon:'✉️', ex:'Put the letter in the envelope.' },
  { en:'stamp',      tr:'pul',             ipa:'/stæmp/',          cat:'İletişim',  icon:'📮', ex:'You need a stamp to post a letter.' },
  { en:'umbrella',   tr:'şemsiye',         ipa:'/ʌmˈbrelə/',      cat:'Giysi',     icon:'☂️', ex:'Take an umbrella — it is raining.' },
  { en:'glasses',    tr:'gözlük',          ipa:'/ˈɡlɑːsɪz/',      cat:'Giysi',     icon:'👓', ex:'She wears glasses to read.' },
  { en:'watch',      tr:'kol saati',       ipa:'/wɒtʃ/',           cat:'Aksesuar',  icon:'⌚', ex:'He bought a new watch.' },
  { en:'ring',       tr:'yüzük',           ipa:'/rɪŋ/',            cat:'Aksesuar',  icon:'💍', ex:'She wore a gold ring.' },
  { en:'necklace',   tr:'kolye',           ipa:'/ˈneklɪs/',        cat:'Aksesuar',  icon:'📿', ex:'She put on a silver necklace.' },
  { en:'toy',        tr:'oyuncak',         ipa:'/tɔɪ/',            cat:'Genel',     icon:'🧸', ex:'The child played with her toys.' },
  { en:'teddy bear', tr:'oyuncak ayı',     ipa:'/ˈtedi beə/',      cat:'Genel',     icon:'🧸', ex:'She slept with her teddy bear.' },
  { en:'balloon',    tr:'balon',           ipa:'/bəˈluːn/',        cat:'Genel',     icon:'🎈', ex:'The birthday balloons were red and yellow.' },
  { en:'candle',     tr:'mum',             ipa:'/ˈkændl/',         cat:'Ev',        icon:'🕯️', ex:'She lit a candle.' },
  { en:'flower',     tr:'çiçek',           ipa:'/ˈflaʊə/',        cat:'Doğa',      icon:'🌸', ex:'He gave her a bunch of flowers.' },
  { en:'leaf',       tr:'yaprak',          ipa:'/liːf/',           cat:'Doğa',      icon:'🍃', ex:'The leaves turn yellow in autumn.' },
  { en:'branch',     tr:'dal',             ipa:'/brɑːntʃ/',        cat:'Doğa',      icon:'🌿', ex:'The cat sat on a branch.' },
  { en:'seed',       tr:'tohum',           ipa:'/siːd/',           cat:'Doğa',      icon:'🌱', ex:'Plant the seeds in spring.' },
  { en:'wood',       tr:'ahşap / tahta',   ipa:'/wʊd/',            cat:'Malzeme',   icon:'🪵', ex:'The table is made of wood.' },
  { en:'metal',      tr:'metal',           ipa:'/ˈmetl/',          cat:'Malzeme',   icon:'🔩', ex:'The gate is made of metal.' },
  { en:'plastic',    tr:'plastik',         ipa:'/ˈplæstɪk/',      cat:'Malzeme',   icon:'♻️', ex:'This box is made of plastic.' },
  { en:'glass',      tr:'cam',             ipa:'/ɡlɑːs/',          cat:'Malzeme',   icon:'🪟', ex:'The window is made of glass.' },
  { en:'paper',      tr:'kâğıt',           ipa:'/ˈpeɪpə/',        cat:'Malzeme',   icon:'📄', ex:'Write your name on the paper.' },
  { en:'gold',       tr:'altın',           ipa:'/ɡəʊld/',          cat:'Malzeme',   icon:'🥇', ex:'The ring is made of gold.' },
  { en:'silver',     tr:'gümüş',           ipa:'/ˈsɪlvə/',        cat:'Malzeme',   icon:'🥈', ex:'She wore a silver bracelet.' },
  { en:'cotton',     tr:'pamuk',           ipa:'/ˈkɒtən/',        cat:'Malzeme',   icon:'🧵', ex:'The shirt is made of cotton.' },
  { en:'wool',       tr:'yün',             ipa:'/wʊl/',            cat:'Malzeme',   icon:'🧶', ex:'The blanket is made of wool.' },
  { en:'electricity',tr:'elektrik',        ipa:'/ɪˌlekˈtrɪsɪti/', cat:'Teknoloji', icon:'⚡', ex:'The electricity went off last night.' },
  { en:'light',      tr:'ışık',            ipa:'/laɪt/',           cat:'Ev',        icon:'💡', ex:'Turn on the light — it is dark.' },
  { en:'shadow',     tr:'gölge',           ipa:'/ˈʃædəʊ/',        cat:'Doğa',      icon:'🌑', ex:'She stood in the shadow of the tree.' },
  { en:'noise',      tr:'gürültü / ses',   ipa:'/nɔɪz/',           cat:'Genel',     icon:'🔊', ex:'There was a loud noise outside.' },
  { en:'smell',      tr:'koku',            ipa:'/smel/',           cat:'Genel',     icon:'👃', ex:'I love the smell of fresh bread.' },
  // ── More Places ───────────────────────────────────────────────────────────
  { en:'classroom',  tr:'sınıf odası',     ipa:'/ˈklɑːsruːm/',    cat:'Okul',      icon:'🏫', ex:'There are thirty students in the classroom.' },
  { en:'playground', tr:'oyun alanı',      ipa:'/ˈpleɪɡraʊnd/',  cat:'Yerler',    icon:'🛝', ex:'The children play in the playground.' },
  { en:'garden',     tr:'bahçe',           ipa:'/ˈɡɑːdən/',       cat:'Ev',        icon:'🌻', ex:'She grows tomatoes in her garden.' },
  { en:'living room',tr:'oturma odası',    ipa:'/ˈlɪvɪŋ ruːm/',   cat:'Ev',        icon:'🛋️', ex:'The family watches TV in the living room.' },
  { en:'dining room',tr:'yemek odası',     ipa:'/ˈdaɪnɪŋ ruːm/',  cat:'Ev',        icon:'🍽️', ex:'We eat in the dining room.' },
  { en:'toilet',     tr:'tuvalet',         ipa:'/ˈtɔɪlɪt/',       cat:'Ev',        icon:'🚽', ex:'Where is the toilet, please?' },
  { en:'hall',       tr:'koridor / giriş', ipa:'/hɔːl/',           cat:'Ev',        icon:'🚪', ex:'Leave your shoes in the hall.' },
  { en:'entrance',   tr:'giriş',           ipa:'/ˈentrəns/',      cat:'Yerler',    icon:'🚪', ex:'Meet me at the entrance.' },
  { en:'exit',       tr:'çıkış',           ipa:'/ˈeksɪt/',        cat:'Yerler',    icon:'🚪', ex:'The exit is on the right.' },
  // ── Basic Grammar Words / Expressions ────────────────────────────────────
  { en:'about',      tr:'hakkında / yaklaşık',ipa:'/əˈbaʊt/',     cat:'Bağlaçlar', icon:'ℹ️', ex:'Tell me about your family.' },
  { en:'because',    tr:'çünkü',           ipa:'/bɪˈkɒz/',        cat:'Bağlaçlar', icon:'💬', ex:'I am happy because it is my birthday.' },
  { en:'but',        tr:'ama / fakat',     ipa:'/bʌt/',            cat:'Bağlaçlar', icon:'↔️', ex:'I like cats but I prefer dogs.' },
  { en:'or',         tr:'veya / ya da',    ipa:'/ɔː/',             cat:'Bağlaçlar', icon:'🔀', ex:'Would you like tea or coffee?' },
  { en:'and',        tr:'ve',              ipa:'/ænd/',            cat:'Bağlaçlar', icon:'➕', ex:'She speaks English and Spanish.' },
  { en:'so',         tr:'bu yüzden / çok', ipa:'/səʊ/',            cat:'Bağlaçlar', icon:'➡️', ex:'It was raining, so we stayed home.' },
  { en:'if',         tr:'eğer',            ipa:'/ɪf/',             cat:'Bağlaçlar', icon:'❓', ex:'If it rains, we will stay inside.' },
  { en:'when',       tr:'ne zaman',        ipa:'/wen/',            cat:'Bağlaçlar', icon:'⏰', ex:'When do you go to school?' },
  { en:'where',      tr:'nerede',          ipa:'/weə/',            cat:'Sorular',   icon:'📍', ex:'Where do you live?' },
  { en:'who',        tr:'kim',             ipa:'/huː/',            cat:'Sorular',   icon:'🙋', ex:'Who is your teacher?' },
  { en:'what',       tr:'ne',              ipa:'/wɒt/',            cat:'Sorular',   icon:'❓', ex:'What is your name?' },
  { en:'how',        tr:'nasıl',           ipa:'/haʊ/',            cat:'Sorular',   icon:'❓', ex:'How are you?' },
  { en:'why',        tr:'neden / niye',    ipa:'/waɪ/',            cat:'Sorular',   icon:'❓', ex:'Why are you late?' },
  { en:'which',      tr:'hangi',           ipa:'/wɪtʃ/',           cat:'Sorular',   icon:'☑️', ex:'Which colour do you prefer?' },
  { en:'whose',      tr:'kimin',           ipa:'/huːz/',           cat:'Sorular',   icon:'❓', ex:'Whose bag is this?' },
  { en:'all',        tr:'hepsi / tüm',     ipa:'/ɔːl/',            cat:'Niceleyiciler',icon:'🔢', ex:'All the students passed the test.' },
  { en:'some',       tr:'biraz / bazı',    ipa:'/sʌm/',            cat:'Niceleyiciler',icon:'🔢', ex:'Can I have some water?' },
  { en:'any',        tr:'herhangi bir',    ipa:'/ˈeni/',           cat:'Niceleyiciler',icon:'🔢', ex:'Do you have any questions?' },
  { en:'many',       tr:'çok (sayılabilir)',ipa:'/ˈmeni/',         cat:'Niceleyiciler',icon:'🔢', ex:'There are many books in the library.' },
  { en:'much',       tr:'çok (sayılamaz)', ipa:'/mʌtʃ/',           cat:'Niceleyiciler',icon:'🔢', ex:'How much does this cost?' },
  { en:'more',       tr:'daha fazla',      ipa:'/mɔː/',            cat:'Niceleyiciler',icon:'➕', ex:'Can I have some more water?' },
  { en:'less',       tr:'daha az',         ipa:'/les/',            cat:'Niceleyiciler',icon:'➖', ex:'Use less sugar in the recipe.' },
  { en:'very',       tr:'çok',             ipa:'/ˈveri/',          cat:'Zarflar',   icon:'‼️', ex:'This soup is very hot.' },
  { en:'too',        tr:'de / da / çok',   ipa:'/tuː/',            cat:'Zarflar',   icon:'➕', ex:'This bag is too heavy.' },
  { en:'enough',     tr:'yeterince',       ipa:'/ɪˈnʌf/',         cat:'Zarflar',   icon:'✅', ex:'I don\'t have enough time.' },
  { en:'just',       tr:'sadece / tam',    ipa:'/dʒʌst/',          cat:'Zarflar',   icon:'🎯', ex:'I just want a glass of water.' },
  { en:'only',       tr:'sadece',          ipa:'/ˈəʊnli/',        cat:'Zarflar',   icon:'1️⃣', ex:'There is only one ticket left.' },
  { en:'also',       tr:'ayrıca / da',     ipa:'/ˈɔːlsəʊ/',       cat:'Zarflar',   icon:'➕', ex:'She also speaks French.' },
  { en:'never',      tr:'hiçbir zaman',    ipa:'/ˈnevə/',          cat:'Zarflar',   icon:'🚫', ex:'I have never tried sushi.' },
  { en:'always',     tr:'her zaman',       ipa:'/ˈɔːlweɪz/',      cat:'Zarflar',   icon:'♾️', ex:'She always comes on time.' },
  { en:'sometimes',  tr:'bazen',           ipa:'/ˈsʌmtaɪmz/',     cat:'Zarflar',   icon:'🔄', ex:'I sometimes walk to work.' },
  { en:'often',      tr:'sık sık',         ipa:'/ˈɒfən/',          cat:'Zarflar',   icon:'🔄', ex:'How often do you exercise?' },
  { en:'usually',    tr:'genellikle',      ipa:'/ˈjuːʒʊəli/',     cat:'Zarflar',   icon:'🔄', ex:'I usually have toast for breakfast.' },
  { en:'really',     tr:'gerçekten',       ipa:'/ˈrɪəli/',        cat:'Zarflar',   icon:'‼️', ex:'This cake is really good.' },
  { en:'quite',      tr:'oldukça',         ipa:'/kwaɪt/',          cat:'Zarflar',   icon:'✅', ex:'It is quite warm today.' },
  { en:'nearly',     tr:'neredeyse',       ipa:'/ˈnɪəli/',        cat:'Zarflar',   icon:'🔜', ex:'It is nearly midnight.' },
  { en:'almost',     tr:'neredeyse / hemen hemen',ipa:'/ˈɔːlməʊst/',cat:'Zarflar', icon:'🔜', ex:'I have almost finished.' },
  { en:'together',   tr:'birlikte',        ipa:'/təˈɡeðə/',       cat:'Zarflar',   icon:'🤝', ex:'Let\'s work together on this.' },
  { en:'quickly',    tr:'hızlıca',         ipa:'/ˈkwɪkli/',       cat:'Zarflar',   icon:'⚡', ex:'She finished the test quickly.' },
  { en:'slowly',     tr:'yavaşça',         ipa:'/ˈsləʊli/',       cat:'Zarflar',   icon:'🐌', ex:'Please speak slowly.' },
  { en:'loudly',     tr:'yüksek sesle',    ipa:'/ˈlaʊdli/',       cat:'Zarflar',   icon:'📢', ex:'She sang loudly.' },
  { en:'quietly',    tr:'sessizce',        ipa:'/ˈkwaɪətli/',     cat:'Zarflar',   icon:'🤫', ex:'Please speak quietly.' },
  { en:'well',       tr:'iyi / iyice',     ipa:'/wel/',            cat:'Zarflar',   icon:'✅', ex:'She speaks English very well.' },
  { en:'badly',      tr:'kötü / kötüce',   ipa:'/ˈbædli/',        cat:'Zarflar',   icon:'❌', ex:'He plays guitar badly.' },
  { en:'hard',       tr:'çok / sıkı (zarf)',ipa:'/hɑːd/',         cat:'Zarflar',   icon:'💪', ex:'She works very hard.' },
  // ── Prepositions & Positions ──────────────────────────────────────────────
  { en:'inside',     tr:'içinde',          ipa:'/ˌɪnˈsaɪd/',      cat:'Edatlar',   icon:'📦', ex:'The cat is inside the box.' },
  { en:'outside',    tr:'dışarıda',        ipa:'/ˌaʊtˈsaɪd/',     cat:'Edatlar',   icon:'🌳', ex:'The children are playing outside.' },
  { en:'above',      tr:'üstünde',         ipa:'/əˈbʌv/',          cat:'Edatlar',   icon:'⬆️', ex:'The picture is above the sofa.' },
  { en:'below',      tr:'altında',         ipa:'/bɪˈləʊ/',        cat:'Edatlar',   icon:'⬇️', ex:'The temperature is below zero.' },
  { en:'opposite',   tr:'karşısında',      ipa:'/ˈɒpəzɪt/',      cat:'Edatlar',   icon:'↔️', ex:'The bank is opposite the post office.' },
  { en:'along',      tr:'boyunca',         ipa:'/əˈlɒŋ/',         cat:'Edatlar',   icon:'➡️', ex:'Walk along the river.' },
  { en:'past',       tr:'yanından geçerek',ipa:'/pɑːst/',         cat:'Edatlar',   icon:'➡️', ex:'Walk past the school and turn right.' },
  { en:'through',    tr:'içinden / boyunca',ipa:'/θruː/',          cat:'Edatlar',   icon:'➡️', ex:'Drive through the tunnel.' },
  { en:'across',     tr:'karşısına / çapraz',ipa:'/əˈkrɒs/',      cat:'Edatlar',   icon:'↔️', ex:'Walk across the bridge.' },
  { en:'around',     tr:'etrafında',       ipa:'/əˈraʊnd/',       cat:'Edatlar',   icon:'🔄', ex:'They sat around the table.' },
  { en:'between',    tr:'arasında',        ipa:'/bɪˈtwiːn/',      cat:'Edatlar',   icon:'↔️', ex:'The shop is between the bank and the café.' },
  { en:'among',      tr:'arasında (çok)',  ipa:'/əˈmʌŋ/',         cat:'Edatlar',   icon:'👥', ex:'She stood among her friends.' },
  { en:'during',     tr:'süresince / sırasında',ipa:'/ˈdjʊərɪŋ/', cat:'Edatlar',   icon:'⏱️', ex:'Please be quiet during the exam.' },
  { en:'until',      tr:'kadar (-e kadar)',ipa:'/ənˈtɪl/',        cat:'Edatlar',   icon:'⏳', ex:'Wait until I come back.' },
  { en:'before',     tr:'önce',            ipa:'/bɪˈfɔː/',        cat:'Edatlar',   icon:'⏪', ex:'Brush your teeth before bed.' },
  { en:'after',      tr:'sonra',           ipa:'/ˈɑːftə/',        cat:'Edatlar',   icon:'⏩', ex:'She called me after dinner.' },
  { en:'without',    tr:'olmadan',         ipa:'/wɪˈðaʊt/',       cat:'Edatlar',   icon:'🚫', ex:'Don\'t leave without your coat.' },
  { en:'like',       tr:'gibi',            ipa:'/laɪk/',           cat:'Edatlar',   icon:'🤝', ex:'She swims like a fish.' },
];

let added = 0, skipped = 0;
const toAdd = [];
for (const w of newA1) {
  const key = w.en.toLowerCase().trim();
  if (existing.has(key)) { skipped++; continue; }
  toAdd.push({
    id: w.en.toLowerCase().replace(/\s+/g,'_'),
    en: w.en, tr: w.tr, ipa: w.ipa, level: 'A1',
    cat: w.cat, icon: w.icon, ex: w.ex, syns: [], colloc: [],
  });
  existing.add(key);
  added++;
}

console.log('Added: ' + added + ', Skipped: ' + skipped);
const combined = WORDS.concat(toAdd);
const levels = {};
for (const w of combined) levels[w.level] = (levels[w.level]||0)+1;
console.log('Level counts:', JSON.stringify(levels));
fs.writeFileSync(path.join(__dirname,'../js/data.js'),
  'const WORDS = '+JSON.stringify(combined,null,2)+';\n');
console.log('Written.');
