const fs = require('fs');
const path = require('path');
const raw = fs.readFileSync(path.join(__dirname, '../js/data.js'), 'utf8');
const arrStr = raw.slice(raw.indexOf('['), raw.lastIndexOf(']') + 1);
const WORDS = eval('(' + arrStr + ')');
const existing = new Set(WORDS.map(w => w.en.toLowerCase().trim()));

const newA1 = [
  // ── Nationalities / demonyms ──────────────────────────────────────────────
  { en:'Turkish',    tr:'Türk / Türkçe',   ipa:'/ˈtɜːkɪʃ/',      cat:'Milliyetler',icon:'🇹🇷', ex:'She speaks Turkish fluently.' },
  { en:'English',    tr:'İngiliz / İngilizce',ipa:'/ˈɪŋɡlɪʃ/',   cat:'Milliyetler',icon:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', ex:'English is spoken all over the world.' },
  { en:'German',     tr:'Alman / Almanca',  ipa:'/ˈdʒɜːmən/',     cat:'Milliyetler',icon:'🇩🇪', ex:'She is learning German.' },
  { en:'French',     tr:'Fransız / Fransızca',ipa:'/frentʃ/',     cat:'Milliyetler',icon:'🇫🇷', ex:'He speaks a little French.' },
  { en:'Italian',    tr:'İtalyan / İtalyanca',ipa:'/ɪˈtæliən/',   cat:'Milliyetler',icon:'🇮🇹', ex:'She loves Italian food.' },
  { en:'Spanish',    tr:'İspanyol / İspanyolca',ipa:'/ˈspænɪʃ/', cat:'Milliyetler',icon:'🇪🇸', ex:'He speaks Spanish very well.' },
  { en:'Japanese',   tr:'Japon / Japonca',  ipa:'/ˌdʒæpəˈniːz/', cat:'Milliyetler',icon:'🇯🇵', ex:'They watched a Japanese film.' },
  { en:'Chinese',    tr:'Çinli / Çince',    ipa:'/ˌtʃaɪˈniːz/',  cat:'Milliyetler',icon:'🇨🇳', ex:'She is learning Chinese.' },
  { en:'Russian',    tr:'Rus / Rusça',      ipa:'/ˈrʌʃən/',       cat:'Milliyetler',icon:'🇷🇺', ex:'He studied Russian at university.' },
  // ── More Adjectives ───────────────────────────────────────────────────────
  { en:'angry',      tr:'kızgın',           ipa:'/ˈæŋɡri/',       cat:'Duygular',  icon:'😠', ex:'She was angry about the broken vase.' },
  { en:'surprised',  tr:'şaşırmış',         ipa:'/səˈpraɪzd/',    cat:'Duygular',  icon:'😲', ex:'He was surprised by the gift.' },
  { en:'scared',     tr:'korkmuş',          ipa:'/skeəd/',         cat:'Duygular',  icon:'😱', ex:'She was scared of the big dog.' },
  { en:'bored',      tr:'sıkılmış',         ipa:'/bɔːd/',          cat:'Duygular',  icon:'😑', ex:'He was bored at the party.' },
  { en:'nervous',    tr:'gergin / sinirli', ipa:'/ˈnɜːvəs/',      cat:'Duygular',  icon:'😬', ex:'She felt nervous before the exam.' },
  { en:'confused',   tr:'kafası karışık',   ipa:'/kənˈfjuːzd/',   cat:'Duygular',  icon:'😕', ex:'He was confused by the question.' },
  { en:'relaxed',    tr:'rahat / sakin',    ipa:'/rɪˈlækst/',     cat:'Duygular',  icon:'😌', ex:'She felt relaxed after the holiday.' },
  { en:'interested',  tr:'ilgili / meraklı', ipa:'/ˈɪntrestɪd/',  cat:'Duygular',  icon:'🧐', ex:'She is interested in learning about animals.' },
  { en:'pleased',    tr:'memnun',           ipa:'/pliːzd/',        cat:'Duygular',  icon:'😊', ex:'He was very pleased with his results.' },
  { en:'disappointed',tr:'hayal kırıklığına uğramış',ipa:'/ˌdɪsəˈpɔɪntɪd/',cat:'Duygular',icon:'😞', ex:'She was disappointed with the film.' },
  { en:'comfortable',tr:'rahat',            ipa:'/ˈkʌmftəbəl/',   cat:'Sıfatlar',  icon:'🛋️', ex:'The sofa is very comfortable.' },
  { en:'tasty',      tr:'lezzetli',         ipa:'/ˈteɪsti/',      cat:'Sıfatlar',  icon:'😋', ex:'The soup is very tasty.' },
  { en:'delicious',  tr:'nefis',            ipa:'/dɪˈlɪʃəs/',     cat:'Sıfatlar',  icon:'😋', ex:'The cake was absolutely delicious.' },
  { en:'fresh',      tr:'taze',             ipa:'/freʃ/',          cat:'Sıfatlar',  icon:'🌿', ex:'Buy fresh vegetables from the market.' },
  { en:'clean',      tr:'temiz',            ipa:'/kliːn/',         cat:'Sıfatlar',  icon:'✨', ex:'The kitchen is very clean.' },
  { en:'dirty',      tr:'kirli',            ipa:'/ˈdɜːti/',       cat:'Sıfatlar',  icon:'🪣', ex:'His boots were dirty after walking.' },
  { en:'safe',       tr:'güvenli / emniyetli',ipa:'/seɪf/',        cat:'Sıfatlar',  icon:'🔒', ex:'This is a safe area to walk at night.' },
  { en:'dangerous',  tr:'tehlikeli',        ipa:'/ˈdeɪndʒərəs/',  cat:'Sıfatlar',  icon:'⚠️', ex:'The icy road was very dangerous.' },
  { en:'easy',       tr:'kolay',            ipa:'/ˈiːzi/',         cat:'Sıfatlar',  icon:'✅', ex:'The exam was easy.' },
  { en:'difficult',  tr:'zor',              ipa:'/ˈdɪfɪkəlt/',    cat:'Sıfatlar',  icon:'⚠️', ex:'This exercise is very difficult.' },
  { en:'sick',       tr:'hasta',            ipa:'/sɪk/',           cat:'Sağlık',    icon:'🤒', ex:'She stayed home because she was sick.' },
  { en:'hurt',       tr:'yaralı / acıyan',  ipa:'/hɜːt/',          cat:'Sağlık',    icon:'🩹', ex:'My shoulder is still hurt.' },
  { en:'noisy',      tr:'gürültülü',        ipa:'/ˈnɔɪzi/',       cat:'Sıfatlar',  icon:'🔊', ex:'The street is very noisy.' },
  // ── New Verbs ─────────────────────────────────────────────────────────────
  { en:'prepare',    tr:'hazırlamak',       ipa:'/prɪˈpeə/',      cat:'Fiiller',   icon:'🛠️', ex:'She prepared lunch for the family.' },
  { en:'continue',   tr:'devam etmek',      ipa:'/kənˈtɪnjuː/',   cat:'Fiiller',   icon:'▶️', ex:'Please continue with exercise two.' },
  { en:'happen',     tr:'olmak / gerçekleşmek',ipa:'/ˈhæpən/',    cat:'Fiiller',   icon:'💬', ex:'What happened here?' },
  { en:'mean',       tr:'anlamına gelmek',  ipa:'/miːn/',          cat:'Fiiller',   icon:'💡', ex:'What does this word mean?' },
  { en:'seem',       tr:'görünmek / gibi gözükmek',ipa:'/siːm/',   cat:'Fiiller',   icon:'🤔', ex:'She seems happy today.' },
  { en:'look',       tr:'bakmak / görünmek',ipa:'/lʊk/',           cat:'Fiiller',   icon:'👀', ex:'You look tired — are you OK?' },
  { en:'remember',   tr:'hatırlamak',       ipa:'/rɪˈmembə/',     cat:'Fiiller',   icon:'💭', ex:'Remember to bring your pen.' },
  { en:'forget',     tr:'unutmak',          ipa:'/fəˈɡet/',        cat:'Fiiller',   icon:'😶', ex:'I always forget her birthday.' },
  { en:'believe',    tr:'inanmak',          ipa:'/bɪˈliːv/',      cat:'Fiiller',   icon:'🙏', ex:'I believe you can do it.' },
  { en:'understand', tr:'anlamak',          ipa:'/ˌʌndəˈstænd/',  cat:'Fiiller',   icon:'💡', ex:'Do you understand the question?' },
  { en:'speak',      tr:'konuşmak',         ipa:'/spiːk/',         cat:'Fiiller',   icon:'🗣️', ex:'She speaks three languages.' },
  { en:'hear',       tr:'duymak',           ipa:'/hɪə/',           cat:'Fiiller',   icon:'👂', ex:'I can\'t hear you — speak louder.' },
  { en:'smell',      tr:'koklamak',         ipa:'/smel/',          cat:'Fiiller',   icon:'👃', ex:'Can you smell the flowers?' },
  { en:'taste',      tr:'tatmak',           ipa:'/teɪst/',         cat:'Fiiller',   icon:'👅', ex:'Taste the soup and add salt if needed.' },
  { en:'touch',      tr:'dokunmak',         ipa:'/tʌtʃ/',          cat:'Fiiller',   icon:'✋', ex:'Don\'t touch the hot pan.' },
  { en:'use',        tr:'kullanmak',        ipa:'/juːz/',          cat:'Fiiller',   icon:'🔧', ex:'Use a ruler to draw a straight line.' },
  { en:'collect',    tr:'toplamak / koleksiyonu olmak',ipa:'/kəˈlekt/',cat:'Fiiller',icon:'📦', ex:'She collects stamps.' },
  { en:'visit',      tr:'ziyaret etmek',    ipa:'/ˈvɪzɪt/',       cat:'Fiiller',   icon:'🗺️', ex:'We visit our grandparents on Sunday.' },
  { en:'call',       tr:'aramak / çağırmak',ipa:'/kɔːl/',          cat:'Fiiller',   icon:'📞', ex:'Call me when you get home.' },
  { en:'hurry',      tr:'acele etmek',      ipa:'/ˈhʌri/',         cat:'Fiiller',   icon:'🏃', ex:'Hurry up — we are late!' },
  { en:'rest',       tr:'dinlenmek',        ipa:'/rest/',          cat:'Fiiller',   icon:'😌', ex:'Rest for an hour after lunch.' },
  { en:'travel',     tr:'seyahat etmek',    ipa:'/ˈtrævəl/',      cat:'Fiiller',   icon:'✈️', ex:'She loves to travel.' },
  { en:'cross',      tr:'karşıya geçmek',   ipa:'/krɒs/',          cat:'Fiiller',   icon:'🚸', ex:'Cross the road at the traffic lights.' },
  { en:'park',       tr:'park etmek',       ipa:'/pɑːk/',          cat:'Fiiller',   icon:'🚗', ex:'You can park near the supermarket.' },
  { en:'arrive',     tr:'varmak / ulaşmak', ipa:'/əˈraɪv/',       cat:'Fiiller',   icon:'📍', ex:'The train arrived on time.' },
  // ── New Nouns ─────────────────────────────────────────────────────────────
  { en:'way',        tr:'yol / yön',        ipa:'/weɪ/',           cat:'Genel',     icon:'🗺️', ex:'Which way is the station?' },
  { en:'place',      tr:'yer',              ipa:'/pleɪs/',         cat:'Genel',     icon:'📍', ex:'This is a great place for a picnic.' },
  { en:'thing',      tr:'şey',              ipa:'/θɪŋ/',           cat:'Genel',     icon:'📦', ex:'What is that thing on the table?' },
  { en:'time',       tr:'zaman',            ipa:'/taɪm/',          cat:'Zaman',     icon:'⏰', ex:'What time is it?' },
  { en:'day',        tr:'gün',              ipa:'/deɪ/',           cat:'Zaman',     icon:'📅', ex:'Have a nice day!' },
  { en:'night',      tr:'gece',             ipa:'/naɪt/',          cat:'Zaman',     icon:'🌙', ex:'She reads before she sleeps at night.' },
  { en:'morning',    tr:'sabah',            ipa:'/ˈmɔːnɪŋ/',      cat:'Zaman',     icon:'🌅', ex:'She runs every morning.' },
  { en:'evening',    tr:'akşam',            ipa:'/ˈiːvnɪŋ/',      cat:'Zaman',     icon:'🌆', ex:'He watches TV in the evening.' },
  { en:'afternoon',  tr:'öğleden sonra',    ipa:'/ˌɑːftəˈnuːn/',  cat:'Zaman',     icon:'☀️', ex:'She has a nap in the afternoon.' },
  { en:'week',       tr:'hafta',            ipa:'/wiːk/',          cat:'Zaman',     icon:'📅', ex:'I exercise three times a week.' },
  { en:'month',      tr:'ay',               ipa:'/mʌnθ/',          cat:'Zaman',     icon:'📅', ex:'I go to the dentist every six months.' },
  { en:'year',       tr:'yıl',              ipa:'/jɪə/',           cat:'Zaman',     icon:'🗓️', ex:'She reads fifty books a year.' },
  { en:'name',       tr:'isim',             ipa:'/neɪm/',          cat:'Genel',     icon:'🏷️', ex:'Write your name at the top of the page.' },
  { en:'number',     tr:'sayı / numara',    ipa:'/ˈnʌmbə/',       cat:'Genel',     icon:'🔢', ex:'What is your phone number?' },
  { en:'colour',     tr:'renk',             ipa:'/ˈkʌlə/',        cat:'Genel',     icon:'🌈', ex:'What is your favourite colour?' },
  { en:'size',       tr:'boyut / beden',    ipa:'/saɪz/',          cat:'Genel',     icon:'📐', ex:'What size do you wear?' },
  { en:'price',      tr:'fiyat',            ipa:'/praɪs/',         cat:'Alışveriş', icon:'🏷️', ex:'The price of this shirt is too high.' },
  { en:'idea',       tr:'fikir',            ipa:'/aɪˈdɪə/',       cat:'Genel',     icon:'💡', ex:'She had a good idea for the project.' },
  { en:'information',tr:'bilgi',            ipa:'/ˌɪnfəˈmeɪʃən/', cat:'Genel',     icon:'ℹ️', ex:'Do you have information about the bus times?' },
  { en:'help',       tr:'yardım',           ipa:'/help/',          cat:'Genel',     icon:'🙋', ex:'Can I ask for your help?' },
  { en:'problem',    tr:'sorun',            ipa:'/ˈprɒbləm/',     cat:'Genel',     icon:'❗', ex:'There is a problem with the printer.' },
  { en:'question',   tr:'soru',             ipa:'/ˈkwestʃən/',    cat:'Genel',     icon:'❓', ex:'Do you have any questions?' },
  { en:'news',       tr:'haber',            ipa:'/njuːz/',         cat:'Medya',     icon:'📰', ex:'She watches the news every evening.' },
  { en:'sport',      tr:'spor',             ipa:'/spɔːt/',         cat:'Spor',      icon:'⚽', ex:'Do you like sport?' },
  { en:'music',      tr:'müzik',            ipa:'/ˈmjuːzɪk/',     cat:'Müzik',     icon:'🎵', ex:'I love all types of music.' },
  { en:'art',        tr:'sanat',            ipa:'/ɑːt/',           cat:'Sanat',     icon:'🎨', ex:'She is good at art.' },
  { en:'science',    tr:'fen / bilim',      ipa:'/ˈsaɪəns/',      cat:'Okul',      icon:'🔬', ex:'Science is her favourite subject.' },
  { en:'history',    tr:'tarih',            ipa:'/ˈhɪstri/',      cat:'Okul',      icon:'📜', ex:'He is interested in history.' },
  { en:'health',     tr:'sağlık',           ipa:'/helθ/',          cat:'Sağlık',    icon:'💪', ex:'Good health is very important.' },
  { en:'food',       tr:'yiyecek',          ipa:'/fuːd/',          cat:'Yiyecekler',icon:'🍽️', ex:'What is your favourite food?' },
  { en:'water',      tr:'su',               ipa:'/ˈwɔːtə/',       cat:'İçecekler', icon:'💧', ex:'Drink eight glasses of water a day.' },
  { en:'fruit',      tr:'meyve',            ipa:'/fruːt/',         cat:'Meyveler',  icon:'🍎', ex:'Eat more fruit and vegetables.' },
  { en:'vegetable',  tr:'sebze',            ipa:'/ˈvedʒtəbəl/',   cat:'Sebzeler',  icon:'🥦', ex:'She grows vegetables in her garden.' },
  { en:'meat',       tr:'et',               ipa:'/miːt/',          cat:'Yiyecekler',icon:'🥩', ex:'He does not eat meat.' },
  { en:'bread',      tr:'ekmek',            ipa:'/bred/',          cat:'Yiyecekler',icon:'🍞', ex:'She buys fresh bread every morning.' },
  { en:'rice',       tr:'pirinç',           ipa:'/raɪs/',          cat:'Yiyecekler',icon:'🍚', ex:'Rice is eaten every day in Asia.' },
  { en:'egg',        tr:'yumurta',          ipa:'/eɡ/',            cat:'Yiyecekler',icon:'🥚', ex:'She had two eggs for breakfast.' },
  { en:'milk',       tr:'süt',              ipa:'/mɪlk/',          cat:'İçecekler', icon:'🥛', ex:'Children should drink milk every day.' },
  { en:'butter',     tr:'tereyağı',         ipa:'/ˈbʌtə/',        cat:'Yiyecekler',icon:'🧈', ex:'She spread butter on the bread.' },
  { en:'cheese',     tr:'peynir',           ipa:'/tʃiːz/',         cat:'Yiyecekler',icon:'🧀', ex:'He put cheese on the pizza.' },
  { en:'oil',        tr:'yağ',              ipa:'/ɔɪl/',           cat:'Yiyecekler',icon:'🫙', ex:'Cook the onions in a little oil.' },
  { en:'sugar',      tr:'şeker',            ipa:'/ˈʃʊɡə/',        cat:'Yiyecekler',icon:'🍬', ex:'Add a spoon of sugar to the tea.' },
  { en:'salt',       tr:'tuz',              ipa:'/sɔːlt/',         cat:'Yiyecekler',icon:'🧂', ex:'Don\'t add too much salt.' },
  { en:'pepper',     tr:'biber',            ipa:'/ˈpepə/',        cat:'Yiyecekler',icon:'🫑', ex:'Add salt and pepper to taste.' },
  { en:'honey',      tr:'bal',              ipa:'/ˈhʌni/',        cat:'Yiyecekler',icon:'🍯', ex:'She puts honey in her tea.' },
  { en:'coffee',     tr:'kahve',            ipa:'/ˈkɒfi/',        cat:'İçecekler', icon:'☕', ex:'She drinks two cups of coffee a day.' },
  { en:'tea',        tr:'çay',              ipa:'/tiː/',           cat:'İçecekler', icon:'🍵', ex:'Would you like a cup of tea?' },
  { en:'juice',      tr:'meyve suyu',       ipa:'/dʒuːs/',        cat:'İçecekler', icon:'🍊', ex:'She drinks orange juice for breakfast.' },
  // ── Geography / Nature ───────────────────────────────────────────────────
  { en:'sun',        tr:'güneş',            ipa:'/sʌn/',           cat:'Doğa',      icon:'☀️', ex:'The sun is very hot today.' },
  { en:'moon',       tr:'ay',               ipa:'/muːn/',          cat:'Doğa',      icon:'🌙', ex:'The moon was full last night.' },
  { en:'star',       tr:'yıldız',           ipa:'/stɑː/',          cat:'Doğa',      icon:'⭐', ex:'I can see many stars tonight.' },
  { en:'sea',        tr:'deniz',            ipa:'/siː/',           cat:'Doğa',      icon:'🌊', ex:'We swam in the sea.' },
  { en:'river',      tr:'nehir',            ipa:'/ˈrɪvə/',        cat:'Doğa',      icon:'🏞️', ex:'The river flows through the city.' },
  { en:'lake',       tr:'göl',              ipa:'/leɪk/',          cat:'Doğa',      icon:'🏞️', ex:'We went fishing at the lake.' },
  { en:'mountain',   tr:'dağ',              ipa:'/ˈmaʊntɪn/',     cat:'Doğa',      icon:'⛰️', ex:'The mountain is covered in snow.' },
  { en:'hill',       tr:'tepe',             ipa:'/hɪl/',           cat:'Doğa',      icon:'⛰️', ex:'They walked up the hill.' },
  { en:'forest',     tr:'orman',            ipa:'/ˈfɒrɪst/',      cat:'Doğa',      icon:'🌲', ex:'There is a forest behind the village.' },
  { en:'park',       tr:'park',             ipa:'/pɑːk/',          cat:'Yerler',    icon:'🌳', ex:'We had a picnic in the park.' },
  { en:'street',     tr:'sokak / cadde',    ipa:'/striːt/',        cat:'Coğrafya',  icon:'🏙️', ex:'She lives on a busy street.' },
  { en:'road',       tr:'yol',              ipa:'/rəʊd/',          cat:'Coğrafya',  icon:'🛣️', ex:'The road is blocked.' },
  { en:'bridge',     tr:'köprü',            ipa:'/brɪdʒ/',        cat:'Coğrafya',  icon:'🌉', ex:'Cross the bridge and turn left.' },
  { en:'path',       tr:'patika / yol',     ipa:'/pɑːθ/',          cat:'Coğrafya',  icon:'🛤️', ex:'Walk along the path by the river.' },
  { en:'sand',       tr:'kum',              ipa:'/sænd/',          cat:'Doğa',      icon:'🏖️', ex:'The children played in the sand.' },
  { en:'ice',        tr:'buz',              ipa:'/aɪs/',           cat:'Doğa',      icon:'🧊', ex:'Be careful — there is ice on the road.' },
  { en:'snow',       tr:'kar',              ipa:'/snəʊ/',          cat:'Hava',      icon:'❄️', ex:'The children played in the snow.' },
  { en:'rain',       tr:'yağmur',           ipa:'/reɪn/',          cat:'Hava',      icon:'🌧️', ex:'It rained all day yesterday.' },
  { en:'wind',       tr:'rüzgar',           ipa:'/wɪnd/',          cat:'Hava',      icon:'💨', ex:'The wind is very strong today.' },
  { en:'cloud',      tr:'bulut',            ipa:'/klaʊd/',         cat:'Hava',      icon:'☁️', ex:'There are lots of clouds today.' },
  { en:'fog',        tr:'sis',              ipa:'/fɒɡ/',           cat:'Hava',      icon:'🌫️', ex:'There is thick fog on the road.' },
  // ── Transport ─────────────────────────────────────────────────────────────
  { en:'car',        tr:'araba',            ipa:'/kɑː/',           cat:'Ulaşım',    icon:'🚗', ex:'She drives to work by car.' },
  { en:'bus',        tr:'otobüs',           ipa:'/bʌs/',           cat:'Ulaşım',    icon:'🚌', ex:'Take the bus from stop number five.' },
  { en:'train',      tr:'tren',             ipa:'/treɪn/',         cat:'Ulaşım',    icon:'🚂', ex:'The train leaves at half past eight.' },
  { en:'taxi',       tr:'taksi',            ipa:'/ˈtæksi/',       cat:'Ulaşım',    icon:'🚕', ex:'She took a taxi to the airport.' },
  { en:'bicycle',    tr:'bisiklet',         ipa:'/ˈbaɪsɪkəl/',    cat:'Ulaşım',    icon:'🚲', ex:'He rides his bicycle to school.' },
  { en:'boat',       tr:'tekne',            ipa:'/bəʊt/',          cat:'Ulaşım',    icon:'⛵', ex:'We went on a boat trip.' },
  { en:'plane',      tr:'uçak',             ipa:'/pleɪn/',         cat:'Ulaşım',    icon:'✈️', ex:'The plane lands at two o\'clock.' },
  { en:'ticket',     tr:'bilet',            ipa:'/ˈtɪkɪt/',       cat:'Seyahat',   icon:'🎫', ex:'Buy your ticket online.' },
  { en:'station',    tr:'istasyon',         ipa:'/ˈsteɪʃən/',     cat:'Seyahat',   icon:'🚉', ex:'The train station is five minutes away.' },
  { en:'airport',    tr:'havalimanı',       ipa:'/ˈeəpɔːt/',      cat:'Seyahat',   icon:'✈️', ex:'We need to get to the airport early.' },
  // ── School subjects ───────────────────────────────────────────────────────
  { en:'English',    tr:'İngilizce',        ipa:'/ˈɪŋɡlɪʃ/',     cat:'Okul',      icon:'📝', ex:'I have English class at nine.' },
  { en:'maths',      tr:'matematik',        ipa:'/mæθs/',          cat:'Okul',      icon:'➕', ex:'Maths is not easy.' },
  { en:'science',    tr:'fen bilgisi',      ipa:'/ˈsaɪəns/',      cat:'Okul',      icon:'🔬', ex:'We have science on Wednesday.' },
  { en:'art',        tr:'resim dersi',      ipa:'/ɑːt/',           cat:'Okul',      icon:'🎨', ex:'She is very good at art.' },
  { en:'history',    tr:'tarih dersi',      ipa:'/ˈhɪstri/',      cat:'Okul',      icon:'📜', ex:'History is my favourite subject.' },
  { en:'music',      tr:'müzik dersi',      ipa:'/ˈmjuːzɪk/',     cat:'Okul',      icon:'🎵', ex:'He plays guitar in music class.' },
  { en:'PE',         tr:'beden eğitimi',    ipa:'/piː iː/',        cat:'Okul',      icon:'⚽', ex:'We play sports in PE class.' },
  // ── Common Adjectives (more) ──────────────────────────────────────────────
  { en:'kind',       tr:'nazik',            ipa:'/kaɪnd/',         cat:'Sıfatlar',  icon:'💛', ex:'She is always kind to everyone.' },
  { en:'clever',     tr:'zeki',             ipa:'/ˈklevə/',       cat:'Sıfatlar',  icon:'🧠', ex:'He is a very clever student.' },
  { en:'friendly',   tr:'arkadaş canlısı', ipa:'/ˈfrendli/',     cat:'Sıfatlar',  icon:'😊', ex:'The teacher is very friendly.' },
  { en:'quiet',      tr:'sessiz',           ipa:'/ˈkwaɪət/',      cat:'Sıfatlar',  icon:'🤫', ex:'Please be quiet — the baby is sleeping.' },
  { en:'busy',       tr:'meşgul',           ipa:'/ˈbɪzi/',        cat:'Sıfatlar',  icon:'🏃', ex:'I am very busy this week.' },
  { en:'late',       tr:'geç',              ipa:'/leɪt/',          cat:'Sıfatlar',  icon:'⏰', ex:'She was late for school.' },
  { en:'early',      tr:'erken',            ipa:'/ˈɜːli/',        cat:'Sıfatlar',  icon:'⏰', ex:'He arrived early.' },
  { en:'right',      tr:'doğru / sağ',      ipa:'/raɪt/',          cat:'Sıfatlar',  icon:'✅', ex:'That is the right answer.' },
  { en:'left',       tr:'sol',              ipa:'/left/',          cat:'Sıfatlar',  icon:'⬅️', ex:'Turn left at the corner.' },
  { en:'wrong',      tr:'yanlış',           ipa:'/rɒŋ/',           cat:'Sıfatlar',  icon:'❌', ex:'Sorry, that is the wrong answer.' },
  { en:'next',       tr:'sonraki / yanındaki',ipa:'/nekst/',       cat:'Sıfatlar',  icon:'➡️', ex:'The next bus is in ten minutes.' },
  { en:'other',      tr:'diğer',            ipa:'/ˈʌðə/',         cat:'Sıfatlar',  icon:'🔄', ex:'The other students are waiting.' },
  { en:'both',       tr:'her ikisi de',     ipa:'/bəʊθ/',          cat:'Sıfatlar',  icon:'🔢', ex:'Both books are interesting.' },
  { en:'each',       tr:'her bir',          ipa:'/iːtʃ/',          cat:'Sıfatlar',  icon:'🔢', ex:'Each student has a pencil.' },
  { en:'every',      tr:'her',              ipa:'/ˈevri/',        cat:'Sıfatlar',  icon:'🔢', ex:'He plays football every Saturday.' },
  // ── Common phrases (short) ────────────────────────────────────────────────
  { en:'I see',      tr:'anlıyorum',        ipa:'/aɪ siː/',        cat:'İfadeler',  icon:'💡', ex:'I see — so the answer is five.' },
  { en:'of course',  tr:'tabii ki',         ipa:'/əv kɔːs/',      cat:'İfadeler',  icon:'✅', ex:'Of course I remember you.' },
  { en:'I agree',    tr:'katılıyorum',      ipa:'/aɪ əˈɡriː/',    cat:'İfadeler',  icon:'👍', ex:'I agree with your idea.' },
  { en:'wait a moment',tr:'bir dakika bekle',ipa:'/weɪt ə ˈməʊmənt/',cat:'İfadeler',icon:'⏳', ex:'Wait a moment — I\'ll get my coat.' },
  { en:'you are welcome',tr:'rica ederim',  ipa:'/juː ə ˈwelkəm/',cat:'İfadeler', icon:'😊', ex:'Thank you. You are welcome!' },
  { en:'how much',   tr:'ne kadar',         ipa:'/haʊ mʌtʃ/',     cat:'İfadeler',  icon:'💰', ex:'How much is this bag?' },
  { en:'how many',   tr:'kaç tane',         ipa:'/haʊ ˈmeni/',    cat:'İfadeler',  icon:'🔢', ex:'How many students are in your class?' },
];

let added = 0, skipped = 0;
const toAdd = [];
for (const w of newA1) {
  const key = w.en.toLowerCase().trim();
  if (existing.has(key)) { skipped++; continue; }
  toAdd.push({
    id: w.en.toLowerCase().replace(/\s+/g,'_'),
    en: w.en, tr: w.tr, ipa: w.ipa, level: 'A1',
    cat: w.cat, icon: w.icon, ex: w.ex, syns: [], colloc: [],
  });
  existing.add(key);
  added++;
}

console.log('Added: ' + added + ', Skipped: ' + skipped);
const combined = WORDS.concat(toAdd);
const levels = {};
for (const w of combined) levels[w.level] = (levels[w.level]||0)+1;
console.log('Level counts:', JSON.stringify(levels));
fs.writeFileSync(path.join(__dirname,'../js/data.js'),
  'const WORDS = '+JSON.stringify(combined,null,2)+';\n');
console.log('Written.');
