const fs = require('fs');
const path = require('path');
const raw = fs.readFileSync(path.join(__dirname, '../js/data.js'), 'utf8');
const arrStr = raw.slice(raw.indexOf('['), raw.lastIndexOf(']') + 1);
const WORDS = eval('(' + arrStr + ')');
const existing = new Set(WORDS.map(w => w.en.toLowerCase().trim()));

const newA1 = [
  // ── More basic verbs ──────────────────────────────────────────────────────
  { en:'be',         tr:'olmak',           ipa:'/biː/',            cat:'Fiiller',   icon:'🔤', ex:'I want to be a doctor.' },
  { en:'have',       tr:'sahip olmak',     ipa:'/hæv/',            cat:'Fiiller',   icon:'✋', ex:'I have two brothers.' },
  { en:'do',         tr:'yapmak',          ipa:'/duː/',            cat:'Fiiller',   icon:'🔧', ex:'Do your homework now.' },
  { en:'go',         tr:'gitmek',          ipa:'/ɡəʊ/',            cat:'Fiiller',   icon:'🚶', ex:'Let\'s go to the park.' },
  { en:'come',       tr:'gelmek',          ipa:'/kʌm/',            cat:'Fiiller',   icon:'👋', ex:'Come and sit down.' },
  { en:'see',        tr:'görmek',          ipa:'/siː/',            cat:'Fiiller',   icon:'👀', ex:'Can you see the board?' },
  { en:'make',       tr:'yapmak / hazırlamak',ipa:'/meɪk/',       cat:'Fiiller',   icon:'🛠️', ex:'She made a cake for the party.' },
  { en:'know',       tr:'bilmek',          ipa:'/nəʊ/',            cat:'Fiiller',   icon:'💡', ex:'I know the answer.' },
  { en:'eat',        tr:'yemek',           ipa:'/iːt/',            cat:'Fiiller',   icon:'🍽️', ex:'What do you eat for breakfast?' },
  { en:'drink',      tr:'içmek',           ipa:'/drɪŋk/',          cat:'Fiiller',   icon:'🥤', ex:'Drink plenty of water.' },
  { en:'write',      tr:'yazmak',          ipa:'/raɪt/',           cat:'Fiiller',   icon:'✏️', ex:'Write your name at the top.' },
  { en:'read',       tr:'okumak',          ipa:'/riːd/',           cat:'Fiiller',   icon:'📖', ex:'Read the text carefully.' },
  { en:'hear',       tr:'duymak',          ipa:'/hɪə/',            cat:'Fiiller',   icon:'👂', ex:'I can\'t hear you — speak louder.' },
  { en:'open',       tr:'açmak',           ipa:'/ˈəʊpən/',        cat:'Fiiller',   icon:'🔓', ex:'Open the window, please.' },
  { en:'close',      tr:'kapatmak',        ipa:'/kləʊz/',          cat:'Fiiller',   icon:'🔒', ex:'Please close the door.' },
  { en:'drive',      tr:'araba sürmek',    ipa:'/draɪv/',          cat:'Fiiller',   icon:'🚗', ex:'She drives to work every day.' },
  { en:'fly',        tr:'uçmak',           ipa:'/flaɪ/',           cat:'Fiiller',   icon:'✈️', ex:'Birds fly south in winter.' },
  { en:'ride',       tr:'binmek',          ipa:'/raɪd/',           cat:'Fiiller',   icon:'🚴', ex:'She rides her bike to school.' },
  { en:'enter',      tr:'girmek',          ipa:'/ˈentə/',          cat:'Fiiller',   icon:'🚪', ex:'Enter the building through the main door.' },
  { en:'leave',      tr:'ayrılmak / bırakmak',ipa:'/liːv/',       cat:'Fiiller',   icon:'🚪', ex:'She leaves home at eight.' },
  { en:'arrive',     tr:'ulaşmak / varmak',ipa:'/əˈraɪv/',        cat:'Fiiller',   icon:'🏁', ex:'What time does the train arrive?' },
  { en:'return',     tr:'dönmek / iade etmek',ipa:'/rɪˈtɜːn/',    cat:'Fiiller',   icon:'↩️', ex:'Return the book by Friday.' },
  { en:'stay',       tr:'kalmak',          ipa:'/steɪ/',           cat:'Fiiller',   icon:'🏠', ex:'We stayed at a hotel near the beach.' },
  { en:'live',       tr:'yaşamak',         ipa:'/lɪv/',            cat:'Fiiller',   icon:'🏠', ex:'She lives in Istanbul.' },
  { en:'like',       tr:'sevmek / beğenmek',ipa:'/laɪk/',         cat:'Fiiller',   icon:'👍', ex:'I like this music.' },
  { en:'play',       tr:'oynamak',         ipa:'/pleɪ/',           cat:'Fiiller',   icon:'🎮', ex:'Let\'s play outside.' },
  { en:'work',       tr:'çalışmak',        ipa:'/wɜːk/',           cat:'Fiiller',   icon:'💼', ex:'She works hard every day.' },
  { en:'help',       tr:'yardım etmek',    ipa:'/help/',           cat:'Fiiller',   icon:'🙋', ex:'Can you help me with this?' },
  { en:'find',       tr:'bulmak',          ipa:'/faɪnd/',          cat:'Fiiller',   icon:'🔍', ex:'I can\'t find my keys.' },
  { en:'lose',       tr:'kaybetmek',       ipa:'/luːz/',           cat:'Fiiller',   icon:'😟', ex:'Don\'t lose your ticket.' },
  { en:'buy',        tr:'satın almak',     ipa:'/baɪ/',            cat:'Fiiller',   icon:'🛒', ex:'I need to buy some milk.' },
  { en:'sell',       tr:'satmak',          ipa:'/sel/',            cat:'Fiiller',   icon:'💰', ex:'He sells vegetables at the market.' },
  { en:'start',      tr:'başlamak',        ipa:'/stɑːt/',          cat:'Fiiller',   icon:'▶️', ex:'The lesson starts at nine.' },
  { en:'stop',       tr:'durmak',          ipa:'/stɒp/',           cat:'Fiiller',   icon:'⏹️', ex:'Stop at the red light.' },
  { en:'finish',     tr:'bitirmek',        ipa:'/ˈfɪnɪʃ/',        cat:'Fiiller',   icon:'🏁', ex:'Finish your homework before dinner.' },
  { en:'show',       tr:'göstermek',       ipa:'/ʃəʊ/',            cat:'Fiiller',   icon:'👉', ex:'Show me your ticket.' },
  { en:'follow',     tr:'takip etmek',     ipa:'/ˈfɒləʊ/',        cat:'Fiiller',   icon:'➡️', ex:'Follow the instructions.' },
  { en:'change',     tr:'değiştirmek',     ipa:'/tʃeɪndʒ/',       cat:'Fiiller',   icon:'🔄', ex:'Change your wet clothes.' },
  { en:'take',       tr:'almak / götürmek',ipa:'/teɪk/',           cat:'Fiiller',   icon:'✋', ex:'Take your coat — it is cold.' },
  { en:'walk',       tr:'yürümek',         ipa:'/wɔːk/',           cat:'Fiiller',   icon:'🚶', ex:'She walks to school every day.' },
  { en:'run',        tr:'koşmak',          ipa:'/rʌn/',            cat:'Fiiller',   icon:'🏃', ex:'Run — we are late!' },
  { en:'swim',       tr:'yüzmek',          ipa:'/swɪm/',           cat:'Fiiller',   icon:'🏊', ex:'He swims every morning.' },
  { en:'dance',      tr:'dans etmek',      ipa:'/dɑːns/',          cat:'Fiiller',   icon:'💃', ex:'She loves to dance.' },
  { en:'sing',       tr:'şarkı söylemek',  ipa:'/sɪŋ/',            cat:'Fiiller',   icon:'🎤', ex:'He sings in the choir.' },
  { en:'jump',       tr:'zıplamak',        ipa:'/dʒʌmp/',          cat:'Fiiller',   icon:'🦘', ex:'The children jumped into the pool.' },
  { en:'draw',       tr:'çizmek / resim yapmak',ipa:'/drɔː/',      cat:'Fiiller',   icon:'✏️', ex:'Draw a picture of your family.' },
  { en:'cook',       tr:'yemek yapmak',    ipa:'/kʊk/',            cat:'Fiiller',   icon:'👨‍🍳', ex:'She cooks dinner every evening.' },
  { en:'call',       tr:'aramak (telefon)',ipa:'/kɔːl/',           cat:'Fiiller',   icon:'📞', ex:'Call me when you arrive.' },
  { en:'wait',       tr:'beklemek',        ipa:'/weɪt/',           cat:'Fiiller',   icon:'⏳', ex:'Wait for me outside.' },
  { en:'sit',        tr:'oturmak',         ipa:'/sɪt/',            cat:'Fiiller',   icon:'🪑', ex:'Please sit here.' },
  { en:'stand',      tr:'ayakta durmak',   ipa:'/stænd/',          cat:'Fiiller',   icon:'🧍', ex:'She stood at the door.' },
  { en:'carry',      tr:'taşımak',         ipa:'/ˈkæri/',          cat:'Fiiller',   icon:'📦', ex:'He carried the heavy bag.' },
  // ── Everyday Objects ──────────────────────────────────────────────────────
  { en:'pen',        tr:'kalem (tükenmez)',ipa:'/pen/',            cat:'Okul',      icon:'🖊️', ex:'Write with a blue pen.' },
  { en:'pencil',     tr:'kurşun kalem',    ipa:'/ˈpensɪl/',       cat:'Okul',      icon:'✏️', ex:'Draw the picture in pencil first.' },
  { en:'notebook',   tr:'defter',          ipa:'/ˈnəʊtbʊk/',     cat:'Okul',      icon:'📓', ex:'Write the new words in your notebook.' },
  { en:'book',       tr:'kitap',           ipa:'/bʊk/',            cat:'Okul',      icon:'📚', ex:'She read the book in one day.' },
  { en:'board',      tr:'tahta / pano',    ipa:'/bɔːd/',           cat:'Okul',      icon:'📋', ex:'Write the answer on the board.' },
  { en:'chair',      tr:'sandalye',        ipa:'/tʃeə/',           cat:'Mobilya',   icon:'🪑', ex:'Please take a chair.' },
  { en:'table',      tr:'masa',            ipa:'/ˈteɪbəl/',       cat:'Mobilya',   icon:'🪑', ex:'The food is on the table.' },
  { en:'desk',       tr:'sıra / çalışma masası',ipa:'/desk/',      cat:'Mobilya',   icon:'🖥️', ex:'She sat at her desk.' },
  { en:'bed',        tr:'yatak',           ipa:'/bed/',            cat:'Mobilya',   icon:'🛏️', ex:'Go to bed — it\'s late.' },
  { en:'door',       tr:'kapı',            ipa:'/dɔː/',            cat:'Ev',        icon:'🚪', ex:'Knock on the door before entering.' },
  { en:'window',     tr:'pencere',         ipa:'/ˈwɪndəʊ/',       cat:'Ev',        icon:'🪟', ex:'Open the window — it is hot.' },
  { en:'wall',       tr:'duvar',           ipa:'/wɔːl/',           cat:'Ev',        icon:'🧱', ex:'The picture is on the wall.' },
  { en:'floor',      tr:'zemin / kat',     ipa:'/flɔː/',           cat:'Ev',        icon:'🏢', ex:'She sat on the floor.' },
  { en:'clock',      tr:'duvar saati',     ipa:'/klɒk/',           cat:'Ev',        icon:'🕐', ex:'The clock on the wall shows six.' },
  { en:'phone',      tr:'telefon',         ipa:'/fəʊn/',           cat:'Teknoloji', icon:'📱', ex:'My phone battery is dead.' },
  { en:'television', tr:'televizyon',      ipa:'/ˈtelɪvɪʒən/',    cat:'Teknoloji', icon:'📺', ex:'She watches television in the evening.' },
  { en:'radio',      tr:'radyo',           ipa:'/ˈreɪdiəʊ/',      cat:'Teknoloji', icon:'📻', ex:'He listens to the radio in the car.' },
  { en:'key',        tr:'anahtar',         ipa:'/kiː/',            cat:'Genel',     icon:'🔑', ex:'Have you got your house key?' },
  { en:'lock',       tr:'kilit',           ipa:'/lɒk/',            cat:'Genel',     icon:'🔒', ex:'Use the lock to keep the door closed.' },
  { en:'lamp',       tr:'lamba',           ipa:'/læmp/',           cat:'Ev',        icon:'💡', ex:'She switched on the bedside lamp.' },
  { en:'brush',      tr:'fırça',           ipa:'/brʌʃ/',           cat:'Ev',        icon:'🪥', ex:'Use a brush to clean the floor.' },
  { en:'broom',      tr:'süpürge',         ipa:'/bruːm/',          cat:'Ev',        icon:'🧹', ex:'She swept the floor with a broom.' },
  { en:'bucket',     tr:'kova',            ipa:'/ˈbʌkɪt/',        cat:'Ev',        icon:'🪣', ex:'Fill the bucket with water.' },
  { en:'scissors',   tr:'makas',           ipa:'/ˈsɪzəz/',        cat:'Araçlar',   icon:'✂️', ex:'Cut the paper with scissors.' },
  { en:'hammer',     tr:'çekiç',           ipa:'/ˈhæmə/',         cat:'Araçlar',   icon:'🔨', ex:'He hit the nail with a hammer.' },
  { en:'rope',       tr:'ip / halat',      ipa:'/rəʊp/',           cat:'Araçlar',   icon:'🪢', ex:'Tie the rope to the post.' },
  // ── Simple Nouns (basic) ──────────────────────────────────────────────────
  { en:'face',       tr:'yüz',             ipa:'/feɪs/',           cat:'Vücut',     icon:'😊', ex:'She washed her face.' },
  { en:'head',       tr:'baş / kafa',      ipa:'/hed/',            cat:'Vücut',     icon:'🤯', ex:'He has a headache.' },
  { en:'eye',        tr:'göz',             ipa:'/aɪ/',             cat:'Vücut',     icon:'👁️', ex:'She closed her eyes.' },
  { en:'ear',        tr:'kulak',           ipa:'/ɪə/',             cat:'Vücut',     icon:'👂', ex:'My ear hurts.' },
  { en:'nose',       tr:'burun',           ipa:'/nəʊz/',           cat:'Vücut',     icon:'👃', ex:'She blew her nose.' },
  { en:'mouth',      tr:'ağız',            ipa:'/maʊθ/',           cat:'Vücut',     icon:'👄', ex:'Open your mouth wide.' },
  { en:'hand',       tr:'el',              ipa:'/hænd/',           cat:'Vücut',     icon:'✋', ex:'Raise your hand to answer.' },
  { en:'arm',        tr:'kol',             ipa:'/ɑːm/',            cat:'Vücut',     icon:'💪', ex:'She broke her arm falling off her bike.' },
  { en:'leg',        tr:'bacak',           ipa:'/leɡ/',            cat:'Vücut',     icon:'🦵', ex:'He hurt his leg playing football.' },
  { en:'foot',       tr:'ayak',            ipa:'/fʊt/',            cat:'Vücut',     icon:'🦶', ex:'She washed her feet.' },
  { en:'finger',     tr:'parmak',          ipa:'/ˈfɪŋɡə/',        cat:'Vücut',     icon:'👆', ex:'She cut her finger.' },
  { en:'hair',       tr:'saç',             ipa:'/heə/',            cat:'Vücut',     icon:'💇', ex:'She has long brown hair.' },
  { en:'tooth',      tr:'diş',             ipa:'/tuːθ/',           cat:'Vücut',     icon:'🦷', ex:'Brush your teeth twice a day.' },
  { en:'back',       tr:'sırt / arka',     ipa:'/bæk/',            cat:'Vücut',     icon:'🔙', ex:'My back hurts from sitting all day.' },
  // ── Alphabet / Language ───────────────────────────────────────────────────
  { en:'alphabet',   tr:'alfabe',          ipa:'/ˈælfəbet/',      cat:'Dil',       icon:'🔤', ex:'The English alphabet has 26 letters.' },
  { en:'vowel',      tr:'sesli harf',      ipa:'/ˈvaʊəl/',        cat:'Dil',       icon:'🔤', ex:'A, E, I, O and U are vowels.' },
  { en:'word',       tr:'kelime',          ipa:'/wɜːd/',           cat:'Dil',       icon:'🔤', ex:'Write each word three times.' },
  { en:'sentence',   tr:'cümle',           ipa:'/ˈsentəns/',      cat:'Dil',       icon:'📝', ex:'Write a sentence about yourself.' },
  { en:'question',   tr:'soru',            ipa:'/ˈkwestʃən/',     cat:'Dil',       icon:'❓', ex:'Ask me a question.' },
  { en:'answer',     tr:'cevap',           ipa:'/ˈɑːnsə/',        cat:'Dil',       icon:'💬', ex:'Write your answer here.' },
  { en:'meaning',    tr:'anlam',           ipa:'/ˈmiːnɪŋ/',       cat:'Dil',       icon:'💡', ex:'What is the meaning of this word?' },
  // ── Countries ──────────────────────────────────────────────────────────────
  { en:'Turkey',     tr:'Türkiye',         ipa:'/ˈtɜːki/',        cat:'Ülkeler',   icon:'🇹🇷', ex:'Istanbul is a city in Turkey.' },
  { en:'England',    tr:'İngiltere',       ipa:'/ˈɪŋɡlənd/',      cat:'Ülkeler',   icon:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', ex:'London is the capital of England.' },
  { en:'America',    tr:'Amerika',         ipa:'/əˈmerɪkə/',      cat:'Ülkeler',   icon:'🇺🇸', ex:'She studied in America.' },
  { en:'Germany',    tr:'Almanya',         ipa:'/ˈdʒɜːməni/',     cat:'Ülkeler',   icon:'🇩🇪', ex:'He lives in Germany.' },
  { en:'France',     tr:'Fransa',          ipa:'/frɑːns/',        cat:'Ülkeler',   icon:'🇫🇷', ex:'She visited France last summer.' },
  { en:'Italy',      tr:'İtalya',          ipa:'/ˈɪtəli/',        cat:'Ülkeler',   icon:'🇮🇹', ex:'Pizza comes from Italy.' },
  { en:'Spain',      tr:'İspanya',         ipa:'/speɪn/',          cat:'Ülkeler',   icon:'🇪🇸', ex:'The weather is hot in Spain.' },
  { en:'Japan',      tr:'Japonya',         ipa:'/dʒəˈpæn/',       cat:'Ülkeler',   icon:'🇯🇵', ex:'Sushi is popular in Japan.' },
  { en:'China',      tr:'Çin',             ipa:'/ˈtʃaɪnə/',       cat:'Ülkeler',   icon:'🇨🇳', ex:'China is a very large country.' },
  { en:'Russia',     tr:'Rusya',           ipa:'/ˈrʌʃə/',         cat:'Ülkeler',   icon:'🇷🇺', ex:'Russia is the biggest country in the world.' },
  { en:'Brazil',     tr:'Brezilya',        ipa:'/brəˈzɪl/',       cat:'Ülkeler',   icon:'🇧🇷', ex:'Brazil is famous for football.' },
  { en:'Mexico',     tr:'Meksika',         ipa:'/ˈmeksɪkəʊ/',    cat:'Ülkeler',   icon:'🇲🇽', ex:'Tacos come from Mexico.' },
  { en:'Egypt',      tr:'Mısır',           ipa:'/ˈiːdʒɪpt/',      cat:'Ülkeler',   icon:'🇪🇬', ex:'The Pyramids are in Egypt.' },
  { en:'India',      tr:'Hindistan',       ipa:'/ˈɪndiə/',        cat:'Ülkeler',   icon:'🇮🇳', ex:'India has a very large population.' },
  { en:'Canada',     tr:'Kanada',          ipa:'/ˈkænədə/',       cat:'Ülkeler',   icon:'🇨🇦', ex:'Canada is north of the USA.' },
  // ── Basic Phrases ─────────────────────────────────────────────────────────
  { en:'good morning',tr:'günaydın',       ipa:'/ɡʊd ˈmɔːnɪŋ/',  cat:'İfadeler',  icon:'🌅', ex:'Good morning! Did you sleep well?' },
  { en:'good afternoon',tr:'tünaydın',     ipa:'/ɡʊd ˌɑːftəˈnuːn/',cat:'İfadeler',icon:'☀️', ex:'Good afternoon — how can I help you?' },
  { en:'good evening',tr:'iyi akşamlar',   ipa:'/ɡʊd ˈiːvnɪŋ/',  cat:'İfadeler',  icon:'🌆', ex:'Good evening! Come in and sit down.' },
  { en:'good night',  tr:'iyi geceler',    ipa:'/ɡʊd naɪt/',      cat:'İfadeler',  icon:'🌙', ex:'Good night! Sleep well.' },
  { en:'happy birthday',tr:'iyi günler',   ipa:'/ˈhæpi ˈbɜːθdeɪ/',cat:'İfadeler', icon:'🎂', ex:'Happy birthday! Here is your gift.' },
  { en:'well done',  tr:'aferin / bravo',  ipa:'/wel dʌn/',       cat:'İfadeler',  icon:'👏', ex:'Well done — you got full marks!' },
  { en:'good luck',  tr:'iyi şanslar',     ipa:'/ɡʊd lʌk/',       cat:'İfadeler',  icon:'🍀', ex:'Good luck in your exam!' },
  { en:'me too',     tr:'ben de',          ipa:'/miː tuː/',        cat:'İfadeler',  icon:'🙋', ex:'I like chocolate. Me too!' },
  { en:'of course',  tr:'tabii ki',        ipa:'/əv kɔːs/',       cat:'İfadeler',  icon:'✅', ex:'Of course I will help.' },
  { en:'I do not know',tr:'bilmiyorum',    ipa:'/aɪ dəʊnt nəʊ/', cat:'İfadeler',  icon:'🤷', ex:'I do not know the answer.' },
  { en:'I think so', tr:'öyle sanıyorum',  ipa:'/aɪ θɪŋk səʊ/',  cat:'İfadeler',  icon:'🤔', ex:'Will it rain? I think so.' },
  { en:'I am sorry', tr:'üzgünüm',         ipa:'/aɪ æm ˈsɒri/',   cat:'İfadeler',  icon:'😔', ex:'I am sorry for being late.' },
  { en:'never mind', tr:'önemli değil',    ipa:'/ˈnevə maɪnd/',   cat:'İfadeler',  icon:'😊', ex:'Never mind — it happens to everyone.' },
  { en:'take care',  tr:'kendine iyi bak', ipa:'/teɪk keə/',      cat:'İfadeler',  icon:'💛', ex:'Take care! See you soon.' },
  // ── Numbers (ordinals) ────────────────────────────────────────────────────
  { en:'sixth',      tr:'altıncı',         ipa:'/sɪksθ/',          cat:'Sayılar',   icon:'🔢', ex:'She lives on the sixth floor.' },
  { en:'seventh',    tr:'yedinci',         ipa:'/ˈsevənθ/',       cat:'Sayılar',   icon:'🔢', ex:'Today is the seventh of March.' },
  { en:'eighth',     tr:'sekizinci',       ipa:'/eɪtθ/',           cat:'Sayılar',   icon:'🔢', ex:'She came eighth in the race.' },
  { en:'ninth',      tr:'dokuzuncu',       ipa:'/naɪnθ/',          cat:'Sayılar',   icon:'🔢', ex:'It is his ninth birthday today.' },
  { en:'tenth',      tr:'onuncu',          ipa:'/tenθ/',            cat:'Sayılar',   icon:'🔢', ex:'She finished in tenth place.' },
  // ── Body feelings / health ─────────────────────────────────────────────────
  { en:'hurt',       tr:'acımak / incitmek',ipa:'/hɜːt/',          cat:'Sağlık',    icon:'🤕', ex:'My foot hurts.' },
  { en:'feel',       tr:'hissetmek',       ipa:'/fiːl/',           cat:'Fiiller',   icon:'💗', ex:'How do you feel today?' },
  { en:'doctor',     tr:'doktor',          ipa:'/ˈdɒktə/',        cat:'Sağlık',    icon:'👨‍⚕️', ex:'She went to see the doctor.' },
  { en:'hospital',   tr:'hastane',         ipa:'/ˈhɒspɪtl/',      cat:'Sağlık',    icon:'🏥', ex:'He spent a week in hospital.' },
  { en:'appointment',tr:'randevu',         ipa:'/əˈpɔɪntmənt/',   cat:'Sağlık',    icon:'📅', ex:'I have a doctor\'s appointment at ten.' },
  { en:'thermometer',tr:'termometre',      ipa:'/θəˈmɒmɪtə/',     cat:'Sağlık',    icon:'🌡️', ex:'The thermometer shows 38 degrees.' },
  // ── Classroom language ─────────────────────────────────────────────────────
  { en:'page',       tr:'sayfa',           ipa:'/peɪdʒ/',          cat:'Okul',      icon:'📄', ex:'Open your books at page twelve.' },
  { en:'exercise',   tr:'alıştırma / egzersiz',ipa:'/ˈeksəsaɪz/', cat:'Okul',      icon:'✏️', ex:'Do exercise one on page eight.' },
  { en:'homework',   tr:'ödev',            ipa:'/ˈhəʊmwɜːk/',     cat:'Okul',      icon:'📝', ex:'Did you do your homework?' },
  { en:'exam',       tr:'sınav',           ipa:'/ɪɡˈzæm/',        cat:'Okul',      icon:'📝', ex:'We have an English exam on Friday.' },
  { en:'correct',    tr:'doğru',           ipa:'/kəˈrekt/',       cat:'Okul',      icon:'✅', ex:'Your answer is correct.' },
  { en:'mistake',    tr:'hata',            ipa:'/mɪˈsteɪk/',      cat:'Okul',      icon:'❌', ex:'Everyone makes mistakes.' },
  { en:'topic',      tr:'konu',            ipa:'/ˈtɒpɪk/',        cat:'Okul',      icon:'📌', ex:'What is the topic of today\'s lesson?' },
  // ── Food extras ───────────────────────────────────────────────────────────
  { en:'breakfast',  tr:'kahvaltı',        ipa:'/ˈbrekfəst/',     cat:'Yemekler',  icon:'🍳', ex:'I always eat breakfast before school.' },
  { en:'lunch',      tr:'öğle yemeği',     ipa:'/lʌntʃ/',          cat:'Yemekler',  icon:'🍱', ex:'We eat lunch at twelve.' },
  { en:'dinner',     tr:'akşam yemeği',    ipa:'/ˈdɪnə/',         cat:'Yemekler',  icon:'🍽️', ex:'She made pasta for dinner.' },
  { en:'snack',      tr:'atıştırmalık',    ipa:'/snæk/',           cat:'Yemekler',  icon:'🍎', ex:'He had an apple as a snack.' },
  { en:'meal',       tr:'yemek / öğün',    ipa:'/miːl/',           cat:'Yemekler',  icon:'🍽️', ex:'That was a delicious meal.' },
  // ── Misc ─────────────────────────────────────────────────────────────────
  { en:'animal',     tr:'hayvan',          ipa:'/ˈænɪməl/',       cat:'Hayvanlar', icon:'🐾', ex:'What is your favourite animal?' },
  { en:'plant',      tr:'bitki',           ipa:'/plɑːnt/',         cat:'Doğa',      icon:'🌿', ex:'Water the plants every day.' },
  { en:'colour',     tr:'renk',            ipa:'/ˈkʌlə/',         cat:'Genel',     icon:'🌈', ex:'Which colour do you prefer?' },
  { en:'weather',    tr:'hava durumu',     ipa:'/ˈweðə/',         cat:'Hava',      icon:'⛅', ex:'What is the weather like today?' },
  { en:'season',     tr:'mevsim',          ipa:'/ˈsiːzən/',       cat:'Hava',      icon:'🍂', ex:'What is your favourite season?' },
  { en:'temperature',tr:'sıcaklık',        ipa:'/ˈtemprɪtʃə/',   cat:'Hava',      icon:'🌡️', ex:'The temperature is twenty degrees.' },
  { en:'degree',     tr:'derece',          ipa:'/dɪˈɡriː/',       cat:'Hava',      icon:'🌡️', ex:'It is fifteen degrees outside.' },
  { en:'map',        tr:'harita',          ipa:'/mæp/',            cat:'Coğrafya',  icon:'🗺️', ex:'She checked the map to find the hotel.' },
  { en:'photo',      tr:'fotoğraf',        ipa:'/ˈfəʊtəʊ/',       cat:'Genel',     icon:'📷', ex:'She took a photo of the sunset.' },
  { en:'picture',    tr:'resim / fotoğraf',ipa:'/ˈpɪktʃə/',       cat:'Genel',     icon:'🖼️', ex:'Draw a picture of your home.' },
  { en:'colour',     tr:'renk',            ipa:'/ˈkʌlə/',         cat:'Genel',     icon:'🎨', ex:'Paint the picture with bright colours.' },
];

let added = 0, skipped = 0;
const toAdd = [];
for (const w of newA1) {
  const key = w.en.toLowerCase().trim();
  if (existing.has(key)) { skipped++; continue; }
  toAdd.push({
    id: w.en.toLowerCase().replace(/\s+/g,'_'),
    en: w.en, tr: w.tr, ipa: w.ipa, level: 'A1',
    cat: w.cat, icon: w.icon, ex: w.ex, syns: [], colloc: [],
  });
  existing.add(key);
  added++;
}

console.log('Added: ' + added + ', Skipped: ' + skipped);
const combined = WORDS.concat(toAdd);
const levels = {};
for (const w of combined) levels[w.level] = (levels[w.level]||0)+1;
console.log('Level counts:', JSON.stringify(levels));
fs.writeFileSync(path.join(__dirname,'../js/data.js'),
  'const WORDS = '+JSON.stringify(combined,null,2)+';\n');
console.log('Written.');
