const fs = require('fs');
const path = require('path');
const raw = fs.readFileSync(path.join(__dirname, '../js/data.js'), 'utf8');
const arrStr = raw.slice(raw.indexOf('['), raw.lastIndexOf(']') + 1);
const WORDS = eval('(' + arrStr + ')');

const existing = new Set(WORDS.map(w => w.en.toLowerCase().trim()));

const newA1 = [
  // ── Numbers ──────────────────────────────────────────────────────────────
  { en:'zero',       tr:'sıfır',           ipa:'/ˈzɪərəʊ/',     cat:'Sayılar',      icon:'0️⃣', ex:'The temperature is zero degrees.' },
  { en:'eleven',     tr:'on bir',          ipa:'/ɪˈlevən/',     cat:'Sayılar',      icon:'1️⃣', ex:'There are eleven players in a football team.' },
  { en:'twelve',     tr:'on iki',          ipa:'/twelv/',        cat:'Sayılar',      icon:'🔢', ex:'There are twelve months in a year.' },
  { en:'thirteen',   tr:'on üç',           ipa:'/ˌθɜːˈtiːn/',   cat:'Sayılar',      icon:'🔢', ex:'She is thirteen years old.' },
  { en:'fourteen',   tr:'on dört',         ipa:'/ˌfɔːˈtiːn/',   cat:'Sayılar',      icon:'🔢', ex:'There are fourteen days in two weeks.' },
  { en:'fifteen',    tr:'on beş',          ipa:'/ˌfɪfˈtiːn/',   cat:'Sayılar',      icon:'🔢', ex:'He woke up at fifteen past seven.' },
  { en:'seventeen',  tr:'on yedi',         ipa:'/ˌsevənˈtiːn/', cat:'Sayılar',      icon:'🔢', ex:'She has seventeen books on her shelf.' },
  { en:'eighteen',   tr:'on sekiz',        ipa:'/ˌeɪˈtiːn/',    cat:'Sayılar',      icon:'🔢', ex:'He turned eighteen last month.' },
  { en:'nineteen',   tr:'on dokuz',        ipa:'/ˌnaɪnˈtiːn/',  cat:'Sayılar',      icon:'🔢', ex:'The bus leaves at nineteen minutes past two.' },
  { en:'twenty',     tr:'yirmi',           ipa:'/ˈtwenti/',      cat:'Sayılar',      icon:'🔢', ex:'I have twenty coins in my pocket.' },
  { en:'thirty',     tr:'otuz',            ipa:'/ˈθɜːti/',       cat:'Sayılar',      icon:'🔢', ex:'She lives thirty minutes away.' },
  { en:'forty',      tr:'kırk',            ipa:'/ˈfɔːti/',       cat:'Sayılar',      icon:'🔢', ex:'There are forty students in the class.' },
  { en:'fifty',      tr:'elli',            ipa:'/ˈfɪfti/',       cat:'Sayılar',      icon:'🔢', ex:'The ticket costs fifty pounds.' },
  { en:'sixty',      tr:'altmış',          ipa:'/ˈsɪksti/',      cat:'Sayılar',      icon:'🔢', ex:'There are sixty seconds in a minute.' },
  { en:'seventy',    tr:'yetmiş',          ipa:'/ˈsevənti/',     cat:'Sayılar',      icon:'🔢', ex:'My grandfather is seventy years old.' },
  { en:'eighty',     tr:'seksen',          ipa:'/ˈeɪti/',        cat:'Sayılar',      icon:'🔢', ex:'The building is eighty metres tall.' },
  { en:'ninety',     tr:'doksan',          ipa:'/ˈnaɪnti/',      cat:'Sayılar',      icon:'🔢', ex:'She scored ninety points in the game.' },
  { en:'first',      tr:'birinci',         ipa:'/fɜːst/',         cat:'Sayılar',      icon:'🥇', ex:'She came first in the race.' },
  { en:'second',     tr:'ikinci',          ipa:'/ˈsekənd/',      cat:'Sayılar',      icon:'🥈', ex:'He finished in second place.' },
  { en:'third',      tr:'üçüncü',          ipa:'/θɜːd/',          cat:'Sayılar',      icon:'🥉', ex:'This is the third time I have called.' },
  { en:'fourth',     tr:'dördüncü',        ipa:'/fɔːθ/',          cat:'Sayılar',      icon:'🔢', ex:'She lives on the fourth floor.' },
  { en:'fifth',      tr:'beşinci',         ipa:'/fɪfθ/',          cat:'Sayılar',      icon:'🔢', ex:'Today is the fifth of May.' },
  { en:'last',       tr:'son',             ipa:'/lɑːst/',         cat:'Sayılar',      icon:'🔢', ex:'This is the last bus tonight.' },
  // ── Days ──────────────────────────────────────────────────────────────────
  { en:'Monday',     tr:'Pazartesi',       ipa:'/ˈmʌndeɪ/',      cat:'Günler',       icon:'📅', ex:'School starts on Monday morning.' },
  { en:'Tuesday',    tr:'Salı',            ipa:'/ˈtjuːzdeɪ/',    cat:'Günler',       icon:'📅', ex:'We have a meeting on Tuesday.' },
  { en:'Wednesday',  tr:'Çarşamba',        ipa:'/ˈwenzdeɪ/',     cat:'Günler',       icon:'📅', ex:'The shop is closed on Wednesday.' },
  { en:'weekend',    tr:'hafta sonu',      ipa:'/ˈwiːkend/',     cat:'Günler',       icon:'🎉', ex:'We go to the park at the weekend.' },
  // ── Months ────────────────────────────────────────────────────────────────
  { en:'January',    tr:'Ocak',            ipa:'/ˈdʒænjuəri/',   cat:'Aylar',        icon:'❄️', ex:'January is the first month of the year.' },
  { en:'February',   tr:'Şubat',           ipa:'/ˈfebruəri/',    cat:'Aylar',        icon:'💘', ex:'Valentine\'s Day is in February.' },
  { en:'March',      tr:'Mart',            ipa:'/mɑːtʃ/',         cat:'Aylar',        icon:'🌱', ex:'Spring begins in March.' },
  { en:'April',      tr:'Nisan',           ipa:'/ˈeɪprəl/',      cat:'Aylar',        icon:'🌸', ex:'It often rains in April.' },
  { en:'May',        tr:'Mayıs',           ipa:'/meɪ/',           cat:'Aylar',        icon:'🌼', ex:'The flowers bloom in May.' },
  { en:'June',       tr:'Haziran',         ipa:'/dʒuːn/',         cat:'Aylar',        icon:'☀️', ex:'School finishes in June.' },
  { en:'July',       tr:'Temmuz',          ipa:'/dʒuˈlaɪ/',      cat:'Aylar',        icon:'🏖️', ex:'July is the hottest month here.' },
  { en:'August',     tr:'Ağustos',         ipa:'/ˈɔːɡəst/',      cat:'Aylar',        icon:'🌞', ex:'We go on holiday in August.' },
  { en:'September',  tr:'Eylül',           ipa:'/sepˈtembə/',    cat:'Aylar',        icon:'🍂', ex:'School starts again in September.' },
  { en:'October',    tr:'Ekim',            ipa:'/ɒkˈtəʊbə/',     cat:'Aylar',        icon:'🎃', ex:'The leaves fall in October.' },
  { en:'November',   tr:'Kasım',           ipa:'/nəʊˈvembə/',    cat:'Aylar',        icon:'🍁', ex:'It gets cold in November.' },
  { en:'December',   tr:'Aralık',          ipa:'/dɪˈsembə/',     cat:'Aylar',        icon:'🎄', ex:'Christmas is in December.' },
  // ── Seasons ───────────────────────────────────────────────────────────────
  { en:'spring',     tr:'ilkbahar',        ipa:'/sprɪŋ/',         cat:'Mevsimler',    icon:'🌸', ex:'Flowers grow in spring.' },
  { en:'summer',     tr:'yaz',             ipa:'/ˈsʌmə/',         cat:'Mevsimler',    icon:'☀️', ex:'We swim in summer.' },
  { en:'autumn',     tr:'sonbahar',        ipa:'/ˈɔːtəm/',        cat:'Mevsimler',    icon:'🍂', ex:'Leaves fall in autumn.' },
  { en:'winter',     tr:'kış',             ipa:'/ˈwɪntə/',        cat:'Mevsimler',    icon:'❄️', ex:'We wear coats in winter.' },
  // ── Colors ────────────────────────────────────────────────────────────────
  { en:'purple',     tr:'mor',             ipa:'/ˈpɜːpəl/',      cat:'Renkler',      icon:'💜', ex:'She wore a purple dress.' },
  { en:'dark',       tr:'koyu / karanlık', ipa:'/dɑːk/',          cat:'Sıfatlar',     icon:'🌑', ex:'The room was very dark.' },
  { en:'light',      tr:'açık / hafif',    ipa:'/laɪt/',          cat:'Sıfatlar',     icon:'💡', ex:'The walls are light blue.' },
  // ── Family & People ───────────────────────────────────────────────────────
  { en:'person',     tr:'kişi',            ipa:'/ˈpɜːsən/',      cat:'İnsanlar',     icon:'🧑', ex:'There is only one person in the room.' },
  { en:'people',     tr:'insanlar',        ipa:'/ˈpiːpəl/',      cat:'İnsanlar',     icon:'👥', ex:'Many people go to the park on Sundays.' },
  { en:'man',        tr:'adam',            ipa:'/mæn/',           cat:'İnsanlar',     icon:'👨', ex:'The man is wearing a blue shirt.' },
  { en:'woman',      tr:'kadın',           ipa:'/ˈwʊmən/',       cat:'İnsanlar',     icon:'👩', ex:'The woman is reading a book.' },
  { en:'boy',        tr:'erkek çocuk',     ipa:'/bɔɪ/',           cat:'İnsanlar',     icon:'👦', ex:'The boy is playing in the garden.' },
  { en:'girl',       tr:'kız çocuk',       ipa:'/ɡɜːl/',          cat:'İnsanlar',     icon:'👧', ex:'The girl has a red bag.' },
  { en:'child',      tr:'çocuk',           ipa:'/tʃaɪld/',        cat:'İnsanlar',     icon:'🧒', ex:'Every child loves to play.' },
  { en:'adult',      tr:'yetişkin',        ipa:'/ˈædʌlt/',       cat:'İnsanlar',     icon:'🧑', ex:'This film is for adults only.' },
  { en:'grandchild', tr:'torun',           ipa:'/ˈɡræntʃaɪld/',  cat:'Aile',         icon:'👶', ex:'She has two grandchildren.' },
  { en:'nephew',     tr:'yeğen (erkek)',   ipa:'/ˈnefjuː/',      cat:'Aile',         icon:'👦', ex:'My nephew is five years old.' },
  { en:'niece',      tr:'yeğen (kız)',     ipa:'/niːs/',          cat:'Aile',         icon:'👧', ex:'My niece loves dancing.' },
  { en:'neighbour',  tr:'komşu',           ipa:'/ˈneɪbə/',       cat:'İnsanlar',     icon:'🏠', ex:'Our neighbour is very friendly.' },
  { en:'classmate',  tr:'sınıf arkadaşı', ipa:'/ˈklɑːsmeɪt/',   cat:'Okul',         icon:'🧑‍🤝‍🧑', ex:'She is my classmate.' },
  { en:'partner',    tr:'partner / eş',   ipa:'/ˈpɑːtnə/',      cat:'İnsanlar',     icon:'🤝', ex:'We work as partners on this project.' },
  { en:'guest',      tr:'misafir',         ipa:'/ɡest/',          cat:'İnsanlar',     icon:'🛎️', ex:'We have a guest for dinner tonight.' },
  // ── Food & Drink ──────────────────────────────────────────────────────────
  { en:'sandwich',   tr:'sandviç',         ipa:'/ˈsænwɪdʒ/',     cat:'Yiyecekler',   icon:'🥪', ex:'I ate a cheese sandwich for lunch.' },
  { en:'yoghurt',    tr:'yoğurt',          ipa:'/ˈjɒɡət/',       cat:'Yiyecekler',   icon:'🥛', ex:'I have yoghurt and fruit for breakfast.' },
  { en:'chocolate',  tr:'çikolata',        ipa:'/ˈtʃɒklət/',     cat:'Yiyecekler',   icon:'🍫', ex:'She gave me a box of chocolate.' },
  { en:'grape',      tr:'üzüm',            ipa:'/ɡreɪp/',         cat:'Meyveler',     icon:'🍇', ex:'I bought a bunch of grapes.' },
  { en:'pear',       tr:'armut',           ipa:'/peə/',           cat:'Meyveler',     icon:'🍐', ex:'The pear is soft and sweet.' },
  { en:'peach',      tr:'şeftali',         ipa:'/piːtʃ/',         cat:'Meyveler',     icon:'🍑', ex:'She picked a ripe peach from the tree.' },
  { en:'cherry',     tr:'kiraz',           ipa:'/ˈtʃeri/',        cat:'Meyveler',     icon:'🍒', ex:'The cherries are red and delicious.' },
  { en:'watermelon', tr:'karpuz',          ipa:'/ˈwɔːtəmelən/',  cat:'Meyveler',     icon:'🍉', ex:'We eat watermelon in summer.' },
  { en:'melon',      tr:'kavun',           ipa:'/ˈmelən/',        cat:'Meyveler',     icon:'🍈', ex:'This melon is very sweet.' },
  { en:'plum',       tr:'erik',            ipa:'/plʌm/',          cat:'Meyveler',     icon:'🍑', ex:'She made jam from plums.' },
  { en:'mango',      tr:'mango',           ipa:'/ˈmæŋɡəʊ/',      cat:'Meyveler',     icon:'🥭', ex:'Mangoes are sweet and juicy.' },
  { en:'pineapple',  tr:'ananas',          ipa:'/ˈpaɪnæpəl/',    cat:'Meyveler',     icon:'🍍', ex:'Pineapple grows in hot countries.' },
  { en:'coconut',    tr:'hindistan cevizi',ipa:'/ˈkəʊkənʌt/',    cat:'Meyveler',     icon:'🥥', ex:'She drank water from a coconut.' },
  { en:'avocado',    tr:'avokado',         ipa:'/ˌævəˈkɑːdəʊ/',  cat:'Meyveler',     icon:'🥑', ex:'She put avocado on her toast.' },
  { en:'spinach',    tr:'ıspanak',         ipa:'/ˈspɪnɪdʒ/',     cat:'Sebzeler',     icon:'🥬', ex:'Spinach is very healthy.' },
  { en:'pumpkin',    tr:'kabak',           ipa:'/ˈpʌmpkɪn/',     cat:'Sebzeler',     icon:'🎃', ex:'We made soup from pumpkin.' },
  { en:'mushroom',   tr:'mantar',          ipa:'/ˈmʌʃruːm/',     cat:'Sebzeler',     icon:'🍄', ex:'I added mushrooms to the pizza.' },
  { en:'onion',      tr:'soğan',           ipa:'/ˈʌnjən/',        cat:'Sebzeler',     icon:'🧅', ex:'Cut the onion into small pieces.' },
  { en:'garlic',     tr:'sarımsak',        ipa:'/ˈɡɑːlɪk/',      cat:'Sebzeler',     icon:'🧄', ex:'Add garlic to the sauce.' },
  { en:'corn',       tr:'mısır',           ipa:'/kɔːn/',          cat:'Sebzeler',     icon:'🌽', ex:'We had corn on the cob at the barbecue.' },
  { en:'soup',       tr:'çorba',           ipa:'/suːp/',          cat:'Yiyecekler',   icon:'🍲', ex:'She made tomato soup for lunch.' },
  { en:'jam',        tr:'reçel',           ipa:'/dʒæm/',          cat:'Yiyecekler',   icon:'🍓', ex:'I spread jam on my toast.' },
  { en:'toast',      tr:'kızarmış ekmek',  ipa:'/təʊst/',         cat:'Yiyecekler',   icon:'🍞', ex:'I had toast and eggs for breakfast.' },
  { en:'oil',        tr:'yağ',             ipa:'/ɔɪl/',           cat:'Yiyecekler',   icon:'🫙', ex:'Heat the oil in the pan.' },
  { en:'flour',      tr:'un',              ipa:'/flaʊə/',         cat:'Yiyecekler',   icon:'🌾', ex:'Mix flour with eggs to make dough.' },
  { en:'biscuit',    tr:'bisküvi',         ipa:'/ˈbɪskɪt/',      cat:'Yiyecekler',   icon:'🍪', ex:'She had a cup of tea and a biscuit.' },
  { en:'muffin',     tr:'muffin',          ipa:'/ˈmʌfɪn/',        cat:'Yiyecekler',   icon:'🧁', ex:'She baked chocolate muffins.' },
  { en:'donut',      tr:'çörek',           ipa:'/ˈdəʊnʌt/',      cat:'Yiyecekler',   icon:'🍩', ex:'He bought a donut at the bakery.' },
  { en:'ketchup',    tr:'ketçap',          ipa:'/ˈketʃəp/',       cat:'Yiyecekler',   icon:'🍅', ex:'She put ketchup on her chips.' },
  { en:'mint',       tr:'nane',            ipa:'/mɪnt/',          cat:'Yiyecekler',   icon:'🌿', ex:'This tea has a mint flavour.' },
  { en:'lemonade',   tr:'limonata',        ipa:'/ˌleməˈneɪd/',   cat:'İçecekler',    icon:'🍋', ex:'She drank a cold glass of lemonade.' },
  { en:'beer',       tr:'bira',            ipa:'/bɪə/',           cat:'İçecekler',    icon:'🍺', ex:'He ordered a beer at the pub.' },
  { en:'wine',       tr:'şarap',           ipa:'/waɪn/',          cat:'İçecekler',    icon:'🍷', ex:'She poured a glass of red wine.' },
  { en:'cola',       tr:'kola',            ipa:'/ˈkəʊlə/',        cat:'İçecekler',    icon:'🥤', ex:'He drank a can of cola.' },
  { en:'smoothie',   tr:'smoothie',        ipa:'/ˈsmuːði/',       cat:'İçecekler',    icon:'🥤', ex:'She made a strawberry smoothie.' },
  // ── Home & Furniture ──────────────────────────────────────────────────────
  { en:'home',       tr:'ev',              ipa:'/həʊm/',          cat:'Ev',           icon:'🏠', ex:'She went home after school.' },
  { en:'room',       tr:'oda',             ipa:'/ruːm/',          cat:'Ev',           icon:'🚪', ex:'There are four rooms in the flat.' },
  { en:'sofa',       tr:'kanepe',          ipa:'/ˈsəʊfə/',        cat:'Ev',           icon:'🛋️', ex:'He sat on the sofa to watch TV.' },
  { en:'ceiling',    tr:'tavan',           ipa:'/ˈsiːlɪŋ/',       cat:'Ev',           icon:'🏠', ex:'The ceiling is painted white.' },
  { en:'shelf',      tr:'raf',             ipa:'/ʃelf/',           cat:'Ev',           icon:'📚', ex:'The books are on the shelf.' },
  { en:'drawer',     tr:'çekmece',         ipa:'/drɔː/',           cat:'Ev',           icon:'🪑', ex:'The pen is in the drawer.' },
  { en:'pillow',     tr:'yastık',          ipa:'/ˈpɪləʊ/',        cat:'Ev',           icon:'🛏️', ex:'She put the pillow under her head.' },
  { en:'blanket',    tr:'battaniye',       ipa:'/ˈblæŋkɪt/',      cat:'Ev',           icon:'🛏️', ex:'She covered herself with a blanket.' },
  { en:'towel',      tr:'havlu',           ipa:'/ˈtaʊəl/',        cat:'Ev',           icon:'🧻', ex:'He dried his hands with a towel.' },
  { en:'mirror',     tr:'ayna',            ipa:'/ˈmɪrə/',         cat:'Ev',           icon:'🪞', ex:'She looked in the mirror.' },
  { en:'curtain',    tr:'perde',           ipa:'/ˈkɜːtən/',       cat:'Ev',           icon:'🪟', ex:'Please close the curtains.' },
  { en:'rug',        tr:'halı',            ipa:'/rʌɡ/',            cat:'Ev',           icon:'🪴', ex:'There is a red rug on the floor.' },
  { en:'wardrobe',   tr:'gardırop',        ipa:'/ˈwɔːdrəʊb/',     cat:'Ev',           icon:'👔', ex:'Hang your coat in the wardrobe.' },
  { en:'stairs',     tr:'merdiven',        ipa:'/steəz/',          cat:'Ev',           icon:'🪜', ex:'She walked up the stairs.' },
  { en:'roof',       tr:'çatı',            ipa:'/ruːf/',           cat:'Ev',           icon:'🏠', ex:'The roof of the house is red.' },
  { en:'garage',     tr:'garaj',           ipa:'/ˈɡærɑːʒ/',       cat:'Ev',           icon:'🚗', ex:'He parks his car in the garage.' },
  { en:'balcony',    tr:'balkon',          ipa:'/ˈbælkəni/',      cat:'Ev',           icon:'🌇', ex:'She drinks coffee on the balcony.' },
  { en:'fridge',     tr:'buzdolabı',       ipa:'/frɪdʒ/',          cat:'Ev',           icon:'🧊', ex:'Put the milk in the fridge.' },
  { en:'oven',       tr:'fırın',           ipa:'/ˈʌvən/',          cat:'Ev',           icon:'♨️', ex:'She baked bread in the oven.' },
  { en:'kettle',     tr:'su ısıtıcısı',    ipa:'/ˈketl/',          cat:'Ev',           icon:'🫖', ex:'Boil the kettle for tea.' },
  { en:'pan',        tr:'tava',            ipa:'/pæn/',            cat:'Ev',           icon:'🍳', ex:'Fry the egg in the pan.' },
  { en:'pot',        tr:'tencere',         ipa:'/pɒt/',            cat:'Ev',           icon:'🫕', ex:'She boiled pasta in the pot.' },
  { en:'shampoo',    tr:'şampuan',         ipa:'/ʃæmˈpuː/',       cat:'Ev',           icon:'🧴', ex:'Use shampoo to wash your hair.' },
  { en:'toothpaste', tr:'diş macunu',      ipa:'/ˈtuːθpeɪst/',    cat:'Ev',           icon:'🦷', ex:'Brush your teeth with toothpaste.' },
  { en:'rubbish',    tr:'çöp',             ipa:'/ˈrʌbɪʃ/',        cat:'Ev',           icon:'🗑️', ex:'Put the rubbish in the bin.' },
  // ── Clothing & Accessories ────────────────────────────────────────────────
  { en:'trousers',   tr:'pantolon',        ipa:'/ˈtraʊzəz/',      cat:'Kıyafetler',   icon:'👖', ex:'He wore blue trousers to work.' },
  { en:'blouse',     tr:'bluz',            ipa:'/blaʊz/',          cat:'Kıyafetler',   icon:'👚', ex:'She wore a white blouse.' },
  { en:'jumper',     tr:'kazak',           ipa:'/ˈdʒʌmpə/',       cat:'Kıyafetler',   icon:'🧥', ex:'Put on a jumper — it is cold.' },
  { en:'trainers',   tr:'spor ayakkabı',   ipa:'/ˈtreɪnəz/',      cat:'Kıyafetler',   icon:'👟', ex:'She wore trainers to the gym.' },
  { en:'sandals',    tr:'sandalet',        ipa:'/ˈsændəlz/',      cat:'Kıyafetler',   icon:'👡', ex:'She put on her sandals for the beach.' },
  { en:'gloves',     tr:'eldiven',         ipa:'/ɡlʌvz/',          cat:'Kıyafetler',   icon:'🧤', ex:'He wore gloves in the cold weather.' },
  { en:'scarf',      tr:'atkı',            ipa:'/skɑːf/',          cat:'Kıyafetler',   icon:'🧣', ex:'She wrapped a scarf around her neck.' },
  { en:'belt',       tr:'kemer',           ipa:'/belt/',           cat:'Kıyafetler',   icon:'👔', ex:'He fastened his belt.' },
  { en:'pyjamas',    tr:'pijama',          ipa:'/pəˈdʒɑːməz/',    cat:'Kıyafetler',   icon:'😴', ex:'She changed into her pyjamas.' },
  { en:'swimsuit',   tr:'mayo',            ipa:'/ˈswɪmsuːt/',     cat:'Kıyafetler',   icon:'🩱', ex:'She packed her swimsuit for the holiday.' },
  { en:'raincoat',   tr:'yağmurluk',       ipa:'/ˈreɪnkəʊt/',     cat:'Kıyafetler',   icon:'🌧️', ex:'Take your raincoat — it looks cloudy.' },
  { en:'pocket',     tr:'cep',             ipa:'/ˈpɒkɪt/',        cat:'Kıyafetler',   icon:'👖', ex:'He put the key in his pocket.' },
  { en:'button',     tr:'düğme',           ipa:'/ˈbʌtən/',        cat:'Kıyafetler',   icon:'🔘', ex:'One button fell off her coat.' },
  // ── Body Parts ────────────────────────────────────────────────────────────
  { en:'neck',       tr:'boyun',           ipa:'/nek/',            cat:'Vücut',        icon:'🧣', ex:'She has a sore neck.' },
  { en:'lip',        tr:'dudak',           ipa:'/lɪp/',            cat:'Vücut',        icon:'💋', ex:'She put lipstick on her lips.' },
  { en:'tongue',     tr:'dil',             ipa:'/tʌŋ/',            cat:'Vücut',        icon:'👅', ex:'She burnt her tongue on hot soup.' },
  { en:'chin',       tr:'çene',            ipa:'/tʃɪn/',           cat:'Vücut',        icon:'😐', ex:'He has a small chin.' },
  { en:'knee',       tr:'diz',             ipa:'/niː/',            cat:'Vücut',        icon:'🦵', ex:'He hurt his knee playing football.' },
  { en:'thumb',      tr:'baş parmak',      ipa:'/θʌm/',            cat:'Vücut',        icon:'👍', ex:'She hurt her thumb.' },
  { en:'chest',      tr:'göğüs',           ipa:'/tʃest/',          cat:'Vücut',        icon:'🫀', ex:'He felt pain in his chest.' },
  { en:'stomach',    tr:'mide / karın',    ipa:'/ˈstʌmək/',       cat:'Vücut',        icon:'🫃', ex:'My stomach hurts.' },
  { en:'skin',       tr:'deri',            ipa:'/skɪn/',           cat:'Vücut',        icon:'🙍', ex:'She has smooth skin.' },
  { en:'bone',       tr:'kemik',           ipa:'/bəʊn/',           cat:'Vücut',        icon:'🦴', ex:'The dog is chewing a bone.' },
  { en:'nail',       tr:'tırnak',          ipa:'/neɪl/',           cat:'Vücut',        icon:'💅', ex:'She painted her nails red.' },
  { en:'beard',      tr:'sakal',           ipa:'/bɪəd/',           cat:'Vücut',        icon:'🧔', ex:'He has a short beard.' },
  { en:'forehead',   tr:'alın',            ipa:'/ˈfɔːhed/',       cat:'Vücut',        icon:'😐', ex:'She touched her forehead.' },
  // ── Animals ───────────────────────────────────────────────────────────────
  { en:'rabbit',     tr:'tavşan',          ipa:'/ˈræbɪt/',        cat:'Hayvanlar',    icon:'🐰', ex:'The rabbit jumped over the fence.' },
  { en:'hamster',    tr:'hamster',         ipa:'/ˈhæmstə/',       cat:'Hayvanlar',    icon:'🐹', ex:'She keeps a hamster as a pet.' },
  { en:'turtle',     tr:'kaplumbağa',      ipa:'/ˈtɜːtl/',        cat:'Hayvanlar',    icon:'🐢', ex:'The turtle moves very slowly.' },
  { en:'frog',       tr:'kurbağa',         ipa:'/frɒɡ/',           cat:'Hayvanlar',    icon:'🐸', ex:'There is a frog in the pond.' },
  { en:'butterfly',  tr:'kelebek',         ipa:'/ˈbʌtəflaɪ/',    cat:'Hayvanlar',    icon:'🦋', ex:'A butterfly landed on the flower.' },
  { en:'bee',        tr:'arı',             ipa:'/biː/',            cat:'Hayvanlar',    icon:'🐝', ex:'The bee is collecting honey.' },
  { en:'ant',        tr:'karınca',         ipa:'/ænt/',            cat:'Hayvanlar',    icon:'🐜', ex:'The ants carry food to their nest.' },
  { en:'spider',     tr:'örümcek',         ipa:'/ˈspaɪdə/',       cat:'Hayvanlar',    icon:'🕷️', ex:'There is a spider on the wall.' },
  { en:'worm',       tr:'solucan',         ipa:'/wɜːm/',           cat:'Hayvanlar',    icon:'🪱', ex:'Birds eat worms.' },
  { en:'eagle',      tr:'kartal',          ipa:'/ˈiːɡəl/',        cat:'Hayvanlar',    icon:'🦅', ex:'The eagle flew high in the sky.' },
  { en:'owl',        tr:'baykuş',          ipa:'/aʊl/',            cat:'Hayvanlar',    icon:'🦉', ex:'The owl sleeps during the day.' },
  { en:'wolf',       tr:'kurt',            ipa:'/wʊlf/',           cat:'Hayvanlar',    icon:'🐺', ex:'The wolf howled at the moon.' },
  { en:'fox',        tr:'tilki',           ipa:'/fɒks/',           cat:'Hayvanlar',    icon:'🦊', ex:'A fox ran across the road.' },
  { en:'whale',      tr:'balina',          ipa:'/weɪl/',           cat:'Hayvanlar',    icon:'🐳', ex:'Whales live in the ocean.' },
  { en:'dolphin',    tr:'yunus',           ipa:'/ˈdɒlfɪn/',       cat:'Hayvanlar',    icon:'🐬', ex:'We saw a dolphin near the boat.' },
  { en:'shark',      tr:'köpekbalığı',     ipa:'/ʃɑːk/',           cat:'Hayvanlar',    icon:'🦈', ex:'The shark swims in deep water.' },
  { en:'penguin',    tr:'penguen',         ipa:'/ˈpeŋɡwɪn/',      cat:'Hayvanlar',    icon:'🐧', ex:'Penguins live in Antarctica.' },
  { en:'parrot',     tr:'papağan',         ipa:'/ˈpærət/',        cat:'Hayvanlar',    icon:'🦜', ex:'The parrot can say hello.' },
  { en:'camel',      tr:'deve',            ipa:'/ˈkæməl/',        cat:'Hayvanlar',    icon:'🐪', ex:'Camels can survive without water for days.' },
  { en:'giraffe',    tr:'zürafa',          ipa:'/dʒɪˈrɑːf/',      cat:'Hayvanlar',    icon:'🦒', ex:'The giraffe has a very long neck.' },
  { en:'zebra',      tr:'zebra',           ipa:'/ˈzebrə/',        cat:'Hayvanlar',    icon:'🦓', ex:'Zebras have black and white stripes.' },
  { en:'crocodile',  tr:'timsah',          ipa:'/ˈkrɒkədaɪl/',   cat:'Hayvanlar',    icon:'🐊', ex:'Crocodiles live near rivers.' },
  { en:'bear',       tr:'ayı',             ipa:'/beə/',            cat:'Hayvanlar',    icon:'🐻', ex:'The bear looked for food in the forest.' },
  { en:'monkey',     tr:'maymun',          ipa:'/ˈmʌŋki/',        cat:'Hayvanlar',    icon:'🐒', ex:'The monkey climbed the tree.' },
  { en:'mouse',      tr:'fare',            ipa:'/maʊs/',           cat:'Hayvanlar',    icon:'🐭', ex:'A mouse ran across the kitchen floor.' },
  { en:'cow',        tr:'inek',            ipa:'/kaʊ/',            cat:'Hayvanlar',    icon:'🐄', ex:'The cow is in the field.' },
  { en:'goat',       tr:'keçi',            ipa:'/ɡəʊt/',           cat:'Hayvanlar',    icon:'🐐', ex:'The goat ate the grass.' },
  { en:'donkey',     tr:'eşek',            ipa:'/ˈdɒŋki/',        cat:'Hayvanlar',    icon:'🫏', ex:'The donkey carried heavy bags.' },
  { en:'hen',        tr:'tavuk',           ipa:'/hen/',            cat:'Hayvanlar',    icon:'🐔', ex:'The hen lays eggs every day.' },
  { en:'kitten',     tr:'yavru kedi',      ipa:'/ˈkɪtən/',        cat:'Hayvanlar',    icon:'🐱', ex:'The kitten is sleeping on the sofa.' },
  { en:'puppy',      tr:'yavru köpek',     ipa:'/ˈpʌpi/',          cat:'Hayvanlar',    icon:'🐶', ex:'She got a puppy for her birthday.' },
  // ── Jobs / Occupations ────────────────────────────────────────────────────
  { en:'nurse',      tr:'hemşire',         ipa:'/nɜːs/',           cat:'Meslekler',    icon:'👩‍⚕️', ex:'The nurse gave me the medicine.' },
  { en:'cook',       tr:'aşçı',            ipa:'/kʊk/',            cat:'Meslekler',    icon:'👨‍🍳', ex:'The cook prepared a delicious meal.' },
  { en:'pilot',      tr:'pilot',           ipa:'/ˈpaɪlət/',        cat:'Meslekler',    icon:'✈️', ex:'The pilot landed the plane safely.' },
  { en:'actor',      tr:'aktör',           ipa:'/ˈæktə/',         cat:'Meslekler',    icon:'🎭', ex:'He is a famous actor.' },
  { en:'singer',     tr:'şarkıcı',         ipa:'/ˈsɪŋə/',         cat:'Meslekler',    icon:'🎤', ex:'She is a very popular singer.' },
  { en:'journalist', tr:'gazeteci',        ipa:'/ˈdʒɜːnəlɪst/',   cat:'Meslekler',    icon:'📰', ex:'The journalist wrote an interesting article.' },
  { en:'engineer',   tr:'mühendis',        ipa:'/ˌendʒɪˈnɪə/',    cat:'Meslekler',    icon:'⚙️', ex:'She is an engineer at the car factory.' },
  { en:'scientist',  tr:'bilim insanı',    ipa:'/ˈsaɪəntɪst/',    cat:'Meslekler',    icon:'🔬', ex:'The scientist did an experiment.' },
  { en:'dentist',    tr:'diş hekimi',      ipa:'/ˈdentɪst/',      cat:'Meslekler',    icon:'🦷', ex:'I went to the dentist yesterday.' },
  { en:'vet',        tr:'veteriner',       ipa:'/vet/',            cat:'Meslekler',    icon:'🐾', ex:'We took the dog to the vet.' },
  { en:'firefighter',tr:'itfaiyeci',       ipa:'/ˈfaɪəfaɪtə/',   cat:'Meslekler',    icon:'🚒', ex:'The firefighter put out the fire.' },
  { en:'mechanic',   tr:'tamirci / mekanik',ipa:'/mɪˈkænɪk/',    cat:'Meslekler',    icon:'🔧', ex:'The mechanic fixed my car.' },
  { en:'plumber',    tr:'tesisatçı',       ipa:'/ˈplʌmə/',        cat:'Meslekler',    icon:'🔧', ex:'The plumber fixed the pipe.' },
  { en:'secretary',  tr:'sekreter',        ipa:'/ˈsekrətri/',     cat:'Meslekler',    icon:'💼', ex:'The secretary answered the phone.' },
  { en:'manager',    tr:'müdür',           ipa:'/ˈmænɪdʒə/',      cat:'Meslekler',    icon:'💼', ex:'She is the manager of the shop.' },
  { en:'butcher',    tr:'kasap',           ipa:'/ˈbʊtʃə/',        cat:'Meslekler',    icon:'🥩', ex:'The butcher cut the meat.' },
  { en:'electrician',tr:'elektrikçi',      ipa:'/ɪˌlekˈtrɪʃən/', cat:'Meslekler',    icon:'⚡', ex:'The electrician repaired the light.' },
  { en:'carpenter',  tr:'marangoz',        ipa:'/ˈkɑːpəntə/',     cat:'Meslekler',    icon:'🪚', ex:'The carpenter made a wooden table.' },
  { en:'librarian',  tr:'kütüphaneci',     ipa:'/laɪˈbreəriən/',  cat:'Meslekler',    icon:'📚', ex:'The librarian helped me find the book.' },
  // ── Places ────────────────────────────────────────────────────────────────
  { en:'post office',tr:'postane',         ipa:'/ˈpəʊst ɒfɪs/',  cat:'Yerler',       icon:'📮', ex:'I need to go to the post office to send a letter.' },
  { en:'pharmacy',   tr:'eczane',          ipa:'/ˈfɑːməsi/',      cat:'Yerler',       icon:'💊', ex:'I bought medicine from the pharmacy.' },
  { en:'bakery',     tr:'fırın',           ipa:'/ˈbeɪkəri/',      cat:'Yerler',       icon:'🥖', ex:'She bought fresh bread from the bakery.' },
  { en:'cinema',     tr:'sinema',          ipa:'/ˈsɪnɪmə/',       cat:'Yerler',       icon:'🎬', ex:'We went to the cinema last night.' },
  { en:'museum',     tr:'müze',            ipa:'/mjuːˈzɪəm/',     cat:'Yerler',       icon:'🏛️', ex:'The museum has many old paintings.' },
  { en:'stadium',    tr:'stadyum',         ipa:'/ˈsteɪdiəm/',     cat:'Yerler',       icon:'🏟️', ex:'The stadium is full of fans.' },
  { en:'gym',        tr:'spor salonu',     ipa:'/dʒɪm/',           cat:'Yerler',       icon:'🏋️', ex:'She goes to the gym every morning.' },
  { en:'church',     tr:'kilise',          ipa:'/tʃɜːtʃ/',        cat:'Yerler',       icon:'⛪', ex:'There is an old church in the village.' },
  { en:'mosque',     tr:'cami',            ipa:'/mɒsk/',           cat:'Yerler',       icon:'🕌', ex:'Many people pray at the mosque.' },
  { en:'harbour',    tr:'liman',           ipa:'/ˈhɑːbə/',        cat:'Yerler',       icon:'⚓', ex:'The boats are in the harbour.' },
  { en:'farm',       tr:'çiftlik',         ipa:'/fɑːm/',           cat:'Yerler',       icon:'🌾', ex:'We visited a farm and saw horses.' },
  { en:'castle',     tr:'kale',            ipa:'/ˈkɑːsəl/',       cat:'Yerler',       icon:'🏰', ex:'The castle is on top of the hill.' },
  { en:'cave',       tr:'mağara',          ipa:'/keɪv/',           cat:'Yerler',       icon:'🏔️', ex:'They explored a cave in the mountains.' },
  { en:'desert',     tr:'çöl',             ipa:'/ˈdezət/',        cat:'Doğa',         icon:'🏜️', ex:'It is very hot in the desert.' },
  { en:'island',     tr:'ada',             ipa:'/ˈaɪlənd/',       cat:'Doğa',         icon:'🏝️', ex:'We stayed on a small island.' },
  { en:'valley',     tr:'vadi',            ipa:'/ˈvæli/',          cat:'Doğa',         icon:'🏞️', ex:'The valley is green in spring.' },
  { en:'corner',     tr:'köşe',            ipa:'/ˈkɔːnə/',        cat:'Yerler',       icon:'📍', ex:'Turn left at the corner.' },
  { en:'port',       tr:'liman',           ipa:'/pɔːt/',           cat:'Yerler',       icon:'⚓', ex:'The ship arrived at the port.' },
  { en:'square',     tr:'meydan',          ipa:'/skweə/',          cat:'Yerler',       icon:'🏙️', ex:'We met in the town square.' },
  // ── Nature & Weather ──────────────────────────────────────────────────────
  { en:'storm',      tr:'fırtına',         ipa:'/stɔːm/',          cat:'Hava',         icon:'⛈️', ex:'There was a big storm last night.' },
  { en:'thunder',    tr:'gök gürültüsü',   ipa:'/ˈθʌndə/',        cat:'Hava',         icon:'⛈️', ex:'I heard thunder and saw lightning.' },
  { en:'lightning',  tr:'yıldırım',        ipa:'/ˈlaɪtnɪŋ/',      cat:'Hava',         icon:'⚡', ex:'Lightning lit up the sky.' },
  { en:'rainbow',    tr:'gökkuşağı',       ipa:'/ˈreɪnbəʊ/',      cat:'Hava',         icon:'🌈', ex:'A rainbow appeared after the rain.' },
  { en:'sky',        tr:'gökyüzü',         ipa:'/skaɪ/',           cat:'Doğa',         icon:'🌤️', ex:'The sky is clear and blue today.' },
  { en:'mud',        tr:'çamur',           ipa:'/mʌd/',            cat:'Doğa',         icon:'🪣', ex:'His boots were covered in mud.' },
  { en:'rock',       tr:'kaya / taş',      ipa:'/rɒk/',            cat:'Doğa',         icon:'🪨', ex:'She sat on a big rock.' },
  { en:'stone',      tr:'taş',             ipa:'/stəʊn/',          cat:'Doğa',         icon:'🪨', ex:'The path was made of flat stones.' },
  { en:'wave',       tr:'dalga',           ipa:'/weɪv/',           cat:'Doğa',         icon:'🌊', ex:'The waves were very high.' },
  { en:'ground',     tr:'zemin / yер',     ipa:'/ɡraʊnd/',        cat:'Doğa',         icon:'🌍', ex:'She sat on the ground.' },
  { en:'air',        tr:'hava',            ipa:'/eə/',             cat:'Doğa',         icon:'💨', ex:'The air is clean in the mountains.' },
  { en:'field',      tr:'tarla / alan',    ipa:'/fiːld/',          cat:'Doğa',         icon:'🌾', ex:'Cows are eating grass in the field.' },
  // ── Transport & Travel ────────────────────────────────────────────────────
  { en:'motorbike',  tr:'motosiklet',      ipa:'/ˈməʊtəbaɪk/',   cat:'Ulaşım',       icon:'🏍️', ex:'He rides his motorbike to work.' },
  { en:'van',        tr:'minivan / kamyonet',ipa:'/væn/',          cat:'Ulaşım',       icon:'🚐', ex:'They moved the furniture in a van.' },
  { en:'lorry',      tr:'kamyon',          ipa:'/ˈlɒri/',          cat:'Ulaşım',       icon:'🚛', ex:'A lorry stopped on the motorway.' },
  { en:'helicopter', tr:'helikopter',      ipa:'/ˈhelɪkɒptə/',   cat:'Ulaşım',       icon:'🚁', ex:'The helicopter landed on the roof.' },
  { en:'ship',       tr:'gemi',            ipa:'/ʃɪp/',            cat:'Ulaşım',       icon:'🚢', ex:'The ship sailed across the ocean.' },
  { en:'ferry',      tr:'feribot',         ipa:'/ˈferi/',          cat:'Ulaşım',       icon:'⛴️', ex:'We took the ferry to the island.' },
  { en:'journey',    tr:'yolculuk',        ipa:'/ˈdʒɜːni/',       cat:'Ulaşım',       icon:'🗺️', ex:'The journey takes two hours by train.' },
  { en:'luggage',    tr:'bagaj',           ipa:'/ˈlʌɡɪdʒ/',       cat:'Seyahat',      icon:'🧳', ex:'She carried two pieces of luggage.' },
  { en:'suitcase',   tr:'bavul',           ipa:'/ˈsuːtkeɪs/',     cat:'Seyahat',      icon:'🧳', ex:'He packed his suitcase for the trip.' },
  { en:'passport',   tr:'pasaport',        ipa:'/ˈpɑːspɔːt/',     cat:'Seyahat',      icon:'🛂', ex:'Don\'t forget your passport.' },
  { en:'map',        tr:'harita',          ipa:'/mæp/',            cat:'Seyahat',      icon:'🗺️', ex:'She looked at the map to find the hotel.' },
  // ── Basic Verbs ───────────────────────────────────────────────────────────
  { en:'speak',      tr:'konuşmak',        ipa:'/spiːk/',          cat:'Fiiller',      icon:'🗣️', ex:'Can you speak English?' },
  { en:'understand', tr:'anlamak',         ipa:'/ˌʌndəˈstænd/',   cat:'Fiiller',      icon:'💡', ex:'I don\'t understand this question.' },
  { en:'remember',   tr:'hatırlamak',      ipa:'/rɪˈmembə/',      cat:'Fiiller',      icon:'💭', ex:'I can\'t remember his name.' },
  { en:'forget',     tr:'unutmak',         ipa:'/fəˈɡet/',         cat:'Fiiller',      icon:'😶', ex:'Don\'t forget your keys.' },
  { en:'show',       tr:'göstermek',       ipa:'/ʃəʊ/',            cat:'Fiiller',      icon:'👉', ex:'Show me the way to the station.' },
  { en:'meet',       tr:'tanışmak / buluşmak',ipa:'/miːt/',       cat:'Fiiller',      icon:'🤝', ex:'I will meet my friend at the café.' },
  { en:'wait',       tr:'beklemek',        ipa:'/weɪt/',           cat:'Fiiller',      icon:'⏳', ex:'Wait here until I come back.' },
  { en:'pay',        tr:'ödemek',          ipa:'/peɪ/',            cat:'Fiiller',      icon:'💳', ex:'Can I pay by card?' },
  { en:'clean',      tr:'temizlemek',      ipa:'/kliːn/',          cat:'Fiiller',      icon:'🧹', ex:'She cleans the house every Saturday.' },
  { en:'wash',       tr:'yıkamak',         ipa:'/wɒʃ/',            cat:'Fiiller',      icon:'🧼', ex:'Wash your hands before eating.' },
  { en:'bake',       tr:'fırında pişirmek',ipa:'/beɪk/',           cat:'Fiiller',      icon:'🥧', ex:'She bakes a cake every Sunday.' },
  { en:'boil',       tr:'kaynatmak',       ipa:'/bɔɪl/',           cat:'Fiiller',      icon:'♨️', ex:'Boil the water before drinking.' },
  { en:'fry',        tr:'kızartmak',       ipa:'/fraɪ/',            cat:'Fiiller',      icon:'🍳', ex:'Fry the vegetables in oil.' },
  { en:'cut',        tr:'kesmek',          ipa:'/kʌt/',            cat:'Fiiller',      icon:'✂️', ex:'Cut the bread into slices.' },
  { en:'mix',        tr:'karıştırmak',     ipa:'/mɪks/',           cat:'Fiiller',      icon:'🥣', ex:'Mix the flour and eggs together.' },
  { en:'pour',       tr:'dökmek',          ipa:'/pɔː/',            cat:'Fiiller',      icon:'🫗', ex:'Pour the milk into the glass.' },
  { en:'break',      tr:'kırmak',          ipa:'/breɪk/',          cat:'Fiiller',      icon:'💥', ex:'Be careful — don\'t break the glass.' },
  { en:'fix',        tr:'tamir etmek',     ipa:'/fɪks/',           cat:'Fiiller',      icon:'🔧', ex:'Dad fixed the broken chair.' },
  { en:'build',      tr:'inşa etmek',      ipa:'/bɪld/',           cat:'Fiiller',      icon:'🏗️', ex:'They are building a new house.' },
  { en:'paint',      tr:'boyamak',         ipa:'/peɪnt/',          cat:'Fiiller',      icon:'🎨', ex:'She painted the wall blue.' },
  { en:'plant',      tr:'dikmek',          ipa:'/plɑːnt/',         cat:'Fiiller',      icon:'🌱', ex:'He planted roses in the garden.' },
  { en:'grow',       tr:'büyümek / yetiştirmek',ipa:'/ɡrəʊ/',     cat:'Fiiller',      icon:'🌱', ex:'They grow vegetables in the garden.' },
  { en:'feed',       tr:'beslemek',        ipa:'/fiːd/',           cat:'Fiiller',      icon:'🍽️', ex:'She feeds the cat every morning.' },
  { en:'pull',       tr:'çekmek',          ipa:'/pʊl/',            cat:'Fiiller',      icon:'💪', ex:'Pull the door to open it.' },
  { en:'push',       tr:'itmek',           ipa:'/pʊʃ/',            cat:'Fiiller',      icon:'🚪', ex:'Push the door to enter.' },
  { en:'lift',       tr:'kaldırmak',       ipa:'/lɪft/',           cat:'Fiiller',      icon:'💪', ex:'She lifted the heavy box.' },
  { en:'drop',       tr:'düşürmek',        ipa:'/drɒp/',           cat:'Fiiller',      icon:'⬇️', ex:'He dropped his pen on the floor.' },
  { en:'kick',       tr:'tekmelemek',      ipa:'/kɪk/',            cat:'Fiiller',      icon:'⚽', ex:'He kicked the ball into the goal.' },
  { en:'catch',      tr:'yakalamak',       ipa:'/kætʃ/',           cat:'Fiiller',      icon:'🤲', ex:'Catch the ball!' },
  { en:'throw',      tr:'atmak / fırlatmak',ipa:'/θrəʊ/',         cat:'Fiiller',      icon:'⚾', ex:'Throw the ball to me.' },
  { en:'hit',        tr:'vurmak',          ipa:'/hɪt/',            cat:'Fiiller',      icon:'🥊', ex:'He hit the nail with a hammer.' },
  { en:'climb',      tr:'tırmanmak',       ipa:'/klaɪm/',          cat:'Fiiller',      icon:'🧗', ex:'The children climbed the tree.' },
  { en:'skip',       tr:'atlamak / geçmek',ipa:'/skɪp/',          cat:'Fiiller',      icon:'⏭️', ex:'She skips rope every day.' },
  { en:'wave',       tr:'el sallamak',     ipa:'/weɪv/',           cat:'Fiiller',      icon:'👋', ex:'She waved goodbye from the window.' },
  { en:'point',      tr:'işaret etmek',    ipa:'/pɔɪnt/',          cat:'Fiiller',      icon:'👉', ex:'He pointed at the sign.' },
  { en:'knock',      tr:'kapı çalmak',     ipa:'/nɒk/',            cat:'Fiiller',      icon:'🚪', ex:'Knock on the door before entering.' },
  { en:'ring',       tr:'zil çalmak',      ipa:'/rɪŋ/',            cat:'Fiiller',      icon:'🔔', ex:'Ring the doorbell.' },
  { en:'check',      tr:'kontrol etmek',   ipa:'/tʃek/',           cat:'Fiiller',      icon:'✅', ex:'Check your answers carefully.' },
  { en:'count',      tr:'saymak',          ipa:'/kaʊnt/',          cat:'Fiiller',      icon:'🔢', ex:'Count the apples in the basket.' },
  { en:'measure',    tr:'ölçmek',          ipa:'/ˈmeʒə/',         cat:'Fiiller',      icon:'📏', ex:'Measure the length of the table.' },
  { en:'weigh',      tr:'tartmak',         ipa:'/weɪ/',            cat:'Fiiller',      icon:'⚖️', ex:'Weigh the flour before adding it.' },
  { en:'save',       tr:'kaydetmek / kurtarmak',ipa:'/seɪv/',      cat:'Fiiller',      icon:'💾', ex:'Save the file before closing.' },
  { en:'share',      tr:'paylaşmak',       ipa:'/ʃeə/',            cat:'Fiiller',      icon:'🤝', ex:'Share your food with your sister.' },
  { en:'copy',       tr:'kopyalamak',      ipa:'/ˈkɒpi/',          cat:'Fiiller',      icon:'📋', ex:'Copy the words into your notebook.' },
  { en:'print',      tr:'yazdırmak / basmak',ipa:'/prɪnt/',       cat:'Fiiller',      icon:'🖨️', ex:'Print the document and bring it.' },
  { en:'type',       tr:'yazmak (klavye)',  ipa:'/taɪp/',           cat:'Fiiller',      icon:'⌨️', ex:'She types very fast.' },
  { en:'search',     tr:'aramak',          ipa:'/sɜːtʃ/',          cat:'Fiiller',      icon:'🔍', ex:'Search for the answer online.' },
  { en:'smell',      tr:'koklamak',        ipa:'/smel/',           cat:'Fiiller',      icon:'👃', ex:'This flower smells wonderful.' },
  { en:'taste',      tr:'tatmak',          ipa:'/teɪst/',          cat:'Fiiller',      icon:'👅', ex:'Taste the soup before serving.' },
  { en:'touch',      tr:'dokunmak',        ipa:'/tʌtʃ/',           cat:'Fiiller',      icon:'🤚', ex:'Don\'t touch the hot pan.' },
  { en:'feel',       tr:'hissetmek',       ipa:'/fiːl/',           cat:'Fiiller',      icon:'💗', ex:'How do you feel today?' },
  { en:'laugh',      tr:'gülmek',          ipa:'/lɑːf/',           cat:'Fiiller',      icon:'😄', ex:'The children laughed at the clown.' },
  { en:'cry',        tr:'ağlamak',         ipa:'/kraɪ/',           cat:'Fiiller',      icon:'😢', ex:'The baby is crying.' },
  { en:'shout',      tr:'bağırmak',        ipa:'/ʃaʊt/',           cat:'Fiiller',      icon:'📢', ex:'Don\'t shout in the library.' },
  { en:'whisper',    tr:'fısıldamak',      ipa:'/ˈwɪspə/',        cat:'Fiiller',      icon:'🤫', ex:'She whispered the answer to me.' },
  { en:'wake',       tr:'uyanmak',         ipa:'/weɪk/',           cat:'Fiiller',      icon:'⏰', ex:'I wake up at seven every morning.' },
  { en:'sleep',      tr:'uyumak',          ipa:'/sliːp/',          cat:'Fiiller',      icon:'😴', ex:'The baby is sleeping.' },
  { en:'dream',      tr:'rüya görmek',     ipa:'/driːm/',          cat:'Fiiller',      icon:'💤', ex:'I dreamed about a beach holiday.' },
  { en:'rest',       tr:'dinlenmek',       ipa:'/rest/',           cat:'Fiiller',      icon:'😌', ex:'She rested after lunch.' },
  { en:'relax',      tr:'rahatlamak',      ipa:'/rɪˈlæks/',       cat:'Fiiller',      icon:'😌', ex:'He relaxed in the garden.' },
  { en:'enjoy',      tr:'keyif almak',     ipa:'/ɪnˈdʒɔɪ/',       cat:'Fiiller',      icon:'😊', ex:'I enjoy reading books.' },
  { en:'visit',      tr:'ziyaret etmek',   ipa:'/ˈvɪzɪt/',        cat:'Fiiller',      icon:'🗺️', ex:'We visit our grandparents every weekend.' },
  { en:'invite',     tr:'davet etmek',     ipa:'/ɪnˈvaɪt/',       cat:'Fiiller',      icon:'✉️', ex:'She invited me to her party.' },
  { en:'join',       tr:'katılmak',        ipa:'/dʒɔɪn/',          cat:'Fiiller',      icon:'🤝', ex:'Can I join the game?' },
  { en:'choose',     tr:'seçmek',          ipa:'/tʃuːz/',          cat:'Fiiller',      icon:'☑️', ex:'Choose a card from the pack.' },
  { en:'decide',     tr:'karar vermek',    ipa:'/dɪˈsaɪd/',       cat:'Fiiller',      icon:'✅', ex:'She decided to study English.' },
  { en:'agree',      tr:'katılmak',        ipa:'/əˈɡriː/',         cat:'Fiiller',      icon:'👍', ex:'I agree with you.' },
  { en:'borrow',     tr:'ödünç almak',     ipa:'/ˈbɒrəʊ/',        cat:'Fiiller',      icon:'📚', ex:'Can I borrow your pen?' },
  { en:'lend',       tr:'ödünç vermek',    ipa:'/lend/',           cat:'Fiiller',      icon:'🤲', ex:'She lent me her book.' },
  { en:'spend',      tr:'harcamak / geçirmek',ipa:'/spend/',      cat:'Fiiller',      icon:'💸', ex:'I spent all my money on food.' },
  { en:'win',        tr:'kazanmak',        ipa:'/wɪn/',            cat:'Fiiller',      icon:'🏆', ex:'Our team won the match.' },
  // ── Basic Adjectives ──────────────────────────────────────────────────────
  { en:'ugly',       tr:'çirkin',          ipa:'/ˈʌɡli/',          cat:'Sıfatlar',     icon:'😬', ex:'The old building looks ugly.' },
  { en:'clever',     tr:'zeki',            ipa:'/ˈklevə/',        cat:'Sıfatlar',     icon:'🧠', ex:'She is a very clever student.' },
  { en:'brave',      tr:'cesur',           ipa:'/breɪv/',          cat:'Sıfatlar',     icon:'💪', ex:'The brave firefighter saved the child.' },
  { en:'kind',       tr:'nazik / iyi kalpli',ipa:'/kaɪnd/',       cat:'Sıfatlar',     icon:'💛', ex:'She is very kind to everyone.' },
  { en:'polite',     tr:'kibarlı',         ipa:'/pəˈlaɪt/',       cat:'Sıfatlar',     icon:'🤝', ex:'Always be polite to your teachers.' },
  { en:'rude',       tr:'kaba',            ipa:'/ruːd/',           cat:'Sıfatlar',     icon:'😤', ex:'It is rude to talk with your mouth full.' },
  { en:'lazy',       tr:'tembel',          ipa:'/ˈleɪzi/',         cat:'Sıfatlar',     icon:'🛌', ex:'He is too lazy to do his homework.' },
  { en:'careful',    tr:'dikkatli',        ipa:'/ˈkeəfəl/',       cat:'Sıfatlar',     icon:'⚠️', ex:'Be careful when you cross the road.' },
  { en:'correct',    tr:'doğru',           ipa:'/kəˈrekt/',       cat:'Sıfatlar',     icon:'✅', ex:'Your answer is correct.' },
  { en:'wrong',      tr:'yanlış',          ipa:'/rɒŋ/',            cat:'Sıfatlar',     icon:'❌', ex:'That answer is wrong.' },
  { en:'straight',   tr:'düz',             ipa:'/streɪt/',         cat:'Sıfatlar',     icon:'📏', ex:'Draw a straight line.' },
  { en:'round',      tr:'yuvarlak',        ipa:'/raʊnd/',          cat:'Sıfatlar',     icon:'⭕', ex:'The table is round.' },
  { en:'flat',       tr:'düz / yassı',     ipa:'/flæt/',           cat:'Sıfatlar',     icon:'🏢', ex:'They live in a flat.' },
  { en:'sharp',      tr:'keskin',          ipa:'/ʃɑːp/',           cat:'Sıfatlar',     icon:'🔪', ex:'Be careful — the knife is sharp.' },
  { en:'soft',       tr:'yumuşak',         ipa:'/sɒft/',           cat:'Sıfatlar',     icon:'🧸', ex:'The pillow is very soft.' },
  { en:'rough',      tr:'pürüzlü / sert',  ipa:'/rʌf/',            cat:'Sıfatlar',     icon:'🪨', ex:'The road is rough and bumpy.' },
  { en:'wet',        tr:'ıslak',           ipa:'/wet/',            cat:'Sıfatlar',     icon:'💧', ex:'My umbrella is wet.' },
  { en:'dry',        tr:'kuru',            ipa:'/draɪ/',           cat:'Sıfatlar',     icon:'☀️', ex:'The clothes are dry now.' },
  { en:'deep',       tr:'derin',           ipa:'/diːp/',           cat:'Sıfatlar',     icon:'🌊', ex:'The lake is very deep.' },
  { en:'loud',       tr:'gürültülü / yüksek sesli',ipa:'/laʊd/',  cat:'Sıfatlar',     icon:'📢', ex:'The music was very loud.' },
  { en:'silent',     tr:'sessiz',          ipa:'/ˈsaɪlənt/',      cat:'Sıfatlar',     icon:'🤫', ex:'Please be silent in the library.' },
  { en:'bright',     tr:'parlak',          ipa:'/braɪt/',          cat:'Sıfatlar',     icon:'✨', ex:'The sun is very bright today.' },
  { en:'sweet',      tr:'tatlı',           ipa:'/swiːt/',          cat:'Sıfatlar',     icon:'🍬', ex:'This cake is very sweet.' },
  { en:'bitter',     tr:'acı',             ipa:'/ˈbɪtə/',         cat:'Sıfatlar',     icon:'😬', ex:'Black coffee tastes bitter.' },
  { en:'salty',      tr:'tuzlu',           ipa:'/ˈsɔːlti/',       cat:'Sıfatlar',     icon:'🧂', ex:'The soup is too salty.' },
  { en:'sour',       tr:'ekşi',            ipa:'/ˈsaʊə/',         cat:'Sıfatlar',     icon:'🍋', ex:'Lemons taste sour.' },
  { en:'thick',      tr:'kalın',           ipa:'/θɪk/',            cat:'Sıfatlar',     icon:'📕', ex:'This is a very thick book.' },
  { en:'thin',       tr:'ince',            ipa:'/θɪn/',            cat:'Sıfatlar',     icon:'📄', ex:'The wall is thin.' },
  { en:'wide',       tr:'geniş',           ipa:'/waɪd/',           cat:'Sıfatlar',     icon:'↔️', ex:'The road is wide.' },
  { en:'narrow',     tr:'dar',             ipa:'/ˈnærəʊ/',        cat:'Sıfatlar',     icon:'↔️', ex:'The path is too narrow.' },
  { en:'cheap',      tr:'ucuz',            ipa:'/tʃiːp/',          cat:'Sıfatlar',     icon:'💰', ex:'These shoes are cheap.' },
  { en:'expensive',  tr:'pahalı',          ipa:'/ɪkˈspensɪv/',    cat:'Sıfatlar',     icon:'💸', ex:'This bag is very expensive.' },
  { en:'free',       tr:'ücretsiz / özgür',ipa:'/friː/',          cat:'Sıfatlar',     icon:'🆓', ex:'Entrance to the park is free.' },
  { en:'ready',      tr:'hazır',           ipa:'/ˈredi/',          cat:'Sıfatlar',     icon:'✅', ex:'Are you ready to go?' },
  { en:'late',       tr:'geç',             ipa:'/leɪt/',           cat:'Sıfatlar',     icon:'⏰', ex:'Sorry, I am late.' },
  { en:'early',      tr:'erken',           ipa:'/ˈɜːli/',          cat:'Sıfatlar',     icon:'⏰', ex:'She woke up early this morning.' },
  { en:'alone',      tr:'yalnız',          ipa:'/əˈləʊn/',        cat:'Sıfatlar',     icon:'🧍', ex:'She lives alone.' },
  { en:'together',   tr:'birlikte',        ipa:'/təˈɡeðə/',       cat:'Sıfatlar',     icon:'🤝', ex:'We did the project together.' },
  { en:'same',       tr:'aynı',            ipa:'/seɪm/',           cat:'Sıfatlar',     icon:'🔁', ex:'We live in the same street.' },
  { en:'different',  tr:'farklı',          ipa:'/ˈdɪfrənt/',      cat:'Sıfatlar',     icon:'🔀', ex:'These two colours are different.' },
  // ── Time Expressions ──────────────────────────────────────────────────────
  { en:'second',     tr:'saniye',          ipa:'/ˈsekənd/',       cat:'Zaman',        icon:'⏱️', ex:'Wait a second, please.' },
  { en:'minute',     tr:'dakika',          ipa:'/ˈmɪnɪt/',        cat:'Zaman',        icon:'⏱️', ex:'The bus comes in five minutes.' },
  { en:'hour',       tr:'saat',            ipa:'/ˈaʊə/',           cat:'Zaman',        icon:'🕐', ex:'The lesson lasts one hour.' },
  { en:'century',    tr:'yüzyıl',          ipa:'/ˈsentʃəri/',     cat:'Zaman',        icon:'📅', ex:'This building is from the last century.' },
  { en:'ago',        tr:'önce',            ipa:'/əˈɡəʊ/',          cat:'Zaman',        icon:'⏪', ex:'I moved here two years ago.' },
  { en:'already',    tr:'çoktan / zaten',  ipa:'/ɔːlˈredi/',      cat:'Zaman',        icon:'✅', ex:'She has already eaten.' },
  { en:'still',      tr:'hâlâ',            ipa:'/stɪl/',           cat:'Zaman',        icon:'⏸️', ex:'He is still sleeping.' },
  { en:'yet',        tr:'henüz / hâlâ',   ipa:'/jet/',            cat:'Zaman',        icon:'⌛', ex:'I haven\'t finished yet.' },
  { en:'soon',       tr:'yakında',         ipa:'/suːn/',           cat:'Zaman',        icon:'⏩', ex:'Dinner will be ready soon.' },
  { en:'again',      tr:'yeniden',         ipa:'/əˈɡen/',          cat:'Zaman',        icon:'🔁', ex:'Say that again, please.' },
  // ── School & Education ────────────────────────────────────────────────────
  { en:'class',      tr:'sınıf / ders',    ipa:'/klɑːs/',          cat:'Okul',         icon:'🏫', ex:'We have English class at nine.' },
  { en:'lesson',     tr:'ders',            ipa:'/ˈlesən/',         cat:'Okul',         icon:'📖', ex:'The lesson starts at eight.' },
  { en:'subject',    tr:'ders / konu',     ipa:'/ˈsʌbdʒɪkt/',     cat:'Okul',         icon:'📚', ex:'My favourite subject is maths.' },
  { en:'maths',      tr:'matematik',       ipa:'/mæθs/',           cat:'Okul',         icon:'➕', ex:'I like maths but it is difficult.' },
  { en:'science',    tr:'fen / bilim',     ipa:'/ˈsaɪəns/',       cat:'Okul',         icon:'🔬', ex:'We do science experiments in the lab.' },
  { en:'history',    tr:'tarih',           ipa:'/ˈhɪstri/',        cat:'Okul',         icon:'📜', ex:'History is my favourite lesson.' },
  { en:'art',        tr:'sanat',           ipa:'/ɑːt/',            cat:'Okul',         icon:'🎨', ex:'We paint in art class.' },
  { en:'music',      tr:'müzik',           ipa:'/ˈmjuːzɪk/',      cat:'Okul',         icon:'🎵', ex:'She loves music lessons.' },
  { en:'test',       tr:'sınav / test',    ipa:'/test/',           cat:'Okul',         icon:'📝', ex:'We have a maths test tomorrow.' },
  { en:'grade',      tr:'not / sınıf',     ipa:'/ɡreɪd/',          cat:'Okul',         icon:'⭐', ex:'She got a good grade in English.' },
  { en:'ruler',      tr:'cetvel',          ipa:'/ˈruːlə/',         cat:'Okul',         icon:'📏', ex:'Use the ruler to draw a straight line.' },
  { en:'rubber',     tr:'silgi',           ipa:'/ˈrʌbə/',         cat:'Okul',         icon:'✏️', ex:'Can I borrow your rubber?' },
  { en:'folder',     tr:'dosya',           ipa:'/ˈfəʊldə/',       cat:'Okul',         icon:'📁', ex:'Keep your papers in a folder.' },
  { en:'timetable',  tr:'ders programı',   ipa:'/ˈtaɪmteɪbəl/',   cat:'Okul',         icon:'📅', ex:'Check the timetable for your lessons.' },
  { en:'dictionary', tr:'sözlük',          ipa:'/ˈdɪkʃənri/',     cat:'Okul',         icon:'📖', ex:'Look the word up in the dictionary.' },
  { en:'university', tr:'üniversite',      ipa:'/ˌjuːnɪˈvɜːsɪti/',cat:'Okul',         icon:'🎓', ex:'She studies at university.' },
  { en:'chalk',      tr:'tebeşir',         ipa:'/tʃɔːk/',          cat:'Okul',         icon:'🖊️', ex:'The teacher wrote with chalk on the board.' },
  // ── Sports & Hobbies ──────────────────────────────────────────────────────
  { en:'football',   tr:'futbol',          ipa:'/ˈfʊtbɔːl/',      cat:'Spor',         icon:'⚽', ex:'We played football in the park.' },
  { en:'basketball', tr:'basketbol',       ipa:'/ˈbɑːskɪtbɔːl/',  cat:'Spor',         icon:'🏀', ex:'He plays basketball every week.' },
  { en:'tennis',     tr:'tenis',           ipa:'/ˈtenɪs/',        cat:'Spor',         icon:'🎾', ex:'They played tennis on the court.' },
  { en:'volleyball', tr:'voleybol',        ipa:'/ˈvɒlibɔːl/',     cat:'Spor',         icon:'🏐', ex:'Our school has a volleyball team.' },
  { en:'swimming',   tr:'yüzme',           ipa:'/ˈswɪmɪŋ/',       cat:'Spor',         icon:'🏊', ex:'She goes swimming twice a week.' },
  { en:'running',    tr:'koşu',            ipa:'/ˈrʌnɪŋ/',        cat:'Spor',         icon:'🏃', ex:'He goes running in the morning.' },
  { en:'cycling',    tr:'bisiklet sürme',  ipa:'/ˈsaɪklɪŋ/',      cat:'Spor',         icon:'🚴', ex:'Cycling is a great way to keep fit.' },
  { en:'yoga',       tr:'yoga',            ipa:'/ˈjəʊɡə/',        cat:'Spor',         icon:'🧘', ex:'She does yoga every morning.' },
  { en:'skiing',     tr:'kayak yapma',     ipa:'/ˈskiːɪŋ/',       cat:'Spor',         icon:'⛷️', ex:'He loves skiing in the mountains.' },
  { en:'guitar',     tr:'gitar',           ipa:'/ɡɪˈtɑː/',        cat:'Müzik',        icon:'🎸', ex:'He plays the guitar very well.' },
  { en:'piano',      tr:'piyano',          ipa:'/piˈænəʊ/',       cat:'Müzik',        icon:'🎹', ex:'She practises piano every day.' },
  { en:'drum',       tr:'davul',           ipa:'/drʌm/',           cat:'Müzik',        icon:'🥁', ex:'He plays the drums in a band.' },
  { en:'goal',       tr:'gol / hedef',     ipa:'/ɡəʊl/',           cat:'Spor',         icon:'⚽', ex:'He scored a goal in the last minute.' },
  { en:'team',       tr:'takım',           ipa:'/tiːm/',           cat:'Spor',         icon:'👥', ex:'We are all on the same team.' },
  { en:'player',     tr:'oyuncu',          ipa:'/ˈpleɪə/',        cat:'Spor',         icon:'⚽', ex:'He is the best player in the team.' },
  { en:'court',      tr:'kort / alan',     ipa:'/kɔːt/',           cat:'Spor',         icon:'🎾', ex:'The tennis court is wet today.' },
  { en:'race',       tr:'yarış',           ipa:'/reɪs/',           cat:'Spor',         icon:'🏁', ex:'She won the race.' },
  { en:'medal',      tr:'madalya',         ipa:'/ˈmedəl/',        cat:'Spor',         icon:'🏅', ex:'She won a gold medal.' },
  { en:'trophy',     tr:'kupa',            ipa:'/ˈtrəʊfi/',       cat:'Spor',         icon:'🏆', ex:'The team lifted the trophy.' },
  // ── Technology ────────────────────────────────────────────────────────────
  { en:'laptop',     tr:'dizüstü bilgisayar',ipa:'/ˈlæptɒp/',    cat:'Teknoloji',    icon:'💻', ex:'She works on her laptop.' },
  { en:'tablet',     tr:'tablet',          ipa:'/ˈtæblɪt/',      cat:'Teknoloji',    icon:'📱', ex:'He reads books on his tablet.' },
  { en:'charger',    tr:'şarj cihazı',     ipa:'/ˈtʃɑːdʒə/',     cat:'Teknoloji',    icon:'🔌', ex:'My charger is broken.' },
  { en:'keyboard',   tr:'klavye',          ipa:'/ˈkiːbɔːd/',     cat:'Teknoloji',    icon:'⌨️', ex:'She types on the keyboard quickly.' },
  { en:'screen',     tr:'ekran',           ipa:'/skriːn/',        cat:'Teknoloji',    icon:'🖥️', ex:'The screen is cracked.' },
  { en:'battery',    tr:'pil / batarya',   ipa:'/ˈbætəri/',      cat:'Teknoloji',    icon:'🔋', ex:'The battery is low.' },
  { en:'camera',     tr:'kamera / fotoğraf makinesi',ipa:'/ˈkæmərə/',cat:'Teknoloji',icon:'📷', ex:'She took photos with her camera.' },
  { en:'headphones', tr:'kulaklık',        ipa:'/ˈhedfəʊnz/',    cat:'Teknoloji',    icon:'🎧', ex:'He listens to music with headphones.' },
  { en:'microphone', tr:'mikrofon',        ipa:'/ˈmaɪkrəfəʊn/',  cat:'Teknoloji',    icon:'🎤', ex:'Speak into the microphone.' },
  { en:'password',   tr:'şifre',           ipa:'/ˈpɑːswɜːd/',    cat:'Teknoloji',    icon:'🔑', ex:'Don\'t share your password.' },
  // ── Health ────────────────────────────────────────────────────────────────
  { en:'headache',   tr:'baş ağrısı',      ipa:'/ˈhedeɪk/',      cat:'Sağlık',       icon:'🤕', ex:'I have a terrible headache.' },
  { en:'cough',      tr:'öksürük',         ipa:'/kɒf/',           cat:'Sağlık',       icon:'😷', ex:'He has a cough and a cold.' },
  { en:'cold',       tr:'soğuk algınlığı', ipa:'/kəʊld/',         cat:'Sağlık',       icon:'🤧', ex:'She has a cold this week.' },
  { en:'flu',        tr:'grip',            ipa:'/fluː/',           cat:'Sağlık',       icon:'🤒', ex:'He is in bed with the flu.' },
  { en:'pain',       tr:'ağrı',            ipa:'/peɪn/',           cat:'Sağlık',       icon:'😣', ex:'I feel pain in my leg.' },
  { en:'medicine',   tr:'ilaç',            ipa:'/ˈmedsɪn/',       cat:'Sağlık',       icon:'💊', ex:'Take this medicine twice a day.' },
  { en:'healthy',    tr:'sağlıklı',        ipa:'/ˈhelθi/',        cat:'Sağlık',       icon:'💪', ex:'Eat fresh food to stay healthy.' },
  { en:'sick',       tr:'hasta',           ipa:'/sɪk/',            cat:'Sağlık',       icon:'🤒', ex:'She stayed home because she was sick.' },
  { en:'tired',      tr:'yorgun',          ipa:'/ˈtaɪəd/',        cat:'Duygular',     icon:'😴', ex:'I am very tired after work.' },
  { en:'hungry',     tr:'aç',              ipa:'/ˈhʌŋɡri/',       cat:'Duygular',     icon:'🍽️', ex:'I am hungry — let\'s eat.' },
  { en:'thirsty',    tr:'susuz',           ipa:'/ˈθɜːsti/',       cat:'Duygular',     icon:'💧', ex:'I am thirsty — can I have some water?' },
  // ── Greetings & Communication ─────────────────────────────────────────────
  { en:'bye',        tr:'hoşça kal',       ipa:'/baɪ/',            cat:'İfadeler',     icon:'👋', ex:'Bye! See you tomorrow.' },
  { en:'hi',         tr:'merhaba',         ipa:'/haɪ/',            cat:'İfadeler',     icon:'👋', ex:'Hi! How are you?' },
  { en:'excuse me',  tr:'affedersiniz',    ipa:'/ɪkˈskjuːz miː/',cat:'İfadeler',     icon:'🙋', ex:'Excuse me, where is the station?' },
  { en:'how are you',tr:'nasılsın',        ipa:'/haʊ ɑː juː/',    cat:'İfadeler',     icon:'😊', ex:'How are you? — Fine, thanks.' },
  { en:'I am fine',  tr:'iyiyim',          ipa:'/aɪ æm faɪn/',    cat:'İfadeler',     icon:'😊', ex:'How are you? I am fine, thank you.' },
  { en:'what is your name',tr:'adın ne',   ipa:'/wɒt ɪz jə neɪm/',cat:'İfadeler',    icon:'🗣️', ex:'What is your name? My name is Ali.' },
  { en:'nice to meet you',tr:'tanıştığıma memnun oldum',ipa:'/naɪs tə miːt juː/',cat:'İfadeler',icon:'🤝', ex:'Nice to meet you!' },
  { en:'see you',    tr:'görüşürüz',       ipa:'/siː juː/',        cat:'İfadeler',     icon:'👋', ex:'See you on Monday.' },
  { en:'of course',  tr:'tabii ki',        ipa:'/əv kɔːs/',       cat:'İfadeler',     icon:'✅', ex:'Of course I will help you.' },
  { en:'no problem', tr:'sorun değil',     ipa:'/nəʊ ˈprɒbləm/', cat:'İfadeler',     icon:'👍', ex:'No problem — I can do that.' },
  // ── Misc Nouns ────────────────────────────────────────────────────────────
  { en:'birthday',   tr:'doğum günü',      ipa:'/ˈbɜːθdeɪ/',     cat:'Genel',        icon:'🎂', ex:'Happy birthday!' },
  { en:'party',      tr:'parti',           ipa:'/ˈpɑːti/',        cat:'Genel',        icon:'🎉', ex:'She had a party for her birthday.' },
  { en:'present',    tr:'hediye / şimdiki',ipa:'/ˈpreznt/',       cat:'Genel',        icon:'🎁', ex:'He gave me a birthday present.' },
  { en:'surprise',   tr:'sürpriz',         ipa:'/səˈpraɪz/',      cat:'Genel',        icon:'🎁', ex:'It was a lovely surprise.' },
  { en:'holiday',    tr:'tatil',           ipa:'/ˈhɒlədeɪ/',     cat:'Seyahat',      icon:'🏖️', ex:'We are going on holiday next week.' },
  { en:'trip',       tr:'gezi / yolculuk', ipa:'/trɪp/',           cat:'Seyahat',      icon:'🗺️', ex:'We went on a day trip to the coast.' },
  { en:'prize',      tr:'ödül',            ipa:'/praɪz/',          cat:'Genel',        icon:'🏅', ex:'She won first prize.' },
  { en:'sentence',   tr:'cümle',           ipa:'/ˈsentəns/',      cat:'Dil',          icon:'📝', ex:'Write a sentence about your family.' },
  { en:'language',   tr:'dil',             ipa:'/ˈlæŋɡwɪdʒ/',    cat:'Dil',          icon:'🗣️', ex:'She speaks three languages.' },
  { en:'colour',     tr:'renk',            ipa:'/ˈkʌlə/',         cat:'Genel',        icon:'🌈', ex:'What is your favourite colour?' },
  { en:'size',       tr:'beden / boyut',   ipa:'/saɪz/',           cat:'Genel',        icon:'📐', ex:'What size shoes do you wear?' },
  { en:'shape',      tr:'şekil',           ipa:'/ʃeɪp/',           cat:'Genel',        icon:'🔷', ex:'This cake has a round shape.' },
  { en:'age',        tr:'yaş',             ipa:'/eɪdʒ/',           cat:'Genel',        icon:'🎂', ex:'What age are you?' },
  { en:'address',    tr:'adres',           ipa:'/əˈdres/',        cat:'Genel',        icon:'📍', ex:'Can I have your address?' },
  { en:'price',      tr:'fiyat',           ipa:'/praɪs/',          cat:'Alışveriş',    icon:'🏷️', ex:'What is the price of this jacket?' },
  { en:'change',     tr:'bozuk para / değişiklik',ipa:'/tʃeɪndʒ/',cat:'Alışveriş',  icon:'💰', ex:'Here is your change.' },
  { en:'receipt',    tr:'fiş / makbuz',    ipa:'/rɪˈsiːt/',       cat:'Alışveriş',    icon:'🧾', ex:'Keep the receipt in case you return it.' },
  { en:'list',       tr:'liste',           ipa:'/lɪst/',           cat:'Genel',        icon:'📋', ex:'I made a shopping list.' },
  { en:'idea',       tr:'fikir',           ipa:'/aɪˈdɪə/',        cat:'Genel',        icon:'💡', ex:'That is a good idea.' },
  { en:'problem',    tr:'sorun',           ipa:'/ˈprɒbləm/',      cat:'Genel',        icon:'❓', ex:'Is there a problem?' },
  { en:'answer',     tr:'cevap',           ipa:'/ˈɑːnsə/',        cat:'Genel',        icon:'💬', ex:'Write your answer here.' },
  { en:'example',    tr:'örnek',           ipa:'/ɪɡˈzɑːmpəl/',   cat:'Genel',        icon:'📌', ex:'Give me an example.' },
  { en:'reason',     tr:'neden / sebep',   ipa:'/ˈriːzən/',       cat:'Genel',        icon:'💭', ex:'What is the reason for your visit?' },
  { en:'plan',       tr:'plan',            ipa:'/plæn/',           cat:'Genel',        icon:'📋', ex:'What is your plan for tomorrow?' },
  { en:'message',    tr:'mesaj',           ipa:'/ˈmesɪdʒ/',       cat:'İletişim',     icon:'💬', ex:'She sent me a message.' },
  { en:'call',       tr:'arama / aramak',  ipa:'/kɔːl/',           cat:'İletişim',     icon:'📞', ex:'I will call you tonight.' },
  { en:'number',     tr:'sayı / numara',   ipa:'/ˈnʌmbə/',        cat:'Genel',        icon:'🔢', ex:'What is your phone number?' },
  { en:'page',       tr:'sayfa',           ipa:'/peɪdʒ/',          cat:'Genel',        icon:'📄', ex:'Turn to page fifteen.' },
  { en:'line',       tr:'satır / çizgi',   ipa:'/laɪn/',           cat:'Genel',        icon:'➖', ex:'Write on the line.' },
  { en:'part',       tr:'bölüm / parça',   ipa:'/pɑːt/',           cat:'Genel',        icon:'🧩', ex:'This is the best part of the film.' },
  { en:'side',       tr:'yan / taraf',     ipa:'/saɪd/',           cat:'Genel',        icon:'↔️', ex:'Stand on this side of the road.' },
  { en:'end',        tr:'son',             ipa:'/end/',            cat:'Genel',        icon:'🏁', ex:'Wait until the end of the film.' },
  { en:'middle',     tr:'orta',            ipa:'/ˈmɪdl/',          cat:'Genel',        icon:'🎯', ex:'She sits in the middle of the class.' },
  { en:'top',        tr:'üst / tepe',      ipa:'/tɒp/',            cat:'Genel',        icon:'⬆️', ex:'Put the box on top of the shelf.' },
  { en:'bottom',     tr:'alt / dip',       ipa:'/ˈbɒtəm/',        cat:'Genel',        icon:'⬇️', ex:'The answer is at the bottom of the page.' },
  { en:'front',      tr:'ön',              ipa:'/frʌnt/',          cat:'Genel',        icon:'🔼', ex:'She sat at the front of the class.' },
  { en:'back',       tr:'arka',            ipa:'/bæk/',            cat:'Genel',        icon:'🔽', ex:'He sat at the back of the room.' },
];

let added = 0, skipped = 0;
const toAdd = [];

for (const w of newA1) {
  const key = w.en.toLowerCase().trim();
  if (existing.has(key)) {
    skipped++;
  } else {
    toAdd.push({
      id: w.en.toLowerCase().replace(/\s+/g, '_'),
      en: w.en,
      tr: w.tr,
      ipa: w.ipa,
      level: 'A1',
      cat: w.cat,
      icon: w.icon,
      ex: w.ex,
      syns: [],
      colloc: [],
    });
    existing.add(key);
    added++;
  }
}

console.log('Added: ' + added + ', Skipped (duplicate): ' + skipped);

const combined = WORDS.concat(toAdd);
const levels = {};
for (const w of combined) levels[w.level] = (levels[w.level] || 0) + 1;
console.log('Level counts:', JSON.stringify(levels));

require('fs').writeFileSync(
  require('path').join(__dirname, '../js/data.js'),
  'const WORDS = ' + JSON.stringify(combined, null, 2) + ';\n'
);
console.log('Written.');
