const fs = require('fs');

// CEFR Level Map for phrasal verbs
// Anything NOT listed here defaults to B1
const LEVELS = {
  // A1
  'call back':'A1','check in':'A1','check out':'A1','clean up':'A1',
  'come along':'A1','come back':'A1','come from':'A1','come in':'A1',
  'come on':'A1','come out':'A1','come over':'A1','come up':'A1',
  'get in':'A1','get off':'A1','get on':'A1','get out':'A1','get up':'A1',
  'give back':'A1','go back':'A1','go down':'A1','go on':'A1',
  'go out':'A1','go up':'A1','lie down':'A1','log in':'A1','log out':'A1',
  'look at':'A1','pick up':'A1','put down':'A1','put on':'A1',
  'sit down':'A1','stand up':'A1','take off':'A1','turn off':'A1',
  'turn on':'A1','type in':'A1','wake up':'A1',

  // A2
  'ask for':'A2','ask in':'A2','ask out':'A2',
  'bend down':'A2','bend over':'A2',
  'break down':'A2','break in':'A2','break into':'A2','break out':'A2','break up':'A2',
  'breathe in':'A2','breathe out':'A2',
  'bring back':'A2','bring up':'A2',
  'calm down':'A2','care about':'A2','carry on':'A2','catch up':'A2','catch up with':'A2',
  'check into':'A2','check up on':'A2','clean out':'A2',
  'close down':'A2','come across':'A2','come apart':'A2','come down':'A2','come to':'A2',
  'cool down':'A2','cool off':'A2','count on':'A2','cut down':'A2','cut off':'A2','cut up':'A2',
  'drop off':'A2','drop out':'A2',
  'eat out':'A2','eat up':'A2','end up':'A2',
  'fall down':'A2','fall off':'A2',
  'fill in':'A2','fill out':'A2','fill up':'A2','find out':'A2','fix up':'A2',
  'get away':'A2','get back':'A2','get into':'A2',
  'give in':'A2','give out':'A2','give up':'A2',
  'go ahead':'A2','go away':'A2','go in for':'A2','go through':'A2',
  'grow up':'A2',
  'hand in':'A2','hand out':'A2',
  'hang about':'A2','hang on':'A2','hang out':'A2','hang up':'A2',
  'hold on':'A2','hop on':'A2','hop out':'A2','hurry up':'A2',
  'join in':'A2','keep on':'A2','keep up':'A2','kneel down':'A2','knock out':'A2',
  'let in':'A2','let out':'A2','lock up':'A2',
  'look after':'A2','look for':'A2','look out':'A2','look up':'A2',
  'make up':'A2',
  'move in':'A2','move out':'A2','move on':'A2',
  'open up':'A2',
  'pass away':'A2','pass by':'A2','pass out':'A2',
  'pay back':'A2','pay for':'A2','pay off':'A2',
  'pick out':'A2','point out':'A2',
  'put away':'A2','put back':'A2','put off':'A2','put together':'A2','put up':'A2',
  'reach up':'A2','roll over':'A2',
  'run away':'A2','run into':'A2','run out':'A2','run out of':'A2',
  'save up':'A2','set up':'A2','settle down':'A2',
  'show off':'A2','show up':'A2','sign in':'A2','sign out':'A2',
  'sit up':'A2','slow down':'A2','sort out':'A2','speed up':'A2','split up':'A2',
  'start over':'A2','start up':'A2','stay up':'A2',
  'switch off':'A2','switch on':'A2',
  'take away':'A2','take back':'A2','take on':'A2','take out':'A2','take over':'A2',
  'talk about':'A2','think about':'A2','throw away':'A2',
  'try on':'A2','try out':'A2',
  'turn around':'A2','turn back':'A2','turn down':'A2','turn over':'A2','turn up':'A2',
  'use up':'A2','walk in':'A2','watch out':'A2','write down':'A2','zoom in':'A2',

  // B2 (explicit; everything else is B1)
  'ache for':'B2','act out':'B2','act up':'B2','add up to':'B2',
  'agree on':'B2','agree to':'B2','answer for':'B2','arise from':'B2','ask around':'B2',
  'attend to':'B2','average out':'B2',
  'back away':'B2','back down':'B2','back off':'B2','back out':'B2',
  'beat down':'B2','beat up':'B2',
  'blow away':'B2','blow off':'B2','blow over':'B2','blow up':'B2',
  'boil down':'B2','boil over':'B2','boil up':'B2',
  'boot up':'B2','bounce back':'B2','branch off':'B2','branch out':'B2',
  'build on':'B2','build up':'B2','burn down':'B2','burn out':'B2','burn up':'B2',
  'buy in':'B2','buy into':'B2','buy out':'B2','buy up':'B2',
  'catch on':'B2','catch out':'B2','cave in':'B2','clam up':'B2',
  'close in':'B2',
  'come by':'B2','come forward':'B2','come into':'B2','come through':'B2',
  'come round':'B2','come up against':'B2',
  'crack down':'B2','cross over':'B2',
  'cut back':'B2','cut across':'B2','cut away':'B2','cut back on':'B2','cut through':'B2',
  'dash off':'B2','die away':'B2','die down':'B2','do without':'B2',
  'drag on':'B2','drag behind':'B2','drag out':'B2',
  'draw back':'B2','draw away':'B2','draw back from':'B2','draw in':'B2','draw out':'B2','draw up':'B2',
  'drift apart':'B2','drift away':'B2','drift off':'B2',
  'drive up':'B2','drop through':'B2',
  'embark on':'B2','emerge from':'B2','even out':'B2',
  'face up to':'B2',
  'fall back':'B2','fall for':'B2','fall in':'B2','fall into':'B2','fall out':'B2',
  'fall out with':'B2','fall over':'B2','fall short':'B2','fall through':'B2','fall to pieces':'B2',
  'feel out':'B2','filter out':'B2','firm up':'B2',
  'fit out':'B2','flip through':'B2',
  'focus in on':'B2','follow through':'B2','force out':'B2',
  'get about':'B2','get across':'B2','get around':'B2','get at':'B2','get away with':'B2',
  'get behind':'B2','get out of':'B2','get rid of':'B2','go easy on':'B2',
  'go over to':'B2','go steady with':'B2','go under':'B2',
  'grow apart':'B2','grow into':'B2','grow on':'B2','grow out of':'B2',
  'hang back':'B2','head off':'B2',
  'hold back':'B2','hold down':'B2','hold in':'B2','hold off':'B2','hold out':'B2',
  'hunt down':'B2','iron out':'B2',
  'jump at':'B2','jump on':'B2',
  'knock back':'B2','knock down':'B2',
  'land on':'B2','lash out':'B2','laugh off':'B2','lay in':'B2','lay off':'B2','lay out':'B2','lay up':'B2',
  'lead away':'B2','lead on':'B2','lead up to':'B2',
  'let off':'B2','live up to':'B2','lock away':'B2','long for':'B2',
  'lose out':'B2','lose out on':'B2','lose track of':'B2',
  'make do':'B2','make out':'B2','make over':'B2','make up for':'B2',
  'map out':'B2','merge with':'B2','miss out':'B2','miss out on':'B2',
  'nod off':'B2',
  'object to':'B2','open onto':'B2','opt for':'B2','own up to':'B2',
  'pan out':'B2','pass over':'B2','pass up':'B2','peak at':'B2','peer through':'B2',
  'pick up on':'B2','pile up':'B2','pipe down':'B2','pitch in':'B2',
  'play down':'B2','play on':'B2','play out':'B2','play up':'B2',
  'plunge into':'B2',
  'pull away':'B2','pull back':'B2','pull in':'B2','pull off':'B2',
  'pull through':'B2','pull apart':'B2',
  'push ahead':'B2','push for':'B2','push through':'B2',
  'put in for':'B2','put through':'B2',
  'result from':'B2','roll back':'B2','roll out':'B2',
  'run across':'B2','run away with':'B2','run down':'B2','run through':'B2','run up':'B2',
  'rush into':'B2','scale back':'B2','scale down':'B2','scale up':'B2',
  'search through':'B2','see off':'B2','see out':'B2',
  'seek out':'B2','sell off':'B2','sell up':'B2',
  'set aside':'B2','set back':'B2','set out on':'B2',
  'shake off':'B2','shake up':'B2',
  'shoot down':'B2','shoot for':'B2','shoot up':'B2',
  'sit in on':'B2','sit through':'B2','slip away':'B2','slip up':'B2',
  'spill over':'B2','spring up':'B2',
  'stand in for':'B2','stand up to':'B2',
  'step aside':'B2','step down':'B2','step up':'B2',
  'stir up':'B2','strike back':'B2','strike out':'B2',
  'stumble across':'B2','stumble on':'B2','stumble upon':'B2','switch up':'B2',
  'take apart':'B2','take to':'B2',
  'talk back':'B2','talk down to':'B2','talk out of':'B2','talk through':'B2',
  'tear apart':'B2','tear down':'B2',
  'think through':'B2','throw back':'B2','throw off':'B2',
  'tie down':'B2','tip off':'B2','top off':'B2','touch on':'B2',
  'track back':'B2','tread on':'B2','tune out':'B2',
  'turn against':'B2','turn off to':'B2',
  'walk away':'B2','walk away from':'B2','walk out':'B2','warm up to':'B2','watch over':'B2',
  'work around':'B2',

  // C1
  'abandon to':'C1','abide by':'C1','abide with':'C1',
  'account for':'C1','allow for':'C1',
  'bail on':'C1',
  'bear down':'C1','bear down on':'C1','bear on':'C1','bear out':'C1','bear up':'C1','bear with':'C1',
  'beg off':'C1','bend over backwards':'C1','bind over':'C1',
  'blaze through':'C1','blaze up':'C1',
  'bog down':'C1','bolster up':'C1','border on':'C1','bound by':'C1',
  'bring off':'C1','bring round':'C1',
  'cap off':'C1','carry forward':'C1','carry through':'C1',
  'clear through':'C1','comply with':'C1','conjure up':'C1','crack down on':'C1',
  'crowd out':'C1','deal in':'C1','delve into':'C1','depart from':'C1',
  'descend on':'C1','die off':'C1','dismiss as':'C1','distinguish between':'C1',
  'do away with':'C1','do out of':'C1','dote on':'C1',
  'drag through':'C1','draw on':'C1','dump on':'C1','dwell on':'C1',
  'ease off':'C1','ease up':'C1','eat away at':'C1',
  'edge away':'C1','edge in':'C1',
  'face down':'C1','fall back on':'C1',
  'fend for':'C1','fend off':'C1','flag up':'C1','flush out':'C1',
  'fret about':'C1','gain on':'C1',
  'go between':'C1','grind down':'C1',
  'hold forth':'C1','hole up':'C1','hollow out':'C1',
  'isolate from':'C1',
  'latch on to':'C1','lay aside':'C1','let on':'C1','lie low':'C1','linger on':'C1','live down':'C1',
  'make for':'C1','make off':'C1','make off with':'C1',
  'narrow down':'C1',
  'opt out':'C1','phase out':'C1','pine for':'C1','plough through':'C1','pore over':'C1',
  'reason with':'C1','reconcile with':'C1','rein in':'C1',
  'rule out':'C1','rule over':'C1',
  'scrape through':'C1','screen out':'C1','see through':'C1',
  'set against':'C1','shy away':'C1','sign over':'C1','single out':'C1',
  'sleep on':'C1','slip through':'C1',
  'stand down':'C1','stand up for':'C1','steer clear of':'C1','stick up for':'C1',
  'string along':'C1',
  'tap into':'C1','tear into':'C1','tie in with':'C1','toss up':'C1','trace back to':'C1',
  'unwind from':'C1','venture into':'C1','wade through':'C1','walk out on':'C1',
  'zero in':'C1','zero in on':'C1',

  // C2
  'bog off':'C2','bulldoze through':'C2','bug out':'C2','bulge out':'C2',
  'ferret out':'C2','flog off':'C2','give forth':'C2',
  'hang together':'C2','hang with':'C2','ink out':'C2','intersperse with':'C2',
  'reframe as':'C2','trickle down':'C2','whistle for':'C2',
};

function processFile(filePath) {
  let content = fs.readFileSync(filePath, 'utf8');
  let count = 0;

  // Only process entries that do NOT already have a level field
  content = content.replace(
    /^(\s+'([^']+)':\s+)\{(\s*type:'Phrasal Verb',)(?!\s*level:)/gm,
    (match, prefix, phrase, opening) => {
      const level = LEVELS[phrase] || 'B1';
      count++;
      return `${prefix}{${opening} level:'${level}',`;
    }
  );

  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`${filePath}: ${count} entries tagged`);
}

processFile('C:/Users/ruhme/english-rhapsody-push/js/phrasal_verbs_ext.js');
processFile('C:/Users/ruhme/english-rhapsody-push/js/phrasal_verbs_ext2.js');
