/**
 * Rebuilds phrasal_verbs_ext3.js:
 *  1. Removes entries that duplicate keys already in ext1/ext2
 *  2. Removes intra-file duplicates
 *  3. Appends new unique entries to reach 250 per non-B1 level
 */
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');

// ── existing keys (ext1 + ext2) ──────────────────────────────────────────────
const existing = new Set();
['js/phrasal_verbs_ext.js','js/phrasal_verbs_ext2.js'].forEach(f => {
  const c = fs.readFileSync(path.join(ROOT, f), 'utf8');
  const re = /^\s+'([^']+)':\s+\{/gm;
  let m;
  while ((m = re.exec(c)) !== null) existing.add(m[1]);
});

// ── clean ext3 ────────────────────────────────────────────────────────────────
const ext3Raw = fs.readFileSync(path.join(ROOT, 'js/phrasal_verbs_ext3.js'), 'utf8');
const rawLines = ext3Raw.split('\n');
const cleanLines = [];
const ext3Seen = new Set();
const entryRe = /^(\s+'([^']+)':\s+\{.*\},?)$/;

for (const line of rawLines) {
  if (line.trim() === '});') continue;          // will append at end
  const m = entryRe.exec(line);
  if (m) {
    const key = m[2];
    if (existing.has(key) || ext3Seen.has(key)) continue;
    ext3Seen.add(key);
  }
  cleanLines.push(line);
}

const allUsed = new Set([...existing, ...ext3Seen]);

// ── new entry candidates ──────────────────────────────────────────────────────
// Each: [key, tr, ex]
const CANDIDATES = {
  A1: [
    ['bite into','ısırmak; içine girmek','She bit into the apple with a loud crunch.'],
    ['blow off','üfleyerek uçurmak','The wind blew off his hat in the street.'],
    ['brush away','fırçalamak; itmek','She brushed away the crumbs from the table.'],
    ['button down','düğmelerini iliklemek','Button down your shirt before the interview.'],
    ['climb on','tırmanmak; binmek','She climbed on the bus before the doors closed.'],
    ['come apart','parçalanmak; dağılmak','The old book came apart when she opened it.'],
    ['count up','toplamak; saymak','Count up all the coins in the jar.'],
    ['cut across','keserek geçmek','He cut across the park to get home faster.'],
    ['dry off','kurumak; kurulamak','Dry off with a towel after your shower.'],
    ['fall apart','dağılmak; çökmek','The old chair fell apart when he sat on it.'],
    ['fold away','katlanarak saklamak','The bed folds away to save space in the room.'],
    ['fold down','aşağı katlamak','Fold down the seat to make more room in the car.'],
    ['fold up','katlamak','Fold up the chairs and put them in the cupboard.'],
    ['get off at','durakta inmek','Get off at the second stop after the bridge.'],
    ['grab onto','tutunmak; kavramak','Grab onto the railing as you go downstairs.'],
    ['head back','geri dönmek','We headed back home after the picnic.'],
    ['hook up','bağlamak; takmak','Hook up the cable to the television.'],
    ['jump down','aşağı atlamak','She jumped down from the wall carefully.'],
    ['jump up','yukarı atlamak; sıçramak','The dog jumped up to greet its owner.'],
    ['kick off','tekmelemek; başlatmak','They kicked off the game at three o\'clock.'],
    ['knock over','devirmek','He knocked over the glass of water by accident.'],
    ['lean against','yaslanmak','She leaned against the wall while she waited.'],
    ['leave behind','geride bırakmak','Don\'t leave behind your umbrella.'],
    ['let go','bırakmak; serbest bırakmak','Let go of the rope when I say now.'],
    ['lift up','yukarı kaldırmak','She lifted up the heavy box with both hands.'],
    ['line up','sıraya girmek; hizalamak','Please line up at the entrance.'],
    ['lock away','kilitleye saklamak','She locked away the jewellery in the safe.'],
    ['look down','aşağı bakmak','Look down at the steps so you don\'t fall.'],
    ['move back','geri gitmek; geri çekilmek','Move back from the stage a little.'],
    ['pass by','yanından geçmek','Several cars passed by without stopping.'],
    ['pay for','ödemek; parasını vermek','She paid for the coffee with a card.'],
    ['pick up','almak; toplamak','Pick up your bag and follow me.'],
    ['pin up','asmak; iğnelemek','She pinned up the notice on the board.'],
    ['point out','göstermek; işaret etmek','He pointed out the mistake in the text.'],
    ['pour away','döküp atmak','Pour away the cold tea and make a fresh cup.'],
    ['press up','yukarı basmak; şınav çekmek','Press up your whole body in one smooth move.'],
    ['pull down','aşağı çekmek; yıkmak','She pulled down the blinds to block the sun.'],
    ['pull off','çıkarmak; başarmak','He pulled off his boots at the door.'],
    ['push forward','öne itmek; ilerlemek','She pushed forward through the crowd.'],
    ['reach up','uzanmak; yukarı uzanmak','She reached up to get the book from the shelf.'],
    ['run around','etrafında koşmak','The children ran around the garden all afternoon.'],
    ['run out','dışarı koşmak; bitmek','She ran out of the classroom when the bell rang.'],
    ['sail by','yanından geçmek','A large ship sailed by on the horizon.'],
    ['shake hands','el sıkışmak','They shook hands at the end of the meeting.'],
    ['shine on','üzerine parlamak','The sun shone on the water all day long.'],
    ['shut off','kapatmak; söndürmek','Shut off the engine before you get out.'],
    ['sing along','eşlik etmek; beraber şarkı söylemek','Everyone sang along to the chorus.'],
    ['slow up','yavaşlamak','Slow up near the school zone, please.'],
    ['snap up','kapmak; atlamak','Snap up the deal before it is too late.'],
    ['step off','inmek; adım atarak ayrılmak','She stepped off the train onto the platform.'],
    ['stop off','ara vermek; uğramak','We stopped off at a café on the way home.'],
    ['take care','dikkat etmek','Take care when crossing the road.'],
    ['take in','anlamak; almak','It took a moment to take in what she said.'],
    ['throw out','atmak; çıkarmak','Throw out the old magazines you don\'t need.'],
    ['turn around','dönmek; geri çevirmek','She turned around and walked back home.'],
    ['type up','yazmak; temize çekmek','I need to type up my notes from the meeting.'],
    ['walk in','içeri girmek','She walked in and took her seat.'],
    ['walk on','yürümeye devam etmek','Walk on ahead — I will catch up.'],
    ['wash away','yıkamak; süpürmek','The rain washed away the chalk marks.'],
    ['wash off','yıkayarak çıkarmak','This paint washes off with water.'],
    ['wear out','yıpranmak; yormak','These shoes wear out very quickly.'],
    ['wind down','sakinleşmek; azalmak','She listened to music to wind down before bed.'],
    ['wrap up','sarmak; bitirmek','Wrap up the present before the party.'],
    ['zoom out','uzaklaşmak; küçültmek','Zoom out to see the whole map.'],
    ['brush up','tazelemek; tekrar etmek','Brush up your English before the trip.'],
    ['check through','kontrol etmek; gözden geçirmek','Check through your work before handing it in.'],
    ['come in for','maruz kalmak; almak','The plan came in for a lot of criticism.'],
    ['count off','saymak; birer birer saymak','He counted off the names on the list.'],
    ['go round','dolaşmak; yetmek','Is there enough food to go round?'],
    ['hand up','yukarı uzatmak; el kaldırmak','Hands up if you know the answer.'],
    ['head out','dışarı çıkmak','We headed out early to beat the traffic.'],
    ['hold up','kaldırmak; durdurmak','Hold up the sign so everyone can see it.'],
    ['kick in','devreye girmek; etki göstermek','The medicine will kick in after about an hour.'],
    ['knock off','düşürmek; vurup düşürmek','He knocked the glass off the table by accident.'],
    ['lay on','uzanmak; sağlamak','Lay on your back and close your eyes.'],
    ['lean on','yaslanmak; dayanmak','She leaned on the wall to rest her back.'],
    ['leave on','açık bırakmak','Don\'t leave on the lights when you go out.'],
    ['let through','geçirmek; izin vermek','The guard let us through the gate.'],
    ['lie back','geri uzanmak; yaslanmak','Lie back and close your eyes for a moment.'],
    ['link together','birbirine bağlamak','Link together all the pieces to finish the puzzle.'],
    ['look away','başka tarafa bakmak','She looked away when he walked past.'],
    ['look back','geriye bakmak; dönüp bakmak','Don\'t look back — just keep moving forward.'],
    ['look on','seyretmek; izlemek','A crowd of people looked on as the fire spread.'],
    ['move forward','ilerlemek; öne geçmek','Please move forward to let others on the bus.'],
    ['open out','açılmak; genişlemek','The path opens out into a large square.'],
    ['pour out','dökmek; boşaltmak','She poured out a glass of cold water.'],
    ['pull up','durdurmak; durmak','The car pulled up outside the school.'],
    ['push up','yukarı itmek; şınav yapmak','Push up the window to let some air in.'],
    ['put back on','geri takmak; tekrar giymek','She put her glasses back on to read the sign.'],
    ['reach down','aşağı uzanmak','She reached down to pick up her pen.'],
    ['reach out','uzanmak; yardım istemek','He reached out and took her hand.'],
    ['reach over','uzanmak; karşıya uzanmak','Can you reach over and pass the salt?'],
    ['roll down','aşağı yuvarlamak; indirmek','Roll down the window a little, please.'],
    ['rub off','ovarak temizlemek; silinmek','The paint rubbed off on my sleeve.'],
    ['rub out','silmek; kalemle silmek','She rubbed out the wrong answer.'],
    ['run back','geri koşmak','He ran back to get his forgotten keys.'],
    ['run forward','öne koşmak','The children ran forward to meet their father.'],
    ['scratch off','kazımak; kaşımak','Scratch off the silver panel to see your prize.'],
    ['set off for','yola çıkmak; doğru gitmek','We set off for the mountains early in the morning.'],
    ['shake out','silkelemek; çırpmak','Shake out the tablecloth before folding it.'],
    ['sit still','kımıldamamak; hareketsiz oturmak','Please sit still while I take your photo.'],
    ['skip over','atlamak; geçmek','She skipped over the boring parts of the book.'],
    ['slide over','kaymak; yanına geçmek','Slide over so I can sit next to you.'],
    ['snap off','kırmak; koparmak','She snapped off a square of chocolate.'],
    ['stand back','geri çekilmek; uzak durmak','Stand back from the edge of the platform.'],
    ['step back','geri adım atmak','Step back and look at the whole picture.'],
    ['step forward','öne çıkmak; ileri adım atmak','Anyone who wants to help, please step forward.'],
    ['step over','üstünden geçmek; atlamak','Step over the puddle so you don\'t get wet.'],
    ['stir in','içine karıştırmak','Stir in the milk slowly until smooth.'],
    ['sweep away','süpürmek; sürüklemek','She swept away the dust with a broom.'],
    ['sweep off','silip süpürmek; almak','The wind swept off his hat.'],
    ['tap on','hafifçe vurmak; tıklatmak','She tapped on the door before entering.'],
    ['tear off','yırtmak; koparmak','Tear off the wrapper before eating.'],
    ['tip over','devirmek; devrilmek','Be careful not to tip over the vase.'],
    ['toss out','atmak; fırlatmak','Please toss out the rubbish on your way out.'],
    ['touch up','rötuş yapmak; düzeltmek','She touched up her makeup before going in.'],
    ['tuck in','içine sokmak; yatırmak','He tucked in his shirt before the interview.'],
    ['tuck away','saklamak; içine yerleştirmek','She tucked away some money for later.'],
    ['tug at','çekmek; tutup çekmek','The child tugged at his mother\'s sleeve.'],
    ['tug on','çekmek; asılmak','He tugged on the rope to test its strength.'],
    ['twist off','döndürerek açmak','Twist off the cap to open the bottle.'],
    ['walk around','etrafında dolaşmak','We walked around the town for an hour.'],
    ['walk off','yürüyerek gitmek; uzaklaşmak','She walked off without saying goodbye.'],
    ['walk up','yaklaşmak; üst kata çıkmak','He walked up to her and introduced himself.'],
    ['wave away','el sallayarak geri çevirmek','She waved away the waiter politely.'],
    ['wave back','el sallayarak karşılık vermek','He waved back from across the street.'],
    ['wave off','el sallayarak geçirmek','They waved off the departing guests.'],
    ['wipe down','yüzeyi silerek temizlemek','Wipe down the counter after cooking.'],
    ['wipe away','silerek temizlemek','She wiped away her tears with a tissue.'],
    ['wrap around','sarmak; etrafına sarmak','She wrapped the scarf around her neck.'],
    ['zip up','fermuarını çekmek','Zip up your jacket — it is very cold.'],
  ],
  A2: [
    ['act up','yaramazlık yapmak; sorun çıkarmak','The engine started acting up on the motorway.'],
    ['ask around','sormak; araştırmak','Ask around and see if anyone knows a good plumber.'],
    ['be in for','beklemek; maruz kalmak','We are in for a big storm tonight.'],
    ['be out of','bitmek; kalmamak','We are out of milk — I\'ll buy some more.'],
    ['bow out','çekilmek; vazgeçmek','She bowed out of the competition after round two.'],
    ['branch out','yeni alanlara girmek','The bakery branched out and started selling sandwiches.'],
    ['build up','birikmek; artmak','Traffic builds up in the city centre every morning.'],
    ['burn up','tamamen yakmak; alevlenmek','The letter burned up in the fireplace.'],
    ['call up','aramak; askere çağırmak','I\'ll call up the office first thing tomorrow.'],
    ['cash in','bozdurarak para almak','She cashed in her savings to pay for the trip.'],
    ['cave in','çökmek; boyun eğmek','The tunnel caved in after the heavy rainfall.'],
    ['clam up','susmak; ağzını açmamak','He clammed up as soon as the detective arrived.'],
    ['click on','tıklamak','Click on the icon to open the programme.'],
    ['cloud over','bulutlanmak','The sky clouded over just before the storm.'],
    ['come along','gelmek; katılmak','Would you like to come along to the concert tonight?'],
    ['come clean','itiraf etmek','He finally came clean about what had happened.'],
    ['come out','ortaya çıkmak; çıkmak','The results come out at the end of the month.'],
    ['cook up','uydurmak; pişirmek','She cooked up a quick meal from leftovers.'],
    ['cool off','serinlemek; yatışmak','Let him cool off before you try to talk to him.'],
    ['cut back','kısmak; azaltmak','We need to cut back on unnecessary spending.'],
    ['dig up','kazmak; ortaya çıkarmak','Gardeners dug up an old coin in the back garden.'],
    ['dish out','dağıtmak; vermek','He was quick to dish out advice but slow to take it.'],
    ['do over','tekrar yapmak; yeniden düzenlemek','She did over the whole report after the feedback.'],
    ['dream of','hayal etmek','She dreamed of travelling the world one day.'],
    ['drift into','sürüklenmek; dalıp girmek','He drifted into a deep sleep on the sofa.'],
    ['drop by','uğramak','Drop by any time — we are usually home.'],
    ['drop in','uğramak; ziyaret etmek','She dropped in on her parents on the way home.'],
    ['dwell on','takılmak; düşünmek','Try not to dwell on past mistakes.'],
    ['ease off','hafiflemek; rahatlamak','The pain eased off after she took the tablet.'],
    ['eat out','dışarıda yemek yemek','They eat out every Friday evening.'],
    ['fall for','aşık olmak; kanmak','He fell for the oldest trick in the book.'],
    ['fall out','kavga etmek; dökülmek','She fell out with her sister over money.'],
    ['fall over','düşmek','She slipped on the ice and fell over.'],
    ['fall through','suya düşmek','The deal fell through at the last moment.'],
    ['fire up','coşturmak; başlatmak','Fire up the grill and get the food ready.'],
    ['fly in','uçakla gelmek','He flew in from Paris especially for the wedding.'],
    ['follow through','tamamlamak; sonuna götürmek','Start the task and follow through to the end.'],
    ['fool around','eğlenmek; vakit geçirmek','Stop fooling around and get to work.'],
    ['get away','kaçmak; tatile gitmek','We are hoping to get away for a few days.'],
    ['get on','binmek; ilerlemek','Get on the bus at stop number three.'],
    ['give away','dağıtmak; ihanet etmek','He gave away all his old books to charity.'],
    ['go ahead','devam etmek; başlamak','Go ahead and start without me.'],
    ['go in for','girmek; sevmek','She goes in for long-distance running.'],
    ['go through','geçmek; incelemek','We need to go through the contract carefully.'],
    ['grow apart','birbirinden uzaklaşmak','Old friends sometimes grow apart over the years.'],
    ['hurry up','hızlanmak; acele etmek','Hurry up — the bus leaves in five minutes.'],
    ['keep on','devam etmek','Keep on walking until you reach the crossroads.'],
    ['log in','giriş yapmak','Log in with your username and password.'],
    ['look after','bakmak; ilgilenmek','She looks after her neighbour\'s cat at weekends.'],
    ['look for','aramak','I am looking for my car keys.'],
    ['make out','anlamak; başarılı olmak','I could not make out what he was saying.'],
    ['move in','taşınmak','They move in to the new flat next week.'],
    ['move on','devam etmek; ilerlemek','It is time to move on from this topic.'],
    ['move out','taşınmak','She moved out of her parents\' house last year.'],
    ['nod off','uyuyakalmak','He nodded off during the long presentation.'],
    ['open up','açılmak; konuşmak','She opened up about her feelings for the first time.'],
    ['pass out','bayılmak; dağıtmak','She nearly passed out from the heat.'],
    ['pay back','geri ödemek','I will pay back the money I owe you next week.'],
    ['pay off','fayda vermek; ödemek','Hard work always pays off in the end.'],
    ['pick out','seçmek; belirlemek','She picked out a dress for the occasion.'],
    ['pull through','atlatmak; iyileşmek','The doctors said she should pull through.'],
    ['put together','bir araya getirmek','She put together a team of volunteers.'],
    ['put up','koymak; konaklamak; tahammül etmek','They put us up for the night.'],
    ['run away','kaçmak','The dog ran away when it heard the thunder.'],
    ['run into','çarpmak; karşılaşmak','I ran into my old teacher at the market.'],
    ['run out of','tükenmek','We ran out of milk this morning.'],
    ['save up','biriktirmek','She saved up for months to buy the camera.'],
    ['set up','kurmak; hazırlamak','He set up his own business at twenty-five.'],
    ['settle down','yerleşmek; sakinleşmek','They settled down in a small village.'],
    ['show off','gösteriş yapmak','He loves showing off his new sports car.'],
    ['show up','gelmek; ortaya çıkmak','She showed up two hours late.'],
    ['sign in','giriş yapmak; imzalamak','Sign in at the reception when you arrive.'],
    ['sign out','çıkış yapmak','Don\'t forget to sign out when you leave.'],
    ['sit down','oturmak','Sit down and make yourself comfortable.'],
    ['slow down','yavaşlamak','Slow down near the school — children are playing.'],
    ['speed up','hızlanmak','The production line needs to speed up.'],
    ['split up','ayrılmak; bölmek','The group split up to search the area.'],
    ['stand up','ayağa kalkmak','Stand up when the judge enters the room.'],
    ['start up','başlamak; kurmak','She started up a new café last spring.'],
    ['stay up','uyanık kalmak','He stayed up all night to finish the project.'],
    ['switch off','kapatmak; söndürmek','Switch off the lights when you leave.'],
    ['switch on','açmak','Switch on the kettle and I\'ll make tea.'],
    ['take away','götürmek; almak','The waiter took away the empty plates.'],
    ['take back','geri almak; geri götürmek','She took back everything she had said.'],
    ['take over','devralmak','He took over the company from his father.'],
    ['turn around','dönmek; başarıya ulaşmak','They turned around the struggling business.'],
    ['turn back','geri dönmek','They had to turn back because of the snow.'],
    ['turn down','reddetmek; kısmak','She turned down the job offer.'],
    ['use up','tüketmek; bitirmek','We used up all the flour making bread.'],
    ['watch out','dikkat etmek','Watch out — there is ice on the pavement.'],
    ['wind up','bitmek; sona ermek','How did you wind up here?'],
    ['write down','not almak; yazmak','Write down your ideas before you forget them.'],
    ['zoom in','yakınlaştırmak','Zoom in on the detail in the bottom left corner.'],
    ['break away from','kurtulmak; kopmak','She broke away from the group to walk alone.'],
    ['burn off','yakmak; eritip yok etmek','Exercise helps burn off extra calories.'],
    ['carry off','başarmak; götürmek','She carried off first prize at the competition.'],
    ['charge up','şarj etmek; doldurmak','Charge up your phone before the flight.'],
    ['check on','kontrol etmek; bakmak','Check on the baby every hour while she sleeps.'],
    ['close out','bitirmek; kapatmak','They closed out the sale at the end of the month.'],
    ['copy down','not almak; kopyalamak','Please copy down the homework from the board.'],
    ['dart off','fırlamak; hızla gitmek','He darted off before I could say goodbye.'],
    ['dial up','aramak; çevirmek','Dial up the customer service number for help.'],
    ['doze off','uyuyakalmak; hafif uykuya dalmak','She dozed off during the long train journey.'],
    ['empty out','boşaltmak; içini dökmek','Empty out your pockets before washing your clothes.'],
    ['end off','bitirmek; sona erdirmek','He ended off the speech with a funny story.'],
    ['enter into','girmek; başlamak','They entered into a formal agreement last week.'],
    ['feel up to','kendini yetkin hissetmek','I don\'t feel up to going out tonight.'],
    ['freshen up','temizlenmek; tazelemek','Let me freshen up before we go to the restaurant.'],
    ['get on for','yaklaşmak (yaş/saat için)','It is getting on for midnight — time to sleep.'],
    ['heat up','ısınmak; ısıtmak','Heat up the soup before serving it.'],
    ['iron out','düzeltmek; sorunları çözmek','We need to iron out the details before signing.'],
    ['join together','birleştirmek; birleşmek','The two clubs joined together to form one team.'],
    ['keep off','uzak durmak; çekilmek','Please keep off the grass in the garden.'],
    ['look ahead','ileriye bakmak; plan yapmak','Try to look ahead and plan your schedule.'],
    ['make it to','varmak; yetişmek','Did you make it to the concert on time?'],
    ['meet up with','buluşmak; bir araya gelmek','I met up with some old classmates at the café.'],
    ['mop up','silmek; temizlemek','Mop up the spill before someone slips.'],
    ['note down','not almak; yazmak','Note down the main points of the lecture.'],
    ['pass around','elden ele geçirmek; dolaştırmak','Pass around the photos so everyone can see.'],
    ['pay attention to','dikkat etmek','Please pay attention to the instructions.'],
    ['pile into','içine dolmak','The children piled into the back of the car.'],
    ['plug in','prize takmak; bağlamak','Plug in the charger before the battery dies.'],
    ['print off','yazdırmak; çıktı almak','Print off a copy of the form for your records.'],
    ['read back','geri okumak; tekrar okumak','The operator read back my order to confirm it.'],
    ['read over','üzerinden geçmek; gözden geçirmek','Read over your essay before you hand it in.'],
    ['ring back','geri aramak','I\'ll ring back as soon as I\'m free.'],
    ['rush around','koşturmak; oraya buraya koşmak','She rushed around all morning getting ready.'],
    ['save on','tasarruf etmek; tutumlu olmak','We saved on heating by wearing warmer clothes.'],
    ['show around','gezdirmek; tur vermek','He showed us around the new office building.'],
    ['sign up for','kaydolmak; başvurmak','She signed up for a yoga class last week.'],
    ['sleep over','misafir kalmak; gece kalmak','Can I sleep over at your house on Friday?'],
    ['speak out','açıkça konuşmak; sesini yükseltmek','She spoke out against unfair treatment.'],
    ['spread out','yaymak; dağılmak','Spread out the map on the table to read it.'],
    ['stick together','birlikte olmak; ayrılmamak','The team needs to stick together through tough times.'],
    ['stroll around','gezmek; tur atmak','They strolled around the old market for an hour.'],
    ['swap over','değiştirmek; yer değiştirmek','Can we swap over so I sit by the window?'],
    ['talk over','konuşmak; tartışmak','We need to talk over the plan before deciding.'],
    ['tick off','işaretlemek; azarlamak','Tick off each item as you finish it.'],
    ['tidy away','kaldırmak; düzenlemek','Tidy away your toys before dinner.'],
    ['trim off','kırpmak; kesmek','Trim off the fat before cooking the meat.'],
    ['turn in','yatmaya gitmek; teslim etmek','I\'m tired — I think I\'ll turn in early tonight.'],
  ],
  B2: [
    ['bank on','güvenmek; hesaba katmak','Don\'t bank on getting a pay rise this year.'],
    ['bargain for','beklemek; hesaba katmak','She got more than she bargained for at the negotiation.'],
    ['cling to','sarılmak; tutunmak; bağlı kalmak','He clung to the hope that things would improve.'],
    ['cotton on','anlamak; kavramak','It took him a while to cotton on to the joke.'],
    ['count against','aleyhine olmak; dezavantaj oluşturmak','His lack of experience counted against him.'],
    ['cut corners','köşe kesmek; kaliteyi düşürmek','Don\'t cut corners on safety to save money.'],
    ['die hard','kolay ölmemek; değişmemek','Old habits die hard, especially in organisations.'],
    ['fizzle out','fiyasko olmak; sönerek bitmek','The excitement quickly fizzled out after the news.'],
    ['flare up','alevlenmek; şiddetlenmek','Tension flared up again at the border.'],
    ['hammer out','çözüme kavuşturmak; anlaşmak','They hammered out an agreement after long talks.'],
    ['hit back at','karşılık vermek; yanıtlamak','She hit back at critics in her next speech.'],
    ['home in on','hedef almak; odaklanmak','Investigators homed in on the key suspect.'],
    ['muddle through','idare etmek; geçiştirmek','We don\'t have a plan but we\'ll muddle through.'],
    ['phase in','aşamalı olarak getirmek','The new rules will be phased in over two years.'],
    ['rip off','dolandırmak; fahiş fiyat almak','Tourists are often ripped off in crowded markets.'],
    ['rope in','dahil etmek; razı etmek','She was roped in to help at the last minute.'],
    ['round off','tamamlamak; yuvarlamak','We rounded off the evening with dessert and coffee.'],
    ['run by','danışmak; öğrenmek için söylemek','Can you run that idea by me again?'],
    ['slim down','zayıflamak; küçültmek','The company slimmed down its workforce last year.'],
    ['snap up','kapmak; hemen almak','She snapped up the last ticket for the concert.'],
    ['sort through','ayrıştırarak incelemek','She sorted through the old photos in the attic.'],
    ['stand by','destek olmak; beklemek','I will always stand by my decision.'],
    ['sum up','özetlemek','Can you sum up the main points of the article?'],
    ['take stock of','değerlendirmek; durumu gözden geçirmek','It is time to take stock of what we have achieved.'],
    ['throw up','kusmak; ortaya çıkarmak','The research threw up some surprising results.'],
    ['tide over','idare etmek; geçiştirmek','Could you lend me some money to tide me over?'],
    ['tighten up','sıkılaştırmak; iyileştirmek','The manager tightened up the rules on attendance.'],
    ['trade off','takas yapmak; değiş tokuş yapmak','You have to trade off cost against quality.'],
    ['trigger off','tetiklemek; başlatmak','A single remark triggered off a long argument.'],
    ['water down','hafifletmek; sulandırmak','The original proposal was watered down significantly.'],
    ['whip up','aceleyle hazırlamak; kışkırtmak','She whipped up a meal in less than twenty minutes.'],
    ['wipe out','yok etmek; silmek','The storm wiped out several coastal villages.'],
    ['wind up','sona ermek; mahkeme karşısına çıkmak','He wound up in court over the unpaid debt.'],
  ],
  C1: [
    ['abstain from','kaçınmak; uzak durmak','Several MPs abstained from voting on the bill.'],
    ['accrue to','birikmek; kazanmak','Significant benefits accrue to those who invest early.'],
    ['affiliate with','bağlamak; ortaklık kurmak','The college is affiliated with the national university.'],
    ['aggravate by','ağırlaştırmak; kötüleştirmek','The situation was aggravated by poor communication.'],
    ['amend by','değiştirmek; düzeltmek','The law was amended by parliament last spring.'],
    ['anchor to','sabitlemek; bağlamak','Our strategy should be anchored to long-term goals.'],
    ['appeal against','temyize başvurmak; itiraz etmek','She appealed against the court\'s decision.'],
    ['arbitrate between','hakemlik yapmak; arabuluculuk','An independent body arbitrated between the two sides.'],
    ['aspire to','özlemek; hedeflemek','She aspired to a career in international law.'],
    ['bargain with','pazarlık yapmak; müzakere etmek','The union bargained with management for better terms.'],
    ['bear witness to','tanıklık etmek; şahit olmak','This building bears witness to centuries of history.'],
    ['break from','kurtulmak; ayrılmak','It is time to break from traditional methods.'],
    ['bring about','neden olmak; yol açmak','The reforms brought about significant change.'],
    ['call forth','ortaya çıkarmak; harekete geçirmek','The crisis called forth unexpected leadership qualities.'],
    ['cater for','karşılamak; hesaba katmak','The policy must cater for a wide range of needs.'],
    ['cede to','devretmek; teslim etmek','The territory was ceded to the neighbouring state.'],
    ['channel into','yöneltmek; kanalize etmek','She channelled her frustration into productive work.'],
    ['class as','sınıflandırmak; saymak','The substance is classed as a controlled drug.'],
    ['come to grips with','başa çıkmak; kavramak','He struggled to come to grips with the new software.'],
    ['concede to','kabul etmek; teslim olmak','The government conceded to the protesters\' demands.'],
    ['conflate with','birbirine karıştırmak; eşitleştirmek','Do not conflate correlation with causation.'],
    ['conform to','uymak; uyum sağlamak','All staff must conform to the code of conduct.'],
    ['correlate with','ilişkilendirmek; bağlantı kurmak','Higher income does not always correlate with happiness.'],
    ['curtail by','kısaltmak; azaltmak','Our activities were curtailed by a lack of funding.'],
    ['derive benefit from','faydalanmak; yararlanmak','Communities can derive benefit from renewable energy.'],
    ['dispose of','elden çıkarmak; atmak','How should we dispose of hazardous waste safely?'],
    ['distinguish from','ayırt etmek; ayırmak','It is hard to distinguish one twin from the other.'],
    ['draw upon','yararlanmak; başvurmak','She drew upon years of experience for the report.'],
    ['drive at','kastetmek; ima etmek','What exactly are you driving at with that remark?'],
    ['fall under','dahil olmak; kapsamına girmek','This case falls under the jurisdiction of civil law.'],
    ['forge ahead','kararlılıkla ilerlemek','Despite opposition they forged ahead with the project.'],
    ['generalise from','genellemek; çıkarım yapmak','It is dangerous to generalise from a small sample.'],
    ['give rise to','neden olmak; doğurmak','The new policy gave rise to widespread debate.'],
    ['hold to account','hesap sormak; sorumlu tutmak','Leaders must be held to account for their decisions.'],
    ['impose on','yüklemek; dayatmak','New restrictions were imposed on travel last month.'],
    ['incline towards','eğilimli olmak; meyletmek','The committee inclined towards a diplomatic solution.'],
    ['infringe on','ihlal etmek; sınırları aşmak','The new rules infringe on individual freedoms.'],
    ['insist on','ısrar etmek; inatla tutunmak','She insisted on being present at every meeting.'],
    ['lend itself to','uygun olmak; elvermek','The topic lends itself well to classroom debate.'],
    ['look back on','geriye bakarak değerlendirmek','Looking back on the project, we learned a great deal.'],
    ['navigate between','arasında yol bulmak; dengelemek','Leaders must navigate between competing priorities.'],
    ['negotiate with','müzakere etmek; anlaşmak','Both sides were willing to negotiate with each other.'],
    ['originate from','kaynaklanmak; köken almak','The tradition originates from a medieval festival.'],
    ['pass judgement on','hüküm vermek; yargılamak','It is not our place to pass judgement on their choices.'],
    ['place emphasis on','vurgu yapmak; önem vermek','The curriculum places emphasis on critical thinking.'],
    ['pose as','kendini göstermek; -mış gibi davranmak','He posed as an expert to gain their trust.'],
    ['proceed from','hareket etmek; devam etmek','Let us proceed from the assumption that all agree.'],
    ['rally around','etrafında toplanmak; destek vermek','The community rallied around the family in crisis.'],
    ['reckon with','hesaba katmak; göze almak','The new competitor is a force to be reckoned with.'],
    ['refer back to','başvurmak; geri göndermek','Please refer back to page three for the definition.'],
    ['rely upon','güvenmek; dayanmak','We cannot rely upon a single source of income.'],
    ['set forth','ortaya koymak; belirtmek','The report sets forth a clear set of recommendations.'],
    ['shed doubt on','şüphe uyandırmak','New evidence shed doubt on the official version.'],
    ['sift through','eleyerek incelemek','Investigators sifted through hours of footage.'],
    ['sit with','uyum sağlamak; sindirmek','The decision does not sit well with the ethics board.'],
    ['speak to','ele almak; değinmek','The research speaks to a wider cultural trend.'],
    ['stray from','sapmak; uzaklaşmak','Try not to stray from the main argument in your essay.'],
    ['submit to','boyun eğmek; teslim olmak','She refused to submit to pressure from the board.'],
    ['take issue with','itiraz etmek; karşı çıkmak','I take issue with the way the data was presented.'],
    ['tear through','hızla geçmek; yırtarak geçmek','The hurricane tore through the coastal towns.'],
    ['undertake to','üstlenmek; taahhüt etmek','She undertook to deliver the results by Friday.'],
    ['uphold by','sürdürmek; desteklemek','These values are upheld by every member of the team.'],
    ['weigh against','karşılaştırarak değerlendirmek','Benefits must be weighed against the potential risks.'],
    ['work in favour of','lehine çalışmak; avantaj sağlamak','The statistics work in favour of the defence.'],
    ['zone in on','odaklanmak; dikkatini vermek','She zoned in on the key issue immediately.'],
    ['zero out','sıfırlamak; tamamen bitirmek','The budget was zeroed out at the end of the year.'],
    ['wield over','kullanmak; üzerinde uygulamak','He wielded great influence over the board.'],
    ['whittle down','azaltmak; kısaltmak','She whittled down the list to just five candidates.'],
    ['weave into','dokumak; yerleştirmek','He wove personal anecdotes into his speech.'],
    ['vouch for','kefil olmak; tanıklık etmek','I can vouch for his honesty — I\'ve known him for years.'],
    ['verge on','sınırında olmak; neredeyse olmak','Her tone verged on the aggressive.'],
    ['unravel from','çözülmek; dağılmak','The plan began to unravel from the very start.'],
    ['touch upon','hafifçe değinmek','The speech only touched upon the real issue.'],
    ['tease apart','ayrıştırmak; tek tek incelemek','Researchers teased apart the two related conditions.'],
    ['talk round','ikna etmek; etrafından dolaşmak','She talked him round to her point of view.'],
    ['tailor to','uyarlamak; özelleştirmek','The course is tailored to individual learning needs.'],
    ['sweep through','hızla geçmek; yaygınlaşmak','The new trend swept through the industry.'],
    ['spur on','teşvik etmek; hızlandırmak','His early success spurred him on to greater efforts.'],
    ['smooth over','yumuşatmak; halletmek','She tried to smooth over the tension between colleagues.'],
    ['shore up','desteklemek; güçlendirmek','The government acted to shore up the economy.'],
    ['shape up','toparlanmak; şekillenmek','Things are shaping up well for the new term.'],
    ['set upon','saldırmak; üstüne çullanmak','The guard was set upon by two thieves.'],
    ['spring from','kaynaklanmak; doğmak','Many misunderstandings spring from poor communication.'],
  ],
  C2: [
    ['accuse of','suçlamak; itham etmek','He was accused of misrepresenting the facts.'],
    ['adhere to','sadık kalmak; uymak','All members must adhere to the code of conduct.'],
    ['alight on','rastlamak; dikkat çekmek','Her eye alighted on an interesting passage in the text.'],
    ['amass from','biriktirmek; toplamak','He amassed a fortune from small investments over time.'],
    ['apportion to','pay vermek; bölüştürmek','Responsibilities were apportioned to each team member.'],
    ['belie by','yalanlamak; aksini göstermek','Her calm manner belied the stress she felt inside.'],
    ['bestow upon','bahşetmek; hediye etmek','The title was bestowed upon her by the queen.'],
    ['carve out','açmak; kazanmak; edinmek','She carved out a successful career in diplomacy.'],
    ['cast doubt on','şüphe yaratmak','The new report casts doubt on the original findings.'],
    ['coexist with','bir arada var olmak','Traditional values can coexist with modern thinking.'],
    ['compound by','ağırlaştırmak; daha da kötüleştirmek','The crisis was compounded by a lack of leadership.'],
    ['contravene by','çiğnemek; ihlal etmek','The regulation was contravened by several companies.'],
    ['delimit from','sınırlamak; belirlemek','This study delimits its scope from broader economic trends.'],
    ['demystify for','gizemini gidermek; açıklamak','The speaker sought to demystify finance for the public.'],
    ['discount as','bir kenara bırakmak; önemsememek','His concerns were too quickly discounted as alarmist.'],
    ['disown by','sahip çıkmamak; tanımamak','She was effectively disowned by her business partners.'],
    ['eclipse by','gölgede bırakmak; geride bırakmak','His earlier work was eclipsed by his final masterpiece.'],
    ['elicit from','elde etmek; ortaya çıkarmak','The question elicited an unexpected response.'],
    ['elucidate on','aydınlatmak; açıklamak','Could you elucidate on the second point of your argument?'],
    ['foist on','zorla kabul ettirmek; empoze etmek','Decisions should not be foisted on local communities.'],
    ['impinge on','sınırlarını aşmak; dokunmak','The new law impinges on citizens\' right to privacy.'],
    ['invoke against','ileri sürmek; başvurmak','The defence invoked historical precedent against the charge.'],
    ['obfuscate by','anlaşılmaz kılmak; karartmak','The argument was obfuscated by unnecessary jargon.'],
    ['perpetuate by','sürdürmek; kalıcı kılmak','Stereotypes are perpetuated by media representations.'],
    ['precipitate by','neden olmak; tetiklemek','The crisis was precipitated by a series of policy failures.'],
    ['promulgate as','duyurmak; ilan etmek','The new law was promulgated as essential for security.'],
    ['proscribe by','yasaklamak','The activity was proscribed by the new regulation.'],
    ['rationalize as','gerekçelendirmek','She rationalized her decision as purely professional.'],
    ['recant from','geri almak; vazgeçmek','He recanted from his earlier statement under questioning.'],
    ['relegate to','düşürmek; önemsizleştirmek','The story was relegated to the back page of the paper.'],
    ['repudiate by','reddetmek; inkâr etmek','The claims were repudiated by official sources.'],
    ['rescind by','iptal etmek; geri almak','The order was rescinded by the new administration.'],
    ['sanction against','yaptırım uygulamak','New measures were sanctioned against the regime.'],
    ['sequester from','yalıtmak; ayırmak','Jury members were sequestered from all media.'],
    ['subvert by','altını oymak; yıkmak','Democracy can be subverted by disinformation campaigns.'],
    ['supersede by','geçersiz kılmak; yerini almak','The old law was superseded by the new legislation.'],
    ['transgress by','çiğnemek; sınırı aşmak','Professional boundaries were transgressed by the action.'],
    ['vilify by','iftira atmak; karalamak','She was vilified by the press for her controversial speech.'],
  ]
};

// ── select new entries (filter against allUsed) ───────────────────────────────
const NEED = {A1:109, A2:106, B2:16, C1:82, C2:25};
const newLines = {};
const usedKeys = new Set([...allUsed]);

Object.entries(CANDIDATES).forEach(([lvl, entries]) => {
  const section = [];
  for (const [key, tr, ex] of entries) {
    if (section.length >= NEED[lvl]) break;
    if (usedKeys.has(key)) continue;
    usedKeys.add(key);
    const pad = 22 - key.length;
    const spaces = pad > 0 ? ' '.repeat(pad) : ' ';
    const safeEx = ex.replace(/'/g, "\\'");
    section.push(`  '${key}':${spaces}{ type:'Phrasal Verb', level:'${lvl}', tr:'${tr}', ex:'${safeEx}' },`);
  }
  newLines[lvl] = section;
  console.log(lvl, 'new entries added:', section.length, '(need', NEED[lvl]+')');
});

// ── build final file content ──────────────────────────────────────────────────
const header = `// ── Phrasal Verbs Level Pack (CEFR A1 / A2 / B2 / C1 / C2) ──────────────────
// Loaded after ext1+ext2; levels are hardcoded — do NOT re-run add_cefr_levels.js on this file.
Object.assign(PHRASE_DICT, {
`;

// Get clean ext3 body (without header/footer, only entry/comment lines)
const bodyLines = cleanLines.filter(l => {
  const t = l.trim();
  return t !== '' || true; // keep all non-header lines
});

// Find where real content starts (after Object.assign line)
let bodyStart = 0;
for (let i = 0; i < bodyLines.length; i++) {
  if (bodyLines[i].includes('Object.assign')) { bodyStart = i+1; break; }
}
// Sanitize apostrophes in ex:'' values that pass through from cleanLines
const bodyContent = bodyLines.slice(bodyStart).map(line => {
  return line.replace(/(, ex:')(.+?)(' \},)/, (m, pre, ex, suf) => pre + ex.replace(/(?<!\\)'/g, "\\'") + suf);
}).join('\n');

// Build additional section
const addSection = Object.entries(newLines).map(([lvl, lines]) => {
  if (!lines.length) return '';
  const title = {A1:'A 1  —  Additional entries',A2:'A 2  —  Additional entries',B2:'B 2  —  Additional entries',C1:'C 1  —  Additional entries',C2:'C 2  —  Additional entries'}[lvl];
  return `\n  // ════════════════════════════════════════════════════════
  //  ${title}
  // ════════════════════════════════════════════════════════\n${lines.join('\n')}`;
}).join('\n');

const finalContent = header + bodyContent + '\n' + addSection + '\n});\n';
fs.writeFileSync(path.join(ROOT, 'js/phrasal_verbs_ext3.js'), finalContent, 'utf8');
console.log('\nFile written.');
